mail.smtp.protocol = smtp
mail.smtp.host = mail.sahara.com
mail.smtp.port = 587
mail.login = no-reply@1erp.sa
mail.password = Erp0fkpi@sahara
mail.email=no-reply@1erp.sa
mail.from=1erp.sa
mail.ssl=false
mail.isauth=true
