mail.smtp.protocol=smtp
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.login=no-reply@brainbm.uz
mail.password=uwpbjkmftehnohke
mail.email=no-reply@brainbm.uz
mail.from=brain.uz
mail.ssl=false
mail.isauth=true