mail.smtp.protocol=smtp
mail.smtp.host=mail.uzgtl.com
mail.smtp.port=587
mail.login=datasite@uzgtl.com
mail.password=Datasite-GTL-VDS
mail.email=no-reply@uzgtl.com
mail.from=
mail.ssl=true
mail.isauth=true