mail.smtp.protocol=smtp
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.login=no-reply@praaktisgo.com
mail.password=gkgvfrhawghwvipx
mail.email=no-reply@praaktisgo.com
mail.from=PraaktisGO
mail.ssl=false
mail.isauth=true