mail.smtp.protocol=smtp
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.login=noreply@kpi.com
mail.password=bcvgdvdshprdtbrn
mail.email=noreply@kpi.com
mail.from=kpi.com
mail.ssl=false
mail.isauth=true