mail.smtp.protocol=smtp
mail.smtp.host=email-smtp.us-east-1.amazonaws.com
mail.smtp.port=25
mail.login=AKIAIK7TYHMVR7UPS3FA
mail.password=AgQ5jp2Q/GBnPQIYAUYzKPAntQZvkW0epVtY4KCatuLC
mail.email=no-reply@omandatapark.com
mail.from=Omandatapark.com
mail.ssl=false
mail.isauth=true
