
LENINGRAD=Leningrad
ULYANOV=Ulyanov
YAROSLAVL=Yaroslavl
MAGADAN=Magadan
SMOLENSK=Smolensk
PRIMORSK=Primorsk
TVER=Tver
TULA=Tula
AMUR=Amur
RYAZAN=Ryazan
KHABAROVSK=Khabarovsk
VLADIMIR=Vladimir
MURMANSK=Murmansk
KIROV=Kirov
IRKUTSK=Irkutsk
PERM=Perm
ZABAYKAL=Zabaykal
CHELYABINSK=Chelyabinsk
ASTRAKHAN=Astrakhan
PENZA=Penza
SVERDLOVSK=Sverdlovsk
ROSTOV=Rostov
ORENBURG=Orenburg
KALUGA=Kaluga
KRASNODAR=Krasnodar
KEMEROVO=Kemerovo
VOLOGDA=Vologda
ALTAY=Altay
ORLOV=Orlov
KALININGRAD=Kaliningrad
BELGOROD=Belgorod
SARATOV=Saratov
KOSTROMA=Kostroma
STAVROPOL=Stavropol
UFA=Ufa
ARKHANGELSK=Arkhangelsk
VORONEJ=Voronej
TYUMEN=Tyumen
OMSK=Omsk
TOMSK=Tomsk
LIPETSK=Lipetsk
SAMARA=Samara
NOVGOROD=Novgorod
NOVOSIBIRSK=Novosibirsk
MOSCOW=Moscow
NIJEGOROD=Nijegorod
IVANOVO=Ivanovo
VOLGOGRAD=Volgograd
PSKOV=Pskov
TAMBOV=Tambov
KURGAN=Kurgan
KRASNOYARSK=Krasnoyarsk
BRYANSK=Bryansk
KAMCHATKA=Kamchatka
SAKHALIN=Sakhalin
KURSK=Kursk
UKR_KIEV=Kiev
UKR_DNEPROPETROVSK=Dnepropetrovsk
UKR_DONETSK=Donetsk
UKR_ZAPOROJ=Zaporoje
UKR_POLTAVA=Poltava
UKR_XARKOV=Xarkov
UKR_KIEV_REGION=Kiev region
UKR_ODESSA=Odessa
UKR_LUGAN=Lugan
UKR_NIKOLAY=Nikolay
UKR_CHERKASS=Cherkass
UKR_LVOV=Lvov
UKR_KRIM=Krim
UKR_SUMA=Suma
UKR_KIROVGRAD=Kirovgrad
UKR_CHERNIGOV=Chernigov
UKR_IVANO_FRANKOVO=Ivano-Frankovo
UKR_VOLIN=Volin
UKR_ROVNEN=Rovnen
UKR_VINNITS=Vinnits
UKR_XERSON=Xerson
UKR_XMELNITS=Xmelnits
UKR_JITOMIR=Jitomir
UKR_ZAKARPAT=Zakarpat
UKR_CHERNOVITS=Chernovits
UKR_TERNOPOL=Ternopol
UDMURTIYA=Udmurtiya
TATARSTAN=Tatarstan
