
TASK_START_NOTIFICATION=Task start notification.
SICK_REQUEST_ALERT=Leave Request Notification
PROJECT_MANAGER_ASSIGN_NOTIFICATION=Project manager assign notification
WEEKLY_PROGRESS_REPORT=Weekly progress report
STOREFRONT_CLIENT_MAIL_SUBJECT=Client registration
ASSESSMENT_INITIATE_NOTIFICATION_360=360 degree assessment initiate notification
CRM_CASE_MESSAGE_ASSIGNEE_NOTIFICATION=CRM Case Assignee Notification
CRM_CASE_UPDATED_NOTIFICATION=CRM Case Updated Notification
TEAM_ASSIGN_NOTIFICATION=Department assign notification
ISSUE_DELETE_NOTIFICATION=Issue delete notification
TASK_ASSIGN_NOTIFICATION=Task assign notification.
EMPLOYEE_ACTIVATION_NOTIFICATION=Employee Activation Notification
SUBSCRIPTION_PAID_NOTIFICATION=account is expiring
GOOGLE_CONTACT_IMPORTED=Contact Import Finished
CRM_CASE_MESSAGE_CLOSE_NOTIFICATION=CRM Case Closed Notification
PROJECT_ASSIGN_NOTIFICATION=Project assign notification.
ASSESSMENT_DELETE_NOTIFICATION=Assessment delete notification
TASK_UPDATE_NOTIFICATION=Task update notification.
GOOGLE_CONTACT_SYNC=Confirmation: Contact synchronization is finished
PROJECT_UPDATE_NOTIFICATION=Project update notification
CRM_CASE_MESSAGE_REMOVAL_NOTIFICATION=CRM Case Removal Notification
//CLIENT_ACCESS_TO=Client access to
BACKUP_MANAGER_ASSIGN_NOTIFICATION=Backup manager assign notification
ASSESSMENT_REVIEW_NOTIFICATION_360=360 Appraisal Review Notification
PAYPAL_SERVICE_NOTIFICATION=PayPalServiceNotification
GOOGLE_CHECKOUT_NOTIFICATION=GoogleCheckoutNotification
ASSESSMENT_APPROVE_NOTIFICATION_BY_HR=Period Appraisal has been approved by HR manager
CRM_CASE_RESOLVER_CHANGED_NOTIFICATION=CRM Case Resolver Changed Notification
ASSESSMENT_INITIATE_NOTIFICATION=Assessment initiate notification
BUG_REPORT_ADD_NOTIFICATION=Bug Report add notification
SUBSCRIPTION_PAID_EXPIRED_NOTIFICATION=account is expired
ISSUE_ASSIGN_NOTIFICATION=Issue assign notification
CRM_CASE_RESOLVED_NOTIFICATION=CRM Case Resolved Notification
ISSUE_ADD_NOTIFICATION=Issue add notification
EMPLOYEE_ADD_NOTIFICATION=Account Confirmation
PASSWORD_RESET_NOTIFICATION=Password Reset Confirmation
USER_SENT_INVITATION=Sent Invitation
ASSESSMENT_REJECT_NOTIFICATION_BY_HR=Period Appraisal has been rejected by HR manager
TASK_ADD_NOTIFIATION=Task add notification.
ASSESSMENT_RECURRENT_NOTIFICATION_FOR_HR=Not assessed employee list
SUBSCRIPTION_NON_PAID_NOTIFICATION=account has been set up
ISSUE_UPDATE_NOTIFICATION=Issue update notification
ASSESSMENT_APPROVE_NOTIFICATION=Assessment approve notification
CRM_CASE_MESSAGE_REOPEN_NOTIFICATION=CRM Case Reopen Notification
PROJECT_ADD_NOTIFICATION=Project add notification
TASK_DELETE_NOTIFIATION=Task delete notification.
TASK_COMPLETED_PREDECESSOR_NOTIFICATION=Predecessor task has been completed.
CLIENT_ACCESS_TO=Client access to
CRM_CASE_MESSAGE_RESOLVER_NOTIFICATION=CRM Case Resolver Notification
ASSESSMENT_RATE_NOTIFICATION=Assessment rate notification
BUG_REPORT_TITLE=Feedback
TASK_COMPLETE_NOTIFICATION=Task complete notification.
PROJECT_DELETE_NOTIFICATION=Project delete notification
TASK_REJECT_NOTIFICATION=Task reject notification.
TEAM_ADD_NOTIFICATION=Department add notification
SUBSCRIPTION_FREE_NOTIFICATION=Free Trial account is expiring
SIGN_UP=Sign Up
BUG_STATUS_CHANGED=Bug Status Changed
CRM_CASE_ASSIGNEE_CHANGED_NOTIFICATION=CRM Case Assignee Changed Notification
PROJECT_MANAGER_UNASSIGN_NOTIFICATION=Project manager unassign notification
ASSESSMENT_APPROVE_NOTIFICATION_FOR_HR=Period Appraisal has been sent for your approval
BACKUP_MANAGER_UNASSIGN_NOTIFICATION=Backup manager unassign notification
ASSESSMENT_REVIEW_NOTIFICATION=Assessment review notification
TEAN_LEADER_ASSIGN_NOTIFICATION=Department leader assign notification
TASK_COMMENT_ADD_NOTIFIATION=Task comment add notification
SUBMITTED_AN_EXPENSE_CLAIM=submitted an Expense Claim for your attention
CALENDAR_ADD_EVENT_NOTIFICATION=Calendar Add Event Notification
CALENDAR_ADD_EVENT_NOTIFICATION_SUBJECT=Calendar Add Event Notification
EXPENSE_REPORT_SUBMITTED_FOR=Expense Report submitted for
S_ATTENTION=s attention
DECLINED_YOUR_EXPENSE_CLAIN=Declined your Expense Claim
APPROVED_YOUR_EXPENSE_CLAIN=Approved your Expense Claim
RESUBMITTED_THE_EXPENSE_CLAIN=resubmitted the Expense Claim
YOUR=Your
FREE_TRIAL_COMPANY_EXPIRED_NOTIFICATION=FREE TRIAL COMPANY EXPIRED NOTIFICATION
GOOGLE_APPS=Google Apps
CREATED_AN_ACCOUNT_FOR_YOU_AT=created an account for you at
ACCOUNT_CREATION_NOTIFICATION=Account creation notification
NOTIFICATION=notification
REQUEST_NOTIFICATION=Request notification
NEW_TASK=New Task
TASK_DUE_REMINDER=Task Due reminder
DAILY_REPORT=Daily Report
NEW_SUBJECT=New
FROM=from
PASSWORD_RESET=Password Reset
DAILY_STR=Daily
WEEKLY_STR=Weekly
MONTHLY_STR=Monthly
RESOURCE_WORKLOAD_FOR=Resource Workload for
PROJECT_MANAGER=Project Manager
BACKUP_MANAGER=Backup Manager
THIS_REPORT_IS_SENT=This report is sent every morning and contains information about the activity in your managed projects in the last 24 hours.
THIS_REPORT_IS_SENT_WEEK=This report is sent every week and contains information about the activity in your managed projects in the last week.
THIS_REPORT_IS_SENT_MONTHLY=This report is sent every month and contains information about the activity in your managed projects in the last month.
DIRECTOR=Director
SUBMITTED_TIMESHEER_FOR_APPROVAL=submitted timesheet for approval
REVIEWED_YOUR_TIMESHEET_ENTIRIS=reviewed your timesheet entries
INVOICE_OVERDUE_REMINDER=Invoice overdue reminder
TIMESHEET_REMINDER=Timesheet reminder
EVENT_REMINDER=Event reminder
SCHEDULED_REPORT=Scheduled Report
EMPLOYEE_VISA_EXPIRATION_DATE=Employee visa expiry date reminder
CALENDAR=Calendar
SHARE=Share
ADD=Add
EVENT_NOTIFICATION=Event Notification
CALL_NOTIFICATION=Call Notification
CALENDAR_UPDATE_NOTIFICATION=Call Notification
CALENDAR_DELETE_NOTIFICATION=Calendar Delete Event Notification
WEEKLY_USERS_SIGN_UP_REPORT=Weekly users sign up report
PAYSLIP_FOR=Payslip for
ADDITIONAL_PAYMENT=Additional Payment
COMMISSION_FOR=Commission for
PAYMENT_FOR=Payment for
CRM_EVENT_NOTIFICATION=CRM Event Notification
CRM_CASE_NOTIFICATIONS=CRM Case Notifications
CONFIRMATION_OF_INVITATION_TO_THE_NETWORK=Confirmation of Invitation to the Network
CONFIRMATION_OF_REQUEST_TO_JOIN_THE_NETWORK=Confirmation of Request to Join the Network
MEMBER_INVITATION_NOTIFICATION=Member Invitation Notification
ADD_NOTE_TO_CRM_CASE_NOTIFICATION=Add Note To CRM Case Notification
ADD_NOTE_TO=Add note to
TASK_LO=task
PROJECT_LO=project
ADD_COMMENT_TO_TASK_NOTIFICATION=Add comment to task notification
NETWORK_INVITATION_NOTIFICATION=Network Invitation Notification
NETWORK_ADD_NOTIFICATION=Network Add Notification
WEEKLY_NEWS_UPDATES=Weekly News Updates
NETWORK_NEWS_ADD_NOTIFICATION=Network News Add Notification
ADD_COMMENT_NOTIFICATION=Add Comment Notification
REQUEST_TO_JOIN_YOUR_NETWORK=Request to join your network
INVITATION_ACCEPTED_SUBJECT=Invitation accepted
TENTATIVELY_ACCEPTED_SUBJECT=Tentatively Accepted
INVITATION_DECLINED_SUBJECT=Invitation declined
PURCHASE_ORDER_APPROVEL=Purchase Order Approved
PURCHASE_ORDER_REJECTED=Purchase Order Rejected
SALES_QUOTE=Sales Quote
HAS_BEEN_APPROVED_BY=has been approved by
HAS_BEEN_REJECTED_BY=has been rejected by
NEW_QUESTION_POSTED=New question posted
FIXED_ASSET_COUNT_RESULT=Fixed Asset Count result
ADD_ON_REQUEST_FOR=ADD-ON REQUEST FOR
OPPORTUNITY_SUBJECT=Opportunity
CREATED=Created
ASSIGNED=Assigned
KGONLINE_RESCHEDULED_COURSE_CONFIRMATION=KGOnline Rescheduled Course Confirmation
CONSOLIDATED_INVOICE_FOR=Consolidated Invoice for
FOR_THE_PERIOD=for the period
YOUR_REGISTRATION_TO_KHOWLEDGE=Your registration to Knowledge Grid website has been rejected
REGISTRATION_APPLICATION_TO=Registration application to
CRM_CASE_RESOLVER_NOTIFICATION=Send auto message to "assignee" when the case`s resolver is assigned
CRM_CASE_ASSIGNEE_NOTIFICATION=Send auto message to "assignee" when the case is assigned to employee
CRM_CASE_CLOSE_NOTIFICATION=Send auto message to "assignee" when the case is closed
CRM_CASE_REMOVAL_NOTIFICATION=Send auto message to "assignee" when the case is removed
CRM_CASE_REOPEN_NOTIFICATION=Send auto message to "assignee" when the case reopened
POTENTIAL_CONTRACT_HAS_BEEN_ESTIMATED=Potential contract has been estimated
ADDED_A_NEW_APLICATION=Added a new aplication
ESTIMATED_THIS_POTENTIAL_CONTRACT=Eestimated this potential contract
TASK_COMPLETED_NOTIFICATION=Task completion.
WORKSTREAM_OVERDUE_REMINDER=Workstream Due reminder
PROJECT_OVERDUE_REMINDER=Project Due reminder
PERSONAL_GOAL_ASSIGN_NOTIFICATION=Personal goal assign notification.
DEPARTMENT_GOAL_ASSIGN_NOTIFICATION=Department goal assign notification.
PROJECT_GOAL_ASSIGN_NOTIFICATION=Project goal assign notification.
BUSINESS_GOAL_ASSIGN_NOTIFICATION=Business goal assign notification.
PRODUCT_STOCK_NOTIFICATION=Product stock notification
MEETING_MINUTES_ATTENDEESEMPLOYEE=Please be advised that
MEETING_MINUTES_ADDED_TO_MEETING=added you as an attendee to
MEETING_MINUTES=meeting.
MEETING_MINUTES_DETAILS=Meeting Details
PROJECT_SUBMIT_FOR_APPROVAL=submitted for approval
PROJECT_APPROVED_BY_CLIENT=approved by client
PROJECT_REJECTED_BY_CLIENT=rejected by client
STRIPE_PAYMENT_SUBJECT=Stripe Payment Notification
PAYPAL_PAYMENT_SUBJECT=Paypal Payment Notification