package com.edatasite.workforce.mail;

/**
 * Created by IntelliJ IDEA.
 * User: Iskandar
 * Date: 13-Aug-2007
 * Time: 09:59:13
 * To change this template use File | Settings | File Templates.
 */

public interface EdsSubjects {

    String PROJECT_ASSIGN_NOTIFICATION = "PROJECT_ASSIGN_NOTIFICATION";
    String TASK_ASSIGN_NOTIFICATION = "TASK_ASSIGN_NOTIFICATION";
    String TASK_ADD_NOTIFIATION = "TASK_ADD_NOTIFIATION";
    String TASK_COMPLETED_PREDECESSOR_NOTIFICATION = "TASK_COMPLETED_PREDECESSOR_NOTIFICATION";
    String TASK_COMPLETED_NOTIFICATION = "TASK_COMPLETED_NOTIFICATION";
    String TASK_DELETE_NOTIFIATION = "TASK_DELETE_NOTIFIATION";
    String TASK_UPDATE_NOTIFICATION = "TASK_UPDATE_NOTIFICATION";
    String TASK_COMPLETE_NOTIFICATION = "TASK_COMPLETE_NOTIFICATION";
    String TASK_REJECT_NOTIFICATION = "TASK_REJECT_NOTIFICATION";
    String TASK_START_NOTIFICATION = "TASK_START_NOTIFICATION";
    String ASSESSMENT_INITIATE_NOTIFICATION = "ASSESSMENT_INITIATE_NOTIFICATION";
    String ASSESSMENT_DELETE_NOTIFICATION = "ASSESSMENT_DELETE_NOTIFICATION";
    String ASSESSMENT_INITIATE_NOTIFICATION_360 = "ASSESSMENT_INITIATE_NOTIFICATION_360";
    String ASSESSMENT_REVIEW_NOTIFICATION = "ASSESSMENT_REVIEW_NOTIFICATION";
    String ASSESSMENT_REVIEW_NOTIFICATION_360 = "ASSESSMENT_REVIEW_NOTIFICATION_360";

    String ASSESSMENT_RATE_NOTIFICATION = "ASSESSMENT_RATE_NOTIFICATION";
    String ASSESSMENT_APPROVE_NOTIFICATION = "ASSESSMENT_APPROVE_NOTIFICATION";
    String ASSESSMENT_APPROVE_NOTIFICATION_FOR_HR = "ASSESSMENT_APPROVE_NOTIFICATION_FOR_HR";
    String ASSESSMENT_APPROVE_NOTIFICATION_BY_HR = "ASSESSMENT_APPROVE_NOTIFICATION_BY_HR";
    String ASSESSMENT_REJECT_NOTIFICATION_BY_HR = "ASSESSMENT_REJECT_NOTIFICATION_BY_HR";
    String ASSESSMENT_RECURRENT_NOTIFICATION_FOR_HR = "ASSESSMENT_RECURRENT_NOTIFICATION_FOR_HR";
    String TASK_COMMENT_ADD_NOTIFIATION = "TASK_COMMENT_ADD_NOTIFIATION";

    String PROJECT_ADD_NOTIFICATION = "PROJECT_ADD_NOTIFICATION";
    String PROJECT_UPDATE_NOTIFICATION = "PROJECT_UPDATE_NOTIFICATION";
    String PROJECT_DELETE_NOTIFICATION = "PROJECT_DELETE_NOTIFICATION";
    String PROJECT_MANAGER_ASSIGN_NOTIFICATION = "PROJECT_MANAGER_ASSIGN_NOTIFICATION";
    String PROJECT_MANAGER_UNASSIGN_NOTIFICATION = "PROJECT_MANAGER_UNASSIGN_NOTIFICATION";
    String BACKUP_MANAGER_ASSIGN_NOTIFICATION = "BACKUP_MANAGER_ASSIGN_NOTIFICATION";
    String BACKUP_MANAGER_UNASSIGN_NOTIFICATION = "BACKUP_MANAGER_UNASSIGN_NOTIFICATION";

    String TEAM_ADD_NOTIFICATION = "TEAM_ADD_NOTIFICATION";
    String TEAM_ASSIGN_NOTIFICATION = "TEAM_ASSIGN_NOTIFICATION";
    String TEAN_LEADER_ASSIGN_NOTIFICATION = "TEAN_LEADER_ASSIGN_NOTIFICATION";
    String SIGN_UP = "SIGN_UP";
    String EMPLOYEE_ACTIVATION_NOTIFICATION = "EMPLOYEE_ACTIVATION_NOTIFICATION";
    String SICK_REQUEST_ALERT = "SICK_REQUEST_ALERT";
    String GOOGLE_CONTACT_IMPORTED = "GOOGLE_CONTACT_IMPORTED";
    String GOOGLE_CONTACT_SYNC = "GOOGLE_CONTACT_SYNC";

    String ISSUE_ADD_NOTIFICATION = "ISSUE_ADD_NOTIFICATION";
    String ISSUE_ASSIGN_NOTIFICATION = "ISSUE_ASSIGN_NOTIFICATION";
    String ISSUE_DELETE_NOTIFICATION = "ISSUE_DELETE_NOTIFICATION";
    String ISSUE_UPDATE_NOTIFICATION = "ISSUE_UPDATE_NOTIFICATION";

    String BUG_REPORT_ADD_NOTIFICATION = "BUG_REPORT_ADD_NOTIFICATION";

    String WEEKLY_PROGRESS_REPORT = "WEEKLY_PROGRESS_REPORT";

    //    static final String CLIENT_ACCESS_TO = "Client access to ";
    String EMPLOYEE_ADD_NOTIFICATION = "EMPLOYEE_ADD_NOTIFICATION";
    String PASSWORD_RESET_NOTIFICATION = "PASSWORD_RESET_NOTIFICATION";
    String USER_SENT_INVITATION = "USER_SENT_INVITATION";
    String STOREFRONT_CLIENT_MAIL_SUBJECT = "STOREFRONT_CLIENT_MAIL_SUBJECT";
    String BUG_REPORT_TITLE = /*"Bug Report"*/"BUG_REPORT_TITLE";
    String BUG_STATUS_CHANGED = "BUG_STATUS_CHANGED";
    String PAYPAL_SERVICE_NOTIFICATION = "PAYPAL_SERVICE_NOTIFICATION";
    String GOOGLE_CHECKOUT_NOTIFICATION = "GOOGLE_CHECKOUT_NOTIFICATION";

    String SUBSCRIPTION_NON_PAID_NOTIFICATION = "SUBSCRIPTION_NON_PAID_NOTIFICATION";
    String SUBSCRIPTION_FREE_NOTIFICATION = "SUBSCRIPTION_FREE_NOTIFICATION";
    String SUBSCRIPTION_PAID_NOTIFICATION = "SUBSCRIPTION_PAID_NOTIFICATION";
    String SUBSCRIPTION_PAID_EXPIRED_NOTIFICATION = "SUBSCRIPTION_PAID_EXPIRED_NOTIFICATION";

    String TIMESHEET_FOR_APPROVAL = "TIMESHEET_FOR_APPROVAL";
    String TIMESHEET_ENTRIES_REJECTED = "TIMESHEET_ENTRIES_REJECTED";
    String TIMESHEET_ENTRIES_APPROVED = "TIMESHEET_ENTRIES_APPROVED";

    String CRM_CASE_MESSAGE_RESOLVER_NOTIFICATION = "CRM_CASE_MESSAGE_RESOLVER_NOTIFICATION";
    String CRM_CASE_MESSAGE_ASSIGNEE_NOTIFICATION = "CRM_CASE_MESSAGE_ASSIGNEE_NOTIFICATION";
    String CRM_CASE_MESSAGE_REMOVAL_NOTIFICATION = "CRM_CASE_MESSAGE_REMOVAL_NOTIFICATION";
    String CRM_CASE_MESSAGE_CLOSE_NOTIFICATION = "CRM_CASE_MESSAGE_CLOSE_NOTIFICATION";
    String CRM_CASE_MESSAGE_REOPEN_NOTIFICATION = "CRM_CASE_MESSAGE_REOPEN_NOTIFICATION";
    String CRM_CASE_UPDATED_NOTIFICATION = "CRM_CASE_UPDATED_NOTIFICATION";
    String CRM_CASE_RESOLVED_NOTIFICATION = "CRM_CASE_RESOLVED_NOTIFICATION";
    String CRM_CASE_RESOLVER_CHANGED_NOTIFICATION = "CRM_CASE_RESOLVER_CHANGED_NOTIFICATION";
    String CRM_CASE_ASSIGNEE_CHANGED_NOTIFICATION = "CRM_CASE_ASSIGNEE_CHANGED_NOTIFICATION";
    String SUBMITTED_AN_EXPENSE_CLAIM = "SUBMITTED_AN_EXPENSE_CLAIM";
    String CALENDAR_ADD_EVENT_NOTIFICATION_SUBJECT = "CALENDAR_ADD_EVENT_NOTIFICATION_SUBJECT";
    String EXPENSE_REPORT_SUBMITTED_FOR = "EXPENSE_REPORT_SUBMITTED_FOR";
    String S_ATTENTION = "S_ATTENTION";
    String DECLINED_YOUR_EXPENSE_CLAIN = "DECLINED_YOUR_EXPENSE_CLAIN";
    String APPROVED_YOUR_EXPENSE_CLAIN = "APPROVED_YOUR_EXPENSE_CLAIN";
    String RESUBMITTED_THE_EXPENSE_CLAIN = "RESUBMITTED_THE_EXPENSE_CLAIN";
    String YOUR = "YOUR";
    String FREE_TRIAL_COMPANY_EXPIRED_NOTIFICATION = "FREE_TRIAL_COMPANY_EXPIRED_NOTIFICATION";
    String GOOGLE_APPS = "GOOGLE_APPS";
    String CREATED_AN_ACCOUNT_FOR_YOU_AT = "CREATED_AN_ACCOUNT_FOR_YOU_AT";
    String ACCOUNT_CREATION_NOTIFICATION = "ACCOUNT_CREATION_NOTIFICATION";
    String NOTIFICATION = "NOTIFICATION";
    String REQUEST_NOTIFICATION = "REQUEST_NOTIFICATION";
    String NEW_TASK = "NEW_TASK";
    String TASK_DUE_REMINDER = "TASK_DUE_REMINDER";
    String PROJECT_OVERDUE_REMINDER = "PROJECT_OVERDUE_REMINDER";
    String WORKSTREAM_OVERDUE_REMINDER = "WORKSTREAM_OVERDUE_REMINDER";
    String DAILY_REPORT = "DAILY_REPORT";
    String NEW_SUBJECT = "NEW_SUBJECT";
    String FROM = "FROM";
    String PASSWORD_RESET = "PASSWORD_RESET";
    String DAILY_STR = "DAILY_STR";
    String WEEKLY_STR = "WEEKLY_STR";
    String MONTHLY_STR = "MONTHLY_STR";
    String RESOURCE_WORKLOAD_FOR = "RESOURCE_WORKLOAD_FOR";
    String PROJECT_MANAGER = "PROJECT_MANAGER";
    String BACKUP_MANAGER = "BACKUP_MANAGER";
    String THIS_REPORT_IS_SENT = "THIS_REPORT_IS_SENT";
    String THIS_REPORT_IS_SENT_WEEK = "THIS_REPORT_IS_SENT_WEEK";
    String THIS_REPORT_IS_SENT_MONTHLY = "THIS_REPORT_IS_SENT_MONTHLY";
    String DIRECTOR = "DIRECTOR";
    String SUBMITTED_TIMESHEER_FOR_APPROVAL = "SUBMITTED_TIMESHEER_FOR_APPROVAL";
    String REVIEWED_YOUR_TIMESHEET_ENTIRIS = "REVIEWED_YOUR_TIMESHEET_ENTIRIS";
    String INVOICE_OVERDUE_REMINDER = "INVOICE_OVERDUE_REMINDER";
    String TIMESHEET_REMINDER = "TIMESHEET_REMINDER";
    String EVENT_REMINDER = "EVENT_REMINDER";
    String SCHEDULED_REPORT = "SCHEDULED_REPORT";
    String EMPLOYEE_VISA_EXPIRATION_DATE = "EMPLOYEE_VISA_EXPIRATION_DATE";
    String CALENDAR = "CALENDAR";
    String SHARE = "SHARE";
    String ADD = "ADD";
    String EVENT_NOTIFICATION = "EVENT_NOTIFICATION";
    String CALL_NOTIFICATION = "CALL_NOTIFICATION";
    String CALENDAR_UPDATE_NOTIFICATION = "CALENDAR_UPDATE_NOTIFICATION";
    String CALENDAR_DELETE_NOTIFICATION = "CALENDAR_DELETE_NOTIFICATION";
    String WEEKLY_USERS_SIGN_UP_REPORT = "WEEKLY_USERS_SIGN_UP_REPORT";
    String PAYSLIP_FOR = "PAYSLIP_FOR";
    String ADDITIONAL_PAYMENT = "ADDITIONAL_PAYMENT";
    String COMMISSION_FOR = "COMMISSION_FOR";
    String PAYMENT_FOR = "PAYMENT_FOR";
    String CRM_EVENT_NOTIFICATION = "CRM_EVENT_NOTIFICATION";
    String CRM_CASE_NOTIFICATIONS = "CRM_CASE_NOTIFICATIONS";
    String CONFIRMATION_OF_INVITATION_TO_THE_NETWORK = "CONFIRMATION_OF_INVITATION_TO_THE_NETWORK";
    String CONFIRMATION_OF_REQUEST_TO_JOIN_THE_NETWORK = "CONFIRMATION_OF_REQUEST_TO_JOIN_THE_NETWORK";
    String MEMBER_INVITATION_NOTIFICATION = "MEMBER_INVITATION_NOTIFICATION";
    String ADD_NOTE_TO_CRM_CASE_NOTIFICATION = "ADD_NOTE_TO_CRM_CASE_NOTIFICATION";
    String ADD_NOTE_TO = "ADD_NOTE_TO";
    String TASK_LO = "TASK_LO";
    String PROJECT_LO = "PROJECT_LO";
    String ADD_COMMENT_TO_TASK_NOTIFICATION = "ADD_COMMENT_TO_TASK_NOTIFICATION";
    String NETWORK_INVITATION_NOTIFICATION = "NETWORK_INVITATION_NOTIFICATION";
    String NETWORK_ADD_NOTIFICATION = "NETWORK_ADD_NOTIFICATION";
    String WEEKLY_NEWS_UPDATES = "WEEKLY_NEWS_UPDATES";
    String NETWORK_NEWS_ADD_NOTIFICATION = "NETWORK_NEWS_ADD_NOTIFICATION";
    String ADD_COMMENT_NOTIFICATION = "ADD_COMMENT_NOTIFICATION";
    String REQUEST_TO_JOIN_YOUR_NETWORK = "REQUEST_TO_JOIN_YOUR_NETWORK";
    String INVITATION_ACCEPTED_SUBJECT = "INVITATION_ACCEPTED_SUBJECT";
    String TENTATIVELY_ACCEPTED_SUBJECT = "TENTATIVELY_ACCEPTED_SUBJECT";
    String INVITATION_DECLINED_SUBJECT = "INVITATION_DECLINED_SUBJECT";
    String PURCHASE_ORDER_APPROVEL = "PURCHASE_ORDER_APPROVEL";
    String PURCHASE_ORDER_REJECTED = "PURCHASE_ORDER_REJECTED";
    String SALES_QUOTE = "SALES_QUOTE";
    String HAS_BEEN_APPROVED_BY = "HAS_BEEN_APPROVED_BY";
    String HAS_BEEN_REJECTED_BY = "HAS_BEEN_REJECTED_BY";
    String NEW_QUESTION_POSTED = "NEW_QUESTION_POSTED";
    String FIXED_ASSET_COUNT_RESULT = "FIXED_ASSET_COUNT_RESULT";
    String ADD_ON_REQUEST_FOR = "ADD_ON_REQUEST_FOR";
    String OPPORTUNITY_SUBJECT = "OPPORTUNITY_SUBJECT";
    String CREATED = "CREATED";
    String ASSIGNED = "ASSIGNED";
    String KGONLINE_RESCHEDULED_COURSE_CONFIRMATION = "KGONLINE_RESCHEDULED_COURSE_CONFIRMATION";
    String CONSOLIDATED_INVOICE_FOR = "CONSOLIDATED_INVOICE_FOR";
    String FOR_THE_PERIOD = "FOR_THE_PERIOD";
    String YOUR_REGISTRATION_TO_KHOWLEDGE = "YOUR_REGISTRATION_TO_KHOWLEDGE";
    String REGISTRATION_APPLICATION_TO = "REGISTRATION_APPLICATION_TO";
    String POTENTIAL_CONTRACT_HAS_BEEN_ESTIMATED = "POTENTIAL_CONTRACT_HAS_BEEN_ESTIMATED";
    String ADDED_A_NEW_APLICATION = "ADDED_A_NEW_APLICATION";
    String ESTIMATED_THIS_POTENTIAL_CONTRACT = "ESTIMATED_THIS_POTENTIAL_CONTRACT";
    String PERSONAL_GOAL_ASSIGN_NOTIFICATION = "PERSONAL_GOAL_ASSIGN_NOTIFICATION";
    String DEPARTMENT_GOAL_ASSIGN_NOTIFICATION = "DEPARTMENT_GOAL_ASSIGN_NOTIFICATION";
    String PROJECT_GOAL_ASSIGN_NOTIFICATION = "PROJECT_GOAL_ASSIGN_NOTIFICATION";
    String BUSINESS_GOAL_ASSIGN_NOTIFICATION = "BUSINESS_GOAL_ASSIGN_NOTIFICATION";
    String PRODUCT_STOCK_NOTIFICATION = "PRODUCT_STOCK_NOTIFICATION";
    String MEETING_MINUTES_ATTENDEESEMPLOYEE = "MEETING_MINUTES_ATTENDEESEMPLOYEE";
    String MEETING_MINUTES_ADDED_TO_MEETING = "MEETING_MINUTES_ADDED_TO_MEETING";
    String MEETING_MINUTES = "MEETING_MINUTES";
    String MEETING_MINUTES_DETAILS = "MEETING_MINUTES_DETAILS";
    String BENEFIT_REQUEST = "BENEFIT_REQUEST";
    String PROJECT_SUBMIT_FOR_APPROVAL = "PROJECT_SUBMIT_FOR_APPROVAL";
    String PROJECT_APPROVED_BY_CLIENT = "PROJECT_APPROVED_BY_CLIENT";
    String PROJECT_REJECTED_BY_CLIENT = "PROJECT_REJECTED_BY_CLIENT";
    String STRIPE_PAYMENT_SUBJECT = "STRIPE_PAYMENT_SUBJECT";
    String PAYPAL_PAYMENT_SUBJECT = "PAYPAL_PAYMENT_SUBJECT";
}

