package com.edatasite.workforce.gwt.core.server.db.myupdate;

import com.edatasite.workforce.core.domain.myupdates.EdsMyUpdate;
import com.edatasite.workforce.core.domain.myupdates.EdsMyUpdateType;
import com.edatasite.workforce.gwt.core.client.rpc.MyUpdateItem;
import com.edatasite.workforce.gwt.core.server.db.Manager;

/**
 * User: Abdulaziz
 * Date: Jan 7, 2010
 * Time: 12:23:37 PM
 */
public interface MyUpdateTypeManager extends Manager<EdsMyUpdateType> {

    ///////////// Activity/Event Updates /////////////
    String EVENT = "EVENT";
    String EVENT_ADD = "EVENT_ADD";
    String EVENT_EDIT = "EVENT_EDIT";
    String EVENT_DELETE = "EVENT_DELETE";

    ///////////////////// Single Payrun Updates ////////////////////
    String SINGLE_PAYRUN = "SINGLE_PAYRUN";
    String SINGLE_PAYRUN_ADD = "SINGLE_PAYRUN_ADD";
    String SINGLE_PAYRUN_EDIT = "SINGLE_PAYRUN_EDIT";
    String SINGLE_PAYRUN_DELETE = "SINGLE_PAYRUN_DELETE";
    String SINGLE_PAYRUN_SUBMIT = "SINGLE_PAYRUN_SUBMIT";
    String SINGLE_PAYRUN_APPROVE = "SINGLE_PAYRUN_APPROVE";
    String SINGLE_PAYRUN_REJECT = "SINGLE_PAYRUN_REJECT";

    ///////////////////// Group Payrun Updates ////////////////////
    String GROUP_PAYRUN = "GROUP_PAYRUN";
    String GROUP_PAYRUN_ADD = "GROUP_PAYRUN_ADD";
    String GROUP_PAYRUN_EDIT = "GROUP_PAYRUN_EDIT";
    String GROUP_PAYRUN_DELETE = "GROUP_PAYRUN_DELETE";
    String GROUP_PAYRUN_SUBMIT = "GROUP_PAYRUN_SUBMIT";
    String GROUP_PAYRUN_APPROVE = "GROUP_PAYRUN_APPROVE";
    String GROUP_PAYRUN_REJECT = "GROUP_PAYRUN_REJECT";

    ///////////////////// Cash Advance Updates /////////////////
    String CASH_ADVANCE = "CASH_ADVANCE";
    String CASH_ADVANCE_ADD = "CASH_ADVANCE_ADD";
    String CASH_ADVANCE_EDIT = "CASH_ADVANCE_EDIT";
    String CASH_ADVANCE_DELETE = "CASH_ADVANCE_DELETE";
    String CASH_ADVANCE_SUBMIT = "CASH_ADVANCE_SUBMIT";
    String CASH_ADVANCE_APPROVE = "CASH_ADVANCE_APPROVE";
    String CASH_ADVANCE_REJECT = "CASH_ADVANCE_REJECT";

    ///////////////////// Pension Scheme Updates /////////////////
    String PENSION_SCHEME = "PENSION_SCHEME";
    String PENSION_SCHEME_ADD = "PENSION_SCHEME_ADD";
    String PENSION_SCHEME_EDIT = "PENSION_SCHEME_EDIT";

    ///////////////////// End of Service Settings Updates /////////////
    String END_OF_SERVICE_SETTINGS = "END_OF_SERVICE_SETTINGS";
    String END_OF_SERVICE_SETTINGS_EDIT = "END_OF_SERVICE_SETTINGS_EDIT";

    ///////////////////// Task Related Updates//////////////////
    String TASK = "TASK";
    String TASK_ASSIGN = "TASK_ASSIGN";
    String TASK_ASSIGNEE_DELETE = "TASK_ASSIGNEE_DELETE";
    String TASK_STATUS_COMPELETED = "TASK_STATUS_COMPELETED";
    String TASK_STATUS_CANCELLED = "TASK_STATUS_CANCELLED";
    String TASK_STATUS_CLOSED = "TASK_STATUS_CLOSED";
    String TASK_DELETE = "TASK_DELETE";
    String TASK_ADD = "TASK_ADD";
    String TASK_UPDATE = "TASK_UPDATE";
    String TASK_FILE_UPLOAD = "TASK_FILE_UPLOAD";

    //////////////// Project Related Updates ////////////////////////////
    String PROJECT = "PROJECT";
    String PROJECT_ADD = "PROJECT_ADD";
    String PROJECT_DELETE = "PROJECT_DELETE";
    String PROJECT_DELETE_FOR_MANAGERS = "PROJECT_DELETE_FOR_MANAGERS";
    String PROJECT_DELETE_FOR_MEMBERS = "PROJECT_DELETE_FOR_MEMBERS";
    String PROJECT_UPDATE = "PROJECT_UPDATE";
    String PROJECT_STATUS_COMPLETED = "PROJECT_STATUS_COMPLETED";
    String PROJECT_MEMBER_ASSIGN = "PROJECT_MEMBER_ASSIGN";
    String PROJECT_MEMBER_DELETE = "PROJECT_MEMBER_DELETE";
    String PROJECT_MEMBER_EDIT = "PROJECT_MEMBER_EDIT";
    String PROJECT_MANAGER_ASSIGN = "PROJECT_MANAGER_ASSIGN";
    String PROJECT_BACKUP_MANAGER_ASSIGN = "PROJECT_BACKUP_MANAGER_ASSIGN";
    String PROJECT_UPDATE_FOR_MANAGER = "PROJECT_UPDATE_FOR_MANAGER";
    String PROJECT_UPDATE_FOR_BACKUP_MANAGER = "PROJECT_UPDATE_FOR_BACKUP_MANAGER";
    String PROJECT_IMPORT_TASKS_FROM_MS_PROJECT = "PROJECT_IMPORT_TASKS_FROM_MS_PROJECT";
    String PROJECT_FILE_UPLOAD = "PROJECT_FILE_UPLOAD";

    //////////////// User Related Updates ////////////////////////////
    String USER = "USER";
    String USER_CLIENT_CONTACT_ADD = "USER_CLIENT_CONTACT_ADD";
    String USER_CLIENT_CONTACT_EDIT = "USER_CLIENT_CONTACT_EDIT";
    String USER_CLIENT_CONTACT_DELETE = "USER_CLIENT_CONTACT_DELETE";
    String USER_EMPLOYEE_ADD = "USER_EMPLOYEE_ADD";
    String USER_EMPLOYEE_EDIT = "USER_EMPLOYEE_EDIT";
    String USER_EMPLOYEE_DELETE = "USER_EMPLOYEE_DELETE";
    String USER_EMPLOYEE_TERMINATE = "USER_EMPLOYEE_TERMINATE";

    //////////////// Department Related Updates ////////////////////////////
    String DEPARTMENT = "DEPARTMENT";
    String DEPARTMENT_ADD = "DEPARTMENT_ADD";
    String DEPARTMENT_EDIT = "DEPARTMENT_EDIT";
    String DEPARTMENT_DELETE = "DEPARTMENT_DELETE";
    String DEPARTMENT_EMPLOYEE_ADD = "DEPARTMENT_EMPLOYEE_ADD";
    String DEPARTMENT_EMPLOYEE_EDIT = "DEPARTMENT_EMPLOYEE_EDIT";
    String DEPARTMENT_EMPLOYEE_DELETE = "DEPARTMENT_EMPLOYEE_DELETE";
    String DEPARTMENT_EDIT_FOR_LEADER = "DEPARTMENT_EDIT_FOR_LEADER";
    String DEPARTMENT_DELETE_FOR_LEADER = "DEPARTMENT_DELETE_FOR_LEADER";

    ///////////////// Client Related Updates ////////////////////////////////
    String CLIENT = "CLIENT";
    String CLIENT_ADD = "CLIENT_ADD";
    String CLIENT_EDIT = "CLIENT_EDIT";
    String CLIENT_DELETE = "CLIENT_DELETE";

    ///////////////// Issue Related Updates ////////////////////////////////
    String ISSUE = "ISSUE";
    String ISSUE_ADD = "ISSUE_ADD";
    String ISSUE_EDIT = "ISSUE_EDIT";

    String ISSUE_TYPE_EMPLOYEE_ADD = "ISSUE_TYPE_EMPLOYEE_ADD";
    String ISSUE_TYPE_EMPLOYEE_EDIT = "ISSUE_TYPE_EMPLOYEE_EDIT";
    String ISSUE_TYPE_TASK_ADD = "ISSUE_TYPE_TASK_ADD";
    String ISSUE_TYPE_TASK_EDIT = "ISSUE_TYPE_TASK_EDIT";
    String ISSUE_TYPE_DEPARTMENT_ADD = "ISSUE_TYPE_DEPARTMENT_ADD";
    String ISSUE_TYPE_DEPARTMENT_EDIT = "ISSUE_TYPE_DEPARTMENT_EDIT";
    String ISSUE_TYPE_CLIENT_CUSTOMER_ADD = "ISSUE_TYPE_CLIENT_CUSTOMER_ADD";
    String ISSUE_TYPE_CLIENT_CUSTOMER_EDIT = "ISSUE_TYPE_CLIENT_CUSTOMER_EDIT";
    String ISSUE_TYPE_PROJECT_ADD = "ISSUE_TYPE_PROJECT_ADD";
    String ISSUE_TYPE_PROJECT_EDIT = "ISSUE_TYPE_PROJECT_EDIT";
    String ISSUE_FILE_UPLOAD = "ISSUE_FILE_UPLOAD";

    ///////////////// Location Related Updates ////////////////////////////////
    String LOCATION = "LOCATION";
    String LOCATION_ADD = "LOCATION_ADD";
    String LOCATION_EDIT = "LOCATION_EDIT";
    String LOCATION_DELETE = "LOCATION_DELETE";

    ///////////////// Lead Related Updates ////////////////////////////////
    String LEAD = "LEAD";
    String LEAD_ADD = "LEAD_ADD";
    String LEAD_EDIT = "LEAD_EDIT";
    String LEAD_DELETE = "LEAD_DELETE";

    ///////////////// Account Related Updates ////////////////////////////////
    String ACCOUNT = "ACCOUNT";
    String ACCOUNT_ADD = "ACCOUNT_ADD";
    String ACCOUNT_EDIT = "ACCOUNT_EDIT";
    String ACCOUNT_DELETE = "ACCOUNT_DELETE";

    ///////////////// WebForm Updates ////////////////////////////////
    String WEB_FORM = "WEB_FORM";
    String WEB_FORM_ADD = "WEB_FORM_ADD";
    String WEB_FORM_EDIT = "WEB_FORM_EDIT";
    String WEB_FORM_DELETE = "WEB_FORM_DELETE";

    ///////////////// Solution Updates ////////////////////////////////
    String SOLUTION = "SOLUTION";
    String SOLUTION_ADD = "SOLUTION_ADD";
    String SOLUTION_EDIT = "SOLUTION_EDIT";
    String SOLUTION_DELETE = "SOLUTION_DELETE";

    ///////////////// Case Updates ////////////////////////////////
    String CASE = "CASE";
    String CASE_ADD = "CASE_ADD";
    String CASE_EDIT = "CASE_EDIT";
    String CASE_DELETE = "CASE_DELETE";

    ///////////////// Campaign Related Updates ////////////////////////////////
    String CAMPAIGN = "CAMPAIGN";
    String CAMPAIGN_ADD = "CAMPAIGN_ADD";
    String CAMPAIGN_EDIT = "CAMPAIGN_EDIT";
    String CAMPAIGN_DELETE = "CAMPAIGN_DELETE";

    ///////////////// Contact Related Updates ////////////////////////////////
    String CONTACT = "CONTACT";
    String CONTACT_ADD = "CONTACT_ADD";
    String CONTACT_EDIT = "CONTACT_EDIT";
    String CONTACT_DELETE = "CONTACT_DELETE";

    ///////////////// OPPORTUNITY Related Updates ////////////////////////////////
    String OPPORTUNITY = "OPPORTUNITY";
    String OPPORTUNITY_ADD = "OPPORTUNITY_ADD";
    String OPPORTUNITY_EDIT = "OPPORTUNITY_EDIT";
    String OPPORTUNITY_DELETE = "OPPORTUNITY_DELETE";
    String OPPORTUNITY_APPROVED = "OPPORTUNITY_APPROVED";
    String OPPORTUNITY_REJECTED = "OPPORTUNITY_REJECTED";
    String OPPORTUNITY_DRAFT = "OPPORTUNITY_DRAFT";

    ///////////////// CRM CONTACT CATEGORY Related Updates ////////////////////////////////
    String CATEGORY = "CATEGORY";
    String CATEGORY_ADD = "CATEGORY_ADD";
    String CATEGORY_EDIT = "CATEGORY_EDIT";
    String CATEGORY_DELETE = "CATEGORY_DELETE";

    ///////////////// CRM CONTACT CATEGORY Related Updates ////////////////////////////////
    String MAILING = "MAILING";
    String MAILING_ADD = "MAILING_ADD";
    String MAILING_EDIT = "MAILING_EDIT";
    String MAILING_DELETE = "MAILING_DELETE";

    ///////////////// Timesheet Related Updates ////////////////////////////////
    String TIMESHEET = "TIMESHEET";
    String TIMESHEET_STATUS_WAITING = "TIMESHEET_STATUS_WAITING";
    String TIMESHEET_STATUS_REJECTED = "TIMESHEET_STATUS_REJECTED";
    String TIMESHEET_STATUS_APPROVED = "TIMESHEET_STATUS_APPROVED";

    String TIMESHEET_STATUS_WAITING_FOR_EMPLOYEE = "TIMESHEET_STATUS_WAITING_FOR_EMPLOYEE";
    String TIMESHEET_STATUS_REJECTED_FOR_EMPLOYEE = "TIMESHEET_STATUS_REJECTED_FOR_EMPLOYEE";
    String TIMESHEET_STATUS_APPROVED_FOR_EMPLOYEE = "TIMESHEET_STATUS_APPROVED_FOR_EMPLOYEE";

    String TIMESHEET_STATUS_WAITING_FOR_MANAGER = "TIMESHEET_STATUS_WAITING_FOR_MANAGER";
    String TIMESHEET_STATUS_REJECTED_FOR_MANAGER = "TIMESHEET_STATUS_REJECTED_FOR_MANAGER";
    String TIMESHEET_STATUS_APPROVED_FOR_MANAGER = "TIMESHEET_STATUS_APPROVED_FOR_MANAGER";

    ///////////////// TimeSlot Updates ////////////////////////////////
    String TIMESLOT = "TIMESLOT";
    String TIMESLOT_ADD = "TIMESLOT_ADD";
    String TIMESLOT_EDIT = "TIMESLOT_EDIT";
    String TIMESLOT_DELETE = "TIMESLOT_DELETE";

    ///////////////// Holiday Updates ////////////////////////////////
    String HOLIDAY = "HOLIDAY";
    String HOLIDAY_ADD = "HOLIDAY_ADD";
    String HOLIDAY_EDIT = "HOLIDAY_EDIT";
    String HOLIDAY_DELETE = "HOLIDAY_DELETE";

    ///////////////// Workspace Note Related Updates ////////////////////////////////
    String WORKSPACE_NOTE = "WORKSPACE_NOTE";
    String WORKSPACE_NOTE_ADD = "WORKSPACE_NOTE_ADD";
    String WORKSPACE_NOTE_EDIT = "WORKSPACE_NOTE_EDIT";
    String WORKSPACE_NOTE_DELETE = "WORKSPACE_NOTE_DELETE";

    ///////////////// Note Related Updates ////////////////////////////////
    String CONTACT_NOTE = "CONTACT_NOTE";
    String CONTACT_NOTE_ADD = "CONTACT_NOTE_ADD";
    String CONTACT_NOTE_EDIT = "CONTACT_NOTE_EDIT";
    String CONTACT_NOTE_DELETE = "CONTACT_NOTE_DELETE";

    ///////////////// Note Related Updates ////////////////////////////////
    String LEAD_NOTE = "LEAD_NOTE";
    String LEAD_NOTE_ADD = "LEAD_NOTE_ADD";
    String LEAD_NOTE_EDIT = "LEAD_NOTE_EDIT";
    String LEAD_NOTE_DELETE = "LEAD_NOTE_DELETE";

    ///////////////// Product Related Updates /////////////////////////
    String PRODUCT = "PRODUCT";
    String PRODUCT_ADD = "PRODUCT_ADD";
    String PRODUCT_EDIT = "PRODUCT_EDIT";
    String PRODUCT_DELETE = "PRODUCT_DELETE";

    ///////////////// Fixed Asset Related Updates /////////////////////////
    String FIXED_ASSET = "FIXED_ASSET";
    String FIXED_ASSET_ADD = "FIXED_ASSET_ADD";
    String FIXED_ASSET_EDIT = "FIXED_ASSET_EDIT";
    String FIXED_ASSET_DELETE = "FIXED_ASSET_DELETE";
    String FIXED_ASSET_DISPOSE = "FIXED_ASSET_DISPOSE";
    String FIXED_ASSET_OWNER_ADD = "FIXED_ASSET_OWNER_ADD";
    String FIXED_ASSET_OWNER_EDIT = "FIXED_ASSET_OWNER_EDIT";

    ///////////////// Fixed Asset Related Updates /////////////////////////
    String CHECK = "CHECK";
    String CHECK_ADD = "CHECK_ADD";
    String CHECK_EDIT = "CHECK_EDIT";
    String CHECK_DELETE = "CHECK_DELETE";

    ///////////////// Bank Account Related Updates /////////////////////////
    String BANK_ACCOUNT = "BANK_ACCOUNT";
    String BANK_ACCOUNT_ADD = "BANK_ACCOUNT_ADD";
    String BANK_ACCOUNT_EDIT = "BANK_ACCOUNT_EDIT";
    String BANK_ACCOUNT_DELETE = "BANK_ACCOUNT_DELETE";

    ///////////////// Chart of Account  Related Updates /////////////////////////
    String CHART_OF_ACCOUNT = "CHART_OF_ACCOUNT";
    String CHART_OF_ACCOUNT_ADD = "CHART_OF_ACCOUNT_ADD";
    String CHART_OF_ACCOUNT_EDIT = "CHART_OF_ACCOUNT_EDIT";
    String CHART_OF_ACCOUNT_DELETE = "CHART_OF_ACCOUNT_DELETE";

    ///////////////// Sales Invoice Related Updates /////////////////////////
    String SALES_INVOICE = "SALES_INVOICE";
    String SALES_INVOICE_ADD = "SALES_INVOICE_ADD";
    String SALES_INVOICE_EDIT = "SALES_INVOICE_EDIT";
    String SALES_INVOICE_DELETE = "SALES_INVOICE_DELETE";
    String SALES_INVOICE_SEND_TO_CLIENT = "SALES_INVOICE_SEND_TO_CLIENT";
    String SALES_INVOICE_PAYMENT_RECEIVE = "SALES_INVOICE_PAYMENT_RECEIVE";
    String SALES_INVOICE_CONVERTED_FROM_SALES_QUOTE = "SALES_INVOICE_CONVERTED_FROM_SALES_QUOTE";
    String SALES_INVOICE_PAYMENT_VOID = "SALES_INVOICE_PAYMENT_VOID";
    String SALES_INVOICE_PAYMENT_DELETE = "SALES_INVOICE_PAYMENT_DELETE";
    String SALES_INVOICE_ADD_CREDIT_NOTE = "SALES_INVOICE_ADD_CREDIT_NOTE";
    String SALES_INVOICE_REFUND = "SALES_INVOICE_REFUND";
    String SALES_INVOICE_SUBMITTED_TO_MANAGER = "SALES_INVOICE_SUBMITTED_TO_MANAGER";
    String SALES_INVOICE_MANAGER_APPROVE = "SALES_INVOICE_MANAGER_APPROVE";
    String SALES_INVOICE_MANAGER_REJECT = "SALES_INVOICE_MANAGER_REJECT";
    String REJECTED_SALES_INVOICE = "REJECTED_SALES_INVOICE";
    String CLIENT_APPROVED_SALES_INVOICE = "CLIENT_APPROVED_SALES_INVOICE";
    String HAS_SUBMIT_SALES_INVOICE_TO_MANAGER = "HAS_SUBMIT_SALES_INVOICE_TO_MANAGER";
    String SALES_INVOICE_WEBHOOK_RESPONSE_ADD = "SALES_INVOICE_WEBHOOK_RESPONSE_ADD";


    /////////////////// Additional Payment ///////////////////
    String ADDITIONAL_PAYMENT = "ADDITIONAL_PAYMENT";
    String ADDITIONAL_PAYMENT_ADD = "ADDITIONAL_PAYMENT_ADD";
    String ADDITIONAL_PAYMENT_EDIT = "ADDITIONAL_PAYMENT_EDIT";
    String ADDITIONAL_PAYMENT_DELETED = "ADDITIONAL_PAYMENT_DELETED";
    String ADDITIONAL_PAYMENT_APPROVED = "ADDITIONAL_PAYMENT_APPROVED";
    String ADDITIONAL_PAYMENT_REJECTED = "ADDITIONAL_PAYMENT_REJECTED";
    String ADDITIONAL_PAYMENT_DRAFT = "ADDITIONAL_PAYMENT_DRAFT";
    String ADDITIONAL_PAYMENT_SUBMITTED_TO_MANAGER = "ADDITIONAL_PAYMENT_SUBMITTED_TO_MANAGER";


    String REJECTED_ADDITIONAL_PAYMENT = "REJECTED_ADDITIONAL_PAYMENT";
    String ADDED_ADDITIONAL_PAYMENT = "ADDED_ADDITIONAL_PAYMENT";
    String EDITED_ADDITIONAL_PAYMENT = "EDITED_ADDITIONAL_PAYMENT";
    String DRAFT_ADDITIONAL_PAYMENT = "DRAFT_ADDITIONAL_PAYMENT";
    String APPROVED_ADDITIONAL_PAYMENT = "APPROVED_ADDITIONAL_PAYMENT";
    String SUBMITTED_TO_MANAGER_ADDITIONAL_PAYMENT = "SUBMITTED_TO_MANAGER_ADDITIONAL_PAYMENT";

    ///////////////// Recurring Invoice Related Updates /////////////////////////
    String RECURRING_INVOICE = "RECURRING_INVOICE";
    String RECURRING_INVOICE_ADD = "RECURRING_INVOICE_ADD";
    String RECURRING_INVOICE_EDIT = "RECURRING_INVOICE_EDIT";
    String RECURRING_INVOICE_DELETE = "RECURRING_INVOICE_DELETE";
//    public static final String RECURRING_INVOICE_SEND_TO_CLIENT = "RECURRING_INVOICE_SEND_TO_CLIENT";

    ///////////////// Sales Quote Updates /////////////////////////
    String SALES_QUOTE = "SALES_QUOTE";
    String SALES_QUOTE_ADD = "SALES_QUOTE_ADD";
    String SALES_QUOTE_EDIT = "SALES_QUOTE_EDIT";
    String SALES_QUOTE_DELETE = "SALES_QUOTE_DELETE";

    String SALES_QUOTE_CONVERT_TO_SALE_ORDER = "SALES_QUOTE_CONVERT_TO_SALE_ORDER";

    String SALES_QUOTE_CLIENT_APPROVE = "SALES_QUOTE_CLIENT_APPROVE";
    String SALES_QUOTE_REJECT = "SALES_QUOTE_REJECT";

    String SALES_QUOTE_SEND_TO_CLIENT = "SALES_QUOTE_SEND_TO_CLIENT";
    String SALES_QUOTE_SUBMITTED_TO_MANAGER = "SALES_QUOTE_SUBMITTED_TO_MANAGER";
    String SALES_QUOTE_APPROVE = "SALES_QUOTE_APPROVE";

    String SALES_QUOTE_MANAGER_APPROVE = "SALES_QUOTE_MANAGER_APPROVE";
    String SALES_QUOTE_MANAGER_REJECT = "SALES_QUOTE_MANAGER_REJECT";
    String SALES_QUOTE_CLOSED = "SALES_QUOTE_CLOSED";
    String SALES_QUOTE_WEBHOOK_RESPONSE_ADD = "SALES_QUOTE_WEBHOOK_RESPONSE_ADD";

    ///////////////// Sales Quote Updates /////////////////////////
    String SALES_ORDER = "SALES_ORDER";
    String SALES_ORDER_ADD = "SALES_ORDER_ADD";
    String SALES_ORDER_EDIT = "SALES_ORDER_EDIT";
    String SALES_ORDER_DELETE = "SALES_ORDER_DELETE";
    String SALES_ORDER_PICKLIST = "SALES_ORDER_PICKLIST";
    String SALES_ORDER_CLOSED = "SALES_ORDER_CLOSED";
    String SALES_ORDER_CONVERT_FROM_SQ = "SALES_ORDER_CONVERT_FROM_SQ";
    String SALES_ORDER_MANAGER_REJECT = "SALES_ORDER_MANAGER_REJECT";
    String SALES_ORDER_MANAGER_APPROVE = "SALES_ORDER_MANAGER_APPROVE";
    String SALES_ORDER_SUBMITTED_TO_MANAGER = "SALES_ORDER_SUBMITTED_TO_MANAGER";
    String HAS_SUBMIT_SALES_ORDER_TO_MANAGER = "HAS_SUBMIT_SALES_ORDER_TO_MANAGER";
    String MANAGER_APPROVED_SALES_ORDER = "MANAGER_APPROVED_SALES_ORDER";
    String MANAGER_APPROVED_SALES_QUOTE = "MANAGER_APPROVED_SALES_QUOTE";
    String REJECTED_SALES_ORDER = "REJECTED_SALES_ORDER";


    ///////////////// Purchase Order Updates /////////////////////////
    String PURCHASE_ORDER = "PURCHASE_ORDER";
    String PURCHASE_ORDER_ADD = "PURCHASE_ORDER_ADD";
    String PURCHASE_ORDER_EDIT = "PURCHASE_ORDER_EDIT";
    String PURCHASE_ORDER_DELETE = "PURCHASE_ORDER_DELETE";
    String PURCHASE_ORDER_SEND_TO_CLIENT = "PURCHASE_ORDER_SEND_TO_CLIENT";
    String PURCHASE_ORDER_APPROVE = "PURCHASE_ORDER_APPROVE";
    String PURCHASE_ORDER_RECEIVED = "PURCHASE_ORDER_RECEIVED";
    String PURCHASE_ORDER_PARTIAL_RECEIVED = "PURCHASE_ORDER_PARTIAL_RECEIVED";
    String PURCHASE_ORDER_SUBMITTED_TO_MANAGER = "PURCHASE_ORDER_SUBMITTED_TO_MANAGER";
    String HAS_SUBMIT_PURCHASE_ORDER_TO_MANAGER = "HAS_SUBMIT_PURCHASE_ORDER_TO_MANAGER";
    String YOU_HAVE_SUBMITTED_PURCHASE_ORDER_TO_MANAGER = "YOU_HAVE_SUBMITTED_PURCHASE_ORDER_TO_MANAGER";
    String PURCHASE_ORDER_CLOSED = "PURCHASE_ORDER_CLOSED";
    String HAS_PURCHASE_ORDER_CLOSED = "HAS_PURCHASE_ORDER_CLOSED";
    String PURCHASE_ORDER_WEBHOOK_RESPONSE_ADD = "PURCHASE_ORDER_WEBHOOK_RESPONSE_ADD";
    String DEBIT_NOTE_WEBHOOK_RESPONSE_ADD = "DEBIT_NOTE_WEBHOOK_RESPONSE_ADD";
    String CREDIT_NOTE_WEBHOOK_RESPONSE_ADD = "CREDIT_NOTE_WEBHOOK_RESPONSE_ADD";

    ///////////////// Purchase Invoice Updates /////////////////////////
    String PURCHASE_INVOICE = "PURCHASE_INVOICE";
    String PURCHASE_INVOICE_ADD = "PURCHASE_INVOICE_ADD";
    String PURCHASE_INVOICE_EDIT = "PURCHASE_INVOICE_EDIT";
    String PURCHASE_INVOICE_DELETE = "PURCHASE_INVOICE_DELETE";
    String PURCHASE_INVOICE_APPROVE = "PURCHASE_INVOICE_APPROVE";
    String PURCHASE_INVOICE_ADD_CREDIT_NOTE = "PURCHASE_INVOICE_ADD_CREDIT_NOTE";
    String PURCHASE_INVOICE_PAYMENT_VOID = "PURCHASE_INVOICE_PAYMENT_VOID";
    String PURCHASE_INVOICE_PAYMENT_DELETE = "PURCHASE_INVOICE_PAYMENT_DELETE";
    String PURCHASE_INVOICE_PAYMENT_PAY = "PURCHASE_INVOICE_PAYMENT_PAY";
    String PURCHASE_INVOICE_REFUND = "PURCHASE_INVOICE_REFUND";
    String PURCHASE_INVOICE_SUBMITTED_TO_MANAGER = "PURCHASE_INVOICE_SUBMITTED_TO_MANAGER";
    String PURCHASE_INVOICE_MANAGER_APPROVE = "PURCHASE_INVOICE_MANAGER_APPROVE";
    String PURCHASE_INVOICE_MANAGER_REJECT = "PURCHASE_INVOICE_MANAGER_REJECT";
    String HAS_SUBMIT_PURCHASE_INVOICE_TO_MANAGER = "HAS_SUBMIT_PURCHASE_INVOICE_TO_MANAGER";
    String MANAGER_APPROVED_PURCHASE_INVOICE = "MANAGER_APPROVED_PURCHASE_INVOICE";
    String REJECTED_PURCHASE_INVOICE = "REJECTED_PURCHASE_INVOICE";
    String PURCHASE_INVOICE_WEBHOOK_RESPONSE_ADD = "PURCHASE_INVOICE_WEBHOOK_RESPONSE_ADD";

    /////////////////// Expense Report Updates ///////////////////////
    String EXPENSE_REPORT = "EXPENSE_REPORT";
    String EXPENSE_REPORT_ADD = "EXPENSE_REPORT_ADD";
    String EXPENSE_REPORT_EDIT = "EXPENSE_REPORT_EDIT";
    String EXPENSE_REPORT_DELETE = "EXPENSE_REPORT_DELETE";
    String EXPENSE_REPORT_APPROVE = "EXPENSE_REPORT_APPROVE";
    String EXPENSE_REPORT_DECLINE = "EXPENSE_REPORT_DECLINE";
    String EXPENSE_REPORT_SEND_TO_APPROVER = "EXPENSE_REPORT_SEND_TO_APPROVER";
    String EXPENSE_REPORT_GET_FROM_REPORTER = "EXPENSE_REPORT_GET_FROM_REPORTER";
    String EXPENSE_REPORT_WEBHOOK_RESPONSE_ADD = "EXPENSE_REPORT_WEBHOOK_RESPONSE_ADD";

    /////////////////// Expense Payment Updates ///////////////////////
    String EXPENSE_PAYMENT = "EXPENSE_PAYMENT";
    String EXPENSE_PAYMENT_ADD = "EXPENSE_PAYMENT_ADD";

    /////////////////// Bank Transfer Updates /////////////////////////
    String BANK_TRANSFER = "BANK_TRANSFER";
    String BANK_TRANSFER_ADD = "BANK_TRANSFER_ADD";
    String BANK_TRANSFER_APPLIED = "BANK_TRANSFER_APPLIED";
    String BANK_TRANSFER_APPLIED_RECEIVABLE = "BANK_TRANSFER_APPLIED_RECEIVABLE";
    String BANK_TRANSFER_APPLIED_PAYABLE = "BANK_TRANSFER_APPLIED_PAYABLE";
    String BANK_TRANSFER_APPLIED_PAYABLE_MESSAGE = "BANK_TRANSFER_APPLIED_PAYABLE_MESSAGE";
    String BANK_TRANSFER_APPLIED_RECEIVABLE_MESSAGE = "BANK_TRANSFER_APPLIED_RECEIVABLE_MESSAGE";
    String BANK_TRANSFER_EDIT = "BANK_TRANSFER_EDIT";
    String BANK_TRANSFER_DELETE = "BANK_TRANSFER_DELETE";

    /////////////////// Bank Transfer Updates /////////////////////////
    String CUSTOM_FORM_ITEM = "CUSTOM_FORM_ITEM";
    String CUSTOM_FORM_ITEM_ADD = "CUSTOM_FORM_ITEM_ADD";
    String CUSTOM_FORM_ITEM_EDIT = "CUSTOM_FORM_ITEM_EDIT";
    String CUSTOM_FORM_ITEM_DELETE = "CUSTOM_FORM_ITEM_DELETE";
    String CUSTOM_FORM_ITEM_SUBMITTED_TO_MANAGER = "CUSTOM_FORM_ITEM_SUBMITTED_TO_MANAGER";
    String CUSTOM_FORM_ITEM_MANAGER_APPROVE = "CUSTOM_FORM_ITEM_MANAGER_APPROVE";
    String CUSTOM_FORM_ITEM_MANAGER_REJECT = "CUSTOM_FORM_ITEM_MANAGER_REJECT";
    String MANAGER_APPROVED_CUSTOM_FROM_ITEM = "MANAGER_APPROVED_CUSTOM_FROM_ITEM";
    String REJECTED_CUSTOM_FROM_ITEM = "REJECTED_CUSTOM_FROM_ITEM";
    String HAS_SUBMIT_CUSTOM_FROM_ITEM_TO_MANAGER = "HAS_SUBMIT_CUSTOM_FROM_ITEM_TO_MANAGER";

    /////////////////// Manual Transaction ///////////////////////////
    String MANUAL_TRANSACTION = "MANUAL_TRANSACTION";
    String MANUAL_TRANSACTION_ADD = "MANUAL_TRANSACTION_ADD";
    String MANUAL_TRANSACTION_EDIT = "MANUAL_TRANSACTION_EDIT";
    String MANUAL_TRANSACTION_DELETE = "MANUAL_TRANSACTION_DELETE";
    /////////////////// Invoice Payment Updates //////////////////////
    String INVOICE_PAYMENT = "INVOICE_PAYMENT";
    String INVOICE_PAYMENT_ADD = "INVOICE_PAYMENT_ADD";
    String INVOICE_PAYMENT_EDIT = "INVOICE_PAYMENT_EDIT";
    String INVOICE_PAYMENT_DELETE = "INVOICE_PAYMENT_DELETE";
    /////////////////// Batch Payment Updates ////////////////////////
    String BATCH_PAYMENT = "BATCH_PAYMENT";
    String BATCH_PAYMENT_ADD = "BATCH_PAYMENT_ADD";
    String BATCH_PAYMENT_EDIT = "BATCH_PAYMENT_EDIT";
    String BATCH_PAYMENT_DELETE = "BATCH_PAYMENT_DELETE";
    String BATCH_PAYMENT_VOID = "BATCH_PAYMENT_VOID";
    //////////////////// Calendar Event Guest Updates //////////////////////////
    String CALENDAR_EVENT_GUEST = "CALENDAR_EVENT_GUEST";
    String CALENDAR_EVENT_GUEST_STATUS_ACCEPTED = "CALENDAR_EVENT_GUEST_STATUS_ACCEPTED";
    String CALENDAR_EVENT_GUEST_STATUS_TENTATIVELY = "CALENDAR_EVENT_GUEST_STATUS_TENTATIVELY";
    String CALENDAR_EVENT_GUEST_STATUS_DECLINED = "CALENDAR_EVENT_GUEST_STATUS_DECLINED";

    ////////////////////////// LEAVE REQUEST Updates ////////////////////////////////////
    String LEAVE_REQUEST = "LEAVE_REQUEST";
    String LEAVE_REQUEST_ADD = "LEAVE_REQUEST_ADD";
    String LEAVE_REQUEST_EDIT = "LEAVE_REQUEST_EDIT";
    String LEAVE_REQUEST_DELETE = "LEAVE_REQUEST_DELETE";

    /////////////////////////// Rental order Updates //////////////////////////////////
    String ACCOUNTING_RENTAL_ORDER = "RENTAL_ORDER";
    String ACCOUNTING_RENTAL_ORDER_ADD = "RENTAL_ORDER_ADD";
    String ACCOUNTING_RENTAL_ORDER_EDIT = "RENTAL_ORDER_EDIT";
    String ACCOUNTING_RENTAL_ORDER_DELETE = "RENTAL_ORDER_DELETE";
    String ACCOUNTING_RENTAL_ORDER_APPROVE = "RENTAL_ORDER_APPROVE";
    String ACCOUNTING_RENTAL_ORDER_DECLINE = "RENTAL_ORDER_DECLINE";
    String ACCOUNTING_RENTAL_ORDER_SEND_TO_APPROVER = "RENTAL_ORDER_SEND_TO_APPROVER";

    /////////////////////////// Build Assembly Updates //////////////////////////////////
    String ACCOUNTING_BUILD_ASSEMBLY = "BUILD_ASSEMBLY";
    String ACCOUNTING_BUILD_ASSEMBLY_ADD = "BUILD_ASSEMBLY_ADD";
    String ACCOUNTING_BUILD_ASSEMBLY_EDIT = "BUILD_ASSEMBLY_EDIT";
    String ACCOUNTING_BUILD_ASSEMBLY_DELETE = "BUILD_ASSEMBLY_DELETE";
    String ACCOUNTING_BUILD_ASSEMBLY_APPROVE = "BUILD_ASSEMBLY_APPROVE";
    String ACCOUNTING_BUILD_ASSEMBLY_DECLINE = "BUILD_ASSEMBLY_DECLINE";
    String ACCOUNTING_BUILD_ASSEMBLY_SEND_TO_APPROVER = "BUILD_ASSEMBLY_SEND_TO_APPROVER";

    ///////////////////////////My Update Type Manager//////////////////////////////////
    String ADDED_LEAD = "ADDED_LEAD";
    String EDITED_LEAD = "EDITED_LEAD";
    String DELETED_LEAD = "DELETED_LEAD";
    String ADDED_LEAD_BY = "ADDED_LEAD_BY";
    String EDITED_LEAD_BY = "EDITED_LEAD_BY";
    String DELETED_LEAD_BY = "DELETED_LEAD_BY";

    String ADDED_CAMPAIGN = "ADDED_CAMPAIGN";
    String EDITED_CAMPAIGN = "EDITED_CAMPAIGN";
    String DELETED_CAMPAIGN = "DELETED_CAMPAIGN";
    String ADDED_CAMPAIGN_BY = "ADDED_CAMPAIGN_BY";
    String EDITED_CAMPAIGN_BY = "EDITED_CAMPAIGN_BY";
    String DELETED_CAMPAIGN_BY = "DELETED_CAMPAIGN_BY";

    String ADDED_ACCOUNT = "ADDED_ACCOUNT";
    String EDITED_ACCOUNT = "EDITED_ACCOUNT";
    String DELETED_ACCOUNT = "DELETED_ACCOUNT";
    String ADDED_ACCOUNT_BY = "ADDED_ACCOUNT_BY";
    String EDITED_ACCOUNT_BY = "EDITED_ACCOUNT_BY";
    String DELETED_ACCOUNT_BY = "DELETED_ACCOUNT_BY";
    String CRM_ACCOUNT = "CRM_ACCOUNT";
    String CRM_CLIENT = "CRM_CLIENT";
    String CRM_SUPPLIER = "CRM_SUPPLIER";

    String ADDED_WEB_FORM = "ADDED_WEB_FORM";
    String EDITED_WEB_FORM = "EDITED_WEB_FORM";
    String DELETED_WEB_FORM = "DELETED_WEB_FORM";
    String ADDED_WEB_FORM_BY = "ADDED_WEB_FORM_BY";
    String EDITED_WEB_FORM_BY = "EDITED_WEB_FORM_BY";
    String DELETED_WEB_FORM_BY = "DELETED_WEB_FORM_BY";

    String ADDED_CASE = "ADDED_CASE";
    String EDITED_CASE = "EDITED_CASE";
    String DELETED_CASE = "DELETED_CASE";
    String ADDED_CASE_BY = "ADDED_CASE_BY";
    String EDITED_CASE_BY = "EDITED_CASE_BY";
    String DELETED_CASE_BY = "DELETED_CASE_BY";

    String ADDED_SOLUTION = "ADDED_SOLUTION";
    String EDITED_SOLUTION = "EDITED_SOLUTION";
    String DELETED_SOLUTION = "DELETED_SOLUTION";
    String ADDED_SOLUTION_BY = "ADDED_SOLUTION_BY";
    String EDITED_SOLUTION_BY = "EDITED_SOLUTION_BY";
    String DELETED_SOLUTION_BY = "DELETED_SOLUTION_BY";


    String ADDED_CONTACT = "ADDED_CONTACT";
    String EDITED_CONTACT = "EDITED_CONTACT";
    String DELETED_CONTACT = "DELETED_CONTACT";
    String ADDED_CONTACT_BY = "ADDED_CONTACT_BY";
    String EDITED_CONTACT_BY = "EDITED_CONTACT_BY";
    String DELETED_CONTACT_BY = "DELETED_CONTACT_BY";

    String ADDED_OPPORTUNITY = "ADDED_OPPORTUNITY";
    String EDITED_OPPORTUNITY = "EDITED_OPPORTUNITY";
    String DELETED_OPPORTUNITY = "DELETED_OPPORTUNITY";
    String ADDED_OPPORTUNITY_BY = "ADDED_OPPORTUNITY_BY";
    String EDITED_OPPORTUNITY_BY = "EDITED_OPPORTUNITY_BY";
    String DELETED_OPPORTUNITY_BY = "DELETED_OPPORTUNITY_BY";

    String ADDED_CATEGORY = "ADDED_CATEGORY";
    String EDITED_CATEGORY = "EDITED_CATEGORY";
    String ADDED_CATEGORY_BY = "ADDED_CATEGORY_BY";
    String EDITED_CATEGORY_BY = "EDITED_CATEGORY_BY";

    String ADDED_MAILING = "ADDED_MAILING";
    String EDITED_MAILING = "EDITED_MAILING";
    String ADDED_MAILING_BY = "ADDED_MAILING_BY";
    String EDITED_MAILING_BY = "EDITED_MAILING_BY";

    String ADDED_TIMESLOT = "ADDED_TIMESLOT";
    String EDITED_TIMESLOT = "EDITED_TIMESLOT";
    String DELETED_TIMESLOT = "DELETED_TIMESLOT";
    String ADDED_TIMESLOT_BY = "ADDED_TIMESLOT_BY";
    String EDITED_TIMESLOT_BY = "EDITED_TIMESLOT_BY";
    String DELETED_TIMESLOT_BY = "DELETED_TIMESLOT_BY";

    String ADDED_HOLIDAY = "ADDED_HOLIDAY";
    String EDITED_HOLIDAY = "EDITED_HOLIDAY";
    String DELETED_HOLIDAY = "DELETED_HOLIDAY";
    String ADDED_HOLIDAY_BY = "ADDED_HOLIDAY_BY";
    String EDITED_HOLIDAY_BY = "EDITED_HOLIDAY_BY";
    String DELETED_HOLIDAY_BY = "DELETED_HOLIDAY_BY";


    String ADDED_NOTE = "ADDED_NOTE";
    String YOU_HAVE_ADDED_NOTE = "YOU_HAVE_ADDED_NOTE";
    String UPDATED_NOTE = "UPDATED_NOTE";
    String YOU_HAVE_UPDATED_NOTE = "YOU_HAVE_UPDATED_NOTE";
    String HAS_DELETED_NOTE = "HAS_DELETED_NOTE";
    String YOU_HAVE_DELETED_NOTE = "YOU_HAVE_DELETED_NOTE";

    String ADDED_CONTACT_NOTE = "ADDED_CONTACT_NOTE";
    String YOU_HAVE_ADDED_CONTACT_NOTE = "YOU_HAVE_ADDED_CONTACT_NOTE";
    String UPDATED_CONTACT_NOTE = "UPDATED_CONTACT_NOTE";
    String YOU_HAVE_UPDATED_CONTACT_NOTE = "YOU_HAVE_UPDATED_CONTACT_NOTE";
    String HAS_DELETED_CONTACT_NOTE = "HAS_DELETED_CONTACT_NOTE";
    String YOU_HAVE_DELETED_CONTACT_NOTE = "YOU_HAVE_DELETED_CONTACT_NOTE";

    String ADDED_LEAD_NOTE = "ADDED_LEAD_NOTE";
    String YOU_HAVE_ADDED_LEAD_NOTE = "YOU_HAVE_ADDED_LEAD_NOTE";
    String UPDATED_LEAD_NOTE = "UPDATED_LEAD_NOTE";
    String YOU_HAVE_UPDATED_LEAD_NOTE = "YOU_HAVE_UPDATED_LEAD_NOTE";
    String HAS_DELETED_LEAD_NOTE = "HAS_DELETED_LEAD_NOTE";
    String YOU_HAVE_DELETED_LEAD_NOTE = "YOU_HAVE_DELETED_LEAD_NOTE";

    String SUBMIT_TIMESHEET_FOR_APPROVAL = "SUBMIT_TIMESHEET_FOR_APPROVAL";
    String YOUR_TIMESHEET_ENTRIES_HAVE_BENN_SUBMITED_FOR_APPROVAL = "YOUR_TIMESHEET_ENTRIES_HAVE_BENN_SUBMITED_FOR_APPROVAL";
    String SUBMITED_TIMESHEET_ENTRIES_FOR_YOUR_APPROVAL = "SUBMITED_TIMESHEET_ENTRIES_FOR_YOUR_APPROVAL";
    String REVIEWED = "REVIEWED";
    String YOU_HAVE_APPROVED = "YOU_HAVE_APPROVED";
    String YOU_HAVE_REJECTED = "YOU_HAVE_REJECTED";
    String YOU_HAVE_APPROVED_YOUR_TIMESHEET_ENTRIES = "YOU_HAVE_APPROVED_YOUR_TIMESHEET_ENTRIES";
    String YOUR_TIMESHEET_ENTRIES_HAVE_BEEN_APPROVED_BY = "YOUR_TIMESHEET_ENTRIES_HAVE_BEEN_APPROVED_BY";
    String YOU_HAVE_REJECTED_YOUR = "YOU_HAVE_REJECTED_YOUR";
    String YOUR_TIMESHEET_ENTRIES_HAVE_BEEN_REJECTED_BY = "YOUR_TIMESHEET_ENTRIES_HAVE_BEEN_REJECTED_BY";
    String ADDED_LOCATION = "ADDED_LOCATION";
    String YOU_HAVE_ADDED_LOCATION = "YOU_HAVE_ADDED_LOCATION";
    String UPDATED_LOCATION = "UPDATED_LOCATION";
    String YOU_HAVE_UPDATED_LOCATION = "YOU_HAVE_UPDATED_LOCATION";
    String DELETE_LOCATION = "DELETE_LOCATION";
    String YOU_HAVE_DELETE_LOCATION = "YOU_HAVE_DELETE_LOCATION";
    String HAS_ADDED_SALES_INVOICE = "HAS_ADDED_SALES_INVOICE";
    String YOU_HAVE_ADDED_SALES_INVOICE = "YOU_HAVE_ADDED_SALES_INVOICE";
    String HAS_UPDATED_SALES_INVOICE = "HAS_UPDATED_SALES_INVOICE";
    String HAS_ADDED_MANUAL_JOURNAL = "HAS_ADDED_MANUAL_JOURNAL";
    String HAS_ADDED_RFQ = "HAS_ADDED_RFQ";
    String HAS_EDITED_RFQ = "HAS_EDITED_RFQ";
    String HAS_DELETED_RFQ = "HAS_DELETED_RFQ";


    String HAS_ADDED_RFP = "HAS_ADDED_RFP";
    String HAS_EDITED_RFP = "HAS_EDITED_RFP";
    String HAS_DELETED_RFP = "HAS_DELETED_RFP";
    String RFP_SUBMITTED_TO_MANAGER = "RFP_SUBMITTED_TO_MANAGER";
    String RFP_MANAGER_APPROVE = "RFP_MANAGER_APPROVE";
    String RFP_MANAGER_REJECT = "RFP_MANAGER_REJECT";
    String REJECTED_RFP = "REJECTED_RFP";
    String CLIENT_APPROVED_RFP = "CLIENT_APPROVED_RFP";
    String HAS_SUBMIT_RFP_TO_MANAGER = "HAS_SUBMIT_RFP_TO_MANAGER";

    String HAS_ADDED_STOCK_TRANSFER = "HAS_ADDED_STOCK_TRANSFER";
    String HAS_EDITED_STOCK_TRANSFER = "HAS_EDITED_STOCK_TRANSFER";
    String HAS_DELETED_STOCK_TRANSFER = "HAS_DELETED_STOCK_TRANSFER";
    String ACCOUNTING_STOCK_TRANSFER_HAS_BEEN_APPROVED = "ACCOUNTING_STOCK_TRANSFER_HAS_BEEN_APPROVED";
    String YOU_HAVE_APPROVED_STOCK_TRANSFER = "YOU_HAVE_APPROVED_STOCK_TRANSFER";
    String ACCOUNTING_STOCK_TRANSFER_HAS_BEEN_DECLINED = "ACCOUNTING_STOCK_TRANSFER_HAS_BEEN_DECLINED";
    String YOU_HAVE_SENT_ACCOUNTING_STOCK_TRANSFER_TO = "YOU_HAVE_SENT_ACCOUNTING_STOCK_TRANSFER_TO";
    String ACCOUNTING_STOCK_TRANSFER_HAS_BEEN_TRANSFERRED = "ACCOUNTING_STOCK_TRANSFER_HAS_BEEN_TRANSFERRED";
    String YOU_TRANSFERED_STOCK_TRANSFERD = "YOU_TRANSFERED_STOCK_TRANSFERD";

    String HAS_ADDED_STOCK_ADJUSTMENT = "HAS_ADDED_STOCK_ADJUSTMENT";
    String HAS_EDITED_STOCK_ADJUSTMENT = "HAS_EDITED_STOCK_ADJUSTMENT";
    String HAS_DELETED_STOCK_ADJUSTMENT = "HAS_DELETED_STOCK_ADJUSTMENT";
    String ACCOUNTING_STOCK_ADJUSTMENT_HAS_BEEN_APPROVED = "ACCOUNTING_STOCK_ADJUSTMENT_HAS_BEEN_APPROVED";
    String YOU_HAVE_APPROVED_STOCK_ADJUSTMENT = "YOU_HAVE_APPROVED_STOCK_ADJUSTMENT";
    String ACCOUNTING_STOCK_ADJUSTMENT_HAS_BEEN_DECLINED = "ACCOUNTING_STOCK_ADJUSTMENT_HAS_BEEN_DECLINED";
    String YOU_HAVE_SENT_ACCOUNTING_STOCK_ADJUSTMENT_TO = "YOU_HAVE_SENT_ACCOUNTING_STOCK_ADJUSTMENT_TO";

    String YOU_HAVE_ADDED_MANUAL_JOURNAL = "YOU_HAVE_ADDED_MANUAL_JOURNAL";
    String HAS_EDITED_MANUAL_JOURNAL = "HAS_EDITED_MANUAL_JOURNAL";
    String YOU_HAVE_EDITED_MANUAL_JOURNAL = "YOU_HAVE_EDITED_MANUAL_JOURNAL";
    String HAS_REVERSED_MANUAL_JOURNAL = "HAS_REVERSED_MANUAL_JOURNAL";
    String HAS_DELETED_MANUAL_JOURNAL = "HAS_DELETED_MANUAL_JOURNAL";
    String YOU_HAVE_REVERSED_MANUAL_JOURNAL = "YOU_HAVE_REVERSED_MANUAL_JOURNAL";
    String YOU_HAVE_DELETED_MANUAL_JOURNAL = "YOU_HAVE_DELETED_MANUAL_JOURNAL";
    String YOU_HAVE_UPDATED_SALES_INVOICE = "YOU_HAVE_UPDATED_SALES_INVOICE";
    String HAS_DELETED_SALES_INVOICE = "HAS_DELETED_SALES_INVOICE";
    String YOU_HAVE_DELETED_SALES_INVOICE = "YOU_HAVE_DELETED_SALES_INVOICE";
    String HAS_SENT_SALES_INVOICE = "HAS_SENT_SALES_INVOICE";
    String YOU_HAVE_SENT_SALES_INVOICE = "YOU_HAVE_SENT_SALES_INVOICE";
    String HAS_SALES_INVOICE_PAYMENT_VOID = "HAS_SALES_INVOICE_PAYMENT_VOID";
    String HAS_SALES_INVOICE_PAYMENT_DELETE = "HAS_SALES_INVOICE_PAYMENT_DELETE";
    String YOU_SALES_INVOICE_PAYMENT_DELETE = "YOU_SALES_INVOICE_PAYMENT_DELETE";
    String HAS_HAVE_SALES_INVOICE_ADD_CREDIT_NOTE = "HAS_HAVE_SALES_INVOICE_ADD_CREDIT_NOTE";
    String YOU_HAVE_SALES_INVOICE_ADD_CREDIT_NOTE = "YOU_HAVE_SALES_INVOICE_ADD_CREDIT_NOTE";
    String YOU_SALES_INVOICE_PAYMENT_VOID = "YOU_SALES_INVOICE_PAYMENT_VOID";
    String PAYMENT_RECEIVED = "PAYMENT_RECEIVED";
    String BY_CONVERTING_SALES_QUOTE = "BY_CONVERTING_SALES_QUOTE";
    String YOU_HVE_ADDED_BYCONVERTING_SALES_QUOTE = "YOU_HVE_ADDED_BYCONVERTING_SALES_QUOTE";
    String HAS_ADDED_SALES_QUOTE = "HAS_ADDED_SALES_QUOTE";
    String YOU_HAVE_ADDED_SALES_QUOTE = "YOU_HAVE_ADDED_SALES_QUOTE";
    String HAS_UPDATED_SALES_QUOTE = "HAS_UPDATED_SALES_QUOTE";
    String YOU_HAVE_UPDATED_SALES_QUOTE = "YOU_HAVE_UPDATED_SALES_QUOTE";
    String HAS_DELETED_SALES_QUOTE = "HAS_DELETED_SALES_QUOTE";
    String YOU_HAVE_DELETED_SALES_QUOTE = "YOU_HAVE_DELETED_SALES_QUOTE";
    String HAS_ADDED_PURCHASE_ORDER = "HAS_ADDED_PURCHASE_ORDER";
    String YOU_HAVE_ADDED_PURCHASE_ORDER = "YOU_HAVE_ADDED_PURCHASE_ORDER";
    String HAS_UPDATED_PURCHASE_ORDER = "HAS_UPDATED_PURCHASE_ORDER";
    String YOU_HAVE_UPDATED_PURCHASE_ORDER = "YOU_HAVE_UPDATED_PURCHASE_ORDER";
    String HAS_DELETED_PURCHASE_ORDER = "HAS_DELETED_PURCHASE_ORDER";
    String YOU_HAVE_DELETED_PURCHASE_ORDER = "YOU_HAVE_DELETED_PURCHASE_ORDER";
    String HAS_SENT_PURCHASE_ORDER_TO_CLIENT = "HAS_SENT_PURCHASE_ORDER_TO_CLIENT";
    String YOU_HAVE_PURCHASE_ORDER_QUOTE_TO_CLIENT = "YOU_HAVE_PURCHASE_ORDER_QUOTE_TO_CLIENT";
    String YOU_APPROVED_PURCHASE_ORDER = "YOU_APPROVED_PURCHASE_ORDER";
    String HAS_APPROVED_PURCHASE_ORDER = "HAS_APPROVED_PURCHASE_ORDER";
    String HAS_PURCHASE_ORDER_RECEIVED = "HAS_PURCHASE_ORDER_RECEIVED";
    String YOU_PURCHASE_ORDER_RECEIVED = "YOU_PURCHASE_ORDER_RECEIVED";
    String HAS_PURCHASE_ORDER_PARTIAL_RECEIVED = "HAS_PURCHASE_ORDER_PARTIAL_RECEIVED";
    String YOU_PURCHASE_ORDER_PARTIAL_RECEIVED = "YOU_PURCHASE_ORDER_PARTIAL_RECEIVED";
    String HAS_ADDED_PURCHASE_INVOICE = "HAS_ADDED_PURCHASE_INVOICE";
    String YOU_HAVE_ADDED_PURCHASE_INVOICE = "YOU_HAVE_ADDED_PURCHASE_INVOICE";
    String HAS_UPDATED_PURCHASE_INVOICE = "HAS_UPDATED_PURCHASE_INVOICE";
    String YOU_HAVE_UPDATED_PURCHASE_INVOICE = "YOU_HAVE_UPDATED_PURCHASE_INVOICE";
    String HAS_DELETED_PURCHASE_INVOICE = "HAS_DELETED_PURCHASE_INVOICE";
    String YOU_HAVE_DELETED_PURCHASE_INVOICE = "YOU_HAVE_DELETED_PURCHASE_INVOICE";
    String HAS_PURCHASE_INVOICE_APPROVE = "HAS_PURCHASE_INVOICE_APPROVE";
    String HAS_HAVE_PURCHASE_INVOICE_ADD_CREDIT_NOTE = "HAS_HAVE_PURCHASE_INVOICE_ADD_CREDIT_NOTE";
    String YOU_HAVE_PURCHASE_INVOICE_ADD_CREDIT_NOTE = "YOU_HAVE_PURCHASE_INVOICE_ADD_CREDIT_NOTE";
    String HAS_HAVE_PURCHASE_INVOICE_PAYMENT_VOID = "HAS_HAVE_PURCHASE_INVOICE_PAYMENT_VOID";
    String YOU_HAVE_PURCHASE_INVOICE_PAYMENT_VOID = "YOU_HAVE_PURCHASE_INVOICE_PAYMENT_VOID";
    String HAS_HAVE_PURCHASE_INVOICE_PAYMENT_DELETE = "HAS_HAVE_PURCHASE_INVOICE_PAYMENT_DELETE";
    String YOU_HAVE_PURCHASE_INVOICE_PAYMENT_DELETE = "YOU_HAVE_PURCHASE_INVOICE_PAYMENT_DELETE";
    String HAS_HAVE_PURCHASE_INVOICE_PAYMENT_PAY = "HAS_HAVE_PURCHASE_INVOICE_PAYMENT_PAY";
    String YOU_HAVE_PURCHASE_INVOICE_PAYMENT_PAY = "YOU_HAVE_PURCHASE_INVOICE_PAYMENT_PAY";
    //FOR RECURRING INVOICE
    String HAS_ADDED_RECURRING_INVOICE = "HAS_ADDED_RECURRING_INVOICE";
    String YOU_HAVE_ADDED_RECURRING_INVOICE = "YOU_HAVE_ADDED_RECURRING_INVOICE";
    String HAS_UPDATED_RECURRING_INVOICE = "HAS_UPDATED_RECURRING_INVOICE";
    String YOU_HAVE_UPDATED_RECURRING_INVOICE = "YOU_HAVE_UPDATED_RECURRING_INVOICE";
    String HAS_DELETED_RECURRING_INVOICE = "HAS_DELETED_RECURRING_INVOICE";
    String YOU_HAVE_DELETED_RECURRING_INVOICE = "YOU_HAVE_DELETED_RECURRING_INVOICE";
    //FOR SALE ORDER
    String HAS_ADDED_SALES_ORDER = "HAS_ADDED_SALES_ORDER";
    String YOU_HAVE_ADDED_SALES_ORDER = "YOU_HAVE_ADDED_SALES_ORDER";
    String HAS_UPDATED_SALES_ORDER = "HAS_UPDATED_SALES_ORDER";
    String YOU_HAVE_UPDATED_SALES_ORDER = "YOU_HAVE_UPDATED_SALES_ORDER";
    String HAS_DELETED_SALES_ORDER = "HAS_DELETED_SALES_ORDER";
    String YOU_HAVE_DELETED_SALES_ORDER = "YOU_HAVE_DELETED_SALES_ORDER";
    String YOU_PICKLIST_SALES_ORDER = "YOU_PICKLIST_SALES_ORDER";
    String HAS_PICKLIST_SALES_ORDER = "HAS_PICKLIST_SALES_ORDER";
    String HAS_SALES_ORDER_CLOSED = "HAS_SALES_ORDER_CLOSED";
    String HAS_SALES_ORDER_CONVERTED_FROM_SQ = "HAS_SALES_ORDER_CONVERTED_FROM_SQ";
    String HAS_SALES_QUOTE_CLOSED = "HAS_SALES_QUOTE_CLOSED";

    String CLIENT_APPROVED_SALES_QUOTE = "CLIENT_APPROVED_SALES_QUOTE";
    String CLIENT_REJECTED_SALES_QUOTE = "CLIENT_REJECTED_SALES_QUOTE";
    String HAS_CONVERTED_SALEQUOTE_TO = "HAS_CONVERTED_SALEQUOTE_TO";
    String YOU_HAVE_CONVERTED_SALEQUOTE_TO_ORDER = "YOU_HAVE_CONVERTED_SALEQUOTE_TO_ORDER";
    String HAS_SENT_SALES_QUOTE_TO_CLIENT = "HAS_SENT_SALES_QUOTE_TO_CLIENT";
    String HAS_SUBMIT_SALES_QUOTE_TO_MANAGER = "HAS_SUBMIT_SALES_QUOTE_TO_MANAGER";
    String YOU_HAVE_SENT_SALES_QUOTE_TO_CLIENT = "YOU_HAVE_SENT_SALES_QUOTE_TO_CLIENT";
    String YOU_HAVE_SUBMITTED_SALES_QUOTE_TO_MANAGER = "YOU_HAVE_SUBMITTED_SALES_QUOTE_TO_MANAGER";
    String REJECTED_SALES_QUOTE = "REJECTED_SALES_QUOTE";
    //for Product
    String HAS_ADDED_PRODUCT = "HAS_ADDED_PRODUCT";
    String YOU_HAVE_ADDED_PRODUCT = "YOU_HAVE_ADDED_PRODUCT";
    String HAS_UPDATED_PRODUCT = "HAS_UPDATED_PRODUCT";
    String YOU_HAVE_UPDATED_PRODUCT = "YOU_HAVE_UPDATED_PRODUCT";
    String HAS_DELETED_PRODUCT = "HAS_DELETED_PRODUCT";
    String YOU_HAVE_DELETED_PRODUCT = "YOU_HAVE_DELETED_PRODUCT";

    //for Fixed Asset
    String HAS_ADDED_FIXED_ASSET = "HAS_ADDED_FIXED_ASSET";
    String YOU_HAVE_ADDED_FIXED_ASSET = "YOU_HAVE_ADDED_FIXED_ASSET";
    String HAS_UPDATED_FIXED_ASSET = "HAS_UPDATED_FIXED_ASSET";
    String YOU_HAVE_UPDATED_FIXED_ASSET = "YOU_HAVE_UPDATED_FIXED_ASSET";
    String HAS_DELETED_FIXED_ASSET = "HAS_DELETED_FIXED_ASSET";
    String YOU_HAVE_DELETED_FIXED_ASSET = "YOU_HAVE_DELETED_FIXED_ASSET";
    String HAS_DISPOSE_FIXED_ASSET = "HAS_DISPOSE_FIXED_ASSET";
    String YOU_HAVE_DISPOSE_FIXED_ASSET = "YOU_HAVE_DISPOSE_FIXED_ASSET";
    String HAS_ADDED_OWNER_FIXED_ASSET = "HAS_ADDED_OWNER_FIXED_ASSET";
    String YOU_HAVE_ADDED_OWNER_FIXED_ASSET = "YOU_HAVE_ADDED_OWNER_FIXED_ASSET";
    String HAS_EDITED_OWNER_FIXED_ASSET = "HAS_EDITED_OWNER_FIXED_ASSET";
    String YOU_HAVE_EDITED_OWNER_FIXED_ASSET = "YOU_HAVE_EDITED_OWNER_FIXED_ASSET";

    //for Check
    String HAS_ADDED_CHECK = "HAS_ADDED_CHECK";
    String YOU_HAVE_ADDED_CHECK = "YOU_HAVE_ADDED_CHECK";
    String HAS_UPDATED_CHECK = "HAS_UPDATED_CHECK";
    String YOU_HAVE_UPDATED_CHECK = "YOU_HAVE_UPDATED_CHECK";
    String HAS_DELETED_CHECK = "HAS_DELETED_CHECK";
    String YOU_HAVE_DELETED_CHECK = "YOU_HAVE_DELETED_CHECK";
    //for Bank Account
    String HAS_ADDED_BANK_ACCOUNT = "HAS_ADDED_BANK_ACCOUNT";
    String YOU_HAVE_ADDED_BANK_ACCOUNT = "YOU_HAVE_ADDED_BANK_ACCOUNT";
    String HAS_UPDATED_BANK_ACCOUNT = "HAS_UPDATED_BANK_ACCOUNT";
    String YOU_HAVE_UPDATED_BANK_ACCOUNT = "YOU_HAVE_UPDATED_BANK_ACCOUNT";
    String HAS_DELETED_BANK_ACCOUNT = "HAS_DELETED_BANK_ACCOUNT";
    String YOU_HAVE_DELETED_BANK_ACCOUNT = "YOU_HAVE_DELETED_BANK_ACCOUNT";

    //for Chart Of Account
    String HAS_ADDED_CHART_OF_ACCOUNT = "HAS_ADDED_CHART_OF_ACCOUNT";
    String YOU_HAVE_ADDED_CHART_OF_ACCOUNT = "YOU_HAVE_ADDED_CHART_OF_ACCOUNT";
    String HAS_UPDATED_CHART_OF_ACCOUNT = "HAS_UPDATED_CHART_OF_ACCOUNT";
    String YOU_HAVE_UPDATED_CHART_OF_ACCOUNT = "YOU_HAVE_UPDATED_CHART_OF_ACCOUNT";
    String HAS_DELETED_CHART_OF_ACCOUNT = "HAS_DELETED_CHART_OF_ACCOUNT";
    String YOU_HAVE_DELETED_CHART_OF_ACCOUNT = "YOU_HAVE_DELETED_CHART_OF_ACCOUNT";

    String HAS_ADDED_EXPENSE_REPORT = "HAS_ADDED_EXPENSE_REPORT";
    String YOU_HAVE_ADDED_EXPENSE_REPORT = "YOU_HAVE_ADDED_EXPENSE_REPORT";
    String HAS_UPDATED_EXPENSE_REPORT = "HAS_UPDATED_EXPENSE_REPORT";
    String YOU_HAVE_UPDATED_EXPENSE_REPORT = "YOU_HAVE_UPDATED_EXPENSE_REPORT";
    String HAS_DELETED_EXPENSE_REPORT = "HAS_DELETED_EXPENSE_REPORT";
    String YOU_HAVE_DELETED_EXPENSE_REPORT = "YOU_HAVE_DELETED_EXPENSE_REPORT";
    String EXPENSE_REPORT_HAS_BEEN_APPROVED = "EXPENSE_REPORT_HAS_BEEN_APPROVED";
    String UNNAMED = "UNNAMED";
    String YOUR_EXPENSE_REPORT_HAS_BEEN_APPROVED = "YOUR_EXPENSE_REPORT_HAS_BEEN_APPROVED";
    String EXPENSE_REPORT_HAS_BEEN_DECLINED = "EXPENSE_REPORT_HAS_BEEN_DECLINED";
    String YOUR_EXPENSE_REPORT_HAS_BEEN_DECLINED = "YOUR_EXPENSE_REPORT_HAS_BEEN_DECLINED";
    String HAS_GOT_EXPENSE_REPORT_FROM = "HAS_GOT_EXPENSE_REPORT_FROM";
    String HAS_SENT_EXPENSE_REPORT_FOR_YOUR_REVIEW = "HAS_SENT_EXPENSE_REPORT_FOR_YOUR_REVIEW";
    String HAS_SENT_EXPENSE_REPORT_TO = "HAS_SENT_EXPENSE_REPORT_TO";
    String YOU_HAVE_SENT_EXPENSE_REPORT_TO = "YOU_HAVE_SENT_EXPENSE_REPORT_TO";
    String INVITATION_ACCEPTED = "INVITATION_ACCEPTED";
    String HAS_ACCEPTED_INVITATION = "HAS_ACCEPTED_INVITATION";
    String TENTATIVELY_ACCEPTED = "TENTATIVELY_ACCEPTED";
    String HAS_TENTATIVELY_ACCEPTED = "HAS_TENTATIVELY_ACCEPTED";
    String INVITATION_DECLINED = "INVITATION_DECLINED";
    String HAS_DECLINED_INVITATION = "HAS_DECLINED_INVITATION";
    String YOU_HAVE_ADDED_ISSUE = "YOU_HAVE_ADDED_ISSUE";
    String YOU_HAVE_UPDATED_ISSUE = "YOU_HAVE_UPDATED_ISSUE";
    String ADDED_DOCUMENT_TO_ISSUE = "ADDED_DOCUMENT_TO_ISSUE";
    String YOU_HAVE_ADDED_DOCUMENT_TO_ISSUE = "YOU_HAVE_ADDED_DOCUMENT_TO_ISSUE";
    String ADDED_CLIENT = "ADDED_CLIENT";
    String YOU_HAVE_ADDED_CLIENT = "YOU_HAVE_ADDED_CLIENT";
    String UPDATED_CLIENT = "UPDATED_CLIENT";
    String YOU_HAVE_UPDATED_CLIENT = "YOU_HAVE_UPDATED_CLIENT";
    String DELETED_CLIENT = "DELETED_CLIENT";
    String YOU_HAVE_DELETED_CLIENT = "YOU_HAVE_DELETED_CLIENT";
    String ADDED_DEPARTAMENT = "ADDED_DEPARTAMENT";
    String YOY_HAVE_ADDED_DEPARTAMENT = "YOY_HAVE_ADDED_DEPARTAMENT";
    String UPDATED_DEPARTMENT = "UPDATED_DEPARTMENT";
    String YOU_HAVE_UPDATED_DEPARTMENT = "YOU_HAVE_UPDATED_DEPARTMENT";
    String DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
    String YOU_HAVE_DELETE_DEPARTMENT = "YOU_HAVE_DELETE_DEPARTMENT";
    String HAS_BEEN_ASSIGNED_AS_A_DEPARTMENT_LEADER = "HAS_BEEN_ASSIGNED_AS_A_DEPARTMENT_LEADER";
    String HAS_BEEN_ASSIGNED_TO_DEPARTMENT = "HAS_BEEN_ASSIGNED_TO_DEPARTMENT";
    String YOU_HAVE_HAS_BEEN_ASSIGNED_AS_A_DEPARTMENT_LEADER = "YOU_HAVE_HAS_BEEN_ASSIGNED_AS_A_DEPARTMENT_LEADER";
    String YOU_HAVE_ASSIGNED_TO_DEPARTMENT = "YOU_HAVE_ASSIGNED_TO_DEPARTMENT";
    String HAS_BEEN_UNASSIGNED_FROM_DEPARTMENT = "HAS_BEEN_UNASSIGNED_FROM_DEPARTMENT";
    String YOU_HAVE_BEEN_UNASSIGNED_FROM_DEPARTMENT = "YOU_HAVE_BEEN_UNASSIGNED_FROM_DEPARTMENT";
    String YOU_HAVE_DEPARTMENT = "YOU_HAVE_DEPARTMENT";
    String HAS_UPDATED_DEPARTMENT = "HAS_UPDATED_DEPARTMENT";
    String YOU_HAVE_DELETED_DEPARTMENT = "YOU_HAVE_DELETED_DEPARTMENT";
    String HAS_DELETED_DEPARTMENT = "HAS_DELETED_DEPARTMENT";
    String HAS_ADDED_AS_A_CLIENT_CONTACT = "HAS_ADDED_AS_A_CLIENT_CONTACT";
    String YOU_HAVE_ADDED_AS_A_CLIENT_CONTACT = "YOU_HAVE_ADDED_AS_A_CLIENT_CONTACT";
    String HAS_UPDATED_CONTACTS_OF_CLIENT = "HAS_UPDATED_CONTACTS_OF_CLIENT";
    String YOU_HAVE_UPDATED_CONTACTS_OF_CLIENT = "YOU_HAVE_UPDATED_CONTACTS_OF_CLIENT";
    String HAS_DELETED_CLIENT_CONTACT = "HAS_DELETED_CLIENT_CONTACT";
    String YOU_DELETED_CLIENT_CONTACT = "YOU_DELETED_CLIENT_CONTACT";
    String ADDED_A_NEW_EMPLOYEE = "ADDED_A_NEW_EMPLOYEE";
    String YOU_HAVE_ADDED_A_NEW_EMPLOYEE = "YOU_HAVE_ADDED_A_NEW_EMPLOYEE";
    String UPDATED_THE_EMPLOYEE = "UPDATED_THE_EMPLOYEE";
    String YOU_HAVE_UPDATED_EMPLOYEE_THE = "YOU_HAVE_UPDATED_EMPLOYEE_THE";
    String DELETED_THE_EMPLOYEE = "DELETED_THE_EMPLOYEE";
    String YOU_HAVE_DELETED_THE_EMPLOYEE = "YOU_HAVE_DELETED_THE_EMPLOYEE";
    String TERMINATED_THE_EMPLOYEE = "TERMINATED_THE_EMPLOYEE";
    String YOU_HAVE_TERMINATED_THE_EMPLOYEE = "YOU_HAVE_TERMINATED_THE_EMPLOYEE";
    String ADDED_PROJECT = "ADDED_PROJECT";
    String YOU_ADDED_PROJECT = "YOU_ADDED_PROJECT";
    String DELETED_PROJECT = "DELETED_PROJECT";
    String YOU_HAVE_DELETED_PROJECT = "YOU_HAVE_DELETED_PROJECT";
    String PROJECT_HAS_BEEN_DELETED = "PROJECT_HAS_BEEN_DELETED";
    String HAS_BEEN_ASSIGNED_AS_A_PROJECT_MANAGER_TO_PROJECT = "HAS_BEEN_ASSIGNED_AS_A_PROJECT_MANAGER_TO_PROJECT";
    String YOU_HAVE_BEEN_ASSIGNED_AS_A_PROJECT_MANAGER_TO_PROJECT = "YOU_HAVE_BEEN_ASSIGNED_AS_A_PROJECT_MANAGER_TO_PROJECT";
    String DISCUSSION = "DISCUSSION";
    String NEWS = "NEWS";
    String ANONYMOUS = "ANONYMOUS";
    String HAS_BEEN_ASSIGNED_AS_A_BACKUPMANAGE_TO_PROJECT = "HAS_BEEN_ASSIGNED_AS_A_BACKUPMANAGE_TO_PROJECT";
    String YOUHAVE_BEEN_ASSIGNED_AS_A_BACKUPMANAGE_TO_PROJECT = "YOUHAVE_BEEN_ASSIGNED_AS_A_BACKUPMANAGE_TO_PROJECT";
    String HAS_BEEN_ASSIGNED_AS_A_MEMBER_TO_PROJECT = "HAS_BEEN_ASSIGNED_AS_A_MEMBER_TO_PROJECT";
    String YOU_HAVE_BEEN_ASSIGNED_AS_A_MEMBER_TO_PROJECT = "YOU_HAVE_BEEN_ASSIGNED_AS_A_MEMBER_TO_PROJECT";
    String UPDATED_PROJECT = "UPDATED_PROJECT";
    String YOU_HAVE_UPDATED_PROJECT = "YOU_HAVE_UPDATED_PROJECT";
    String COMPLETED_PROJECT = "COMPLETED_PROJECT";
    String YOU_HAVE_COMPLETED_PROJECT = "YOU_HAVE_COMPLETED_PROJECT";
    String HAS_BEEN_UNASSIGNED_FROM_PROJECT = "HAS_BEEN_UNASSIGNED_FROM_PROJECT";
    String YOU_HAVE_BEEN_UNASSIGNED_FROM_PROJECT = "YOU_HAVE_BEEN_UNASSIGNED_FROM_PROJECT";
    String HAS_UPDATED_PROJECT = "HAS_UPDATED_PROJECT";
    String IMPORTED_TASKS_TO_PROJECT = "IMPORTED_TASKS_TO_PROJECT";
    String YOU_HAVEIMPORTED_TASKS_TO_PROJECT = "YOU_HAVEIMPORTED_TASKS_TO_PROJECT";
    String ADDED_DOCUMENT_TO_PROJECT = "ADDED_DOCUMENT_TO_PROJECT";
    String YOU_ADDED_DOCUMENT_TO_PROJECT = "YOU_ADDED_DOCUMENT_TO_PROJECT";
    String CANCELLED_TASK = "CANCELLED_TASK";
    String YOU_HAVE_CANCELLED_TASK = "YOU_HAVE_CANCELLED_TASK";
    String CLOSED_TASK = "CLOSED_TASK";
    String YOU_HAVE_CLOSED_TASK = "YOU_HAVE_CLOSED_TASK";
    String COMPLETED_TASK = "COMPLETED_TASK";
    String YOU_HAVE_COMPLETED_TASK = "YOU_HAVE_COMPLETED_TASK";
    String ADDED_TASK = "ADDED_TASK";
    String ADDED_CUSTOM_FORM = "ADDED_CUSTOM_FORM";
    String YOU_HAVE_ADDED_TASK = "YOU_HAVE_ADDED_TASK";
    String UPDATED_TASK = "UPDATED_TASK";
    String EDITED_CUSTOM_FORM = "EDITED_CUSTOM_FORM";
    String YOU_HAVE_UPDATED_TASK = "YOU_HAVE_UPDATED_TASK";
    String DELETED_TASK = "DELETED_TASK";
    String DELETED_CUSTOM_FORM = "DELETED_CUSTOM_FORM";
    String YOU_HAVE_DELETED_TASK = "YOU_HAVE_DELETED_TASK";
    String HAS_BEEN_ASSIGNED_TO_TASK = "HAS_BEEN_ASSIGNED_TO_TASK";
    String YOU_HAVE_BEEN_ASSIGNED_TO_TASK = "YOU_HAVE_BEEN_ASSIGNED_TO_TASK";
    String HAS_BEEN_UNASSIGNED_FROM_TASK = "HAS_BEEN_UNASSIGNED_FROM_TASK";
    String YOU_HAVE_BEEN_UNASSIGNED_FROM_TASK = "YOU_HAVE_BEEN_UNASSIGNED_FROM_TASK";
    String ADDED_DOCUMENT_TO_TASK = "ADDED_DOCUMENT_TO_TASK";
    String YOU_HAVE_ADDED_DOCUMENT_TO_TASK = "YOU_HAVE_ADDED_DOCUMENT_TO_TASK";
    String DELETED_LEAVE_REQUEST = "DELETED_LEAVE_REQUEST";
    String YOU_HAVE_DELETED_LEAVE_REQUEST = "YOU_HAVE_DELETED_LEAVE_REQUEST";
    String HAS_CREATED_NETWORK = "HAS_CREATED_NETWORK";
    String YOU_HAVE_CREATED_NETWORK = "YOU_HAVE_CREATED_NETWORK";
    String HAS_UPDATED_NETWORK = "HAS_UPDATED_NETWORK";
    String YOU_HAVE_UPDATED_NETWORK = "YOU_HAVE_UPDATED_NETWORK";
    String HAS_DELETED_NETWORK = "HAS_DELETED_NETWORK";
    String YOU_HAVE_DELETED_NETWORK = "YOU_HAVE_DELETED_NETWORK";
    String NETWORK = "NETWORK";
    String HAS_ADDED_OF = "HAS_ADDED_OF";
    String YOU_HAVE_ADDED_OF = "YOU_HAVE_ADDED_OF";
    String HAS_UPDATED_OF = "HAS_UPDATED_OF";
    String YOU_HAVE_UPDATED_OF = "YOU_HAVE_UPDATED_OF";
    String HAS_DELETED_OF = "HAS_DELETED_OF";
    String YOU_HAVE_DELETED_OF = "YOU_HAVE_DELETED_OF";
    String HAS_COMMENTED_OF_NETWORK = "HAS_COMMENTED_OF_NETWORK";
    String YOU_HAVE_COMMENTED_OF_NETWORK = "YOU_HAVE_COMMENTED_OF_NETWORK";
    String HAS_RATED_NETWORK = "HAS_RATED_NETWORK";
    String YOU_HAVE_RATED_NETWORK = "YOU_HAVE_RATED_NETWORK";
    String HAS_CONFIRMED_NETWORK = "HAS_CONFIRMED_NETWORK";
    String YOU_HAVE_CONFIRMED_NETWORK = "YOU_HAVE_CONFIRMED_NETWORK";
    String REQUESTED_TO_JOIN_NETWORK_HAS_BENN_REJECTED = "REQUESTED_TO_JOIN_NETWORK_HAS_BENN_REJECTED";
    String YOU_REJECTED_INVITATION_TO_JOIN = "YOU_REJECTED_INVITATION_TO_JOIN";
    String YOU_WERE_REJECTED_TO_JOIN = "YOU_WERE_REJECTED_TO_JOIN";
    String HAS_INVITED_TO_NETWORK = "HAS_INVITED_TO_NETWORK";
    String YOU_HAVE_BENN_INVITED_NETWORK = "YOU_HAVE_BENN_INVITED_NETWORK";
    String HAS_ADDED_TO_NETWORK = "HAS_ADDED_TO_NETWORK";
    String YOU_HAVE_ADDED_TO_NETWORK = "YOU_HAVE_ADDED_TO_NETWORK";
    String HAS_DELETED_FROM_NETWORK = "HAS_DELETED_FROM_NETWORK";
    String YOU_HAVE_DELETED_FROM_NETWORK = "YOU_HAVE_DELETED_FROM_NETWORK";

    String PM_TASKS_LIST = "PM_TASKS_LIST";
    String PM_ISSUE_LIST = "PM_ISSUE_LIST";
    String PM_TIMESHEET = "PM_TIMESHEET";
    String PM_TIMESHEET_APPROVAL = "PM_TIMESHEET_APPROVAL";
    String PM_PROJECT_LIST = "PM_PROJECT_LIST";
    String PM_CUSTOMER_LIST = "PM_CUSTOMER_LIST";
    String PM_EMPLOYEE_LIST = "PM_EMPLOYEE_LIST";
    String PM_DEPARTMENT_LIST = "PM_DEPARTMENT_LIST";
    String PM_LOCATION_LIST = "PM_LOCATION_LIST";
    String PM_TASKS_ADD = "PM_TASKS_ADD";
    String PM_TASKS_ADD_MULTI = "PM_TASKS_ADD_MULTI";
    String PM_TASKS_EDIT = "PM_TASKS_EDIT";
    String PM_TASKS_REMOVE = "PM_TASKS_REMOVE";
    String PM_TASKS_DOCUMENTS = "PM_TASKS_DOCUMENTS";
    String PM_TASKS_NOTES = "PM_TASKS_NOTES";
    String PM_TASKS_PDF_EXCEL_EXPORT = "PM_TASKS_PDF_EXCEL_EXPORT";
    String PM_TASKS_TIMER = "PM_TASKS_TIMER";
    String PM_TASKS_VIEW_PROJECT_COST = "PM_TASKS_VIEW_PROJECT_COST";
    String WORKSPACE_MAIN_MENU = "WORKSPACE_MAIN_MENU";
    String PM_MAIN_MENU = "PM_MAIN_MENU";
    String HRMS_MAIN_MENU = "HRMS_MAIN_MENU";
    String CRM_MAIN_MENU = "CRM_MAIN_MENU";
    String ACCOUNTING_MAIN_MENU = "ACCOUNTING_MAIN_MENU";
    String PAYROLL_MAIN_MENU = "PAYROLL_MAIN_MENU";
    String DOCUMENTS_MAIN_MENU = "DOCUMENTS_MAIN_MENU";
    String DASHBOARD_MAIN_MENU = "DASHBOARD_MAIN_MENU";
    String MYACCOUNT_MAIN_MENU = "MYACCOUNT_MAIN_MENU";
    String SETTINGS_MAIN_MENU = "SETTINGS_MAIN_MENU";
    String REPORTING_MAIN_MENU = "REPORTING_MAIN_MENU";
    String CRM_LEADS_LIST = "CRM_LEADS_LIST";
    String CRM_SALES_TAB = "CRM_SALES_TAB";
    String CRM_OPPORTUNITIES_LIST = "CRM_OPPORTUNITIES_LIST";
    String CRM_ACCOUNTS_LIST = "CRM_ACCOUNTS_LIST";
    String CRM_CONTACTS_LIST = "CRM_CONTACTS_LIST";
    String CRM_CAMPAIGNS_LIST = "CRM_CAMPAIGNS_LIST";
    String CRM_TASKS_LIST = "CRM_TASKS_LIST";
    String CRM_ACTIVITIES_LIST = "CRM_ACTIVITIES_LIST";
    String CRM_WEB_FORMS_LIST = "CRM_WEB_FORMS_LIST";
    String ADD_NEW_LEAD = "ADD_NEW_LEAD";
    String CUSTOMER_SERVICE_TAB = "CUSTOMER_SERVICE_TAB";
    String CRM_CONTACTS = "CRM_CONTACTS";
    String CRM_CONTACTS_IN_SERVICE_CUSTOMER_LIST = "CRM_CONTACTS_IN_SERVICE_CUSTOMER_LIST";
    String CRM_CASES_LIST = "CRM_CASES_LIST";
    String CRM_SOLUTIONS_LIST = "CRM_SOLUTIONS_LIST";
    String CRM_E_MAIL_MARKETING_TAB = "CRM_E_MAIL_MARKETING_TAB";
    String CRM_ACCOUNTS_IN_SERVICE_CUSTOMER_LIST = "CRM_ACCOUNTS_IN_SERVICE_CUSTOMER_LIST";
    String CRM_MAILING_LIST = "CRM_MAILING_LIST";
    String CRM_DRAFT_MESSAGES_LIST = "CRM_DRAFT_MESSAGES_LIST";
    String CRM_SENT_MESSAGES_LIST = "CRM_SENT_MESSAGES_LIST";
    String CRM_QUEUED_MESSAGES_LIST = "CRM_QUEUED_MESSAGES_LIST";
    String CRM_Calendar = "CRM_Calendar";
    String CRM_MESSAGE_CENTER = "CRM_MESSAGE_CENTER";
    String PM_PROJECT_ADD = "PM_PROJECT_ADD";
    String PM_PROJECT_EDIT = "PM_PROJECT_EDIT";
    String ADD_NEW_CASE = "ADD_NEW_CASE";
    String ADD_NEW_SOLUTION = "ADD_NEW_SOLUTION";
    String ADD_SOLUTION_SUMMARY = "ADD_SOLUTION_SUMMARY";
    String ADD_EDIT_SOLUTION = "ADD_EDIT_SOLUTION";
    String CRM_EDIT_SOLUTION = "CRM_EDIT_SOLUTION";
    String CRM_REMOVE_SOLUTION = "CRM_REMOVE_SOLUTION";
    String CRM_ADD_NEW_MESSAGE = "CRM_ADD_NEW_MESSAGE";
    String CRM_MAILING_LIST_SUMMARY = "CRM_MAILING_LIST_SUMMARY";
    String CRM_EDIT_MAILING_LIST = "CRM_EDIT_MAILING_LIST";
    String CRM_REMOVE_MAILING_LIST = "CRM_REMOVE_MAILING_LIST";
    String CRM_ADD_NEW_MESSAGE_IN_DRAFT_LIST = "CRM_ADD_NEW_MESSAGE_IN_DRAFT_LIST";
    String CRM_MESSAGE_SUMMARY = "CRM_MESSAGE_SUMMARY";
    String CRM_MESSAGE_EDIT = "CRM_MESSAGE_EDIT";
    String CRM_MESSAGE_REMOVE = "CRM_MESSAGE_REMOVE";
    String CRM_NEW_MESSAGE_IN_SENT_MESSAGE = "CRM_NEW_MESSAGE_IN_SENT_MESSAGE";
    String CRM_VIEW_SUMMARY_IN_SENT_MESSAGE = "CRM_VIEW_SUMMARY_IN_SENT_MESSAGE";
    String CRM_TRACK_MESSAGES_IN_SENT_MESSAGE = "CRM_TRACK_MESSAGES_IN_SENT_MESSAGE";
    String CRM_UPDATE_STATISTIC_IN_SENT_MESSAGE = "CRM_UPDATE_STATISTIC_IN_SENT_MESSAGE";
    String CRM_EDIT_MESSAGE_IN_SENT_MESSAGE = "CRM_EDIT_MESSAGE_IN_SENT_MESSAGE";
    String PM_APPROVE_REJECT = "PM_APPROVE_REJECT";
    String PAYROLL_PAYMENT_DEDUCATION_LIST = "PAYROLL_PAYMENT_DEDUCATION_LIST";
    String PAYROLL_PAYMENT_DEDUCATION_ADD = "PAYROLL_PAYMENT_DEDUCATION_ADD";
    String PAYROLL_PAYMENT_DEDUCATION_VIEW = "PAYROLL_PAYMENT_DEDUCATION_VIEW";
    String PAYROLL_PAYSLIP_LIST = "PAYROLL_PAYSLIP_LIST";
    String PAYROLL_PAYSLIP_ADD = "PAYROLL_PAYSLIP_ADD";
    String PAYROLL_PAYSLIP_EDIT = "PAYROLL_PAYSLIP_EDIT";
    String PAYROLL_PAYSLIP_PDF = "PAYROLL_PAYSLIP_PDF";
    String PAYROLL_PAYSLIP_PROCESS_PAYRUN = "PAYROLL_PAYSLIP_PROCESS_PAYRUN";
    String PAYROLL_PAYSLIP_ROLLBACK_P11 = "PAYROLL_PAYSLIP_ROLLBACK_P11";
    String PAYROLL_FORMS_REPORT = "PAYROLL_FORMS_REPORT";
    String PAYROLL_FORMS_REPORT_TAX_CODE_CHANGES = "PAYROLL_FORMS_REPORT_TAX_CODE_CHANGES";
    String PAYROLL_FORMS_REPORT_NI_CATEGORY_CHANGES = "PAYROLL_FORMS_REPORT_NI_CATEGORY_CHANGES";
    String PAYROLL_FORMS_REPORT_P32_FORM = "PAYROLL_FORMS_REPORT_P32_FORM";
    String PAYROLL_FORMS_REPORT_EFILES_P35 = "PAYROLL_FORMS_REPORT_EFILES_P35";
    String PAYROLL_SETTINGS = "PAYROLL_SETTINGS";
    String PAYROLL_SETTINGS_EMPLOYER_SETTINGS = "PAYROLL_SETTINGS_EMPLOYER_SETTINGS";
    String PAYROLL_SETTINGS_PENSION_PROVIDERS = "PAYROLL_SETTINGS_PENSION_PROVIDERS";
    String PAYROLL_SETTINGS_PENSION_SCHEMES = "PAYROLL_SETTINGS_PENSION_SCHEMES";
    String PAYROLL_SETTINGS_PAYE_TAX_BAND = "PAYROLL_SETTINGS_PAYE_TAX_BAND";
    String PAYROLL_SETTINGS_NI_BANDS_AND_RATES = "PAYROLL_SETTINGS_NI_BANDS_AND_RATES";
    String PAYROLL_SETTINGS_STUDENT_LOAN = "PAYROLL_SETTINGS_STUDENT_LOAN";
    String PAYROLL_SETTINGS_PAYMENT_CATEGORIES = "PAYROLL_SETTINGS_PAYMENT_CATEGORIES";
    String PAYROLL_SETTINGS_DEDUCATION_CATEGORIES = "PAYROLL_SETTINGS_DEDUCATION_CATEGORIES";
    String PAYROLL_SETTINGS_PROCESS_PAYRUN = "PAYROLL_SETTINGS_PROCESS_PAYRUN";
    String PAYROLL_EMPLOYEES_LIST = "PAYROLL_EMPLOYEES_LIST";
    String PAYROLL_EMPLOYEES_ADD = "PAYROLL_EMPLOYEES_ADD";
    String PAYROLL_EMPLOYEES_PAYROLL_SETTINGS = "PAYROLL_EMPLOYEES_PAYROLL_SETTINGS";
    String PAYROLL_EMPLOYEES_RECURRING_PAYMENT_DEDUCATION_SETTINGS = "PAYROLL_EMPLOYEES_RECURRING_PAYMENT_DEDUCATION_SETTINGS";
    String PAYROLL_EMPLOYEES_BANK_DETAILS = "PAYROLL_EMPLOYEES_BANK_DETAILS";
    String PAYROLL_EMPLOYEES_PAYSLIPS = "PAYROLL_EMPLOYEES_PAYSLIPS";
    String PAYROLL_EMPLOYEES_ATTACHMENT_ARRESMENT_ORDERS = "PAYROLL_EMPLOYEES_ATTACHMENT_ARRESMENT_ORDERS";
    String PAYROLL_EMPLOYEES_P11_FORM = "PAYROLL_EMPLOYEES_P11_FORM";
    String PAYROLL_EMPLOYEES_P45_FORM = "PAYROLL_EMPLOYEES_P45_FORM";
    String PAYROLL_EMPLOYEES_P60_FORM = "PAYROLL_EMPLOYEES_P60_FORM";
    String PAYROLL_EMPLOYEES_P14_FORM = "PAYROLL_EMPLOYEES_P14_FORM";
    String PAYROLL_EFILE_TO_HRMS = "PAYROLL_EFILE_TO_HRMS";
    String HRMS_MAP_LOCATION = "HRMS_MAP_LOCATION";
    String HRMS_ADD_NEW_POSITION = "HRMS_ADD_NEW_POSITION";
    String HRMS_POSITION_SUMMARRY = "HRMS_POSITION_SUMMARRY";
    String HRMS_POSITION_EDIT = "HRMS_POSITION_EDIT";
    String HRMS_POSITION_REMOVE = "HRMS_POSITION_REMOVE";
    String HRMS_ADD_NEW_GRADE = "HRMS_ADD_NEW_GRADE";
    String HRMS_GRADE_SUMMARY = "HRMS_GRADE_SUMMARY";
    String HRMS_EDIT_GRADE = "HRMS_EDIT_GRADE";
    String HRMS_GRADE_REMOVE = "HRMS_GRADE_REMOVE";
    String HRMS_ADD_NEW_EXPENSE_CLAIM = "HRMS_ADD_NEW_EXPENSE_CLAIM";
    String HRMS_VIEW_EXPENSE_CLAIM = "HRMS_VIEW_EXPENSE_CLAIM";
    String HRMS_NEW_PERSONAL_GOALS = "HRMS_NEW_PERSONAL_GOALS";
    String HRMS_NEW_DEPARTMENT_GOAL = "HRMS_NEW_DEPARTMENT_GOAL";
    String HRMS_NEW_PROJECT_GOAL = "HRMS_NEW_PROJECT_GOAL";
    String HRMS_NEW_BUSINESS_GOALS = "HRMS_NEW_BUSINESS_GOALS";
    String HRMS_NEW_COMPANY_GOALS = "HRMS_NEW_COMPANY_GOALS";
    String HRMS_GOAL_SUMMARY = "HRMS_GOAL_SUMMARY";
    String HRMS_EDIT_GOAL = "HRMS_EDIT_GOAL";
    String HRMS_GOAL_REMOVE = "HRMS_GOAL_REMOVE";
    String HRMS_ADD_NEW_INCIDENT = "HRMS_ADD_NEW_INCIDENT";
    String HRMS_SUMMARY_INCIDENT = "HRMS_SUMMARY_INCIDENT";
    String HRMS_EDIT_INCIDENT = "HRMS_EDIT_INCIDENT";
    String HRMS_REMOVE_INCIDENT = "HRMS_REMOVE_INCIDENT";
    String HRMS_ADD_NEW_PERSONAL_GOALS = "HRMS_ADD_NEW_PERSONAL_GOALS";
    String HRMS_PERSONAL_GOAL_SUMMARY = "HRMS_PERSONAL_GOAL_SUMMARY";
    String HRMS_EDIT_PERSONAL_GOAL = "HRMS_EDIT_PERSONAL_GOAL";
    String HRMS_NOTES_PERSONAL_GOAL = "HRMS_NOTES_PERSONAL_GOAL";
    String HRMS_PERSONAL_GOAL_REMOVE = "HRMS_PERSONAL_GOAL_REMOVE";
    String HRMS_ADD_NEW_DEPARTMENT_GOALS = "HRMS_ADD_NEW_DEPARTMENT_GOALS";
    String HRMS_DEPARTMENT_GOAL_SUMMARY = "HRMS_DEPARTMENT_GOAL_SUMMARY";
    String HRMS_EDIT_DEPARTMENT_GOAL = "HRMS_EDIT_DEPARTMENT_GOAL";
    String HRMS_NOTES_DEPARTMENT_GOAL = "HRMS_NOTES_DEPARTMENT_GOAL";
    String HRMS_DEPARTMENT_GOAL_REMOVE = "HRMS_DEPARTMENT_GOAL_REMOVE";
    String HRMS_ADD_NEW_PROJECT_GOALS = "HRMS_ADD_NEW_PROJECT_GOALS";
    String HRMS_PROJECT_GOAL_SUMMARY = "HRMS_PROJECT_GOAL_SUMMARY";
    String HRMS_EDIT_PROJECT_GOAL = "HRMS_EDIT_PROJECT_GOAL";
    String HRMS_NOTES_PROJECT_GOAL = "HRMS_NOTES_PROJECT_GOAL";
    String HRMS_PROJECT_GOAL_REMOVE = "HRMS_PROJECT_GOAL_REMOVE";
    String HRMS_ADD_NEW_BUSINESS_GOALS = "HRMS_ADD_NEW_BUSINESS_GOALS";
    String HRMS_BUSINESS_GOAL_SUMMARY = "HRMS_BUSINESS_GOAL_SUMMARY";
    String HRMS_EDIT_BUSINESS_GOAL = "HRMS_EDIT_BUSINESS_GOAL";
    String HRMS_NOTES_BUSINESS_GOAL = "HRMS_NOTES_BUSINESS_GOAL";
    String HRMS_BUSINESS_GOAL_REMOVE = "HRMS_BUSINESS_GOAL_REMOVE";
    String HRMS_ADD_NEW_COMPANY_GOALS = "HRMS_ADD_NEW_COMPANY_GOALS";
    String HRMS_COMPANY_GOAL_SUMMARY = "HRMS_COMPANY_GOAL_SUMMARY";
    String HRMS_EDIT_COMPANY_GOAL = "HRMS_EDIT_COMPANY_GOAL";
    String HRMS_NOTES_COMPANY_GOAL = "HRMS_NOTES_COMPANY_GOAL";
    String HRMS_COMPANY_GOAL_REMOVE = "HRMS_COMPANY_GOAL_REMOVE";
    String HRMS_ADD_NEW_APPRAISALS = "HRMS_ADD_NEW_APPRAISALS";
    String HRMS_NEW_EMPLOYEE_360_APPRAISALS = "HRMS_NEW_EMPLOYEE_360_APPRAISALS";
    String HRMS_NEW_APPRAISALS_TEMPLATES = "HRMS_NEW_APPRAISALS_TEMPLATES";
    String HRMS_EDIT_TEMPLATED = "HRMS_EDIT_TEMPLATED";
    String HRMS_REMOVE_TEMPLATED = "HRMS_REMOVE_TEMPLATED";
    String HRMS_ADD_COMPETENCES = "HRMS_ADD_COMPETENCES";
    String HRMS_REMOVE_COMPETENCES = "HRMS_REMOVE_COMPETENCES";
    String HRMS_ADD_NEW_PERFORMANCE_NOTE = "HRMS_ADD_NEW_PERFORMANCE_NOTE";
    String HRMS_PERFORMANCE_NOTE_SUMMERY = "HRMS_PERFORMANCE_NOTE_SUMMERY";
    String HRMS_EDIT_PERFORMANCE_NOTE = "HRMS_EDIT_PERFORMANCE_NOTE";
    String HRMS_REMOVE_PERFORMANCE_NOTE = "HRMS_REMOVE_PERFORMANCE_NOTE";
    String PM_CUSTOMER_EDIT = "PM_CUSTOMER_EDIT";
    String PM_CUSTOMER_CLIENT_NOTES = "PM_CUSTOMER_CLIENT_NOTES";
    String PM_CUSTOMER_REMOVE_CLIENT = "PM_CUSTOMER_REMOVE_CLIENT";
    String PM_CUSTOMER_ADD_CLIENT = "PM_CUSTOMER_ADD_CLIENT";
    String ACCOUNTING_GETTING_STARTED_MENU = "ACCOUNTING_GETTING_STARTED_MENU";
    String ACCOUNTING_ACCOUNTING_MENU = "ACCOUNTING_ACCOUNTING_MENU";
    String ACCOUNTING_WAREHOUSE_MENU = "ACCOUNTING_WAREHOUSE_MENU";
    String ACCOUNTING_REPORTS_MENU = "ACCOUNTING_REPORTS_MENU";
    String ACCOUNTING_STOREFRONT_MENU = "ACCOUNTING_STOREFRONT_MENU";
    String ACCOUNTING_SETTINGS_MENU = "ACCOUNTING_SETTINGS_MENU";
    String ACCOUNTING_SALES_QUOTE_LIST = "ACCOUNTING_SALES_QUOTE_LIST";
    String ACCOUNTING_SALES_QUOTE_ADD = "ACCOUNTING_SALES_QUOTE_ADD";
    String ACCOUNTING_SALES_QUOTE_EDIT = "ACCOUNTING_SALES_QUOTE_EDIT";
    String ACCOUNTING_SALES_QUOTE_DELETE = "ACCOUNTING_SALES_QUOTE_DELETE";
    String ACCOUNTING_SALES_QUOTE_SUMMARY = "ACCOUNTING_SALES_QUOTE_SUMMARY";
    String ACCOUNTING_SALES_QUOTE_COPY = "ACCOUNTING_SALES_QUOTE_COPY";
    String ACCOUNTING_SALES_ORDER_LIST = "ACCOUNTING_SALES_ORDER_LIST";
    String ACCOUNTING_SALES_ORDER_ADD = "ACCOUNTING_SALES_ORDER_ADD";
    String ACCOUNTING_SALES_ORDER_DELETE = "ACCOUNTING_SALES_ORDER_DELETE";
    String ACCOUNTING_SALES_ORDER_SUMMARY = "ACCOUNTING_SALES_ORDER_SUMMARY";
    String ACCOUNTING_SALES_ORDER_PICKLIST = "ACCOUNTING_SALES_ORDER_PICKLIST";
    String ACCOUNTING_SALES_ORDER_COPYTOPO = "ACCOUNTING_SALES_ORDER_COPYTOPO";
    String ACCOUNTING_SALES_INVOICE_LIST = "ACCOUNTING_SALES_INVOICE_LIST";
    String ACCOUNTING_SALES_INVOICE_ADD = "ACCOUNTING_SALES_INVOICE_ADD";
    String ACCOUNTING_SALES_INVOICE_EDIT = "ACCOUNTING_SALES_INVOICE_EDIT";
    String ACCOUNTING_SALES_INVOICE_DELETE = "ACCOUNTING_SALES_INVOICE_DELETE";
    String ACCOUNTING_SALES_INVOICE_VOID = "ACCOUNTING_SALES_INVOICE_VOID";
    String ACCOUNTING_SALES_INVOICE_SUMMARY = "ACCOUNTING_SALES_INVOICE_SUMMARY";
    String ACCOUNTING_SALES_CREDIT_NOTE_ADD = "ACCOUNTING_SALES_CREDIT_NOTE_ADD";
    String ACCOUNTING_SALES_INVOICE_COPY = "ACCOUNTING_SALES_INVOICE_COPY";
    String ACCOUNTING_SALES_INVOICE_COPYTOPO = "ACCOUNTING_SALES_INVOICE_COPYTOPO";
    String ACCOUNTING_RECEIVE_PAYMENT = "ACCOUNTING_RECEIVE_PAYMENT";
    String ACCOUNTING_PREPAYMENT_ADD = "ACCOUNTING_PREPAYMENT_ADD";
    String ACCOUNTING_CUSTOMER_PROJECT_BALANCE = "ACCOUNTING_CUSTOMER_PROJECT_BALANCE";
    String ACCOUNTING_RECURRING_INVOICE_LIST = "ACCOUNTING_RECURRING_INVOICE_LIST";
    String ACCOUNTING_RECURRING_INVOICE_ADD = "ACCOUNTING_RECURRING_INVOICE_ADD";
    String ACCOUNTING_RECURRING_INVOICE_EDIT = "ACCOUNTING_RECURRING_INVOICE_EDIT";
    String ACCOUNTING_RECURRING_INVOICE_DELETE = "ACCOUNTING_RECURRING_INVOICE_DELETE";
    String ACCOUNTING_RECURRING_INVOICE_SUMMARY = "ACCOUNTING_RECURRING_INVOICE_SUMMARY";
    String ACCOUNTING_RECURRING_INVOICE_COPY = "ACCOUNTING_RECURRING_INVOICE_COPY";
    String ACCOUNTING_CUSTOMER_LIST = "ACCOUNTING_CUSTOMER_LIST";
    String ACCOUNTING_CUSTOMER_ADD = "ACCOUNTING_CUSTOMER_ADD";
    String ACCOUNTING_CUSTOMER_EDIT = "ACCOUNTING_CUSTOMER_EDIT";
    String ACCOUNTING_CUSTOMER_DELETE = "ACCOUNTING_CUSTOMER_DELETE";
    String ACCOUNTING_CUSTOMER_SUMMARY = "ACCOUNTING_CUSTOMER_SUMMARY";
    String ACCOUNTING_PURCHASE_ORDER_LIST = "ACCOUNTING_PURCHASE_ORDER_LIST";
    String ACCOUNTING_PURCHASE_ORDER_ADD = "ACCOUNTING_PURCHASE_ORDER_ADD";
    String ACCOUNTING_PURCHASE_ORDER_EDIT = "ACCOUNTING_PURCHASE_ORDER_EDIT";
    String ACCOUNTING_PURCHASE_ORDER_DELETE = "ACCOUNTING_PURCHASE_ORDER_DELETE";
    String ACCOUNTING_PURCHASE_ORDER_SUMMARY = "ACCOUNTING_PURCHASE_ORDER_SUMMARY";
    String ACCOUNTING_PURCHASE_ORDER_COPY = "ACCOUNTING_PURCHASE_ORDER_COPY";
    String ACCOUNTING_PURCHASE_INVOICE_LIST = "ACCOUNTING_PURCHASE_INVOICE_LIST";
    String ACCOUNTING_PURCHASE_INVOICE_ADD = "ACCOUNTING_PURCHASE_INVOICE_ADD";
    String ACCOUNTING_PURCHASE_INVOICE_EDIT = "ACCOUNTING_PURCHASE_INVOICE_EDIT";
    String ACCOUNTING_PURCHASE_INVOICE_DELETE = "ACCOUNTING_PURCHASE_INVOICE_DELETE";
    String ACCOUNTING_PURCHASE_INVOICE_VOID = "ACCOUNTING_PURCHASE_INVOICE_VOID";
    String ACCOUNTING_PURCHASE_INVOICE_SUMMARY = "ACCOUNTING_PURCHASE_INVOICE_SUMMARY";
    String ACCOUNTING_PURCHASE_CREDIT_NOTE_ADD = "ACCOUNTING_PURCHASE_CREDIT_NOTE_ADD";
    String ACCOUNTING_PURCHASE_INVOICE_COPY = "ACCOUNTING_PURCHASE_INVOICE_COPY";
    String ACCOUNTING_PAY_BILL = "ACCOUNTING_PAY_BILL";
    String ACCOUNTING_SUPPLIER_LIST = "ACCOUNTING_SUPPLIER_LIST";
    String ACCOUNTING_SUPPLIER_ADD = "ACCOUNTING_SUPPLIER_ADD";
    String ACCOUNTING_SUPPLIER_EDIT = "ACCOUNTING_SUPPLIER_EDIT";
    String ACCOUNTING_SUPPLIER_DELETE = "ACCOUNTING_SUPPLIER_DELETE";
    String ACCOUNTING_SUPPLIER_SUMMARY = "ACCOUNTING_SUPPLIER_SUMMARY";
    String ACCOUNTING_FIXED_ASSET_LIST = "ACCOUNTING_FIXED_ASSET_LIST";
    String ACCOUNTING_FIXED_ASSET_ADD = "ACCOUNTING_FIXED_ASSET_ADD";
    String ACCOUNTING_FIXED_ASSET_EDIT = "ACCOUNTING_FIXED_ASSET_EDIT";
    String ACCOUNTING_FIXED_ASSET_DELETE = "ACCOUNTING_FIXED_ASSET_DELETE";
    String ACCOUNTING_FIXED_ASSET_DEPRECIATION_UPDATE = "ACCOUNTING_FIXED_ASSET_DEPRECIATION_UPDATE";
    String ACCOUNTING_PRODUCT_LIST = "ACCOUNTING_PRODUCT_LIST";
    String ACCOUNTING_PRODUCT_ADD = "ACCOUNTING_PRODUCT_ADD";
    String ACCOUNTING_PRODUCT_GROUP_ADD = "ACCOUNTING_PRODUCT_GROUP_ADD";
    String ACCOUNTING_PRODUCT_EDIT = "ACCOUNTING_PRODUCT_EDIT";
    String ACCOUNTING_PRODUCT_DELETE = "ACCOUNTING_PRODUCT_DELETE";
    String ACCOUNTING_PRODUCT_SUMMARY = "ACCOUNTING_PRODUCT_SUMMARY";
    String ACCOUNTING_VARIATION_ADD = "ACCOUNTING_VARIATION_ADD";
    String ACCOUNTING_VARIATION_DELETE = "ACCOUNTING_VARIATION_DELETE";
    String ACCOUNTING_STOCK_ADJUSTMENT = "ACCOUNTING_STOCK_ADJUSTMENT";
    String ACCOUNTING_STOCK_ADJUSTMENT_ADD = "ACCOUNTING_STOCK_ADJUSTMENT_ADD";
    String ACCOUNTING_STOCK_ADJUSTMENT_EDIT = "ACCOUNTING_STOCK_ADJUSTMENT_EDIT";
    String ACCOUNTING_STOCK_ADJUSTMENT_DELETE = "ACCOUNTING_STOCK_ADJUSTMENT_DELETE";
    String ACCOUNTING_STOCK_ADJUSTMENT_APPROVE = "ACCOUNTING_STOCK_ADJUSTMENT_APPROVE";
    String ACCOUNTING_STOCK_ADJUSTMENT_DECLINE = "ACCOUNTING_STOCK_ADJUSTMENT_DECLINE";
    String ACCOUNTING_STOCK_ADJUSTMENT_SEND_TO_APPROVER = "ACCOUNTING_STOCK_ADJUSTMENT_SEND_TO_APPROVER";

    String ACCOUNTING_STOCK_TRANSFER = "ACCOUNTING_STOCK_TRANSFER";
    String ACCOUNTING_STOCK_TRANSFER_ADD = "ACCOUNTING_STOCK_TRANSFER_ADD";
    String ACCOUNTING_STOCK_TRANSFER_EDIT = "ACCOUNTING_STOCK_TRANSFER_EDIT";
    String ACCOUNTING_STOCK_TRANSFER_DELETE = "ACCOUNTING_STOCK_TRANSFER_DELETE";
    String ACCOUNTING_STOCK_TRANSFER_APPROVE = "ACCOUNTING_STOCK_TRANSFER_APPROVE";
    String ACCOUNTING_STOCK_TRANSFER_DECLINE = "ACCOUNTING_STOCK_TRANSFER_DECLINE";
    String ACCOUNTING_STOCK_TRANSFER_SEND_TO_APPROVER = "ACCOUNTING_STOCK_TRANSFER_SEND_TO_APPROVER";
    String ACCOUNTING_STOCK_TRANSFER_TRANSFERRED = "ACCOUNTING_STOCK_TRANSFER_TRANSFERRED";

    String ACCOUNTING_EXPENSE_REPORT_LIST = "ACCOUNTING_EXPENSE_REPORT_LIST";
    String ACCOUNTING_EXPENSE_REPORT_ADD = "ACCOUNTING_EXPENSE_REPORT_ADD";
    String ACCOUNTING_EXPENSE_REPORT_EDIT = "ACCOUNTING_EXPENSE_REPORT_EDIT";
    String ACCOUNTING_EXPENSE_REPORT_DELETE = "ACCOUNTING_EXPENSE_REPORT_DELETE";
    String ACCOUNTING_EXPENSE_REPORT_VOID = "ACCOUNTING_EXPENSE_REPORT_VOID";
    String ACCOUNTING_EXPENSE_REPORT_SUMMARY = "ACCOUNTING_EXPENSE_REPORT_SUMMARY";
    String ACCOUNTING_CHECK_LIST = "ACCOUNTING_CHECK_LIST";
    String ACCOUNTING_BANK_ACCOUNT_LIST = "ACCOUNTING_BANK_ACCOUNT_LIST";
    String ACCOUNTING_BANK_ACCOUNT_ADD = "ACCOUNTING_BANK_ACCOUNT_ADD";
    String ACCOUNTING_BANK_ACCOUNT_EDIT = "ACCOUNTING_BANK_ACCOUNT_EDIT";
    String ACCOUNTING_BANK_ACCOUNT_DELETE = "ACCOUNTING_BANK_ACCOUNT_DELETE";
    String ACCOUNTING_BANK_ACCOUNT_SPEND = "ACCOUNTING_BANK_ACCOUNT_SPEND";
    String ACCOUNTING_BANK_ACCOUNT_RECEIVE = "ACCOUNTING_BANK_ACCOUNT_RECEIVE";
    String ACCOUNTING_BANK_ACCOUNT_TRANSFER = "ACCOUNTING_BANK_ACCOUNT_TRANSFER";
    String ACCOUNTING_BANK_ACCOUNT_TRANSACTION_IMPORT = "ACCOUNTING_BANK_ACCOUNT_TRANSACTION_IMPORT";
    String ACCOUNTING_BANK_ACCOUNT_TRANSACTIONS = "ACCOUNTING_BANK_ACCOUNT_TRANSACTIONS";
    String ACCOUNTING_BANK_STATEMENT = "ACCOUNTING_BANK_STATEMENT";
    String ACCOUNTING_ACCOUNT_LIST = "ACCOUNTING_ACCOUNT_LIST";
    String ACCOUNTING_ACCOUNT_ADD = "ACCOUNTING_ACCOUNT_ADD";
    String ACCOUNTING_ACCOUNT_EDIT = "ACCOUNTING_ACCOUNT_EDIT";
    String ACCOUNTING_ACCOUNT_DELETE = "ACCOUNTING_ACCOUNT_DELETE";
    String ACCOUNTING_ACCOUNT_SUMMARY = "ACCOUNTING_ACCOUNT_SUMMARY";
    String ACCOUNTING_RESERVATION_LIST = "ACCOUNTING_RESERVATION_LIST";
    String ACCOUNTING_RESERVATION_ADD = "ACCOUNTING_RESERVATION_ADD";
    String ACCOUNTING_RESERVATION_EDIT = "ACCOUNTING_RESERVATION_EDIT";
    String ACCOUNTING_REQUEST_FOR_QUOTE = "ACCOUNTING_REQUEST_FOR_QUOTE";
    String ACCOUNTING_REQUEST_FOR_QUOTE_ADD = "ACCOUNTING_REQUEST_FOR_QUOTE_ADD";
    String ACCOUNTING_REQUEST_FOR_QUOTE_EDIT = "ACCOUNTING_REQUEST_FOR_QUOTE_EDIT";
    String ACCOUNTING_REQUEST_FOR_QUOTE_DELETE = "ACCOUNTING_REQUEST_FOR_QUOTE_DELETE";
    String ACCOUNTING_REQUEST_FOR_PURCHASE = "ACCOUNTING_REQUEST_FOR_PURCHASE";
    String ACCOUNTING_REQUEST_FOR_PURCHASE_ADD = "ACCOUNTING_REQUEST_FOR_PURCHASE_ADD";
    String ACCOUNTING_REQUEST_FOR_PURCHASE_EDIT = "ACCOUNTING_REQUEST_FOR_PURCHASE_EDIT";
    String ACCOUNTING_REQUEST_FOR_PURCHASE_DELETE = "ACCOUNTING_REQUEST_FOR_PURCHASE_DELETE";
    String ACCOUNTING_MANUAL_JOURNAL = "ACCOUNTING_MANUAL_JOURNAL";
    String ACCOUNTING_MANUAL_JOURNAL_LIST = "ACCOUNTING_MANUAL_JOURNAL_LIST";
    String ACCOUNTING_MANUAL_JOURNAL_ADD = "ACCOUNTING_MANUAL_JOURNAL_ADD";
    String ACCOUNTING_MANUAL_JOURNAL_EDIT = "ACCOUNTING_MANUAL_JOURNAL_EDIT";
    String ACCOUNTING_MANUAL_JOURNAL_DELETE = "ACCOUNTING_MANUAL_JOURNAL_DELETE";
    String ACCOUNTING_MANUAL_JOURNAL_VOID = "ACCOUNTING_MANUAL_JOURNAL_VOID";
    String ACCOUNTING_MANUAL_JOURNAL_SUMMARY = "ACCOUNTING_MANUAL_JOURNAL_SUMMARY";
    String MANUAL_JOURNAL_APPLIED = "MANUAL_JOURNAL_APPLIED";
    String MANUAL_JOURNAL_APPLIED_RECEIVABLE_PAYABLE = "MANUAL_JOURNAL_APPLIED_RECEIVABLE_PAYABLE";
    String MANUAL_JOURNAL_APPLIED_RECEIVABLE_PAYABLE_MESSAGE = "MANUAL_JOURNAL_APPLIED_RECEIVABLE_PAYABLE_MESSAGE";
    String ACCOUNTING_WAREHOUSE_LIST = "ACCOUNTING_WAREHOUSE_LIST";
    String ACCOUNTING_BUDGET_SHEET = "ACCOUNTING_BUDGET_SHEET";
    String ACCOUNTING_JOURNAL_REPORT = "ACCOUNTING_JOURNAL_REPORT";
    String ACCOUNTING_TRIAL_BALANCE = "ACCOUNTING_TRIAL_BALANCE";
    String ACCOUNTING_PROFIT_AND_LOSS = "ACCOUNTING_PROFIT_AND_LOSS";
    String ACCOUNTING_BALANCE_SHEET = "ACCOUNTING_BALANCE_SHEET";
    String ACCOUNTING_ACCOUNT_TRANSACTIONS = "ACCOUNTING_ACCOUNT_TRANSACTIONS";
    String ACCOUNTING_VAT_RETURN = "ACCOUNTING_VAT_RETURN";
    String ACCOUNTING_VAT_RETURNS_LIST = "ACCOUNTING_VAT_RETURNS_LIST";
    String ACCOUNTING_STOCK_VALUATION = "ACCOUNTING_STOCK_VALUATION";
    String ACCOUNTING_INVOICE_SETTINGS = "ACCOUNTING_INVOICE_SETTINGS";
    String ACCOUNTING_FINANCIAL_SETTINGS = "ACCOUNTING_FINANCIAL_SETTINGS";
    String ACCOUNTING_ACCOUNT_NUMBERING = "ACCOUNTING_ACCOUNT_NUMBERING";
    String ACCOUNTING_CONVERSION_BALANCE = "ACCOUNTING_CONVERSION_BALANCE";
    String ACCOUNTING_NUMBERING_SETTINGS = "ACCOUNTING_NUMBERING_SETTINGS";
    String ACCOUNTING_TAX_RATES_LIST = "ACCOUNTING_TAX_RATES_LIST";
    String ACCOUNTING_PRICE_LEVELS_LIST = "ACCOUNTING_PRICE_LEVELS_LIST";
    String ACCOUNTING_DISCOUNTS_LIST = "ACCOUNTING_DISCOUNTS_LIST";
    String ACCOUNTING_UNIT_MEASUREMENTS_LIST = "ACCOUNTING_UNIT_MEASUREMENTS_LIST";
    String ACCOUNTING_PRODUCT_CATEGORIES_LIST = "ACCOUNTING_PRODUCT_CATEGORIES_LIST";
    String ACCOUNTING_BRANDS_LIST = "ACCOUNTING_BRANDS_LIST";
    String ACCOUNTING_SHIPPING_METHODS_LIST = "ACCOUNTING_SHIPPING_METHODS_LIST";
    String ACCOUNTING_INVOICE_TEMPLATES_LIST = "ACCOUNTING_INVOICE_TEMPLATES_LIST";
    String ACCOUNTING_SAASU_INTEGRATION_SETTINGS = "ACCOUNTING_SAASU_INTEGRATION_SETTINGS";
    String PM_PROJECT_EMPLOYEES = "PM_PROJECT_EMPLOYEES";
    String PM_PROJECT_GANTT_CHART = "PM_PROJECT_GANTT_CHART";
    String PM_PROJECT_DOCUMENTS = "PM_PROJECT_DOCUMENTS";
    String PM_PROJECT_NOTES = "PM_PROJECT_NOTES";
    String PM_PROJECT_REMOVE = "PM_PROJECT_REMOVE";
    String PM_PROJECT_WORK_BREAKDOWN_STRUCTURE = "PM_PROJECT_WORK_BREAKDOWN_STRUCTURE";
    String PM_PROJECT_WORKSTREAM_ADD = "PM_PROJECT_WORKSTREAM_ADD";
    String PM_PROJECT_RESOURCE_WORK_LOAD = "PM_PROJECT_RESOURCE_WORK_LOAD";
    String PM_PROJECT_PURCHASE_ORDER = "PM_PROJECT_PURCHASE_ORDER";
    String PM_PROJECT_PURCHASE_INVOICE = "PM_PROJECT_PURCHASE_INVOICE";
    String PM_PROJECT_EXPENSE_CLAIMS = "PM_PROJECT_EXPENSE_CLAIMS";
    String PM_PROJECT_CASE = "PM_PROJECT_CASE";
    String PM_PROJECT_ISSUE = "PM_PROJECT_ISSUE";
    String PM_CASE_ADD_NEW = "PM_CASE_ADD_NEW";
    String HRMS_SECTION_TAB = "HRMS_SECTION_TAB";
    String HRMS_EMPLOYEES = "HRMS_EMPLOYEES";
    String HRMS_DEPARTMENT = "HRMS_DEPARTMENT";
    String HRMS_SALARY_GRADE = "HRMS_SALARY_GRADE";
    String HRMS_POSITION = "HRMS_POSITION";
    String HRMS_LOCATION = "HRMS_LOCATION";
    String HRMS_CURENT_EMPLOYEE_PROFILE_TAB = "HRMS_CURENT_EMPLOYEE_PROFILE_TAB";
    String HRMS_EMPLOYEE_PROFILE_SUMMARY = "HRMS_EMPLOYEE_PROFILE_SUMMARY";
    String HRMS_LIVE_REQUEST = "HRMS_LIVE_REQUEST";
    String HRMS_EXPENCE_REPORT = "HRMS_EXPENCE_REPORT";
    String HRMS_GOALS = "HRMS_GOALS";
    String HRMS_TALENT_PROFILE = "HRMS_TALENT_PROFILE";
    String HRMS_INCIDENT_LIST = "HRMS_INCIDENT_LIST";
    String HRMS_DOCUMENT = "HRMS_DOCUMENT";
    String HRMS_GOAL_MANAGEMENT_TAB = "HRMS_GOAL_MANAGEMENT_TAB";
    String HRMS_PERSONAL_GOALS = "HRMS_PERSONAL_GOALS";
    String HRMS_DEPARTMENT_GOALS = "HRMS_DEPARTMENT_GOALS";
    String HRMS_PROJECT_GOALS = "HRMS_PROJECT_GOALS";
    String HRMS_BUSINESS_GOALS = "HRMS_BUSINESS_GOALS";
    String HRMS_COMPANY_GOALS = "HRMS_COMPANY_GOALS";
    String HRMS_PERFORMANCE_APPRAISALS_TAB = "HRMS_PERFORMANCE_APPRAISALS_TAB";
    String HRMS_360_REVIEW = "HRMS_360_REVIEW";
    String HRMS_SIMPLE_APPRAISALS = "HRMS_SIMPLE_APPRAISALS";
    String HRMS_APPRAISALS_ARCHIVE = "HRMS_APPRAISALS_ARCHIVE";
    String HRMS_TEMPLATES = "HRMS_TEMPLATES";
    String HRMS_COMPETENCES = "HRMS_COMPETENCES";
    String HRMS_PERFORMANCE_NOTE = "HRMS_PERFORMANCE_NOTE";
    String HRMS_ATTENDANCE_TRACKING_TAB = "HRMS_ATTENDANCE_TRACKING_TAB";
    String HRMS_ATTENDANCE_HOME = "HRMS_ATTENDANCE_HOME";
    String HRMS_MY_ATTENDANCE = "HRMS_MY_ATTENDANCE";
    String HRMS_ATTENDANCE_TRACKING = "HRMS_ATTENDANCE_TRACKING";
    String HRMS_ATTENDANCE_REPORT = "HRMS_ATTENDANCE_REPORT";
    String HRMS_EMPLOYEE_LIVE_STATUS = "HRMS_EMPLOYEE_LIVE_STATUS";
    String HRMS_APPROVE_LIVE_STATUS = "HRMS_APPROVE_LIVE_STATUS";
    String HRMS_ADD_NEW_EMPLOYEE = "HRMS_ADD_NEW_EMPLOYEE";
    String HRMS_EMPLOYEE_PROFILE = "HRMS_EMPLOYEE_PROFILE";
    String HRMS_EDIT_PROFILE = "HRMS_EDIT_PROFILE";
    String HRMS_EDIT_GOAL_WEIGHTS = "HRMS_EDIT_GOAL_WEIGHTS";
    String HRMS_EMPLOYEE_REMOVE = "HRMS_EMPLOYEE_REMOVE";
    String HRMS_ACTIVATE_DEACTIVATE = "HRMS_ACTIVATE_DEACTIVATE";
    String HRMS_EMPLOYEES_EXPORT_TO_PDF = "HRMS_EMPLOYEES_EXPORT_TO_PDF";
    String HRMS_ADD_NEW_DEPARTMENT = "HRMS_ADD_NEW_DEPARTMENT";
    String HRMS_DEPARTMENT_SUMMARY = "HRMS_DEPARTMENT_SUMMARY";
    String HRMS_EDIT_DEPARTMENT = "HRMS_EDIT_DEPARTMENT";
    String HRMS_DEPARTMENT_REMOVE = "HRMS_DEPARTMENT_REMOVE";
    String HRMS_DEPARTMENT_NOTES = "HRMS_DEPARTMENT_NOTES";
    String HRMS_DEPARTMENTS_EXPORT_TO_PDF = "HRMS_DEPARTMENTS_EXPORT_TO_PDF";
    String HRMS_ADD_NEW_LOCATION = "HRMS_ADD_NEW_LOCATION";
    String HRMS_LOCATION_SUMMARY = "HRMS_LOCATION_SUMMARY";
    String HRMS_EDIT_LOCATION = "HRMS_EDIT_LOCATION";
    String HRMS_REMOVE_LOCATION = "HRMS_REMOVE_LOCATION";
    String PM_EMPLOYEE_SUMMARY = "PM_EMPLOYEE_SUMMARY";

    String HRMS_PLACEMENT = "HRMS_PLACEMENT";
    String HRMS_PLACEMENT_ADD = "HRMS_PLACEMENT_ADD";
    String HRMS_PLACEMENT_EDIT = "HRMS_PLACEMENT_EDIT";
    String HRMS_PLACEMENT_DELETE = "HRMS_PLACEMENT_DELETE";
    String HRMS_PLACEMENT_APPROVE = "HRMS_PLACEMENT_APPROVE";
    String HRMS_PLACEMENT_DECLINE = "HRMS_PLACEMENT_DECLINE";
    String HRMS_PLACEMENT_SEND_TO_APPROVER = "HRMS_PLACEMENT_SEND_TO_APPROVER";

    ///////////////// Shift ///////////////////////////////
    String SHIFT = "SHIFT";
    String SHIFT_ADD = "SHIFT_ADD";
    String SHIFT_EDIT = "SHIFT_EDIT";
    String SHIFT_DELETE = "SHIFT_DELETE";
    String SHIFT_APPROVED = "SHIFT_APPROVED";
    String SHIFT_REJECTED = "SHIFT_REJECTED";
    String SHIFT_DRAFT = "SHIFT_DRAFT";

    ///////////////// Rotation ///////////////////////////////
    String ROTATION = "ROTATION";
    String ROTATION_ADD = "ROTATION_ADD";
    String ROTATION_EDIT = "ROTATION_EDIT";
    String ROTATION_DELETE = "ROTATION_DELETE";
    String ROTATION_APPROVED = "ROTATION_APPROVED";
    String ROTATION_REJECTED = "ROTATION_REJECTED";
    String ROTATION_DRAFT = "ROTATION_DRAFT";

    ///////////////// Group Placement ///////////////////////////////
    String GROUP_PLACEMENT = "GROUP_PLACEMENT";
    String GROUP_PLACEMENT_ADD = "GROUP_PLACEMENT_ADD";
    String GROUP_PLACEMENT_EDIT = "GROUP_PLACEMENT_EDIT";
    String GROUP_PLACEMENT_DELETE = "GROUP_PLACEMENT_DELETE";
    String GROUP_PLACEMENT_APPROVED = "GROUP_PLACEMENT_APPROVED";
    String GROUP_PLACEMENT_REJECTED = "GROUP_PLACEMENT_REJECTED";
    String GROUP_PLACEMENT_DRAFT = "GROUP_PLACEMENT_DRAFT";

    String REJECTED_PLACEMENT = "REJECTED_PLACEMENT";
    String ADDED_PLACEMENT = "ADDED_PLACEMENT";
    String EDITED_PLACEMENT = "EDITED_PLACEMENT";
    String DRAFT_PLACEMENT = "DRAFT_PLACEMENT";
    String APPROVED_PLACEMENT = "APPROVED_PLACEMENT";
    String SUBMITTED_TO_MANAGER_PLACEMENT = "SUBMITTED_TO_MANAGER_PLACEMENT";

    ///////////////// PRODUCT CATEGORY ///////////////////////////////
    String PRODUCT_CATEGORY = "PRODUCT_CATEGORY";
    String PRODUCT_CATEGORY_ADD = "PRODUCT_CATEGORY_ADD";
    String PRODUCT_CATEGORY_EDIT = "PRODUCT_CATEGORY_EDIT";
    String PRODUCT_CATEGORY_DELETE = "PRODUCT_CATEGORY_DELETE";
    String PRODUCT_CATEGORY_APPROVED = "PRODUCT_CATEGORY_APPROVED";
    String PRODUCT_CATEGORY_REJECTED = "PRODUCT_CATEGORY_REJECTED";
    String PRODUCT_CATEGORY_DRAFT = "PRODUCT_CATEGORY_DRAFT";

    ///////////////// COURSE SCHEDULE ///////////////////////////////
    String COURSE_SCHEDULE = "COURSE_SCHEDULE";
    String COURSE_SCHEDULE_ADD = "COURSE_SCHEDULE_ADD";


    String PM_EMPLOYEE_NOTE = "PM_EMPLOYEE_NOTE";
    String PM_EMPLOYEE_EDIT = "PM_EMPLOYEE_EDIT";
    String PM_EMPLOYEE_REMOVE = "PM_EMPLOYEE_REMOVE";
    String PM_EMPLOYEE_ACTIVATE_DEACTIVATE = "PM_EMPLOYEE_ACTIVATE_DEACTIVATE";
    String CRM_TASKS_ADD = "CRM_TASKS_ADD";
    String CRM_TASKS_ADD_MULTI = "CRM_TASKS_ADD_MULTI";
    String CRM_TASKS_EDIT = "CRM_TASKS_EDIT";
    String CRM_TASKS_DOCUMENTS = "CRM_TASKS_DOCUMENTS";
    String CRM_TASKS_NOTES = "CRM_TASKS_NOTES";
    String CRM_TASKS_REMOVE = "CRM_TASKS_REMOVE";
    String CRM_TASKS_PDF_EXCEL_EXPORT = "CRM_TASKS_PDF_EXCEL_EXPORT";
    String CRM_TASKS_TIMER = "CRM_TASKS_TIMER";
    String CRM_TASKS_COMPOSE = "CRM_TASKS_COMPOSE";
    String PM_TASKS_MEMBERS_INVOLVED = "PM_TASKS_MEMBERS_INVOLVED";
    String PM_TASKS_COMMENTS = "PM_TASKS_COMMENTS";
    String PM_TASKS_EMAILS = "PM_TASKS_EMAILS";
    String PM_TASKS_COMPOSE = "PM_TASKS_COMPOSE";
    String PM_TASKS_CASE = "PM_TASKS_CASE";
    String PM_TASKS_ISSUE = "PM_TASKS_ISSUE";
    String PM_PROJECT_SALES_QUOTE = "PM_PROJECT_SALES_QUOTE";
    String PM_PROJECT_EMAIL = "PM_PROJECT_EMAIL";
    String PM_PROJECT_EMAIL_COMPOSE = "PM_PROJECT_EMAIL_COMPOSE";
    String PM_PROJECT_EMAIL_TRASH = "PM_PROJECT_EMAIL_TRASH";
    String PM_TASK_EMAIL_TRASH = "PM_TASK_EMAIL_TRASH";
    String PM_DEPARTMENT_SUMMARY = "PM_DEPARTMENT_SUMMARY";
    String HRMS_PROFILE_NOTE = "HRMS_PROFILE_NOTE";
    String CRM_ACCOUNT_ADD = "CRM_ACCOUNT_ADD";
    String CRM_SUPPLIER_ADD = "CRM_SUPPLIER_ADD";
    String CRM_CLIENT_ADD = "CRM_CLIENT_ADD";
    String CRM_ACCOUNTS_CONVERT = "CRM_ACCOUNTS_CONVERT";
    String CRM_ACCOUNTS_MERGE = "CRM_ACCOUNTS_MERGE";
    String CRM_ACCOUNTS_DETECT_DUBLICATES = "CRM_ACCOUNTS_DETECT_DUBLICATES";
    String CRM_ACCOUNTS_DELETE = "CRM_ACCOUNTS_DELETE";
    String CRM_ACCOUNTS_ACTIVITY_ADD = "CRM_ACCOUNTS_ACTIVITY_ADD";
    String CRM_ACCOUNTS_EDIT = "CRM_ACCOUNTS_EDIT";
    String CRM_ACCOUNTS_SEND_SALES_QUOTE = "CRM_ACCOUNTS_SEND_SALES_QUOTE";
    String CRM_ACCOUNTS_SEND_SALES_INVOICE = "CRM_ACCOUNTS_SEND_SALES_INVOICE";
    String PM_ASSIGN_TASK_TO_MEMBER = "PM_ASSIGN_TASK_TO_MEMBER";
    String CRM_ADD_NEW_OPPORTUNITIES = "CRM_ADD_NEW_OPPORTUNITIES";
    String CRM_SUMMARY_OPPORTUNITIES = "CRM_SUMMARY_OPPORTUNITIES";
    String CRM_CONVERT_OPPORTUNITIES = "CRM_CONVERT_OPPORTUNITIES";
    String CRM_EDIT_OPPORTUNITIES = "CRM_EDIT_OPPORTUNITIES";
    String CRM_REMOVE_OPPORTUNITIES = "CRM_REMOVE_OPPORTUNITIES";
    String CRM_REMOVE_CASE = "CRM_REMOVE_CASE";
    String CRM_CHANGE_STATUS_CASE = "CRM_CHANGE_STATUS_CASE";
    String CRM_CHANGE_PRIORITY_CASE = "CRM_CHANGE_PRIORITY_CASE";
    String CRM_CHANGE_ASSIGNEE_CASE = "CRM_CHANGE_ASSIGNEE_CASE";
    String CRM_CLOSE_CASE = "CRM_CLOSE_CASE";
    String CRM_CONVERT_TO_CASE = "CRM_CONVERT_TO_CASE";
    String CRM_CREATE_TASK_CASE = "CRM_CREATE_TASK_CASE";
    String CRM_EDIT_CASE = "CRM_EDIT_CASE";
    String CRM_ADD_NEW_CAMPAIGN = "CRM_ADD_NEW_CAMPAIGN";
    String CRM_SUMMARY_CAMPAIGN = "CRM_SUMMARY_CAMPAIGN";
    String CRM_EDIT_CAMPAIGN = "CRM_EDIT_CAMPAIGN";
    String CRM_REMOVE_CAMPAIGN = "CRM_REMOVE_CAMPAIGN";
    String CRM_ADD_NEW_ACTIVITY_EVENT = "CRM_ADD_NEW_ACTIVITY_EVENT";
    String CRM_ADD_NEW_ACTIVITY_LOG_A_CALL = "CRM_ADD_NEW_ACTIVITY_LOG_A_CALL";
    String CRM_SUMMARY_ACTIVITY = "CRM_SUMMARY_ACTIVITY";
    String CRM_EDIT_ACTIVITY = "CRM_EDIT_ACTIVITY";
    String CRM_REMOVE_ACTIVITY = "CRM_REMOVE_ACTIVITY";
    String CRM_ADD_NEW_WEB_FORM = "CRM_ADD_NEW_WEB_FORM";
    String CRM_SUMMARY_WEB_FORM = "CRM_SUMMARY_WEB_FORM";
    String CRM_EDIT_WEB_FORM = "CRM_EDIT_WEB_FORM";
    String CRM_REMOVE_WEB_FORM = "CRM_REMOVE_WEB_FORM";
    String CRM_ADD_NEW_CONTACT = "CRM_ADD_NEW_CONTACT";
    String CRM_ADD_NEW_CATEGORY = "CRM_ADD_NEW_CATEGORY";
    String CRM_ADD_NEW_MAILING_LIST = "CRM_ADD_NEW_MAILING_LIST";
    String CRM_COPY_TO_CATEGORY = "CRM_COPY_TO_CATEGORY";
    String CRM_MOVE_TO_CATEGORY = "CRM_MOVE_TO_CATEGORY";
    String CRM_ADD_SUBSCRIPTIONS = "CRM_ADD_SUBSCRIPTIONS";
    String CRM_REMOVE_FROM_CATEGORY = "CRM_REMOVE_FROM_CATEGORY";
    String CRM_REMOVE_CONTACT = "CRM_REMOVE_CONTACT";
    String CRM_ACTIVATE_DEACTIVATE_CONTACT = "CRM_ACTIVATE_DEACTIVATE_CONTACT";
    String CRM_EDIT_CONTACT = "CRM_EDIT_CONTACT";
    String CRM_EDIT_SUBSCRIPTION = "CRM_EDIT_SUBSCRIPTION";
    String CRM_SEND_SALES_INVOICE = "CRM_SEND_SALES_INVOICE";
    String CRM_SEND_SALES_QUOTE = "CRM_SEND_SALES_QUOTE";
    String CRM_CONTACT_LOOK_UP = "CRM_CONTACT_LOOK_UP";
    String CRM_CONTACT_ADD_ACTIVITY = "CRM_CONTACT_ADD_ACTIVITY";
    String CRM_SUMMARY_CONTACT = "CRM_SUMMARY_CONTACT";
    String CRM_NOTE_CONTACT = "CRM_NOTE_CONTACT";
    String PM_RESOURCE_UTILIZATION_LIST = "PM_RESOURCE_UTILIZATION_LIST";
    String PM_RESOURCE_UTILIZATION_EDITABLE = "PM_RESOURCE_UTILIZATION_EDITABLE";
    String PM_ASSIGN_ISSUE_TO_MEMBER = "PM_ASSIGN_ISSUE_TO_MEMBER";
    String PM_APPROVE_REJECT_ALL_TIMESHEETS = "PM_APPROVE_REJECT_ALL_TIMESHEETS";
    String HRMS_ANNUAL_ALLOWANCE = "HRMS_ANNUAL_ALLOWANCE";
    String HRMS_ADD_NEW_ACTIVITY_EVENT = "HRMS_ADD_NEW_ACTIVITY_EVENT";
    String HRMS_ADD_NEW_ACTIVITY_LOG_A_CALL = "HRMS_ADD_NEW_ACTIVITY_LOG_A_CALL";
    String HRMS_SUMMARY_ACTIVITY = "HRMS_SUMMARY_ACTIVITY";
    String HRMS_EDIT_ACTIVITY = "HRMS_EDIT_ACTIVITY";
    String HRMS_REMOVE_ACTIVITY = "HRMS_REMOVE_ACTIVITY";
    String SETTINGS_COMPANY_SETTINGS = "SETTINGS_COMPANY_SETTINGS";
    String SETTINGS_ACCOUNTING_SETTINGS = "SETTINGS_ACCOUNTING_SETTINGS";
    String SETTINGS_RECURRENCE_SETTINGS = "SETTINGS_RECURRENCE_SETTINGS";
    String SETTINGS_PROFILE_SETTINGS = "SETTINGS_PROFILE_SETTINGS";
    String SETTINGS_USER_CREDENTIALS = "SETTINGS_USER_CREDENTIALS";
    String SETTINGS_EMAIL_SETTINGS = "SETTINGS_EMAIL_SETTINGS";
    String SETTINGS_PROJECT_MANAGEMENT_SETTINGS = "SETTINGS_PROJECT_MANAGEMENT_SETTINGS";
    String SETTINGS_HRMS_SETTINGS = "SETTINGS_HRMS_SETTINGS";
    String SETTINGS_CRM_SETTINGS = "SETTINGS_CRM_SETTINGS";
    String HRMS_DELETE_CANDIDATE = "HRMS_DELETE_CANDIDATE";
    String HRMS_RECRUITMENT = "HRMS_RECRUITMENT";
    String HRMS_ADD_VACAStringNCY = "HRMS_ADD_VACANCY";
    String HRMS_DELETE_VACANCY = "HRMS_DELETE_VACANCY";
    String HRMS_EDIT_VACANCY = "HRMS_EDIT_VACANCY";
    String HRMS_ADD_CANDIDATE = "HRMS_ADD_CANDIDATE";
    String HRMS_EDIT_CANDIDATE = "HRMS_EDIT_CANDIDATE";
    String HRMS_INTERVIEW_CANDIDATE = "HRMS_INTERVIEW_CANDIDATE";
    String HRMS_CHANGE_STATUS_CANDIDATE = "HRMS_CHANGE_STATUS_CANDIDATE";
    String HRMS_SELECT_CANDIDATE = "HRMS_SELECT_CANDIDATE";
    String HRMS_CALL_CANDIDATE = "HRMS_CALL_CANDIDATE";
    String HRMS_MAKE_PLACEMENT = "HRMS_MAKE_PLACEMENT";
    String HRMS_ADD_VALIDITY_PERIOD = "HRMS_ADD_VALIDITY_PERIOD";
    String HRMS_UPLOAD_DOCUMENT = "HRMS_UPLOAD_DOCUMENT";
    String HRMS_REMOVE_DOCUMENT = "HRMS_REMOVE_DOCUMENT";
    String PM_SEE_ALL_PROJECTS = "PM_SEE_ALL_PROJECTS";

    String DLOFPR = "DLofPR";
    String BMOFPR = "BMofPR";
    String CREATOR = "Creator";
    String PMOFPR = "PMofPR";

    String COMPANY_CUSTOM_FIELD = "COMPANY_CUSTOM_FIELD";
    String COMPANY_CUSTOM_FIELD_ADD = "COMPANY_CUSTOM_FIELD_ADD";
    String COMPANY_CUSTOM_FIELD_EDIT = "COMPANY_CUSTOM_FIELD_EDIT";
    String COMPANY_CUSTOM_FIELD_DELETE = "COMPANY_CUSTOM_FIELD_DELETE";
    String HAS_ADDED_CUSTOM_FIELD = "HAS_ADDED_CUSTOM_FIELD";
    String YOU_HAVE_ADDED_CUSTOM_FIELD = "YOU_HAVE_ADDED_CUSTOM_FIELD";
    String HAS_UPDATED_CUSTOM_FIELD = "HAS_UPDATED_CUSTOM_FIELD";
    String YOU_HAVE_UPDATED_CUSTOM_FIELD = "YOU_HAVE_UPDATED_CUSTOM_FIELD";
    String HAS_DELETED_CUSTOM_FIELD = "HAS_DELETED_CUSTOM_FIELD";
    String YOU_HAVE_DELETED_CUSTOM_FIELD = "YOU_HAVE_DELETED_CUSTOM_FIELD";

    String PANEL_SETTING = "PANEL_SETTING";
    String PANEL_SETTING_EDIT = "PANEL_SETTING_EDIT";
    String PANEL_SETTING_EDIT_BY = "PANEL_SETTING_EDIT_BY";
    String PANEL_SETTINGS_EDIT = "PANEL_SETTINGS_EDIT";

    String ADDED = "ADDED";
    String EDITED = "EDITED";
    String DELETED = "DELETED";
    String VOIDED = "VOIDED";
    String OF_AMOUNT = "OF_AMOUNT";

    String ADDED_SINGLE_PAYRUN = "ADDED_SINGLE_PAYRUN";
    String EDITED_SINGLE_PAYRUN = "EDITED_SINGLE_PAYRUN";
    String DELETED_SINGLE_PAYRUN = "DELETED_SINGLE_PAYRUN";
    String SUBMITTED_SINGLE_PAYRUN = "SUBMITTED_SINGLE_PAYRUN";
    String APPROVED_SINGLE_PAYRUN = "APPROVED_SINGLE_PAYRUN";
    String REJECTED_SINGLE_PAYRUN = "REJECTED_SINGLE_PAYRUN";

    String ADDED_GROUP_PAYRUN = "ADDED_GROUP_PAYRUN";
    String EDITED_GROUP_PAYRUN = "EDITED_GROUP_PAYRUN";
    String DELETED_GROUP_PAYRUN = "DELETED_GROUP_PAYRUN";
    String SUBMITTED_GROUP_PAYRUN = "SUBMITTED_GROUP_PAYRUN";
    String APPROVED_GROUP_PAYRUN = "APPROVED_GROUP_PAYRUN";
    String REJECTED_GROUP_PAYRUN = "REJECTED_GROUP_PAYRUN";

    String ADDED_CASH_ADVANCE = "ADDED_CASH_ADVANCE";
    String EDITED_CASH_ADVANCE = "EDITED_CASH_ADVANCE";
    String DELETED_CASH_ADVANCE = "DELETED_CASH_ADVANCE";
    String SUBMITTED_CASH_ADVANCE = "SUBMITTED_CASH_ADVANCE";
    String APPROVED_CASH_ADVANCE = "APPROVED_CASH_ADVANCE";
    String REJECTED_CASH_ADVANCE = "REJECTED_CASH_ADVANCE";

    String ADDED_BANK_TRANSFER = "ADDED_BANK_TRANSFER";
    String EDITED_BANK_TRANSFER = "EDITED_BANK_TRANSFER";
    String DELETED_BANK_TRANSFER = "DELETED_BANK_TRANSFER";

    String CALL_LOG_ADD = "CALL_LOG_ADD";
    String CALL_LOG_EDIT = "CALL_LOG_EDIT";
    String CALL_LOG_DELETE = "CALL_LOG_DELETE";

    /////////////////// Attachment Updates /////////////////////////
    String ATTACHMENT = "ATTACHMENT";
    String ATTACHMENT_ADD = "ATTACHMENT_ADD";
    String ATTACHMENT_DELETE = "ATTACHMENT_DELETE";

    String ADDED_ATTACHMENT = "ADDED_ATTACHMENT";
    String DELETED_ATTACHMENT = "DELETED_ATTACHMENT";

    ///////////////// Overtime ///////////////////////////////
    String OVERTIME = "OVERTIME";
    String OVERTIME_ADD = "OVERTIME_ADD";
    String OVERTIME_EDIT = "OVERTIME_EDIT";
    String OVERTIME_DELETE = "OVERTIME_DELETE";
    String OVERTIME_APPROVED = "OVERTIME_APPROVED";
    String OVERTIME_REJECTED = "OVERTIME_REJECTED";
    String OVERTIME_DRAFT = "OVERTIME_DRAFT";

    /////////////////// Backups Employee /////////////////////
    String BACKUPS_EMPLOYEE = "BACKUPS_EMPLOYEE";
    String BACKUPS_EMPLOYEE_ADD = "BACKUPS_EMPLOYEE_ADD";
    String BACKUPS_EMPLOYEE_EDIT = "BACKUPS_EMPLOYEE_EDIT";
    String BACKUPS_EMPLOYEE_DELETE = "BACKUPS_EMPLOYEE_DELETE";
    String BACKUPS_EMPLOYEE_APPROVED = "BACKUPS_EMPLOYEE_APPROVED";
    String BACKUPS_EMPLOYEE_REJECTED = "BACKUPS_EMPLOYEE_REJECTED";
    String BACKUPS_EMPLOYEE_SUBMITTED_TO_MANAGER = "BACKUPS_EMPLOYEE_SUBMITTED_TO_MANAGER";
    String WEBHOOK_ADD = "WEBHOOK_ADD";

    /////////////////// Company Settings /////////////////////
    String COMPANY_SETTINGS = "COMPANY_SETTINGS";
    String COMPANY_SETTINGS_EDIT = "COMPANY_SETTINGS_EDIT";


    EdsMyUpdateType getType(String code, String parentCode);

    void getMyUpdateMessage(EdsMyUpdate myUpdate, MyUpdateItem item, boolean broadMessage);

    void getMyUpdateMessageAllHistory(EdsMyUpdate myUpdate, MyUpdateItem item, boolean broadMessage, boolean showAllHistory);

    String getUpdatesLink(EdsMyUpdate myUpdate);

    void getMyNetworkUpdateMessage(EdsMyUpdate myUpdate, MyUpdateItem item, boolean broadMessage);

    String getSectionURL(EdsMyUpdate myUpdate);
}
