
WebForm=WebForn List Panel
Location=Location List Panel
AssessmentArchive=Assessment Archive List Panel
Message=Message List Panel
CustomEntity=Custom Entity List Panel
Directory=Directory List Panel
VatReports=Task List Panel
PunishmentsPromotionsList=Punishments/Promotions List Panel
Employee=Employee List Panel
BouncedMessage=BouncedMessage List Panel
Tag=Tag List Panel
ProductComments=Product Comments List Panel
WebsiteMenu=WebSite List Panel
TaxRates=Tax rates List Panel
Website=Website List Panel
CLOSED=Closed
Survey=Surveys List Panel
Positions=Positions List Panel
MessageTrack=MessageTrack List Panel
ProjectInvoicesListView=Project Invoices List Panel
ServerLog=Server Log List Panel
QueuedMessages=Queued Messages List Panel
SalaryGrade=Salary Grade List Panel
BugsListSummary=BugsListSummary Lisst Panel
_TASK_PRIORITY_HIGH=High
WareHousesLocations=Ware Houses Locations List Panel
ReportingXMLTemplates=Reporting XML Templates List Panel
PersonalGoal=Goal list panel
Activity=Activity List Panel
NOT_STARTED=Not Started
_TASK_PRIORITY_MEDIUM=Medium
Block=Block List Panel
CustomFields=Custom Fields List Panel
Client=Client List Panel
AppraisalTemplate=Appraisal Template List Panel
StoreFront=StoreFront List Panel
TimeSheetApproval=TimeSheet Approval List Panel
Holiday=Holiday List Panel
PurchaseInvoice=Purchase Invoice
COMPLETED=Completed
CANCELLED=Cancelled
AEO=AEO List Panel
IN_PROGRESS=In Progress
Mail=Mail List Panel
Department=Department List Panel
QuickbookSynchHistory=QuickbookSynchHistory list panel
Estimate=Estimate List Panel
PageBlock=Page Block List Panel
MailListMember=Members Panel
MessageCenter=Message Center
ProducktServiceStockView=Product Service Stock List Panel
Unsubbed=Unsubbed List Panel
CustomForms=Custom Forms List Panel
Event=Events List Panel
WareHouses=Warehouses List Panel
PageLayout=PageLayout List Panel
PaymentDeductionListPanel=Payment/Deduction list panel
Poll=Polls List Panel
Project=Project List Panel
Document=Document List Panel
Lead=Lead List Panel
ReportingDashoboardDownloadLink=Dashoboard Download Link List Panel
EmployeesGoal=Employee goal list panel
ManualTransaction=Manual Transactions List Panel
WAITING_FOR_SOMEONE_ELSE=Waiting for someone else
_TASK_PRIORITY_LOW=Low
ProductCategoryStoreFront=ProductCategory List Panel
BackendCustomisedPDFTemplatesListView=Customised PDF Templates List Panel
BrandsListView=Brands List Panel
Incient=Incient list panel
CompanyGoal=Company Goal List Panel
SaleQuote=Sale Quote List Panel
SaleOrder=Sale Order List Panel
BusinessGoal=Business Goal List Panel
AttendanceTrackingListView=Attendance Tracking List Panel
PurchaseOrder=Purchase Order List Panel
WebSiteLayout=WebSite Layout List Panel
PageLayoutBlock=PageLayout Block List Panel
CrmAccount=CrmAccount List Panel
SaleInvoice=Sale Invoice List Panel
Supplier=Supplier List Panel
BankAccountTransaction=Bank Account Transaction List Panel
Competency=Competency List Panel
CustomPage=CustomPage List Panel
HrmsExpenceReportView=Hrms Expence List Panel
Blog=Blog List Panel
BankAccounts=Bank Accounting List Panel
RecurrenceLog=Recurrence List Panel
TenderCardList=Tender Card List Panel
ReportingDashboard=Dashboard List Panel
WebsiteLayoutBlock=Website Layout Block List Panel
SolrInconsistency=Solr Inconsistency List Panel
Campain=Campain List Panel
BmtListValues=Manage List Panel
EmployeePunishmentsPromotionsList=Employee Punishments/Promotions List Panel
SentMessage=Sent Messages
Solution=Solution List Panel
ReportingDashlet=Dashlet List Panel
Contact=Contact List Panel
ON_HOLD=On Hold
PremiumRecommendationsList=Premium Recommendations List Panel
Task=Task List Panel
Schemas=Schema List Panel
Departments=Issues list Panel
News=News List Panel
BookingItemsView=Booking Items List
PAYETax=PAYET tax list panel
PerformanceNote=Performance Note List Panel
ProjectGoal=Project Goal List Panel
ReportingSystem=Reporting List Panel
BackendAccessLogListPanel=Access Log List Panel
FixedAsset=Fixed Asset Register List Panel
InventoryItemsView=Inventory Items List Panel
ExpenceReportView=Expense List Panel
Contract=Contract List Panel
AccountTransactions=Account Transactions List Panel
ConsignmentList=Consignment List Panel
MessageClickTrack=MessageClickTrack List Panel
EmailAccount=Email Accounts List Panel
Issues=Issues List Panel
SinglePayrun=Single Payrun list panel
DependentListView=Dependent List Panel
PastEmploymentListView=Past Employment List Panel
EmployeeDocumentList=Employee Document List Panel
EmployeePayslipList=Employee Payslip List Panel
CashAdvancePaymentList=Employee History List View
EmployeeBonuses=Employee Bonuses List Panel
ReferenceView=Reference List
CountrySettingsList=Country Settings List
BenefitList=Benefit List Panel
Role=Role List Panel
Workflow=Workflow List Panel
WorkflowActivities=Workflow Activities List Panel
Certificates=Certificate List Panel
BenefitRequestList=Benefit Request List Panel
CompanyDocumentList=Company Document List Panel
PeriodAppraisalsListView=Period Appraisals List Panel
EmployeeLeave=Employee Leave Status
AnnualAllowanceListView=Annual Allowance List Panel
ValidityPeriodListView=Validity Period List Panel
WorkspaceNews=News List Panel
Vacancy=Vacancy List Panel
Candidate=Candidate List Panel
EmployeeHistoryList=Employee History List View
Terms=Terms List Panel
Timeslot=Timeslot List Panel
WorkspaceCategory=News Category List Panel
ProductServiceView=Product Service List Panel
ProjectManagement=Project Management
HRMS=HRMS
CRM=CRM
Payroll=Payroll
Custom=Custom
Folders=Folders
RecurringInvoice=Reccuring Invoice List Panel
ProjectExpenseClaimsListView=Project Expense Claims List Panel
ProjectPurchaseOrderListView=Project Purchase Order List Panel
MeasurementsList=Unit Measurement List Panel
Discount=Discount List Panel
MeetingMInutesView=Meeting Notes List
WorkflowUpdateField=Workflow Update Field List Panel
WorkflowPushNotification=Workflow Push Notification List Panel
WorkflowActions=Workflow Actions List Panel
WorkflowSMSAlert=Workflow SMS Alert List Panel
WorkflowAlert=Workflow Alert List Panel
ImportLogsView=Import Logs List
UsageHistory=Usage History List Panel
Signature=Signature List Panel
SMSTemplates=SMS Templates List Panel
EmailTemplates=Email Templates List Panel
ShortList=Short List Panel
Placement=Placement List Panel
SMSSetting=SMS Setting List Panel
EmailFilter=Email Filter Panel
MessagesView=Messages List
RequestForQuote=Request For Quote List Panel
RequestForPurchase=Request For Purchase List Panel
RecurringBill=Recurring Bill List Panel
ReservationView=Reservation List Panel
StockAdjustments=Stock Adjustments List Panel
BankTransferList=Bank/Cash Transfer List Panel
Prepayment=Prepayment List Panel
CheckList=Check List Panel
BatchInvoicePaymentView=Batch Invoice Payment List Panel
BatchPayBillView=Batch Pay Bill List Panel
CurrencyList=Currency Rates List Panel
PaymentMethodList=Payment Method List Panel
InvoiceTemplatesListView=Invoice Templates List Panel
AccountingView=Accounting  List Panel
EmployeeTemplateList=Payroll Employee Template List Panel
SALE_INVOICE_ITEM=Sale invoice item columns
SALE_QUOTE_ITEM=Sale quote item columns
PURCHASE_INVOICE_ITEM=Purchase invoice item columns
PURCHASE_ORDER_ITEM=Purchase order item columns
OPPORTUNITY_SUB_ITEM=Opportunity item columns
BILL_OF_MATERIALS_ITEM=Bill of material item columns
EXPENSE_CLAIM_ITEM=Expense claim item columns
RFQ_ITEM=Request For Quote item columns
RFP_ITEM=Request For Purchase item columns
CLIENT_ITEM=Customer item columns
SUPPLIER_ITEM=Supplier item columns
ShippingData=Shipping Data List Panel
CREDIT_NOTE_ITEM=Credit Note item columns
CUSTOM_FORM=Custom form
SHIPPING_DATA=Gdn/Grn
MANUAL_JOURNAL_ITEM=Manual Entry item columns
BANK_RECEIPT_ITEM=Bank Receipt item
BANK_PAYMENT_ITEM=Bank Paymet item
CASH_RECEIPT_ITEM=Cash Receipt item
CASH_PAYMENT_ITEM=Cash Payment item