package com.edatasite.workforce.gwt.core.client.enums;

/**
 * Author: Azazello
 * Date: 2/22/2018
 * Time: 6:34 PM
 */
public enum WorkflowExecutionCriteriaEnum {
    _WORKFLOW_EXECUTION_CRITERIA_CREATE,
    _WORKFLOW_EXECUTION_CRITERIA_EDIT,
    _WORKFLOW_EXECUTION_CRITERIA_CREATE_EDIT,
    _WORKFLOW_EXECUTION_CRITERIA_REMOVE,
    _WORKFLOW_EXECUTION_CRITERIA_UPDATE_SPECIFIED_FIELD,
    _WORKFLOW_EXECUTION_CRITERIA_RECURRENCE,
    _WORKFLOW_ACTION_APPROVING,
    _WORKFLOW_ACTION_EDIT
}
