package com.edatasite.workforce.gwt.core.server.servlets.pdf;

/**
 * Created by IntelliJ IDEA.
 * User: Sherzod
 * Date: Mar 23, 2011
 * Time: 4:16:36 PM
 * To change this template use File | Settings | File Templates.
 */
public interface PDFConstants {
    //INVOICE/QUOTE ITEMS
    String ITEM_NO = "NO";
    String ITEM_NUMBER = "ITEM_NUMBER";
    String ITEM_NAME = "NAME";
    String ITEM_PRODUCT_NAME = "PRODUCT_NAME";
    String ITEM_DESCRIPTION = "DESCRIPTION";
    String ITEM_TYPE = "ITEM_TYPE";
    String ITEM_EST_AMOUNT = "ITEM_EST_AMOUNT";
    String ITEM_PRIOR_AMOUNT = "ITEM_PRIOR_AMOUNT";
    String ITEM_QTY_HRS = "QTY_HRS";
    String ITEM_QTY = "ITEM_QTY";
    String QTY = "QTY";
    String ITEM_UNIT_PRICE = "UNIT_PRICE";
    String ITEM_UNIT_PRICE_IN_BASE = "UNIT_PRICE_IN_BASE";
    String ITEM_UNIT_PRICE_DISCOUNTED = "UNIT_PRICE_DISCOUNTED";
    String ITEM_UNIT_PRICE_AVERAGE = "UNIT_PRICE_AVERAGE";
    String ITEM_UNIT_MEASUREMENT = "UNIT_MEASUREMENT";
    String ITEM_UNIT_MEASUREMENT_DESCRIPTION = "UNIT_MEASUREMENT_DESCRIPTION";
    String ITEM_NET_WITHOUT_DISCOUNT = "NET_WITHOUT_DISCOUNT";
    String ITEM_DISCOUNT = "DISCOUNT";
    String ITEM_DISCOUNT_AMOUNT = "DISCOUNT_AMOUNT";
    String ITEM_DISCOUNT_TYPE = "DISCOUNT_TYPE";
    String ITEM_DOUBLE_DISCOUNT = "DOUBLE_DISCOUNT";
    String ITEM_DOUBLE_DISCOUNT_AMOUNT = "DOUBLE_DISCOUNT_AMOUNT";
    String ITEM_DOUBLE_DISCOUNT_TYPE = "DOUBLE_DISCOUNT_TYPE";
    String ITEM_NET_AMOUNT = "NET_AMOUNT";
    String ITEM_NET_AMOUNT_IN_BASE = "NET_AMOUNT_IN_BASE";
    String ITEM_TAX_LABEL = "TAX_LABEL";
    String ITEM_TAX_RATE = "TAX_RATE";
    String ITEM_TAX_AMOUNT = "TAX_AMOUNT";
    String ITEM_TAX_RATE_COUNT = "TAX_RATE_COUNT";
    String ITEM_TAX_AMOUNT_IN_BASE = "TAX_AMOUNT_IN_BASE";
    String ITEM_TOTAL_AMOUNT = "TOTAL_AMOUNT";
    String ITEM_TOTAL_AMOUNT_IN_BASE = "TOTAL_AMOUNT_IN_BASE";
    String ITEM_CATEGORY = "ITEM_CATEGORY";
    String ITEM_MANUFACTURER = "ITEM_MANUFACTURER";
    String ITEM_PART_NUMBER = "ITEM_PART_NUMBER";
    String ITEM_DOUBLE_TAX_LABEL = "DOUBLE_TAX_LABEL";
    String ITEM_DOUBLE_TAX_RATE = "ITEM_DOUBLE_TAX_RATE";
    String ITEM_DOUBLE_TAX_AMOUNT = "ITEM_DOUBLE_TAX_AMOUNT";
    String ITEM_VENDOR = "ITEM_VENDOR";
    String ITEM_PICTURE = "ITEM_PICTURE";
    String ITEM_PROJECT = "ITEM_PROJECT";
    String ITEM_SUB_PROJECT = "ITEM_SUB_PROJECT";
    String ITEM_BRAND_NAME = "ITEM_BRAND_NAME";
    String ITEM_ORIGINAL_PRICE = "ITEM_ORIGINAL_PRICE";
    String ITEM_CONVERTED_QUOTE_CUSTOM_FIELDS = "ITEM_CONVERTED_QUOTE_CUSTOM_FIELDS";
    String ITEM_CUSTOM_AMOUNT = "CUSTOM_AMOUNT";
    String ITEM_COMISSION = "ITEM_COMISSION";

    String ITEM_PRODUCT_SERIAL = "ITEM_PRODUCT_SERIAL";
    String ITEM_PRODUCT_LOT_NUMBER = "ITEM_PRODUCT_LOT_NUMBER";
    String ITEM_PRODUCT_LOT_NUMBER_QTY = "ITEM_PRODUCT_LOT_NUMBER_QTY";
    String ITEM_PRODUCT_EXPIRATION_DATE = "ITEM_PRODUCT_EXPIRATION_DATE";
    String ITEM_COST_PRICE = "ITEM_COST_PRICE";
    String ITEM_BARCODE = "ITEM_BARCODE";
    String ITEM_WAREHOUSE = "ITEM_WAREHOUSE";
    String ITEM_IS_PICKABLE = "ITEM_IS_PICKABLE";
    String PICK_ITEM_REFERENCE = "PICK_ITEM_REFERENCE";
    String PICK_ITEM_NUMBER_PACKS = "PICK_ITEM_NUMBER_PACKS";
    String PICK_ITEM_QTY_PER_PACK = "PICK_ITEM_QTY_PER_PACK";
    String PICK_ITEM_SHIPPED_QTY = "PICK_ITEM_SHIPPED_QTY";
    String PICK_ITEM_LAST_SHIPPED_QTY = "PICK_ITEM_LAST_SHIPPED_QTY";
    String PICK_ITEM_BOOKED_QTY = "PICK_ITEM_BOOKED_QTY";

    String ITEM_QUOTE_QUANTITY_ORDERED = "ITEM_QUOTE_QUANTITY_ORDERED";
    String ITEM_BACK_ORDERED = "ITEM_BACK_ORDERED";
    String ITEM_SKU_NUMBER = "ITEM_SKU_NUMBER";
    String ITEM_PROFIT_PERCENTAGE_IC = "PROFIT_PERCENTAGE_IC";
    String ITEM_PROFIT_IC = "ITEM_PROFIT_IC";
    String ITEM_NET_PROFIT = "ITEM_NET_PROFIT";
    String ITEM_TOTAL_SALES_PRICE = "ITEM_TOTAL_SALES_PRICE";
    String ITEM_TOTAL_COST_PRICE = "ITEM_TOTAL_COST_PRICE";

    String ITEM_ACCOUNT = "ACCOUNT";
    String ITEM_DEPARTMENT = "DEPARTMENT";
    String ITEM_QTY_ON_HAND = "QTY_ON_HAND";
    String ITEM_ORDERED_QTY = "ORDERED_QTY";
    String ITEM_ORDERED_PRODUCT_QTY = "ORDERED_PRODUCT_QTY";
    String ITEM_PREV_INVOICES_PRODUCT_QTY = "PREV_INVOICES_PRODUCT_QTY";
    String ITEM_RECIEVE = "ITEM_RECIEVE";
    String ITEM_AMOUNT = "AMOUNT";
    String ITEM_JUSTIFICATION = "JUSTIFICATION";
    String ITEM_INCIDENT = "INCIDENT";
    String ITEM_BASE_AMOUNT = "BASE_AMOUNT";
    String ITEM_PAYMENT_BASE_AMOUNT = "PAYMENT_BASE_AMOUNT";
    String HIRE_DATE = "HIRE_DATE";
    String RESIGNATION_DATE = "RESIGNATION_DATE";

    //for Payment History
    String ITEM_PAYMENT_DATE = "PAYMENT_DATE";
    String ITEM_PAYMENT_USER = "PAYMENT_USER";
    String ITEM_PAYMENT_AMOUNT = "PAYMENT_AMOUNT";
    String ITEM_PAYMENT_CUSTOMER = "PAYMENT_CUSTOMER";
    String ITEM_PAYMENT_REFERENCE = "PAYMENT_REFERENCE";
    String ITEM_PAYMENT_PAID_TO = "PAYMENT_PAID_TO";
    String ITEM_PAYMENT_DETAIL = "PAYMENT_DETAIL";
    String ITEM_CURRENT_QTY = "CURRENT_QTY";
    String ITEM_USED_QTY = "USED_QTY";
    String ITEM_NEW_QTY = "NEW_QTY";
    String ITEM_COST_PER_ITEM = "COST_PER_ITEM";

    String PAYMENT_RECEIVED_FROM_WITH_DATE = "paymentReceivedFromWithDate";

    //NUMBER AND DATES TABLE
    String RECEIPT = "RECEIPT";
    String RECEIPT_NO = "RECEIPT_NO";
    String INV_NUMBER = "INV_NUMBER";
    String INV_TYPE = "INV_TYPE";
    String QT_NUMBER = "QT_NUMBER";
    String PO_NUMBER = "PO_NUMBER";
    String GRN_NUMBER = "GRN_NUMBER";
    String GDN_NUMBER = "GDN_NUMBER";
    String SHIPPING_LABEL = "SHIPPING_LABEL";
    String REFERENCE = "REFERENCE";
    String PARENT_PROJECT = "PARENT_PROJECT";
    String PROJECT_NAME = "PROJECT_NAME";
    String PROJECT_CODE_ONLY = "PROJECT_CODE_ONLY";
    String PROJECT_DESC = "PROJECT_DESC";
    String PROJECT_BACKUP_MANAGERS = "PROJECT_BACKUP_MANAGERS";
    String PROJECT_RELATIONS_CONTACT = "PROJECT_RELATIONS_CONTACT";
    String PROJECT_RELATIONS_ACCOUNT = "PROJECT_RELATIONS_ACCOUNT";
    String PAYMENT_TERMS = "PAYMENT_TERMS";
    String COMP_VAT_NUMBER = "COMP_VAT_NUMBER";
    String INV_DATE = "INV_DATE";
    String INV_DATE_UNIQUE_FORMAT = "INV_DATE_UNIQUE_FORMAT";
    String INV_DUE_DATE_UNIQUE_FORMAT = "INV_DUE_DATE_UNIQUE_FORMAT";
    String INV_DUE_DATE = "INV_DUE_DATE";
    String QT_DATE = "QT_DATE";
    String PERIOD_DAYS = "PERIOD_DAYS";
    String PERIOD = "PERIOD";
    String RECEIPT_DATE = "RECEIPT_DATE";
    String PAYMENT_DATE = "PAYMENT_DATE";
    String CANCEL_DATE = "CANCEL_DATE";
    String PREVIOUS_BALANCE = "PREVIOUS_BALANCE";
    String PAYMENTS_RECEIVED = "PAYMENTS_RECEIVED";
    String PAYMENT_ADJUSTMENT = "PAYMENT_ADJUSTMENT";
    String PROJECT_NUMBER = "PROJECT_NUMBER";
    String PROJECT_START_DATE = "PROJECT_START_DATE";
    String PROJECT_DUE_DATE = "PROJECT_DUE_DATE";
    String INVOICE_DUE_TERMS = "INVOICE_DUE_TERMS";
    String SALE_QUOTE_APPROVER = "SALE_QUOTE_APPROVER";
    String PURCHASE_ORDER_APPROVER = "PURCHASE_ORDER_APPROVER";
    String PURCHASE_ORDER_APPROVER_POSITION = "PURCHASE_ORDER_APPROVER_POSITION";
    String OPPORTUNITY_NUMBER = "OPPORTUNITY_NUMBER";
    String OPPORTUNITY_NAME = "OPPORTUNITY_NAME";
    String LAST_UPDATED_DATE = "LAST_UPDATED_DATE";
    String LAST_UPDATER = "LAST_UPDATER";
    String PICK_GROSS_WEIGHT = "PICK_GROSS_WEIGHT";
    String PICK_SHIP_DATE = "PICK_SHIP_DATE";
    String PICK_CARRIER_ACCOUNT_ID = "PICK_CARRIER_ACCOUNT_ID";
    String COLUMN_CODE = "COLUMN_CODE";
    String CUSTOMER_BALANCE = "CUSTOMER_BALANCE";
    String PROJECT_MANAGER = "PROJECT_MANAGER";
    String FROM_QUOTE_NUMBER = "FROM_QUOTE_NUMBER";
    String QUOTATION_DATE = "QUOTATION_DATE";
    String COLUMN_NAME = "COLUMN_NAME";
    String COLUMN_VALUE = "COLUMN_VALUE";
    String GROUP = "GROUP";
    String CATEGORY_TYPE = "CATEGORY_TYPE";
    String CONVERTED_QUOTE_APPROVER = "CONVERTED_QUOTE_APPROVER";
    String DEPARTMENT_LEADER = "DEPARTMENT_LEADER";
    String BRIGADA_NAME = "BRIGADA_NAME";
    String BRIGADA_NUMBER = "BRIGADA_NUMBER";

    //UAE VAT RETURN TABLE
    String COLUMN_BOX = "COLUMN_BOX";
    String COLUMN_DESCRIPTION = "COLUMN_DESCRIPTION";
    String COLUMN_TAXABLE_AMOUNT = "COLUMN_TAXABLE_AMOUNT";
    String COLUMN_TAX_AMOUNT = "COLUMN_TAX_AMOUNT";
    String COLUMN_ADJUSTMENTS = "COLUMN_ADJUSTMENTS";
    String COLUMN_FORMULA = "COLUMN_FORMULA";

    //BILL TO ADDRESS TABLE
    String CLIENT = "CLIENT";
    String CRNUMBER = "CRNUMBER";
    String MEMO = "MEMO";
    String COMMENT_SIZE = "COMMENT_SIZE";
    String PUBLISHED_DATE = "PUBLISHED_DATE";
    String VISIBILITY = "VISIBILITY";
    String COMMENT_DATE = "COMMENT_DATE";
    String USER_IMAGE = "USER_IMAGE";
    String ENABLED_MULTI_WAREHOUSE = "ENABLED_MULTI_WAREHOUSE";
    String TASK_NAME = "TASK_NAME";
    String SUNDAYSHORT = "SUNDAYSHORT";
    String MONDAYSHORT = "MONDAYSHORT";
    String TUESDAYSHORT = "TUESDAYSHORT";
    String WEDNESDAYSHORT = "WEDNESDAYSHORT";
    String THURSDAYSHORT = "THURSDAYSHORT";
    String FRIDAYSHORT = "FRIDAYSHORT";
    String SATURDAYSHORT = "SATURDAYSHORT";
    String COMPLETED = "COMPLETED";
    String ESTIMATEDTIME = "ESTIMATEDTIME";

    String CONSIGNOR = "CONSIGNOR";
    String CONSIGNEE = "CONSIGNEE";
    String CUSTOMER = "CUSTOMER";
    String HEADER = "HEADER";
    String PURCHASE_CLIENT_HEADER = "PURCHASE_CLIENT_HEADER";
    String PURCHASE_CLIENT_NAME = "PURCHASE_CLIENT_NAME";
    String PURCHASE_CLIENT_CONTACT_NAME = "PURCHASE_CLIENT_CONTACT_NAME";
    String PURCHASE_CLIENT_EMAIL = "PURCHASE_CLIENT_EMAIL";
    String PURCHASE_CLIENT_PHONE = "PURCHASE_CLIENT_PHONE";
    String NAME = "NAME";
    String ACCOUNT_OWNER = "ACCOUNT_OWNER";
    String CLIENT_PHONE = "CLIENT_PHONE";
    String CLIENT_FAX = "CLIENT_FAX";
    String BILL_TO_HEADER = "BILL_TO_HEADER";
    String SHIP_TO_HEADER = "SHIP_TO_HEADER";
    String CLIENT_CONTACT = "CLIENT_CONTACT";
    String CONTACT_FIRST_NAME = "CONTACT_FIRST_NAME";
    String CONTACT_LAST_NAME = "CONTACT_LAST_NAME";
    String CONTACT_MIDDLE_NAME = "CONTACT_MIDDLE_NAME";
    String CONTACT_PHONE = "CONTACT_PHONE";
    String CONTACT_EMAIL = "CONTACT_EMAIL";
    String CONTACT_JOB_TITLE = "CONTACT_JOB_TITLE";
    String PARENT_ACCOUNT = "PARENT_ACCOUNT";
    String CLIENT_CURRENCY = "CLIENT_CURRENCY";
    String CLIENT_VAT_NUMBER = "CLIENT_VAT_NUMBER";
    String CLIENT_CODE = "CLIENT_CODE";
    String CLIENT_EMAIL = "CLIENT_EMAIL";
    String CLIENT_WEBSITE = "CLIENT_WEBSITE";
    String CLIENT_OWNER = "CLIENT_OWNER";
    String CLIENT_PRE_PAYMENT_BALANCE = "CLIENT_PRE_PAYMENT_BALANCE";
    String TC_REFERENCE_NUMBER = "TC_REFERENCE_NUMBER";
    String TC_CUSTOMER_NAME = "TC_CUSTOMER_NAME";
    String TC_PERIOD = "TC_PERIOD";
    String TC_LOCATION = "TC_LOCATION";
    String OWNER = "OWNER";
    String CATEGORY = "CATEGORY";
    String COST = "COST";
    String PURCHASE_DATE = "PURCHASE_DATE";
    String USE_FUL_LIFE = "USE_FUL_LIFE";
    String RESIDUAL_VALUE = "RESIDUAL_VALUE";
    String LEADER = "LEADER";
    String IMAGE_URL = "IMAGE_URL";
    String BARCODE_IMAGE_URL = "BARCODE_IMAGE_URL";
    String FROM_WAREHOUSE = "FROM_WAREHOUSE";
    String FROM_ACCOUNT = "FROM_ACCOUNT";
    String TO_WAREHOUSE = "TO_WAREHOUSE";
    String TO_ACCOUNT = "TO_ACCOUNT";

    String BILL_ADDRESS_NAME = "BILL_ADDRESS_NAME";
    String BILL_ADDRESS = "BILL_ADDRESS";
    String BILL_ADDRESS2 = "BILL_ADDRESS2";
    String BILL_CITY = "BILL_CITY";
    String BILL_BUILDING_NUMBER = "BILL_BUILDING_NUMBER";
    String BILL_STATE = "BILL_STATE";
    String BILL_ZIPCODE = "BILL_ZIPCODE";
    String BUILDING_NUMBER = "BUILDING_NUMBER";
    String PLOT_IDENTIFICATION = "PLOT_IDENTIFICATION";
    String CITY_SUBDIVISION_NAME = "CITY_SUBDIVISION_NAME";
    String BILL_CITYSTATEZIP = "BILL_CITYSTATEZIP";
    String BILL_COUNTRY = "BILL_COUNTRY";
    String BILL_COUNTRY_EU_MEMBER = "BILL_COUNTRY_EU_MEMBER";

    String COMP_BILL_ADDRESS_NAME = "COMP_BILL_ADDRESS_NAME";
    String COMP_BILL_ADDRESS = "COMP_BILL_ADDRESS";
    String COMP_BILL_ADDRESS2 = "COMP_BILL_ADDRESS2";
    String COMP_BILL_CITY = "COMP_BILL_CITY";
    String COMP_BILL_STATE = "COMP_BILL_STATE";
    String COMP_BILL_ZIPCODE = "COMP_BILL_ZIPCODE";
    String COMP_BILL_CITYSTATEZIP = "COMP_BILL_CITYSTATEZIP";
    String COMP_BILL_COUNTRY = "COMP_BILL_COUNTRY";

    String MAIL_ADDRESS_NAME = "MAIL_ADDRESS_NAME";
    String MAIL_ADDRESS = "MAIL_ADDRESS";
    String MAIL_ADDRESS2 = "MAIL_ADDRESS2";
    String MAIL_CITY = "MAIL_CITY";
    String MAIL_STATE = "MAIL_STATE";
    String MAIL_ZIPCODE = "MAIL_ZIPCODE";
    String MAIL_CITYSTATEZIP = "MAIL_CITYSTATEZIP";
    String MAIL_COUNTRY = "MAIL_COUNTRY";
    String MAIL_COUNTRY_EU_MEMBER = "MAIL_COUNTRY_EU_MEMBER";

    String COMP_MAIL_ADDRESS_NAME = "COMP_MAIL_ADDRESS_NAME";
    String COMP_MAIL_ADDRESS = "COMP_MAIL_ADDRESS";
    String COMP_MAIL_ADDRESS2 = "COMP_MAIL_ADDRESS2";
    String COMP_MAIL_CITY = "COMP_MAIL_CITY";
    String COMP_MAIL_STATE = "COMP_MAIL_STATE";
    String COMP_MAIL_ZIPCODE = "COMP_MAIL_ZIPCODE";
    String COMP_MAIL_CITYSTATEZIP = "COMP_MAIL_CITYSTATEZIP";
    String COMP_MAIL_COUNTRY = "COMP_MAIL_COUNTRY";

    String PRIMARY_CONTACT_ADDESS_NAME = "PRIMARY_CONTACT_ADDESS_NAME";
    String PRIMARY_CONTACT_ADDESS_LINE1 = "PRIMARY_CONTACT_ADDESS_LINE1";
    String PRIMARY_CONTACT_ADDESS_LINE2 = "PRIMARY_CONTACT_ADDESS_LINE2";
    String PRIMARY_CONTACT_COUNTRY = "PRIMARY_CONTACT_COUNTRY";
    String PRIMARY_CONTACT_STATE = "PRIMARY_CONTACT_STATE";
    String PRIMARY_CONTACT_CITY = "PRIMARY_CONTACT_CITY";
    String PRIMARY_CONTACT_ZIPCODE = "PRIMARY_CONTACT_ZIPCODE";

    String PRIMARY_CONTACT_SECONDARY_ADDESS_NAME = "PRIMARY_CONTACT_SECONDARY_ADDESS_NAME";
    String PRIMARY_CONTACT_SECONDARY_ADDESS_LINE1 = "PRIMARY_CONTACT_SECONDARY_ADDESS_LINE1";
    String PRIMARY_CONTACT_SECONDARY_ADDESS_LINE2 = "PRIMARY_CONTACT_SECONDARY_ADDESS_LINE2";
    String PRIMARY_CONTACT_SECONDARY_COUNTRY = "PRIMARY_CONTACT_SECONDARY_COUNTRY";
    String PRIMARY_CONTACT_SECONDARY_STATE = "PRIMARY_CONTACT_SECONDARY_STATE";
    String PRIMARY_CONTACT_SECONDARY_CITY = "PRIMARY_CONTACT_SECONDARY_CITY";
    String PRIMARY_CONTACT_SECONDARY_ZIPCODE = "PRIMARY_CONTACT_SECONDARY_ZIPCODE";


    //Warehouse Data
    String WH_NAME = "WH_NAME";
    String WH_CONTACT_NAME = "WH_CONTACT_NAME";
    String WH_PHONE = "WH_PHONE";
    String WH_FAX = "WH_FAX";
    String WH_EMAIL = "WH_EMAIL";
    String WH_ADDRESS = "WH_ADDRESS";

    String USERNAME = "USERNAME";
    String USER_F_NAME = "USER_F_NAME";
    String USER_L_NAME = "USER_L_NAME";
    String USER_M_NAME = "USER_M_NAME";
    String USER_EMAIL = "USER_EMAIL";
    String USER_PHONE = "USER_PHONE";

    //TOTAL TABLE
    String TYPE = "TYPE";
    String REASON = "REASON";
    String SUBTOTAL = "SUBTOTAL";
    String DISCOUNT_TOTAL = "DISCOUNT_TOTAL";
    String DISCOUNTED_SUBTOTAL = "DISCOUNTED_SUBTOTAL";
    String TAX_ = "TAX_";
    String GROUP_TAX_ = "GROUP_TAX_";
    String TAX_TOTAL = "TAX_TOTAL";
    String SHIPPING_TOTAL = "SHIPPING_TOTAL";
    String SHIPPING_TOTAL_NAME = "SHIPPING_TOTAL_NAME";
    String SHIPPING_VAT = "SHIPPING_VAT";
    String SHIPPING_VAT_NAME = "SHIPPING_VAT_NAME";
    String TOTAL = "TOTAL";
    String TOTAL_YTD = "TOTAL_YTD";
    String PAYMENT_ = "PAYMENT_";
    String PAYMENT_TOTAL = "PAYMENT_TOTAL";
    String LAST_PAYMENT = "LAST_PAYMENT";
    String DUE_AMOUNT = "DUE_AMOUNT";
    String DUE_AMOUNT_WORD = "DUE_AMOUNT_WORD";
    String HAS_BILL_EXP_TOTAL = "HAS_BILL_EXP_TOTAL";
    String BILL_EXP_TOTAL = "BILL_EXP_TOTAL";
    String BILL_EXP_TAX_TOTAL = "BILL_EXP_TAX_TOTAL";
    String SUBTOTAL_WORD = "SUBTOTAL_WORD";
    String TOTAL_WORD = "TOTAL_WORD";
    String TOTAL_IN_BASE_WORD = "TOTAL_IN_BASE_WORD";
    String TOTAL_IN_USD_WORD = "TOTAL_IN_USD_WORD";
    String EXP_TOTAL_WORD = "EXP_TOTAL_WORD";
    String TOTAL_WORD_ALL = "TOTAL_WORD_ALL";
    String TOTAL_ARABIC_WORD_ALL = "TOTAL_ARABIC_WORD_ALL";
    String TOTAL_UZB_WORD_ALL = "TOTAL_UZB_WORD_ALL";
    String TOTAL_UZB_WORD_ALL_LOTIN = "TOTAL_UZB_WORD_ALL_LOTIN";
    String DUE_AMOUNT_ARABIC_WORD = "DUE_AMOUNT_ARABIC_WORD";
    String SUBTOTAL_WORD_ALL = "SUBTOTAL_WORD_ALL";
    String TOTAL_IN_BASE = "TOTAL_IN_BASE";
    String TOTAL_IN_WORDS = "TOTAL_IN_WORDS";
    String TOTAL_NUMERIC = "TOTAL_NUMERIC";
    String SUBTOTAL_IN_BASE = "SUBTOTAL_IN_BASE";
    String TAX_TOTAL_IN_BASE = "TAX_TOTAL_IN_BASE";
    String TOTAL_QUONTITY = "TOTAL_QUONTITY";
    String TOTAL_PROFIT_AMOUNT = "TOTAL_PROFIT_AMOUNT";
    String TOTAL_OVERALL_DISCOUNT = "TOTAL_OVERALL_DISCOUNT";
    String DISCOUNT_TOTAL_WORD_ALL = "DISCOUNT_TOTAL_WORD_ALL";
    String INVOICED_AMOUNT = "INVOICED_AMOUNT";
    String REMAINING_BALANCE = "REMAINING_BALANCE";
    //uzr lekin bu musor customization constantlari
    String BTW_MIN_TOTAL = "BTW_MIN_TOTAL";
    String BTW_MAX_TOTAL = "BTW_MAX_TOTAL";
    String BTW_TOTAL = "BTW_TOTAL";
    String EIND_SUBTOTAL = "EIND_SUBTOTAL";
    String EINDTOTAL = "EINDTOTAL";
    String CREDIT_NOTE_IN_TOTAL = "CREDIT_NOTE_IN_TOTAL";
    String CREDIT_NOTE_INVOICE_SUB_TOTAL = "CREDIT_NOTE_INVOICE_SUB_TOTAL";
    String CREDIT_NOTE_INVOICE_REVISED_SUB_TOTAL = "CREDIT_NOTE_INVOICE_REVISED_SUB_TOTAL";
    String CREDIT_NOTE_BALANCE = "CREDIT_NOTE_BALANCE";
    String INVOICE_QUOTE_UNREC_REVENUE_TOTAL = "INVOICE_QUOTE_UNREC_REVENUE_TOTAL";

    //BANK ACCOUNT
    String BANK_NAME = "BANK_NAME";
    String ACCOUNT_NUMBER = "ACCOUNT_NUMBER";
    String ACCOUNT_CODE = "ACCOUNT_CODE";
    String ACCOUNT_NAME = "ACCOUNT_NAME";
    String BRANCH = "BRANCH";
    String PHONE_NUMBER = "PHONE_NUMBER";
    String SWIFT_BIC = "SWIFT_BIC";
    String SORT_CODE = "SORT_CODE";
    String IBAN_CODE = "IBAN_CODE";
    String ABA_CODE = "ABA_CODE";
    String ACCOUNT_BALANCE = "ACCOUNT_BALANCE";
    String CATEGORY_CODE = "CATEGORY_CODE";
    String PARENT_CODE = "PARENT_CODE";
    String PARENT_NAME = "PARENT_NAME";
    String BANK_ACCOUNT_COUNTRY = "BANK_ACCOUNT_COUNTRY";
    String BANK_ACCOUNT_CITY = "BANK_ACCOUNT_CITY";
    String BANK_ACCOUNT_STATE = "BANK_ACCOUNT_STATE";
    String BANK_ACCOUNT_POSTCODE = "BANK_ACCOUNT_POSTCODE";
    String STREET_ADDRESS = "STREET_ADDRESS";
    String AGENT_ID = "AGENT_ID";
    String INDUSTRY = "INDUSTRY";

    //BANK TRANSFER
    String BANK_ACCOUNT_CODE = "BANK_ACCOUNT_CODE";
    String BANK_ACCOUNT_NUMBER = "BANK_ACCOUNT_NUMBER";
    String CASH_ACCOUNT = "CASH_ACCOUNT";
    String CASH_ACCOUNT_CODE = "CASH_ACCOUNT_CODE";
    String TRANSACTION_NUMBER = "NUMBER";
    String CHECK_NUMBER = "CHECK_NUMBER";
    String NARRATION = "NARRATION";
    String NAME_LIST = "NAME_LIST";
    String DESCRIPTION_LIST = "DESCRIPTION_LIST";

    String ITEM_DEBIT_TOTAL = "DEBIT_TOTAL";
    String ITEM_CREDIT_TOTAL = "CREDIT_TOTAL";

    String ITEM_BASE_DEBIT_TOTAL = "BASE_DEBIT_TOTAL";
    String ITEM_BASE_CREDIT_TOTAL = "BASE_CREDIT_TOTAL";


    //TRIAL BALANCE
    String BEGINNET_DEBIT = "BEGINNET_DEBIT";
    String BEGINNET_CREDIT = "BEGINNET_CREDIT";
    String BEGINNET_BALANCE = "BEGINNET_BALANCE";
    String DEBIT = "DEBIT";
    String CREDIT = "CREDIT";
    String ENDING_DEBIT = "ENDING_DEBIT";
    String ENDING_CREDIT = "ENDING_CREDIT";
    String ENDING_BALANCE = "ENDING_BALANCE";
    String HAS_CHILD = "HAS_CHILD";

    //BANK ACCOUNT 2
    String EXT_BANK_NAME = "EXT_BANK_NAME";
    String EXT_ACCOUNT_NUMBER = "EXT_ACCOUNT_NUMBER";
    String EXT_ACCOUNT_CODE = "EXT_ACCOUNT_CODE";
    String EXT_ACCOUNT_NAME = "EXT_ACCOUNT_NAME";
    String EXT_BRANCH = "EXT_BRANCH";
    String EXT_PHONE_NUMBER = "EXT_PHONE_NUMBER";
    String EXT_SWIFT_BIC = "EXT_SWIFT_BIC";
    String EXT_SORT_CODE = "EXT_SORT_CODE";
    String EXT_IBAN_CODE = "EXT_IBAN_CODE";
    String EXT_ABA_CODE = "EXT_ABA_CODE";

    //EXPENSE REPORT
    String TITLE = "TITLE";
    String REPORTER = "REPORTER";
    String REPORTER_DATE = "REPORTER_DATE";
    String REPORTER_JOB_TITLE = "REPORTER_JOB_TITLE";
    String REPORTER_DEPARTMENT = "REPORTER_DEPARTMENT";

    String REPORTER_NUMBER = "REPORTER_NUMBER";
    String REPORTER_EMAIL = "REPORTER_EMAIL";
    String REPORTER_PHONE = "REPORTER_PHONE";
    String REPORTER_MOBILE_PHONE = "REPORTER_MOBILE_PHONE";
    String APPROVER = "APPROVER";
    String APPROVER_NAME = "APPROVER_NAME";
    String APPROVERS = "APPROVERS";
    String APPROVERS_DATES = "APPROVERS_DATES";
    String EXP_NUMBER = "EXP_NUMBER";
    String EXP_BILL_TO = "EXP_BILL_TO";
    String EXP_LESS_PAYMENT = "EXP_LESS_PAYMENT";
    String EXP_TOTAL = "EXP_TOTAL";
    String EXP_DESCRIPTION = "EXP_DESCRIPTION";
    String EXP_START_DATE = "START_DATE";  //Period Start
    String EXP_END_DATE = "END_DATE";      //Period End
    String RELATED_PROJECT = "PROJECT";
    String STATUS = "STATUS";
    String AMOUNTS = "AMOUNTS";
    String RATES = "RATES";
    String UNIT = "UNIT";
    String AMOUNTS_NUMERIC = "AMOUNTS_NUMERIC";
    String AMOUNTS_BASIC = "AMOUNTS_BASIC";
    String REMARKS = "REMARKS";
    String CURRENCY = "CURRENCY";
    String ITEM_DATE = "DATE";
    String ITEM_BASE_TOTAL = "BASE_TOTAL";
    String PROJECT_BASE_ITEM = "PROJECT_BASE_ITEM";
    String CURRENCY_SYMBOL = "CURRENCY_SYMBOL";
    String FOREIGN_TOTAL = "FOREIGN_TOTAL";
    String FOREIGN_CURRENCY = "FOREIGN_CURRENCY";
    String FOREIGN_TOTAL_WORD = "FOREIGN_TOTAL_WORD";
    String TAX_TYPE_NAME = "TAX_TYPE_NAME";
    String PAID_FROM = "PAID_FROM";

    //EXPENSE REPORT Table
    String ITEM_EXPENSE_CATEGORY = "ITEM_EXPENSE_CATEGORY";
    String ITEM_EXPENSE_DESCRIPTION = "ITEM_EXPENSE_DESCRIPTION";
    String ITEM_EXPENSE_TOTAL_AMOUNT = "ITEM_EXPENSE_TOTAL_AMOUNT";
    String ITEM_EXPENSE_TOTAL_WITH_MARKUP = "ITEM_EXPENSE_TOTAL_WITH_MARKUP";
    String ITEM_EXPENSE_MARKUP_AMOUNT = "ITEM_EXPENSE_MARKUP_AMOUNT";
    String ITEM_EXPENSE_MARKUP_TAX_AMOUNT = "ITEM_EXPENSE_MARKUP_TAX_AMOUNT";
    String ITEM_EXPENSE_MARKUP_TAX_RATE = "ITEM_EXPENSE_MARKUP_TAX_RATE";
    String ITEM_EXPENSE_BEDRAG_AMOUNT = "ITEM_EXPENSE_BEDRAG_AMOUNT";
    String ITEM_EXPENSE_DATE = "ITEM_EXPENSE_DATE";
    String ITEM_EXPENSE_CURRENCY = "ITEM_EXPENSE_CURRENCY";

    //PRODUCT SERIAL TABLE
    String ITEM_SERIAL_NUMBER = "ITEM_SERIAL_NUMBER";
    String ITEM_LOT_NUMBER = "ITEM_LOT_NUMBER";
    String ITEM_REF_NUMBER = "ITEM_REF_NUMBER";
    String ITEM_EXPIRATION_DATE = "ITEM_EXPIRATION_DATE";

    //PO Table Constants
    String REQUISTIONED_BY = "REQUISTIONED_BY";
    String PO_PAYMENT_TYPE = "PAYMENT_TYPE";
    String SHIPPING_TERMS = "SHIPPING_TERMS";
    String SHIPPING_METHOD = "SHIPPING_METHOD";

    //CUSTOM_FIELD  TYPES
    String ACCOUNT = "ACCOUNT";
    String INVOICE = "INVOICE";
    String HRMS = "HRMS";
    String EXPENSE = "EXPENSE";

    //CUSTOM_DATA FIELDS
    String CUSTOM_DATA = "CUSTOM_DATA";
    String CURRENT_DATE = "CURRENT_DATE";
    String SHIPPING_DATE = "SHIPPING_DATE";
    String CURRENT_YEAR = "CURRENT_YEAR";
    String CURRENT_TIME = "CURRENT_TIME";
    String CURRENT_DATE_BY_COMPANY_FORMAT = "CURRENT_DATE_BY_COMPANY_FORMAT";

    //TC Table Constants
    String REF_IND_NUMBER = "REF_IND_NUMBER";
    String RES_CARD_NUMBER = "RES_CARD_NUMBER";
    String COURSE_TITLE = "COURSE_TITLE";
    String COURSE_CODE = "COURSE_CODE";
    String LANGUAGE = "LANGUAGE";
    String COURSE_DATE = "COURSE_DATE";
    String LOCATION = "LOCATION";
    String LOCATION_CODE = "LOCATION_CODE";
    String LOCATION_PHONE = "LOCATION_PHONE";
    String LOCATION_FAX = "LOCATION_FAX";
    String LOCATION_EMAIL = "LOCATION_EMAIL";
    String POSITION = "POSITION";

    //Statement Constants
    String CUSTOMER_ADDRESS = "CUSTOMER_ADDRESS";
    String AGING_SUMMARY = "AGING_SUMMARY";
    String TOTAL_AMOUNT = "TOTAL_AMOUNT";
    String CURRENT_AMOUNT = "CURRENT_AMOUNT";
    String WEEKLY_AMOUNT = "WEEKLY_AMOUNT";
    String MONTHLY_AMOUNT = "MONTHLY_AMOUNT";
    String TWO_MONTHLY_AMOUNT = "TWO_MONTHLY_AMOUNT";
    String THREE_MONTHLY_AMOUNT = "THREE_MONTHLY_AMOUNT";
    String FOUR_MONTHLY_AND_OVER_AMOUNT = "FOUR_MONTHLY_AND_OVER_AMOUNT";

    //Single payrun Constants
    String PAYMENT_PERIOD = "PAYMENT_PERIOD";
    String PAYMENT_METHOD = "PAYMENT_METHOD";
    String PERIOD_START_DATE = "PERIOD_START_DATE";
    String PERIOD_END_DATE = "PERIOD_END_DATE";
    String PERIOD_FROM_TO = "PERIOD_FROM_TO";
    String CREATED_DATE = "CREATED_DATE";
    String PROCESSED_DATE = "PROCESSED_DATE";
    String APPROVED_DATE = "APPROVED_DATE";
    String TOTAL_GROSS_PAY = "TOTAL_GROSS_PAY";
    String GROSS_SALARY = "GROSS_SALARY";
    String TOTAL_ADDITIONAL = "TOTAL_ADDITIONAL";
    String TOTAL_LIVING = "TOTAL_LIVING";
    String TOTAL_OVERTIME = "TOTAL_OVERTIME";
    String DEDUCTIONS = "DEDUCTIONS";
    String DEDUCTIONS_NUMERIC = "DEDUCTIONS_NUMERIC";
    String PETROL_CHARGE = "PETROL_CHARGE";
    String SALIK_CHARGE = "SALIK_CHARGE";
    String SITE = "SITE";

    //Project custom pdf
    String PROJECT_CONTENT_TABLE = "PROJECT_CONTENT_TABLE";
    String ATTACHMENTS = "ATTACHMENTS";
    String NOTE_DETAILS = "NOTE_DETAILS";
    String ISSUE_DETAILS = "ISSUE_DETAILS";
    String PROJECT_TASKS = "PROJECT_TASKS";
    String MEMBERS_INVOLVED = "MEMBERS_INVOLVED";
    String MEMBER = "MEMBER";
    String GRAND_TOTAL = "GRAND_TOTAL";

    //Meeting Minutes pdf
    String MEETING_ID = "MEETING_ID";
    String MEETING_APOLOGIES = "MEETING_APOLOGIES";
    String MEETING_PROJECT = "MEETING_PROJECT";
    String MEETING_SUBJECT = "MEETING_SUBJECT";
    String MEETING_PLACE = "MEETING_PLACE";
    String MEETING_DATE_TIME = "MEETING_DATE_TIME";
    String MEETING_MINUTES_BY = "MEETING_MINUTES_BY";
    String MEETING_PRESENTS= "MEETING_PRESENTS";
    String MEETING_REPRESENTING = "MEETING_REPRESENTING";
    String MEETING_TITLE = "MEETING_TITLE";

    String MEETING_TOPIC_NO= "MEETING_TOPIC_NO";
    String MEETING_MINUTE_NAME = "MEETING_MINUTE_NAME";
    String MEETING_ACTION_WHOM = "MEETING_ACTION_WHOM";
    String MEETING_ACTION_WHEN = "MEETING_ACTION_WHEN";
    String MEETING_REVISED_ACTION_DATE = "MEETING_REVISED_ACTION_DATE";

    String START_MONTH = "START_MONTH";
    String END_MONTH = "END_MONTH";

    String EMPLOYEE_TABLE = "EMPLOYEE_TABLE";
    String TOTAL_TABLE = "TOTAL_TABLE";
    String EMPLOYER_SETTINGS_TABLE = "EMPLOYER_SETTINGS_TABLE";

    String EMPLOYEE_FIRSTNAME = "EMPLOYEE_FIRSTNAME";
    String EMPLOYEE_LASTNAME = "EMPLOYEE_LASTNAME";
    String EMPLOYEE_MIDDLE_NAME = "EMPLOYEE_MIDDLENAME";
    String EMPLOYEE_CODE = "EMPLOYEE_CODE";
    String FROM_DATE = "FROM_DATE";
    String TO_DATE = "TO_DATE";
    String BACK_TO_WORK_DATE = "BACK_TO_WORK_DATE";
    String DEDUCTION_AMOUNT = "DEDUCTION_AMOUNT";
    String EXPENSE_AMOUNT = "EXPENSE_AMOUNT";
    String COMMENTS = "COMMENTS";
    String TOTAL_PAY = "TOTAL_PAY";
    String LEAVE_TYPE = "LEAVE_TYPE";
    String LEAVE_TYPE_CODE = "LEAVE_TYPE_CODE";
    String DESCRIPTION = "DESCRIPTION";
    String DURATION = "DURATION";
    String TAKEN_FROM_ALLOWANCE = "TAKEN_FROM_ALLOWANCE";
    String SUPERVISOR_CODE = "SUPERVISOR_CODE";
    String SUPERVISOR = "SUPERVISOR";
    String TAKEN_DAYS_BEFORE = "TAKEN_DAYS_BEFORE";
    String TOTAL_TAKEN_DAYS_BEFORE_AND_DURATION = "TOTAL_TAKEN_DAYS_BEFORE_AND_DURATION";
    String LEAVE_REQUEST_HOLIDAYS = "LEAVE_REQUEST_HOLIDAYS";
    String ANNUAL_LEAVE_ALLOWANCE_DAYS = "ANNUAL_LEAVE_ALLOWANCE_DAYS";
    String LEFT_DAYS = "LEFT_DAYS";
    String ITEM_ALLOCATE = "ALLOCATE";
    String GRN_CREATOR = "GRN_CREATOR";
    String EMPLOYEE_PHOTO = "EMPLOYEE_PHOTO";
    String EMPLOYEE_PHOTO_ID = "EMPLOYEE_PHOTO_ID";
    String GENDER = "GENDER";
    String EMPLOYMENT_MODE = "EMPLOYMENT_MODE";
    String DATE_OF_BIRTH = "DATE_OF_BIRTH";
    String MARITAL_STATUS = "MARITAL_STATUS";
    String TERMS_OF_CONTRACT = "TERMS_OF_CONTRACT";
    String QUALIFICATION = "QUALIFICATION";
    String PASSPORT_NUMBER = "PASSPORT_NUMBER";
    String PASSPORT_ISSUE = "PASSPORT_ISSUE";
    String PASSPORT_ISSUE_DATE = "PASSPORT_ISSUE_DATE";
    String PASSPORT_EXPIRY_DATE = "PASSPORT_EXPIRY_DATE";
    String VISA_NUMBER = "VISA_NUMBER";
    String VISA_ISSUE_DATE = "VISA_ISSUE_DATE";
    String VISA_EXPIRY_DATE = "VISA_EXPIRY_DATE";
    String INSURANCE_NUMBER = "INSURANCE_NUMBER";
    String INSURANCE_EXPIRY_DATE = "INSURANCE_EXPIRY_DATE";
    String BANK_ADDRESS = "BANK_ADDRESS";

    //Home and Work Address
    String HOME_ADDRESS_TITLE = "HOME_ADDRESS_TITLE";
    String HOME_ADDRESS_NAME = "HOME_ADDRESS_NAME";
    String HOME_ADDRESS_FULL = "HOME_ADDRESS_FULL";
    String HOME_ADDRESS = "HOME_ADDRESS";
    String HOME_ADDRESS2 = "HOME_ADDRESS2";
    String HOME_CITY = "HOME_CITY";
    String HOME_COUNTRY = "HOME_COUNTRY";
    String HOME_STATE = "HOME_STATE";
    String HOME_ZIPCODE = "HOME_ZIPCODE";

    String CORPORATE_ADDRESS_TITLE = "CORPORATE_ADDRESS_TITLE";
    String CORPORATE_ADDRESS_NAME = "CORPORATE_ADDRESS_NAME";
    String CORPORATE_ADDRESS_FULL = "CORPORATE_ADDRESS_FULL";
    String CORPORATE_ADDRESS = "CORPORATE_ADDRESS";
    String CORPORATE_ADDRESS2 = "CORPORATE_ADDRESS2";
    String CORPORATE_CITY = "CORPORATE_CITY";
    String CORPORATE_COUNTRY = "CORPORATE_COUNTRY";
    String CORPORATE_STATE = "CORPORATE_STATE";
    String CORPORATE_ZIPCODE = "CORPORATE_ZIPCODE";

    String HOME_PHONE = "HOME_PHONE";
    String CORPORATE_PHONE = "CORPORATE_PHONE";
    String MOBILE_PHONE = "MOBILE_PHONE";

    String PERSONAL_EMAIL = "PERSONAL_EMAIL";
    String CORPORATE_EMAIL = "CORPORATE_EMAIL";
    String OTHER_EMAIL = "OTHER_EMAIL";
    String PRIMARY_EMAIL = "PRIMARY_EMAIL";

    String CONTACT_INFORMATION = "CONTACT_INFORMATION";
    String EMPLOYMENT_INFORMATION = "EMPLOYMENT_INFORMATION";
    String BANK_ACCOUNT_INFORMATION = "BANK_ACCOUNT_INFORMATION";
    String ADDRESS_INFORMATION = "ADDRESS_INFORMATION";
    String ADDITIONAL_INFORMATION = "ADDITIONAL_INFORMATION";
    String NOTES_INFORMATION = "NOTES_INFORMATION";
    String CUSTOMER_INFORMATION = "CUSTOMER_INFORMATION";
    String CUSTOMER_CONTACTS_INFORMATION = "CUSTOMER_CONTACTS_INFORMATION";
    String ASSIGNEE_NAME = "ASSIGNEE_NAME";
    String CAMPAIGN = "CAMPAIGN";
    String LEAD_SOURCE = "LEAD_SOURCE";
    String LEAD_STATUS = "LEAD_STATUS";
    String VACANCY = "VACANCY";
    String CLIENT_ATTACHMENTS = "CLIENT_ATTACHMENTS";
    String ITEM_BASIC_AMOUNT_PAY = "ITEM_BASIC_AMOUNT_PAY";
    String ITEM_PERCENTAGE = "ITEM_PERCENTAGE";
    String ITEM_BASIC_SALARY = "ITEM_BASIC_SALARY";
    String MONTH_DATE = "MONTH_DATE";
    String MONTH_DATE_UZ = "MONTH_DATE_UZ";
    String DAYS = "DAYS";
    String WORK_HOURS = "WORK_HOURS";
    String APPROVER_POSITION = "APPROVER_POSITION";
    String VERIFY_URL = "VERIFY_URL";
    String SUMMARY = "SUMMARY";
}
