package com.edatasite.workforce.gwt.core.client.ui;

public interface Errors {
    int EMPLOYEE_WITH_THIS_EMAIL_ALREADY_EXISTS = -1;
    int CAN_NOT_CREATE_EMPLOYEE = -2;
    int EMPLOYEE_WITH_THIS_EMAIL_DOES_NOT_EXIST = 0;
    int EMPLOYEE_WITH_THIS_EMAIL_HOST_DOES_NOT_EXIST = -3;
    int EMPLOYEE_STATUS_NO_ACCESS = -4;
    String TASK_LIMIT_EXCEEDED = "TASK_LIMIT_EXCEEDED";
    String PROJECT_LIMIT_EXCEEDED = "PROJECT_LIMIT_EXCEEDE";

    /*Add Location*/
    int THIS_LOCATION_ALREADY_EXISTS = -5;
    /*Add Role*/
    int THIS_ROLE_ALREADY_EXISTS = -5;

    int STUDENT_WITH_THIS_EMAIL_ALREADY_EXISTS = -6;
    int EMPLOYEE_WITH_THIS_CODE_ALREADY_EXISTS = -7;
    int IN_PROCESS = -8;
    int COMPLETED = -9;
    int THIS_NAME_IS_ALREADY_EXIST = -10;

    int ACTIVE_LIMIT_EXCEEDED = -11;
    int NO_ACCESS_LIMIT_EXCEEDED = -12;
    int ESS_LIMIT_EXCEEDED = -13;
    int SUPERVISOR_CIRCULAR_REFERENCE = -14;
    int LEAST_ONE_ADMIN_ROLE = -15;
    int EMPLOYEE_LABOUR_PERIOD_USED = -16;
    int MORE_THAN_UNALLOCATED_AMOUNT = -17;
    int EMPLOYEE_WITH_THIS_PASSPORT_NUMBER_ALREADY_EXISTS = -18;

}
