INSERT INTO "anv".modelfield ( customlabel, defaultvalue, disableupdate, fieldsetstyle, fieldstyle, field_id, form_id, fullwidth, halfsetstyle, helpmessage, hide, hideincustomizeform, iscustomfield, isentityfield, isworkflowattribute, label, mandatory, nolabelfor, nowrapperfor, place, rowstyle, section, sectionstyle, sorder, source, split, systemdisable, systemmandatory, type, usablebyworkflow, widget, columntype, forder, fsection, gridheight, gridwidth, gridx, gridy, customizabletable, customformlocalizationid, referenceid, deleted, widgetforbm) VALUES
    ( null, null, false, null, 'field', 'BANK_FEE_ACCOUNT', 'SUPPLIER_CREDIT_FORM', false, null, null, false, false, false, false, false, null, true, null, null, 0, null, 'PREPAYMENT_FORM_TITLE', '', null, null, false, false, false, null, false, 'LOOKUP', 'COL_1', 4, 'PREPAYMENT_FORM_TITLE', 1, 4, 0, 0, false, null, null, false, null);

INSERT INTO "anv".modelfield ( customlabel, defaultvalue, disableupdate, fieldsetstyle, fieldstyle, field_id, form_id, fullwidth, halfsetstyle, helpmessage, hide, hideincustomizeform, iscustomfield, isentityfield, isworkflowattribute, label, mandatory, nolabelfor, nowrapperfor, place, rowstyle, section, sectionstyle, sorder, source, split, systemdisable, systemmandatory, type, usablebyworkflow, widget, columntype, forder, fsection, gridheight, gridwidth, gridx, gridy, customizabletable, customformlocalizationid, referenceid, deleted, widgetforbm) VALUES
    ( null, null, false, null, 'field', 'FEE_TYPE', 'SUPPLIER_CREDIT_FORM', false, null, null, false, false, false, false, false, null, true, null, null, 0, null, 'PREPAYMENT_FORM_TITLE', '', null, null, false, false, false, null, false, 'DropDown', 'COL_2', 9, 'PREPAYMENT_FORM_TITLE', 1, 4, 0, 0, false, null, null, false, null);


INSERT INTO "anv".modelfield ( customlabel, defaultvalue, disableupdate, fieldsetstyle, fieldstyle, field_id, form_id, fullwidth, halfsetstyle, helpmessage, hide, hideincustomizeform, iscustomfield, isentityfield, isworkflowattribute, label, mandatory, nolabelfor, nowrapperfor, place, rowstyle, section, sectionstyle, sorder, source, split, systemdisable, systemmandatory, type, usablebyworkflow, widget, columntype, forder, fsection, gridheight, gridwidth, gridx, gridy, customizabletable, customformlocalizationid, referenceid, deleted, widgetforbm) VALUES
    ( null, null, false, null, 'field', 'AMOUNT_PERCENTAGE', 'SUPPLIER_CREDIT_FORM', false, null, null, false, false, false, false, false, null, true, null, null, 0, null, 'PREPAYMENT_FORM_TITLE', '', null, null, false, false, false, null, false, 'TextBox', 'COL_3', 10, 'PREPAYMENT_FORM_TITLE', 1, 4, 0, 0, false, null, null, false, null);
