
--Suragan companylar uchun
INSERT INTO "84939".genericsettings (key, value)
VALUES ('ENABLE_REFERENCE_OR_PONUMBER_AGED_RECEIVABLES_PDF', 'YES')
ON CONFLICT (key) DO NOTHING;
INSERT INTO "307944".genericsettings (key, value)
VALUES ('ENABLE_REFERENCE_OR_PONUMBER_AGED_RECEIVABLES_PDF', 'YES')
ON CONFLICT (key) DO NOTHING;
INSERT INTO "307096".genericsettings (key, value)
VALUES ('ENABLE_REFERENCE_OR_PONUMBER_AGED_RECEIVABLES_PDF', 'YES')
ON CONFLICT (key) DO NOTHING;