package com.edatasite.workforce.rest.v2.release10.enums;
/**
 * Created by Abdurakhmonov Farrukh on 14/03/2018.
 */
public enum RequiredEntityFieldName {
    STATUS, PHONE, EMAIL, ADDRESS, //Lead
    ACCOUNT_OWNER, ACCOUNT_NAME, PARENT_ACCOUNT, ACCOUNT_TYPE, ADDRESS_INFORMATION, PRIMARY_CONTACT, //suppliers, customers, accounts
    COMPANY, CONTACT_ADDRESSES, SUPERVISOR, //contacts
    ASSIGNEE, BACKUP_ASSIGNEE, OPPORTUNITY_NAME, AMOUNT, CURRENCY, CLOSE_DATE, COMPANY_NAME, CONTACT_NAME, STAGE, //opportunities
    //task
    PROJECT, TASK_NAME, TASK_DESCRIPTION, WHEN, PRIORITY, BILLABLE, ASSIGNEES, PARENT_WORKSTREAM, DATE_REMINDER, PREDECESSOR, SUCCESSOR

}
