bg_databaseType=FREE
bg_hostName=hrm.uzgtl.com
bg_autoStartup=true
bg_recurringJobsManager_enabled=true
bg_logaudit_enabled=false
bg_error_email_enabled=false
#if path is empty s3 using default AwsCredentials.properties
aws.profile.path=
minio.profile.path=
minio.profile.endpoint=https://storage-hrm.uzgtl.com
email.limit=4


#Triggers
bg_efilingTrigger=false
bg_smsSenderTrigger=true
bg_prefMailerTrigger=true
bg_nonPrefMailerTrigger=true
bg_workflowMailerTrigger=true
bg_dailyReportTrigger=true
#bg_dailySubscriptionTrigger=false
bg_recurrencesUpdateTrigger=true
bg_eventpostprocessorTrigger=false
bg_cooTrigger=false
bg_messageCenterTrigger=false
bg_solrOptimizeAllCoresTrigger=false
bg_weeklySubsciptionReportTrigger=false
bg_subscriptionExpireReportTrigger=true
bg_customFormItemValuesTrigger=false
bg_productCountTrigger=true
bg_heartBeatTrigger=false
bg_fireLateRecurrencesTrigger=false
bg_invoiceUpdateStatusTrigger=true
bg_postedTransactioinTrigger=true
bg_massMailingBouncedEmailHandlerJobTrigger=true
bg_emailSessionClearTrigger=false
bg_createRecurringEventInstancesTrigger=true
bg_createRecurringTaskInstancesTrigger=true
bg_createRecurringHolidayInstancesTrigger=true
bg_expireTemporaryLockTrigger=true
bg_backendStatisticsUpdateJobTrigger=false
bg_tcScheduledTaskTrigger=true
bg_dailyCreateSchemasTrigger=false
bg_dailyGWDSyncTrigger=false
bg_endOfYearTrigger=true
bg_generateTemplateSchemaTrigger=false
bg_createXmlBackupTrigger=false

#Trigger properties
bg_generateTemplateSchema.cron=0 0/30 * * * ?
bg_generateTemplateSchema.limit=10
