update "1".useremailsettings set fingerprintuserid=2 where userid=28419;     --Reynsberg Yuri
update "1".useremailsettings set fingerprintuserid=3 where userid=40661;     --OfficeManager Mayya
update "1".useremailsettings set fingerprintuserid=4 where userid=4428;      --Pankratov Artem
update "1".useremailsettings set fingerprintuserid=5 where userid=562;       --Matsko Stanislav
update "1".useremailsettings set fingerprintuserid=6 where userid=40473;     --Juraev Nodir
update "1".useremailsettings set fingerprintuserid=7 where userid=40675;     --Akbarov Mirzohid
update "1".useremailsettings set fingerprintuserid=8 where userid=40479;     --Kasimov Otabek
update "1".useremailsettings set fingerprintuserid=9 where userid=40592;     --Musaev Farhod
update "1".useremailsettings set fingerprintuserid=10 where userid=40584;    --Satimov Murod
update "1".useremailsettings set fingerprintuserid=11 where userid=6603;      --Khalmuhamedov Aziz
update "1".useremailsettings set fingerprintuserid=12 where userid=40672;     --Togaev Shohin
update "1".useremailsettings set fingerprintuserid=13 where userid=5;         --Karabaev Akmal
update "1".useremailsettings set fingerprintuserid=14 where userid=40650;     --Ismatullaeva Vasila
update "1".useremailsettings set fingerprintuserid=15 where userid=40654;     --Tillakhanov Bekzod
update "1".useremailsettings set fingerprintuserid=16 where userid=40697;     --Abdidjalilov Kahhor
update "1".useremailsettings set fingerprintuserid=17 where userid=5373;      --Rahimov Hayotbek
update "1".useremailsettings set fingerprintuserid=19 where userid=40688;     --Karimova Surayyo
update "1".useremailsettings set fingerprintuserid=20 where userid=6405;      --Lutfullaev Ilhom
update "1".useremailsettings set fingerprintuserid=21 where userid=40433;     --Madrahimov Dilshod
update "1".useremailsettings set fingerprintuserid=22 where userid=3886;      --Mamasharipov Sherali
update "1".useremailsettings set fingerprintuserid=23 where userid=40607;     --Mustafin Raushan
update "1".useremailsettings set fingerprintuserid=24 where userid=40357;     --Navruzov To'lqin
update "1".useremailsettings set fingerprintuserid=25 where userid=1044;      --Nigmatjanov Fathulla
update "1".useremailsettings set fingerprintuserid=26 where userid=13706;     --Otaboev Farhod
update "1".useremailsettings set fingerprintuserid=27 where userid=40676;     --Bahshulloyev Habibullo
update "1".useremailsettings set fingerprintuserid=28 where userid=200;       --Pirnafasov Sherali
update "1".useremailsettings set fingerprintuserid=29 where userid=2;         --Shodiev Lochin
update "1".useremailsettings set fingerprintuserid=30 where userid=3018;      --Tadjiev Dilshod
update "1".useremailsettings set fingerprintuserid=31 where userid=40432;     --Taslimov Fahriddin
update "1".useremailsettings set fingerprintuserid=33 where userid=40438;     --Tsoy Valeriya
update "1".useremailsettings set fingerprintuserid=34 where userid=8576;       --Yamaletdinov Munir
update "1".useremailsettings set fingerprintuserid=35 where userid=7713;       --Aripov Bakhtiyor
update "1".useremailsettings set fingerprintuserid=36 where userid=40356;      --Babaev Hushnud
update "1".useremailsettings set fingerprintuserid=37 where userid=40459;       --Sultonov Zafar
update "1".useremailsettings set fingerprintuserid=38 where userid=6959;         --Usanov Zamir
update "1".useremailsettings set fingerprintuserid=39 where userid=40406;       --Abdullaev Bahrom
update "1".useremailsettings set fingerprintuserid=41 where userid=5116;        --Fayzullaev Sarvar
update "1".useremailsettings set fingerprintuserid=42 where userid=12347;       --Holmirzayev Sanjar
update "1".useremailsettings set fingerprintuserid=43 where userid=4706;        --Imamov Shahobiddin
update "1".useremailsettings set fingerprintuserid=44 where userid=40578;       --Karimov Umidbek
update "1".useremailsettings set fingerprintuserid=45 where userid=40647;       --Bahodirov Mirjalol
update "1".useremailsettings set fingerprintuserid=46 where userid=40682;        --Zverev Aleksey
update "1".useremailsettings set fingerprintuserid=47 where userid=40485;        --Turdiev Bobur
update "1".useremailsettings set fingerprintuserid=48 where userid=40686;       --Yadgarov Ahrorho'ja
update "1".useremailsettings set fingerprintuserid=49 where userid=40671;       --Asamatdinov Damir
update "1".useremailsettings set fingerprintuserid=50 where userid=40687;        --Ergashev Fozilbek
update "1".useremailsettings set fingerprintuserid=51 where userid=40670;        --Turdiev Sherali
update "1".useremailsettings set fingerprintuserid=52 where userid=40698;        --Nazarov Zafar
update "1".useremailsettings set fingerprintuserid=53 where userid=40408;        --Arifjanov Tahir
update "1".useremailsettings set fingerprintuserid=54 where userid=3884;         --Buriev Normurod
update "1".useremailsettings set fingerprintuserid=55 where userid=442;          --Atabaeva Feruza
update "1".useremailsettings set fingerprintuserid=56 where userid=12480;        --Tokhirova Nazokat
update "1".useremailsettings set fingerprintuserid=57 where userid=40529;        --Ashurov Iskandar
update "1".useremailsettings set fingerprintuserid=58 where userid=40693;        --Egamberdiev Sanat
update "1".useremailsettings set fingerprintuserid=59 where userid=40465;        --Israilova Aziza
update "1".useremailsettings set fingerprintuserid=60 where userid=71;           --Hasanov Abror
update "1".useremailsettings set fingerprintuserid=61 where userid=404;          --Mahkamov Doniyor
update "1".useremailsettings set fingerprintuserid=62 where userid=40610;        --Shamsiddinova Dilafruz
update "1".useremailsettings set fingerprintuserid=63 where userid=40439;        --Halilov Bunyod
update "1".useremailsettings set fingerprintuserid=64 where userid=40668;        --Fayzullaev Javohir
update "1".useremailsettings set fingerprintuserid=65 where userid=40667;        --Mirzahmetov Timur
update "1".useremailsettings set fingerprintuserid=66 where userid=40669;        --Sofiev Ibrohim
update "1".useremailsettings set fingerprintuserid=67 where userid=40692;        --Rajabov Xurshid
update "1".useremailsettings set fingerprintuserid=68 where userid=40701;        --Hamidov Faruh
update "1".useremailsettings set fingerprintuserid=69 where userid=40691;        --Shermatov Behzod
update "1".useremailsettings set fingerprintuserid=70 where userid=474;          --Shametov Javlon
update "1".useremailsettings set fingerprintuserid=71 where userid=40681;         --Haydarov  Farhod
update "1".useremailsettings set fingerprintuserid=72 where userid=381;           --Urmanov Timur
update "1".useremailsettings set fingerprintuserid=73 where userid=40606;         --Haqberdiev Aziz
update "1".useremailsettings set fingerprintuserid=74 where userid=40475;         --Pulatov Shuhrat
update "1".useremailsettings set fingerprintuserid=75 where userid=54;            --Mirzarakhimov Bahtiyor
update "1".useremailsettings set fingerprintuserid=76 where userid=65;            --Akramov Anvar
update "1".useremailsettings set fingerprintuserid=77 where userid=38;            --Karabaev Tolib
update "1".useremailsettings set fingerprintuserid=78 where userid=40591;         --Rajabova Shakhlo
update "1".useremailsettings set fingerprintuserid=79 where userid=40646;         --Musaeva Nargiza
update "1".useremailsettings set fingerprintuserid=80 where userid=40649;         --Bekmirzayev Oybek
update "1".useremailsettings set fingerprintuserid=81 where userid=40463;         --Ho'janazarov Hasan
update "1".useremailsettings set fingerprintuserid=89 where userid=40427;         --Hasanov Muhiddin
update "1".useremailsettings set fingerprintuserid=90 where userid=5431;          --Jumaev Ilhom
update "1".useremailsettings set fingerprintuserid=100 where userid=40721;        --Mamatmurodov Azam
update "1".useremailsettings set fingerprintuserid=101 where userid=40716;        --Zinin Pavel
update "1".useremailsettings set fingerprintuserid=104 where userid=40705;        --Umid Ahmedjanov
update "1".useremailsettings set fingerprintuserid=105 where userid=40707;        --Shonazarov Mardon
update "1".useremailsettings set fingerprintuserid=107 where userid=40436;        --Turdiev Rahim
update "1".useremailsettings set fingerprintuserid=108 where userid=40700;        --Djuraev Hurshid
update "1".useremailsettings set fingerprintuserid=111 where userid=40694;        --Asil Ashirov
update "1".useremailsettings set fingerprintuserid=112 where userid=40703;        --Normatov Murodjon
update "1".useremailsettings set fingerprintuserid=113 where userid=40704;        --Musulmanov Navruz
update "1".useremailsettings set fingerprintuserid=114 where userid=40690;        --Israilov Sanjar
update "1".useremailsettings set fingerprintuserid=116 where userid=40709;        --Artem Abdurakhmanov
update "1".useremailsettings set fingerprintuserid=117 where userid=40715;        --Inna Yakovleva
update "1".useremailsettings set fingerprintuserid=118 where userid=40714;        --Javohir Mamadiyarov
update "1".useremailsettings set fingerprintuserid=121 where userid=9144;         --Abdullo Isabaev
update "1".useremailsettings set fingerprintuserid=122 where userid=40712;        --Nugzar Gaguliya
update "1".useremailsettings set fingerprintuserid=123 where userid=40719;        --Hakimov Bobur
update "1".useremailsettings set fingerprintuserid=124 where userid=40720;        --Bahrom Turgunov
update "1".useremailsettings set fingerprintuserid=127 where userid=40722;        --Farrux Atabayev
update "1".useremailsettings set fingerprintuserid=128 where userid=40689;        --Anvar Musamuhamedov
update "1".useremailsettings set fingerprintuserid=129 where userid=40449;        --Bekzod Mirakhmedov
update "1".useremailsettings set fingerprintuserid=130 where userid=40723;        --Bekzod Mirakhmedov
update "1".useremailsettings set fingerprintuserid=131 where userid=40726;        --Nuritdinov Avazbek
update "1".useremailsettings set fingerprintuserid=134 where userid=40729;        --Navruzov Aliakbar
update "1".useremailsettings set fingerprintuserid=136 where userid=40732;        --Azizbek Bekturdiev
update "1".useremailsettings set fingerprintuserid=137 where userid=40730;        --Jahongir Madaminov
update "1".useremailsettings set fingerprintuserid=138 where userid=40731;        --Sardor Asatillaev
update "1".useremailsettings set fingerprintuserid=139 where userid=40734;        --Sherzod Usmonov
update "1".useremailsettings set fingerprintuserid=140 where userid=40769;        --Abror Abdukadirov
update "1".useremailsettings set fingerprintuserid=141 where userid=40736;        --Olimkhon Eshonkhujaev
update "1".useremailsettings set fingerprintuserid=144 where userid=40770;        --Djalilov Aziz
update "1".useremailsettings set fingerprintuserid=157 where userid=40778;        --Ziyoda Mirsaidova
update "1".useremailsettings set fingerprintuserid=158 where userid=40779;        --Otabek Halilov
