
termsAndCondition=Terms and Conditions:
invoiceFooterContactText=If you have any questions concerning this invoice, contact
assetCode=Asset Code
onlyAppraisalTemplates=Appraisal Templates
description=Description
paymentType=Payment Type
accountName=Account Name:
introduction=Introduction:
netProfit=Net Profit
overall=Overall
budget=Budget
swiftBic=SWIFT/BIC:
orderDate=Order Date:
invoiceReceiptDate=Invoice Receipt Date
totalPrice=Total Price
total=Total
bank=Bank
apAgingSummary=Accounts Payable Aging Report
apAgingDetail=A/P Aging Detail
subTotal=Subtotal:
invoiceNo=Invoice No
email=Email
quoteDate=Quote Date:
taxNumber=Tax Number
expenseNumber=Expense No.:
quantityOnHand=Qty on Hand
warehouseName=Warehouse Name
client=Client
unitOfMeasure=U/M
abaCode=Financial code/ABA Code
bankAddress=Bank Address:
transactions=Transactions
date=Date
accountNo=Account No:
vatAmount=Vat Amount
vatNumberLabel=VAT â
grossProfit=Gross Profit
reference=Reference:
invoice=Invoice
totalAmount=Total Amount
billableExpenseTotal=Billable Expense Total
receiptDate=Receipt Date:
branch=Branch
check=Check
bsbcode=BSB code:
stockValuation=Stock Valuation
reportDescription=Report Description:
assetName=Asset Name
sortCode=Sort code:
thankYuoForYourBusiness=THANK YOU FOR YOUR BUSINESS!
netAmount=Net Amount
amount=Amount
shipTo=Ship To:
expenseReport=Expense Report
ibanCode=IBAN Code:
bankCheckList=Bank Check List
receipts=Receipt(s)
memo=Memo
payTo=Pay To
vatTable=Vat Table
poNumber=PO Number:
fax=Fax
reportDate=Report Date:
poCurrency=P. O. Currency
current=Current
balanceDue=Balance Due
To=To
invoicedAmount=Invoiced Amount
andradeFooterMessage=andradeFooterMessage
amountReceived=Amount Received
bankAccount=Bank Account
statementofAccounts=Statement of Accounts
phoneNumber=Phone Number
poweredBy=Powered by
registratedOffice=Registered office
downloadedTime=Downloaded Time:
debitNoteFooterContactText=If you have any questions concerning this debit note,contact
creditNoteFooterContactText=If you have any questions concerning this credit note,contact
quoteNumber=Quote No.:
hours=Hrs
quantity=Quantity
footerSaleOrderText=This is Sales Order and not an invoice. Once agreed on Sales Order Terms Sales invoice will be generated 
If=you have any questions concerning this sales order,contact
footerInvoiceText=If you have any questions concerning this invoice, contact
unitPrice=Unit Price
manualTransaction=Manual Transaction
expenseRecieptTableHeader=Please follow the below links to download the receipts attached to this expense report.If receipts are in image formats then they are displayed below.
period=Period
salesQuote=SALES QUOTE
salesOrder=Sales Order
purchaseInvoice=PURCHASE INVOICE
qtyOrHrs=Qty/Hours
taxAmount=Tax Amount
relatedProject=Related Project
arAgingDetail=A/R Aging Detail
totalTaxId=Company reg
page=Page
of=of
requisitionedBy=Requisitioned by
shipping=Shipping
productName=Product/Service
supplier=Supplier
taxTotal=Tax Total
billTo=Bill To:
orderNumber=Order No
invoiceDiscount=Invoice Discount
paymentDate=Payment Date
paymentTerms=Payment Terms
reciepNumber=Receipt Number
phone=Phone
footerSaleQuoteText=This is Sales Quote and not an invoice. Once agreed on Sales Quote Terms Sales invoice will be generated If you have any questions concerning this sales quote, contact
paymentInstructions=Payment instructions:
discountedSubTotal=Discounted Subtotal
productDiscount=Product Discount
purchaseOrderDate=Purchase Order Date:
invoiceStatus=Invoice Status
shipDate=Ship Date:
dueDate=Due Date:
validUntil=Valid Until:
invoiceDate=Invoice Date:
debitNote=DEBIT NOTE
creditNote=CREDIT NOTE
project=Project
warehouse=Warehouse:
footerPurchaseOrderText=If you have any questions about this Purchase Order, please contact
assetStatus=Asset Status
customer=Customer
quantityUnits=Quantity Units
salesInvoice=Sales Invoices
purchaseOrder=PURCHASE ORDER
lessPayment=Less Payment
number=No.
openingBalance=Opening Balance
accountSummary=Account Summary
Qnumber=Number
discountAmount=Discount Amount:
receiptNo=Receipt No.:
assetCategory=Asset Category
orderInfomation=Order Information:
arAgingSummary=Accounts Receivable Aging Report
discount=Discount
discount2=Discount 2
salesReceipt=SALES RECEIPT
fixedAssetsCount=Fixed Assets Count
shippingTerms=Shipping Terms
address=Address
balance=Balance
payments=Payments
tax=Tax
qty=Qty
receiveMoney=Receive Money
currency=Currency
exchangeRate=Exchange Rate
price=Price
account=Account
taxRate=Tax Rate
from=From
to=To
customerBalance=Customer balance
vat=Vat
spendMoney=Spend Money
checks=Ð¡hecks
opportunityNumber=Opportunity Number
department=Department
accountCode = Account Code
postedDate=Posted Date
goodsReceivedNotes=Goods Received Note
goodsDeliveredNotes=Goods Delivered Note
homePhone=Home Phone
workPhone=Corporate Phone
mobilePhone=Mobile Phone
homeEmail=Personal e-mail
workEmail=Corporate e-mail
otherEmail=Other e-mail
poDate=PO Date:
customerContactsInformation=Customer Contacts Information
projectInformation=Project Information
billableExpense=Billable Expense
parentBrand=Parent Brand
brandsList=Brands List
shippingMethodsList=Shipping Methods List
requestForPurchaseList=Request For Purchase List
rfpNumber=RFP Number
fixedAssetsList=Fixed Assets List
expenseClaimsList=Expense Claims List
terms=Terms
blocked=Blocked
customerCenterList=Customer Center List
suppliers=Suppliers
productOrServicesList=Products/Services List
inventoryItemsList=Inventory Items List
bankAccountsList=Bank Accounts List
supplierPrepaymentList=Supplier Prepayment List
supplierPrepayment=Supplier Prepayment List
customerPrepaymentList=Customer Prepayment
customerPrepayment=Customer Prepayment
manualEntriesList=Manual Entries List
measurements=Measurements List
productCategoriesList=Product Categories List
warehousesList=Warehouses List
paymentMethodList=Payment Method List
leadsList=Leads
crmAccountsList=Crm Accounts List
leaveReasonByStatusList=Leave Reason by Status List
placementList=Placement List
modules=Modules
users=Users
calculatedAsOfResigDate=Calculated as of Resignation date
allowance=Allowance
expensePayment=Expense Payment
expenseDeduction=Expense Deduction
salaryReport=Salary Report
cashAdvanceDate=Cash Advance Date
cashAdvanceReport=Cash Advance Report
leftLeaveDays=Left Leave Days
benefitPayment=Benefit Payment
calculationType=Calculation Type
gratuityTotal=Gratuity Total
employeeResignation=Employee Resignation
contractTermination=Contract Termination
enquiryList=Enquiry List
holidayList=Holiday List
productOrServicesStockList=Products/Services Stock List
regitratedStudentList=Regitrated Student List
scheduledCourseList=Scheduled Course List
singlePayrunList=Single Payruns List
cashAdvanceList=Cash Advance List
additionalPaymentList=Additional Payments
studentList=Student List
timeslotList=Timeslot List
subscriptionHistoryList=Subscription History List
sentMessagesList=Sent Messages List
unsubscribedList=Unsubscribed List
expenseClaim=Expense Claim
news=News
comments=Comments
supplierName=Supplier
supplierCode=Supplier Code
notesInformation=Notes Information
taskInformation=Task Information
gdnNumber=GDN No.
grnNumber=GRN No
rfqDate=RFQ Date
rfq=RFQ
accountingDashboard=Accounting Dashboard
rfp=RFP
parentProject=Parent Project
opportunity=
opportunityInformation=Opportunity Information
stockAdjustmentList=Stock Adjustment List
stockTransferList=Stock Transfer List
itemBatchHistoryList=Item Batch History List
benefitRequestList=Benefit Request List
name=Name
contact=Contact
contactEmail=Contact Email
assignee=Assignee
stage=Stage
closeDate=Close Date
additionalInformation=Additional Information
product=Product/Service
measurementUnit=Measurement Unit
employee=Employees List
endOfServiceReport=End Of Service
tasks=Tasks
cashAdvanceLoan=Cash Advance
candidates=Candidates
placementOnly=Placement
customersCenter=Customer Center
payInvoices=Pay Invoices
competencies=Competencies
stockAdjustment=Stock Adjustment
ACCOUNTING_RECEIVE_PAYMENT_LIST=Receive Payments
companies=Companies
endOfService=End of Service
annualLeaveBalance=Annual Leave Report
salesquotes=Sales Quotes
um=U/M

