insert into region (name, countryid) values
('Cairo', (select id from country  where code= 'EG' and name = 'Egypt')),
('Alexandria', (select id from country  where code= 'EG' and name = 'Egypt')),
('Giza', (select id from country  where code= 'EG' and name = 'Egypt')),
('Qalyubia', (select id from country  where code= 'EG' and name = 'Egypt')),
('Port Said', (select id from country  where code= 'EG' and name = 'Egypt')),
('Suez', (select id from country  where code= 'EG' and name = 'Egypt')),
('Gharbia', (select id from country  where code= 'EG' and name = 'Egypt')),
('Luxor', (select id from country  where code= 'EG' and name = 'Egypt')),
('Dakahlia', (select id from country  where code= 'EG' and name = 'Egypt')),
('Asyut', (select id from country  where code= 'EG' and name = 'Egypt')),
('Ismailia', (select id from country  where code= 'EG' and name = 'Egypt')),
('Faiyum', (select id from country  where code= 'EG' and name = 'Egypt')),
('Sharqia', (select id from country  where code= 'EG' and name = 'Egypt')),
('Damietta', (select id from country  where code= 'EG' and name = 'Egypt')),
('Aswan', (select id from country  where code= 'EG' and name = 'Egypt')),
('Minya', (select id from country  where code= 'EG' and name = 'Egypt')),
('Beheira', (select id from country  where code= 'EG' and name = 'Egypt')),
('Beni Suef', (select id from country  where code= 'EG' and name = 'Egypt')),
('Red Sea', (select id from country  where code= 'EG' and name = 'Egypt')),
('Qena', (select id from country  where code= 'EG' and name = 'Egypt')),
('Sohag', (select id from country  where code= 'EG' and name = 'Egypt')),
('Monufia', (select id from country  where code= 'EG' and name = 'Egypt')),
('North Sinai', (select id from country  where code= 'EG' and name = 'Egypt'));