--COUNTRY TABLE
update country set uzname = 'Albaniya' where name = 'Albania';
update country set uzname = 'Gaiti' where name = 'Haiti';
update country set uzname = 'Gonkong' where name = 'Hong Kong';
update country set uzname = 'Gonduras' where name = 'Honduras';
update country set uzname = 'Vengriya' where name = 'Hungary';
update country set uzname = 'Islandiya' where name = 'Iceland';
update country set uzname = 'Hindiston' where name = 'India';
update country set uzname = 'Indoneziya' where name = 'Indonesia';
update country set uzname = 'Man oroli' where name = 'Isle of Man';
update country set uzname = 'Eron' where name = 'Iran';

update country set uzname = 'Irlandiya' where name = 'Ireland';
update country set uzname = 'Iroq' where name = 'Iraq';
update country set uzname = 'Isroil' where name = 'Israel';
update country set uzname = 'Italiya' where name = 'Italy';
update country set uzname = 'Kot-d Ivuar' where name = 'Ivory Coast';
update country set uzname = 'Yamayka' where name = 'Jamaica';
update country set uzname = 'Yaponiya' where name = 'Japan';
update country set uzname = 'Iordaniya' where name = 'Jordan';
update country set uzname = 'Qozog''iston' where name = 'Kazakhstan';
update country set uzname = 'Keniya' where name = 'Kenya';

update country set uzname = 'Kiribati' where name = 'Kiribati';
update country set uzname = 'Shimoliy Koreya' where name = 'North Korea';
update country set uzname = 'Tonga Qirolligi' where name = 'Kingdom of Tonga';
update country set uzname = 'Quvayt' where name = 'Kuwait';
update country set uzname = 'Qirg''iziston' where name = 'Kyrgyzistan';
update country set uzname = 'Latviya' where name = 'Latvia';
update country set uzname = 'Livan' where name = 'Lebanon';
update country set uzname = 'Lesoto' where name = 'Lesotho';
update country set uzname = 'Liberiya' where name = 'Liberia';

update country set uzname = 'Lixtenshteyn' where name = 'Liechtenstein';
update country set uzname = 'Litva' where name = 'Lithuania';
update country set uzname = 'Liviya' where name = 'Libya';
update country set uzname = 'Lyuksemburg' where name = 'Luxembourg';
update country set uzname = 'Malta' where name = 'Malta';
update country set uzname = 'Macao' where name = 'Macao';
update country set uzname = 'Madagaskar' where name = 'Madagascar';
update country set uzname = 'Monako' where name = 'Monaco';
update country set uzname = 'Mo''g''uliston' where name = 'Mongolia';
update country set uzname = 'Moldova' where name = 'Moldova';

update country set uzname = 'Marokash' where name = 'Morocco';
update country set uzname = 'Mozambik' where name = 'Mozambique';
update country set uzname = 'Myanma (Birma)' where name = 'Myanmar';
update country set uzname = 'Namibiya' where name = 'Namibia';
update country set uzname = 'Gollandiya Antil orollari' where name = 'Netherlands Antilles';
update country set uzname = 'Nauru' where name = 'Nauru';
update country set uzname = 'Yangi Kaledoniya' where name = 'New Caledonia';
update country set uzname = 'Nepal' where name = 'Nepal';
update country set uzname = 'Niderlandiya' where name = 'Netherlands';

update country set uzname = 'Nikaragua' where name = 'Nicaragua';
update country set uzname = 'Nigeriya' where name = 'Nigeria';
update country set uzname = 'Norvegiya' where name = 'Norway';
update country set uzname = 'Yangi Zelandiya' where name = 'New Zealand';
update country set uzname = 'Ummon' where name = 'Oman';
update country set uzname = 'Pokiston' where name = 'Pakistan';
update country set uzname = 'Fransuz Polineziyasi' where name = 'Palestinian Territory';
update country set uzname = 'Panama' where name = 'Panama';
update country set uzname = 'Paragvay' where name = 'Paraguay';
update country set uzname = 'Peru' where name = 'Peru';

update country set uzname = 'Filippin' where name = 'Philippines';
update country set uzname = 'Papua-Yangi Gvineya' where name = 'Papua New Guinea';
update country set uzname = 'Polsha' where name = 'Poland';
update country set uzname = 'Portugaliya' where name = 'Portugal';
update country set uzname = 'Qatar' where name = 'Qatar';
update country set uzname = 'Reyunion' where name = 'Reunion';
update country set uzname = 'Ruminiya' where name = 'Romania';
update country set uzname = 'Rossiya' where name = 'Russia';
update country set uzname = 'Ruanda' where name = 'Rwanda';
update country set uzname = 'Janubiy Afrika' where name = 'South Africa';
update country set uzname = 'San-Tome va Prinsipi' where name = 'Sao Tome - Principe';

update country set uzname = 'Saudiya Arabistoni' where name = 'Saudi Arabia';
update country set uzname = 'Senegal' where name = 'Senegal';
update country set uzname = 'Serbiya' where name = 'Serbia';
update country set uzname = 'Seyshel orollari' where name = 'Seychelles';
update country set uzname = 'Syerra-Leone' where name = 'Sierra Leone';
update country set uzname = 'Singapur' where name = 'Singapore';
update country set uzname = 'Sent-Kits' where name = 'St Kitts';
update country set uzname = 'Slovakiya' where name = 'Slovakia';
update country set uzname = 'Sent-Lusiya' where name = 'St Lucia';
update country set uzname = 'Sloveniya' where name = 'Slovenia';

update country set uzname = 'Sent-Martin' where name = 'St Martin';
update country set uzname = 'San-Marino' where name = 'San Marino';
update country set uzname = 'Sulaymon orollari' where name = 'Solomon Islands';
update country set uzname = 'Somali' where name = 'Somalia';
update country set uzname = 'Ispaniya' where name = 'Spain';
update country set uzname = 'Shri-Lanka' where name = 'Sri Lanka';
update country set uzname = 'Sudan' where name = 'Sudan';
update country set uzname = 'Surinam' where name = 'Suriname';
update country set uzname = 'Sent-Vinsent va Grenadin' where name = 'St Vincent and The Grenadines';
update country set uzname = 'Svazilend' where name = 'Swaziland';
update country set uzname = 'Shvetsiya' where name = 'Sweden';

update country set uzname = 'Shvetsariya' where name = 'Switzerland';
update country set uzname = 'Suriya' where name = 'Syria';
update country set uzname = 'Taiti' where name = 'Tahiti';
update country set uzname = 'Tayvan' where name = 'Taiwan';
update country set uzname = 'Tojikiston' where name = 'Tajikistan';
update country set uzname = 'Birlashgan Qirollik' where name = 'United Kingdom';
update country set uzname = 'Tanzaniya' where name = 'Tanzania';
update country set uzname = 'Turks va Kaykos orollari' where name = 'Turks and Caicos Islands';
update country set uzname = 'Tayland' where name = 'Thailand';
update country set uzname = 'Togo' where name = 'Togo';
update country set uzname = 'Tongo' where name = 'Tongo';

update country set uzname = 'Trinadad - Tobago' where name = 'Trinidad - Tobago';
update country set uzname = 'Turkmaniston' where name = 'Turkmenistan';
update country set uzname = 'Tunis' where name = 'Tunisia';
update country set uzname = 'Turkiya' where name = 'Turkey';
update country set uzname = 'Tuvalu' where name = 'Tuvalu';
update country set uzname = 'Birlashgan Arab Amirliklari' where name = 'United Arab Emirates';
update country set uzname = 'Uganda' where name = 'Uganda';
update country set uzname = 'Ukraina' where name = 'Ukraine';
update country set uzname = 'Urugvay' where name = 'Uruguay';
update country set uzname = 'O''zbekiston' where name = 'Uzbekistan';

update country set uzname = 'Vanuatu' where name = 'Vanuatu';
update country set uzname = 'Vatikan shahri' where name = 'Vatican City';
update country set uzname = 'Venesuela' where name = 'Venezuela';
update country set uzname = 'Vyetnam' where name = 'Vietnam';
update country set uzname = 'G''arbiy Samoa' where name = 'Western Samoa';
update country set uzname = 'Yaman' where name = 'Yemen';
update country set uzname = 'Estoniya' where name = 'Estonia';
update country set uzname = 'Efiopiya' where name = 'Ethiopia';
update country set uzname = 'Farer orollari' where name = 'Faroe Islands';
update country set uzname = 'Fransuz Gvianasi' where name = 'French Guiana';

update country set uzname = 'Fiji orollari' where name = 'Fiji Islands';
update country set uzname = 'Finlandiya' where name = 'Finland';
update country set uzname = 'Fransiya  ' where name = 'France';
update country set uzname = 'Fransiya G''arbiy Hind orollari' where name = 'French West Indies';
update country set uzname = 'Gabon' where name = 'Gabon';
update country set uzname = 'Gambiya' where name = 'Gambia';
update country set uzname = 'Gvineya-Bisau' where name = 'Guinea-Bissau';
update country set uzname = 'Gurjiston' where name = 'Georgia';
update country set uzname = 'Germaniya' where name = 'Germany';
update country set uzname = 'Gana' where name = 'Ghana';

update country set uzname = 'Gibraltar' where name = 'Gibraltar';
update country set uzname = 'Makedoniya' where name = 'Macedonia';
update country set uzname = 'Zambiya' where name = 'Zambia';
update country set uzname = 'Zimbabve' where name = 'Zimbabwe';
update country set uzname = 'Kanada' where name = 'Canada';
update country set uzname = 'Meksika' where name = 'Mexico';
update country set uzname = 'Belgiya' where name = 'Belgium';
update country set uzname = 'Amerika Samoasi' where name = 'American Samoa';
update country set uzname = 'Britaniya Hind okeani hududi' where name = 'British Indian Ocean Territory';
update country set uzname = 'Kristmas oroli' where name = 'Christmas Island';

update country set uzname = 'Kokos (Kiling) orollari' where name = 'Cocos (Keeling) Islands';
update country set uzname = 'Kuk orollari' where name = 'Cook Islands';
update country set uzname = 'Kosta-Rika' where name = 'Costa Rica';
update country set uzname = 'Sharqiy Timor' where name = 'East Timor';
update country set uzname = 'Ekvatorial Gvineya' where name = 'Equatorial Guinea';
update country set uzname = 'Folklend orollari (Malvinalar)' where name = 'Falkland Islands (Malvinas)';
update country set uzname = 'Fransuz Polineziyasi' where name = 'French Polynesia';
update country set uzname = 'Fransiya Janubiy hududlari' where name = 'French Southern Territories';
update country set uzname = 'Guam' where name = 'Guam';

update country set uzname = 'Gerd va MakDonald orollari' where name = 'Heard and McDonald Islands';
update country set uzname = 'Marshall orollari' where name = 'Marshall Islands';
update country set uzname = 'Mayotte' where name = 'Mayotte';
update country set uzname = 'Mikroneziya' where name = 'Micronesia';
update country set uzname = 'Monserat' where name = 'Montserrat';
update country set uzname = 'Niger' where name = 'Niger';
update country set uzname = 'Niue' where name = 'Niue';
update country set uzname = 'Norfolk oroli' where name = 'Norfolk Island';
update country set uzname = 'Shimoliy Marian orollari' where name = 'Northern Mariana Islands';
update country set uzname = 'Palau' where name = 'Palau';

update country set uzname = 'Pitkairn' where name = 'Pitcairn';
update country set uzname = 'Puerto-Riko' where name = 'Puerto Rico';
update country set uzname = 'Sent-Kits va Nevis' where name = 'Saint Kitts and Nevis';
update country set uzname = 'Sent-Lusiya' where name = 'Saint Lucia';
update country set uzname = 'Sent-Vinsent va Grenadin' where name = 'Saint Vincent and the Grenadines';
update country set uzname = 'Samoa' where name = 'Samoa';
update country set uzname = 'Janubiy Gurjiston va Janubiy Sandvich orollari' where name = 'South Georgia and The South Sandwich Islands';
update country set uzname = 'Janubiy Koreya' where name = 'South Korea';
update country set uzname = 'Sent-Yelena' where name = 'St. Helena';
update country set uzname = 'Sent-Per va Mikelon' where name = 'St. Pierre and Miquelon';

update country set uzname = 'Svalbard va Yan-Mayen orollari' where name = 'Svalbard and Jan Mayen Islands';
update country set uzname = 'Tokelau' where name = 'Tokelau';
update country set uzname = 'Tongo' where name = 'Tonga';
update country set uzname = 'AQSh''ning kichik tashqi orollari' where name = 'United States Minor Outlying Islands';
update country set uzname = 'Virjiniya orollari (Britaniya)' where name = 'Virgin Islands (British)';
update country set uzname = 'Virjiniya orollari (AQSh)' where name = 'Virgin Islands (U.S.)';
update country set uzname = 'Uollis va Futuna orollari' where name = 'Wallis and Futuna Islands';
update country set uzname = 'G''arbiy Sahro' where name = 'Western Sahara';
update country set uzname = 'G''arbiy Sahro' where name = 'Montenegro';
update country set uzname = 'Lao Xalq Demokratik Respublikasi' where name = 'Lao People''s Democratic Republic';
update country set uzname = 'Jazoir' where name = 'Algeria';
update country set uzname = 'Armaniston' where name = 'Armenia';

update country set uzname = 'Ozarbayjon' where name = 'Azerbaijan';
update country set uzname = 'Afg''oniston' where name = 'Afghanistan';
update country set uzname = 'Bahrayn' where name = 'Bahrain';
update country set uzname = 'Bangladesh' where name = 'Bangladesh';
update country set uzname = 'Barbados' where name = 'Barbados';
update country set uzname = 'Andorra' where name = 'Andorra';
update country set uzname = 'Angola' where name = 'Angola';
update country set uzname = 'Antigua va Barbuda' where name = 'Antigua and Barbuda';
update country set uzname = 'Angiliya' where name = 'Anguilla';
update country set uzname = 'Argentina' where name = 'Argentina';
update country set uzname = 'Aruba' where name = 'Aruba';

update country set uzname = 'Buvet oroli' where name = 'Bouvet Island';
update country set uzname = 'Avstriya' where name = 'Austria';
update country set uzname = 'Avstraliya' where name = 'Australia';
update country set uzname = 'Bagama' where name = 'Bahamas';
update country set uzname = 'Belarussiya' where name = 'Belarus';
update country set uzname = 'Beliz' where name = 'Belize';
update country set uzname = 'Benin' where name = 'Benin';
update country set uzname = 'Bermuda' where name = 'Bermuda';
update country set uzname = 'Amerika Qo''shma Shtatlari' where name = 'United States Of America';
update country set uzname = 'Bosniya va Gersegovina' where name = 'Bosnia-Herzegovina';

update country set uzname = 'Butan' where name = 'Bhutan';
update country set uzname = 'Kamboja' where name = 'Cambodia';
update country set uzname = 'Kot-d Ivuar' where name = 'Cote d''Ivoire';
update country set uzname = 'Kongo Demokratik Respublikasi' where name = 'Congo, Democratic Republic';
update country set uzname = 'Bofutatsvana' where name = 'Bophuthatswana';
update country set uzname = 'Botsvana' where name = 'Botswana';
update country set uzname = 'Braziliya' where name = 'Brazil';
update country set uzname = 'Burkina Faso' where name = 'Burkina Faso';
update country set uzname = 'Bolgariya' where name = 'Bulgaria';
update country set uzname = 'Birma' where name = 'Burma';

update country set uzname = 'Burundi' where name = 'Burundi';
update country set uzname = 'Britaniya Virjin orollari' where name = 'British  Virgin Islands';
update country set uzname = 'Kabo-Verde' where name = 'Cape Verde';
update country set uzname = 'Kamerun' where name = 'Cameroon';
update country set uzname = 'Markaziy Afrika Respublikasi' where name = 'Central African Republic';
update country set uzname = 'Chad' where name = 'Chad';
update country set uzname = 'Xitoy' where name = 'China';
update country set uzname = 'Chili' where name = 'Chile';
update country set uzname = 'Kayman orollari' where name = 'Cayman Islands';
update country set uzname = 'Kolumbiya' where name = 'Colombia';

update country set uzname = 'Komoros' where name = 'Comoros';
update country set uzname = 'Xorvatiya' where name = 'Croatia';
update country set uzname = 'Normand orollar' where name = 'Channel Islands';
update country set uzname = 'Kuba' where name = 'Cuba';
update country set uzname = 'Kurakao' where name = 'Curacao';
update country set uzname = 'Kipr' where name = 'Cyprus';
update country set uzname = 'Chexiya Respublikasi' where name = 'Czech Republic';
update country set uzname = 'Daniya' where name = 'Denmark';
update country set uzname = 'Grenada' where name = 'Grenada';
update country set uzname = 'Gretsiya' where name = 'Greece';

update country set uzname = 'Grenlandiya' where name = 'Greenland';
update country set uzname = 'Gvatemala' where name = 'Guatemala';
update country set uzname = 'Gvadelupa' where name = 'Guadeloupe';
update country set uzname = 'Gvineya' where name = 'Guinea';
update country set uzname = 'Guyana' where name = 'Guyana';
update country set uzname = 'Mali' where name = 'Mali';
update country set uzname = 'Malayziya' where name = 'Malaysia';
update country set uzname = 'Mavritaniya' where name = 'Mauritania';
update country set uzname = 'Martinika' where name = 'Martinique';
update country set uzname = 'Mavrikiy' where name = 'Mauritius';

update country set uzname = 'Maldiv orollari' where name = 'Maldives';
update country set uzname = 'Malavi' where name = 'Malawi';
update country set uzname = 'Boliviya' where name = 'Bolivia';
update country set uzname = 'Bruney Darussalam' where name = 'Brunei Darussalam';
update country set uzname = 'Jibuti' where name = 'Djibouti';
update country set uzname = 'Dominika' where name = 'Dominica';
update country set uzname = 'Dominika Respublikasi' where name = 'Dominican Republic';
update country set uzname = 'Ekvador' where name = 'Ecuador';
update country set uzname = 'Misr' where name = 'Egypt';
update country set uzname = 'Salvador' where name = 'El Salvador';
update country set uzname = 'Eritreya' where name = 'Eritrea';

insert into region (name, countryid, runame, uzname) values ('Tashkent', (select id from country where code='UZ' and name='Uzbekistan'), 'Ташкент', 'Toshkent shahri');