DELETE FROM "0".customformsection WHERE form_id='PM_EMPLOYEE_FORM' AND section='ASTERISK_SETTINGS';
DELETE FROM "anv".customformsection WHERE form_id='PM_EMPLOYEE_FORM' AND section='ASTERISK_SETTINGS';

DELETE FROM "0".modelfield WHERE field_id='ASTERISK_HOST' AND form_id='PM_EMPLOYEE_FORM';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_HOST' AND form_id='PM_EMPLOYEE_FORM';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_PORT' AND form_id='PM_EMPLOYEE_FORM';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_PORT' AND form_id='PM_EMPLOYEE_FORM';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_USERNAME' AND form_id='PM_EMPLOYEE_FORM';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_USERNAME' AND form_id='PM_EMPLOYEE_FORM';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_PASSWORD' AND form_id='PM_EMPLOYEE_FORM';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_PASSWORD' AND form_id='PM_EMPLOYEE_FORM';

DELETE FROM "0".customformsection WHERE form_id='HRMS_EMPLOYEE_FORM' AND section='ASTERISK_SETTINGS';
DELETE FROM "anv".customformsection WHERE form_id='HRMS_EMPLOYEE_FORM' AND section='ASTERISK_SETTINGS';

DELETE FROM "0".modelfield WHERE field_id='ASTERISK_HOST' AND form_id='HRMS_EMPLOYEE_FORM';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_HOST' AND form_id='HRMS_EMPLOYEE_FORM';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_PORT' AND form_id='HRMS_EMPLOYEE_FORM';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_PORT' AND form_id='HRMS_EMPLOYEE_FORM';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_USERNAME' AND form_id='HRMS_EMPLOYEE_FORM';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_USERNAME' AND form_id='HRMS_EMPLOYEE_FORM';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_PASSWORD' AND form_id='HRMS_EMPLOYEE_FORM';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_PASSWORD' AND form_id='HRMS_EMPLOYEE_FORM';

DELETE FROM "0".customformsection WHERE form_id='PM_EMPLOYEE_EDIT_OWN_PROFILE' AND section='ASTERISK_SETTINGS';
DELETE FROM "anv".customformsection WHERE form_id='PM_EMPLOYEE_EDIT_OWN_PROFILE' AND section='ASTERISK_SETTINGS';

DELETE FROM "0".modelfield WHERE field_id='ASTERISK_HOST' AND form_id='PM_EMPLOYEE_EDIT_OWN_PROFILE';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_HOST' AND form_id='PM_EMPLOYEE_EDIT_OWN_PROFILE';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_PORT' AND form_id='PM_EMPLOYEE_EDIT_OWN_PROFILE';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_PORT' AND form_id='PM_EMPLOYEE_EDIT_OWN_PROFILE';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_USERNAME' AND form_id='PM_EMPLOYEE_EDIT_OWN_PROFILE';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_USERNAME' AND form_id='PM_EMPLOYEE_EDIT_OWN_PROFILE';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_PASSWORD' AND form_id='PM_EMPLOYEE_EDIT_OWN_PROFILE';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_PASSWORD' AND form_id='PM_EMPLOYEE_EDIT_OWN_PROFILE';

DELETE FROM "0".customformsection WHERE form_id='HRMS_EDIT_OWN_PROFILE' AND section='ASTERISK_SETTINGS';
DELETE FROM "anv".customformsection WHERE form_id='HRMS_EDIT_OWN_PROFILE' AND section='ASTERISK_SETTINGS';

DELETE FROM "0".modelfield WHERE field_id='ASTERISK_HOST' AND form_id='HRMS_EDIT_OWN_PROFILE';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_HOST' AND form_id='HRMS_EDIT_OWN_PROFILE';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_PORT' AND form_id='HRMS_EDIT_OWN_PROFILE';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_PORT' AND form_id='HRMS_EDIT_OWN_PROFILE';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_USERNAME' AND form_id='HRMS_EDIT_OWN_PROFILE';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_USERNAME' AND form_id='HRMS_EDIT_OWN_PROFILE';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_PASSWORD' AND form_id='HRMS_EDIT_OWN_PROFILE';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_PASSWORD' AND form_id='HRMS_EDIT_OWN_PROFILE';

DELETE FROM "0".customformsection WHERE form_id='PM_EMPLOYEE_SUMMARY' AND section='ASTERISK_SETTINGS';
DELETE FROM "anv".customformsection WHERE form_id='PM_EMPLOYEE_SUMMARY' AND section='ASTERISK_SETTINGS';

DELETE FROM "0".modelfield WHERE field_id='ASTERISK_HOST' AND form_id='PM_EMPLOYEE_SUMMARY';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_HOST' AND form_id='PM_EMPLOYEE_SUMMARY';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_PORT' AND form_id='PM_EMPLOYEE_SUMMARY';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_PORT' AND form_id='PM_EMPLOYEE_SUMMARY';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_USERNAME' AND form_id='PM_EMPLOYEE_SUMMARY';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_USERNAME' AND form_id='PM_EMPLOYEE_SUMMARY';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_PASSWORD' AND form_id='PM_EMPLOYEE_SUMMARY';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_PASSWORD' AND form_id='PM_EMPLOYEE_SUMMARY';

DELETE FROM "0".customformsection WHERE form_id='HRMS_EDIT_PROFILE' AND section='ASTERISK_SETTINGS';
DELETE FROM "anv".customformsection WHERE form_id='HRMS_EDIT_PROFILE' AND section='ASTERISK_SETTINGS';

DELETE FROM "0".modelfield WHERE field_id='ASTERISK_HOST' AND form_id='HRMS_EDIT_PROFILE';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_HOST' AND form_id='HRMS_EDIT_PROFILE';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_PORT' AND form_id='HRMS_EDIT_PROFILE';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_PORT' AND form_id='HRMS_EDIT_PROFILE';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_USERNAME' AND form_id='HRMS_EDIT_PROFILE';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_USERNAME' AND form_id='HRMS_EDIT_PROFILE';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_PASSWORD' AND form_id='HRMS_EDIT_PROFILE';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_PASSWORD' AND form_id='HRMS_EDIT_PROFILE';

DELETE FROM "0".customformsection WHERE form_id='SETTINGS_EMPLOYEE_FORM' AND section='ASTERISK_SETTINGS';
DELETE FROM "anv".customformsection WHERE form_id='SETTINGS_EMPLOYEE_FORM' AND section='ASTERISK_SETTINGS';

DELETE FROM "0".modelfield WHERE field_id='ASTERISK_HOST' AND form_id='SETTINGS_EMPLOYEE_FORM';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_HOST' AND form_id='SETTINGS_EMPLOYEE_FORM';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_PORT' AND form_id='SETTINGS_EMPLOYEE_FORM';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_PORT' AND form_id='SETTINGS_EMPLOYEE_FORM';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_USERNAME' AND form_id='SETTINGS_EMPLOYEE_FORM';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_USERNAME' AND form_id='SETTINGS_EMPLOYEE_FORM';
DELETE FROM "0".modelfield WHERE field_id='ASTERISK_PASSWORD' AND form_id='SETTINGS_EMPLOYEE_FORM';
DELETE FROM "anv".modelfield WHERE field_id='ASTERISK_PASSWORD' AND form_id='SETTINGS_EMPLOYEE_FORM';

