delete  from "anv".form_property where form_id ='CLIENT_FORM';
insert into "anv".form_property (form_id, settingsjsondata)
values ('CLIENT_FORM',
        '[
  {
    "code": "CRM_NOTE",
    "title": "Notes",
    "aliasName": "NOTE",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CRM_ACCOUNT_OWNER",
    "title": "Owners",
    "aliasName": "OWNER",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CRM_ACCOUNT_NAME",
    "title": "Name",
    "aliasName": "NAME",
    "changed": false,
    "required": true,
    "widget": "Widget",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CRM_ACCOUNT_PARENT",
    "title": "Parent Account",
    "aliasName": "PARENT_ACCOUNT",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CRM_ACCOUNT_NUMBER",
    "title": "Number",
    "aliasName": "NUMBER",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "PRIMARY_CONTACT",
    "title": "Primary Contact",
    "aliasName": "PRIMARY_CONTACT",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CRM_ACCOUNT_TYPE",
    "title": "Type",
    "aliasName": "TYPE",
    "changed": false,
    "required": false,
    "widget": "MATRIX_TABLE",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CRM_ACCOUNT_INDUSTRY",
    "title": "Industry",
    "aliasName": "INDUSTRY",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CRM_ACCOUNT_EMAIL",
    "title": "Email",
    "aliasName": "EMAIL",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CRM_ACCOUNT_PHONE",
    "title": "Phone",
    "aliasName": "PHONE",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CRM_ACCOUNT_FAX",
    "title": "Fax",
    "aliasName": "FAX",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CRM_ACCOUNT_WEBSITE",
    "title": "WebSite",
    "aliasName": "WEBSITE",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "REGISTRATION_NUMBER",
    "title": "Registration Number",
    "aliasName": "REGISTRATION_NUMBER",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "VAT_NUMBER",
    "title": "Vat Number",
    "aliasName": "VAT_NUMBER",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CURRENCY",
    "title": "Currency",
    "aliasName": "CURRENCY",
    "changed": false,
    "required": true,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CRM_ACCOUNT_TAX_TREATMENT",
    "title": "Tax Treatment",
    "aliasName": "TAX_TREATMENT",
    "changed": false,
    "required": true,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "PAYMENT_METHOD",
    "title": "Payment Method",
    "aliasName": "PAYMENT_METHOD",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CLIENT_INVOICE_TERM",
    "title": "Terms",
    "aliasName": "TERMS",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CLIENT_AS_OF_DATE",
    "title": "As Of Date",
    "aliasName": "AS_OF_DATE",
    "changed": false,
    "required": false,
    "widget": "DatePicker",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CLIENT_AMOUNT",
    "title": "Opening Balance",
    "aliasName": "AMOUNT",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "SUPPLIER_AS_OF_DATE",
    "title": "As Of Date",
    "aliasName": "AS_OF_DATE",
    "changed": false,
    "required": false,
    "widget": "DatePicker",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "SUPPLIER_AMOUNT",
    "title": "Opening Balance",
    "aliasName": "AMOUNT",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CLIENT_CREDIT_LIMIT",
    "title": "Credit Limit",
    "aliasName": "CREDIT_LIMIT",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CLIENT_QUOTE_CREDIT_LIMIT",
    "title": "Credit Limit for Quote",
    "aliasName": "QUOTE_CREDIT_LIMIT",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "PRICE_LEVEL",
    "title": "Price Level",
    "aliasName": "PRICE_LEVEL",
    "changed": false,
    "required": false,
    "widget": "CUSTOMLIST",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CLIENT_DISCOUNT",
    "title": "Discount",
    "aliasName": "DISCOUNT",
    "changed": false,
    "required": false,
    "widget": "CUSTOMLIST",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CLIENT_BANK_ACCOUNT",
    "title": "Bank Accounts",
    "aliasName": "BANK_ACCOUNT",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "ACCOUNTS_RECEIVABLE_PAYABLE",
    "title": "Accounts Receivable",
    "aliasName": "ACCOUNTS_RECEIVABLE_PAYABLE",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "GL_ACCOUNT",
    "title": "Create GL Account",
    "aliasName": "GL_ACCOUNT",
    "changed": false,
    "required": false,
    "widget": "CheckBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CLIENT_SUBSIDIARIES",
    "title": "Subsidiary",
    "aliasName": "SUBSIDIARIES",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CLIENT_VAT",
    "title": "Tax",
    "aliasName": "TAX",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CLIENT_TYPE",
    "title": "Client Type",
    "aliasName": "CLIENT_TYPE",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "WAREHOUSE",
    "title": "Warehouse",
    "aliasName": "WAREHOUSE",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "DEPARTMENT",
    "title": "Department",
    "aliasName": "DEPARTMENT",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  }
]');