delete from modelfield where form_id = 'CLIENT_FORM' and field_ID in ('CRM_ACCOUNT_TAX_TREATMENT', 'CRM_ACCOUNT_PLACEOFSUPPLY_COUNTRY', 'CRM_ACCOUNT_PLACEOFSUPPLY_STATE', 'CRM_ACCOUNT_TRN');
delete from modelfield where form_id = 'ACCOUNT_FORM' and field_ID in ('CRM_ACCOUNT_TAX_TREATMENT', 'CRM_ACCOUNT_PLACEOFSUPPLY_COUNTRY', 'CRM_ACCOUNT_PLACEOFSUPPLY_STATE', 'CRM_ACCOUNT_TRN');

delete from "0".modelfield where form_id = 'CLIENT_FORM' and field_ID in ('CRM_ACCOUNT_TAX_TREATMENT', 'CRM_ACCOUNT_PLACEOFSUPPLY_COUNTRY', 'CRM_ACCOUNT_PLACEOFSUPPLY_STATE', 'CRM_ACCOUNT_TRN');
delete from "0".modelfield where form_id = 'ACCOUNT_FORM' and field_ID in ('CRM_ACCOUNT_TAX_TREATMENT', 'CRM_ACCOUNT_PLACEOFSUPPLY_COUNTRY', 'CRM_ACCOUNT_PLACEOFSUPPLY_STATE', 'CRM_ACCOUNT_TRN');

delete from "anv".modelfield where form_id = 'CLIENT_FORM' and field_ID in ('CRM_ACCOUNT_TAX_TREATMENT', 'CRM_ACCOUNT_PLACEOFSUPPLY_COUNTRY', 'CRM_ACCOUNT_PLACEOFSUPPLY_STATE', 'CRM_ACCOUNT_TRN');
delete from "anv".modelfield where form_id = 'ACCOUNT_FORM' and field_ID in ('CRM_ACCOUNT_TAX_TREATMENT', 'CRM_ACCOUNT_PLACEOFSUPPLY_COUNTRY', 'CRM_ACCOUNT_PLACEOFSUPPLY_STATE', 'CRM_ACCOUNT_TRN');

insert into modelfield(form_ID, field_ID, columntype, fsection, forder, mandatory) values
('CLIENT_FORM', 'CRM_ACCOUNT_TAX_TREATMENT', 'COL_1', 'CRM_ACCOUNT_FINANCIAL_INFORMATION', 0, true),
('CLIENT_FORM', 'CRM_ACCOUNT_TRN', 'COL_1', 'CRM_ACCOUNT_FINANCIAL_INFORMATION', 1, true),
('CLIENT_FORM', 'CRM_ACCOUNT_PLACEOFSUPPLY_STATE', 'COL_1', 'CRM_ACCOUNT_FINANCIAL_INFORMATION', 2, true),
('CLIENT_FORM', 'CRM_ACCOUNT_PLACEOFSUPPLY_COUNTRY', 'COL_1', 'CRM_ACCOUNT_FINANCIAL_INFORMATION', 2, true);
update modelfield set forder = 3 where form_id = 'CLIENT_FORM' and field_id = 'CLIENT_VAT';

insert into "0".modelfield(form_ID, field_ID, columntype, fsection, forder, mandatory) values
('CLIENT_FORM', 'CRM_ACCOUNT_TAX_TREATMENT', 'COL_1', 'CRM_ACCOUNT_FINANCIAL_INFORMATION', 0, true),
('CLIENT_FORM', 'CRM_ACCOUNT_TRN', 'COL_1', 'CRM_ACCOUNT_FINANCIAL_INFORMATION', 1, true),
('CLIENT_FORM', 'CRM_ACCOUNT_PLACEOFSUPPLY_STATE', 'COL_1', 'CRM_ACCOUNT_FINANCIAL_INFORMATION', 2, true),
('CLIENT_FORM', 'CRM_ACCOUNT_PLACEOFSUPPLY_COUNTRY', 'COL_1', 'CRM_ACCOUNT_FINANCIAL_INFORMATION', 2, true);
update "0".modelfield set forder = 3 where form_id = 'CLIENT_FORM' and field_id = 'CLIENT_VAT';

insert into "anv".modelfield(form_ID, field_ID, columntype, fsection, forder, mandatory) values
('CLIENT_FORM', 'CRM_ACCOUNT_TAX_TREATMENT', 'COL_1', 'CRM_ACCOUNT_FINANCIAL_INFORMATION', 0, true),
('CLIENT_FORM', 'CRM_ACCOUNT_TRN', 'COL_1', 'CRM_ACCOUNT_FINANCIAL_INFORMATION', 1, true),
('CLIENT_FORM', 'CRM_ACCOUNT_PLACEOFSUPPLY_STATE', 'COL_1', 'CRM_ACCOUNT_FINANCIAL_INFORMATION', 2, true),
('CLIENT_FORM', 'CRM_ACCOUNT_PLACEOFSUPPLY_COUNTRY', 'COL_1', 'CRM_ACCOUNT_FINANCIAL_INFORMATION', 2, true);
update "anv".modelfield set forder = 3 where form_id = 'CLIENT_FORM' and field_id = 'CLIENT_VAT';

