update "0".reporting set code='profit_And_Loss' where code='Profit and Loss';
update "0".reporting set code='Trial_Balance' where code='Trial Balance';
update "0".reporting set code='Balance_Sheet' where code='Balance Sheet';
update "0".reporting set code='Cash_Flow' where code='Cash Flow';
update "0".reporting set code='Income_By_Customer_Summary' where code='Income By Customer Summary';
update "0".reporting set code='Aged_Receivables' where code='Aged Receivables';
update "0".reporting set code='Aged_Payables' where code='Aged Payables';
update "0".reporting set code='Account_Transactions' where code='Account Transactions';
update "0".reporting set code='Journal_Report' where code='Journal Report';
update "0".reporting set code='Budget_Summary' where code='Budget Summary';
update "0".reporting set code='PERSONAL_GOALS' where code='PERSONAL GOALS';
update "0".reporting set code='RECRUITMENT_REPORT' where code='RECRUITMENT REPORT';
update "0".reporting set code='Budget_Variance' where code='Budget Variance';
update "0".reporting set code='COMPANY_GOALS' where code='COMPANY GOALS';
update "0".reporting set code='Expenses_by_Contact' where code='Expenses by Contact';
update "0".reporting set code='LEAVE_REQUESTS_FOR_CURRENT_AND_NEXT_WEEK' where code='LEAVE REQUESTS FOR CURRENT AND NEXT WEEK';
update "0".reporting set code='COMPLETED_APPRAILSALS' where code='COMPLETED APPRAISALS';
update "0".reporting set code='DRAFT_APPRAISALS' where code='DRAFT APPRAISALS';
update "0".reporting set code='Income_by_Contact' where code='Income by Contact';
update "0".reporting set code='YOUR_PENDING_APPRAISALS' where code='YOUR PENDING APPRAISALS';
update "0".reporting set code='LEAVE_REQUESTS_THIS_WEEK' where code='LEAVE REQUESTS THIS WEEK';
update "0".reporting set code='LEAVE_REQUESTS_TODAY' where code='LEAVE REQUESTS TODAY';
update "0".reporting set code='LEAVE_REQUESTS_UNAVAILABLE_EMPLOYEES_TODAY' where code='LEAVE REQUESTS UNAVAILABLE EMPLOYEES TODAY';
update "0".reporting set code='LEAD_BY_SOURCE' where code='LEAD BY SOURCE';
update "0".reporting set code='COLLECTION_LAST_30DAYS' where code='COLLECTION LAST 30 DAYS';
update "0".reporting set code='CUSTOMER_AGEING_REPORT' where code='CUSTOMER AGEING REPORT';
update "0".reporting set code='CUSTOMER_BALANCE_DETAILS' where code='CUSTOMER BALANCE DETAILS';
update "0".reporting set code='DEFAULT_CONTACTS' where code='DEFAULT CONTACTS';
update "0".reporting set code='EXPENSE_BREAKDOWN' where code='EXPENSE BREAKDOWN';
update "0".reporting set code='EXPENSES_BY_CATEGORY' where code='EXPENSES BY CATEGORY';
update "0".reporting set code='OUTSTANDING_BILLS' where code='OUTSTANDING BILLS';
update "0".reporting set code='OVERDUE_INVOICE' where code='OVERDUE INVOICE';
update "0".reporting set code='PROGRESS_INVOICE_STATUSES' where code='PROGRESS INVOICE STATUSES';
update "0".reporting set code='SALES_BY_COUNTRY_DETAILS' where code='SALES BY COUNTRY DETAILS';
update "0".reporting set code='SALES_DETAIL_BY_SALES_PERSON' where code='SALES DETAIL BY SALES PERSON';
update "0".reporting set code='SALES_DETAIL_BY_SERIAL_NUMBER' where code='SALES DETAIL BY SERIAL NUMBER';
update "0".reporting set code='TAX_SUMMARY_REPORT' where code='TAX SUMMARY REPORT';
update "0".reporting set code='TOP_CUSTOMER' where code='TOP CUSTOMER';
update "0".reporting set code='CUSTOMER_INVOICE_REPORT' where code='CUSTOMER INVOICE REPORT';
update "0".reporting set code='SUPPLIER_INVOICE_REPORT' where code='SUPPLIER INVOICE REPORT';
update "0".reporting set code='SALES_FOR_THIS_MONTH' where code='SALES FOR THIS MONTH';
update "0".reporting set code='PROJECT_REVENUE_FOR_COMING_MONTH' where code='PROJECT REVENUE FOR COMING MONTH';
update "0".reporting set code='OVERDUE_PAYMENT_PER_CUSTOMER' where code='OVERDUE PAYMENT PER CUSTOMER';
update "0".reporting set code='Income_By_Customer_Summary' where code='Income By Customer Summary';
update "0".reporting set code='Expenses_by_Contact' where code='Expenses by Contact';
update "0".reporting set code='Budget_Variance' where code='Budget Variance';
update "0".reporting set code='ACCOUNTS_RECEIVABLE_GRAPH' where code='ACCOUNTS RECEIVABLE GRAPH';



update "anv".reporting set code='profit_And_Loss' where code='Profit and Loss';
update "anv".reporting set code='Trial_Balance' where code='Trial Balance';
update "anv".reporting set code='Balance_Sheet' where code='Balance Sheet';
update "anv".reporting set code='Cash_Flow' where code='Cash Flow';
update "anv".reporting set code='Income_By_Customer_Summary' where code='Income By Customer Summary';
update "anv".reporting set code='Aged_Receivables' where code='Aged Receivables';
update "anv".reporting set code='Aged_Payables' where code='Aged Payables';
update "anv".reporting set code='Account_Transactions' where code='Account Transactions';
update "anv".reporting set code='Journal_Report' where code='Journal Report';
update "anv".reporting set code='Budget_Summary' where code='Budget Summary';
update "anv".reporting set code='PERSONAL_GOALS' where code='PERSONAL GOALS';
update "anv".reporting set code='RECRUITMENT_REPORT' where code='RECRUITMENT REPORT';
update "anv".reporting set code='Budget_Variance' where code='Budget Variance';
update "anv".reporting set code='COMPANY_GOALS' where code='COMPANY GOALS';
update "anv".reporting set code='Expenses_by_Contact' where code='Expenses by Contact';
update "anv".reporting set code='LEAVE_REQUESTS_FOR_CURRENT_AND_NEXT_WEEK' where code='LEAVE REQUESTS FOR CURRENT AND NEXT WEEK';
update "anv".reporting set code='COMPLETED_APPRAILSALS' where code='COMPLETED APPRAISALS';
update "anv".reporting set code='DRAFT_APPRAISALS' where code='DRAFT APPRAISALS';
update "anv".reporting set code='Income_by_Contact' where code='Income by Contact';
update "anv".reporting set code='YOUR_PENDING_APPRAISALS' where code='YOUR PENDING APPRAISALS';
update "anv".reporting set code='LEAVE_REQUESTS_THIS_WEEK' where code='LEAVE REQUESTS THIS WEEK';
update "anv".reporting set code='LEAVE_REQUESTS_TODAY' where code='LEAVE REQUESTS TODAY';
update "anv".reporting set code='LEAVE_REQUESTS_UNAVAILABLE_EMPLOYEES_TODAY' where code='LEAVE REQUESTS UNAVAILABLE EMPLOYEES TODAY';
update "anv".reporting set code='LEAD_BY_SOURCE' where code='LEAD BY SOURCE';
update "anv".reporting set code='COLLECTION_LAST_30DAYS' where code='COLLECTION LAST 30 DAYS';
update "anv".reporting set code='CUSTOMER_AGEING_REPORT' where code='CUSTOMER AGEING REPORT';
update "anv".reporting set code='CUSTOMER_BALANCE_DETAILS' where code='CUSTOMER BALANCE DETAILS';
update "anv".reporting set code='DEFAULT_CONTACTS' where code='DEFAULT CONTACTS';
update "anv".reporting set code='EXPENSE_BREAKDOWN' where code='EXPENSE BREAKDOWN';
update "anv".reporting set code='EXPENSES_BY_CATEGORY' where code='EXPENSES BY CATEGORY';
update "anv".reporting set code='OUTSTANDING_BILLS' where code='OUTSTANDING BILLS';
update "anv".reporting set code='OVERDUE_INVOICE' where code='OVERDUE INVOICE';
update "anv".reporting set code='PROGRESS_INVOICE_STATUSES' where code='PROGRESS INVOICE STATUSES';
update "anv".reporting set code='SALES_BY_COUNTRY_DETAILS' where code='SALES BY COUNTRY DETAILS';
update "anv".reporting set code='SALES_DETAIL_BY_SALES_PERSON' where code='SALES DETAIL BY SALES PERSON';
update "anv".reporting set code='SALES_DETAIL_BY_SERIAL_NUMBER' where code='SALES DETAIL BY SERIAL NUMBER';
update "anv".reporting set code='TAX_SUMMARY_REPORT' where code='TAX SUMMARY REPORT';
update "anv".reporting set code='TOP_CUSTOMER' where code='TOP CUSTOMER';
update "anv".reporting set code='CUSTOMER_INVOICE_REPORT' where code='CUSTOMER INVOICE REPORT';
update "anv".reporting set code='SUPPLIER_INVOICE_REPORT' where code='SUPPLIER INVOICE REPORT';
update "anv".reporting set code='SALES_FOR_THIS_MONTH' where code='SALES FOR THIS MONTH';
update "anv".reporting set code='PROJECT_REVENUE_FOR_COMING_MONTH' where code='PROJECT REVENUE FOR COMING MONTH';
update "anv".reporting set code='OVERDUE_PAYMENT_PER_CUSTOMER' where code='OVERDUE PAYMENT PER CUSTOMER';
update "anv".reporting set code='Income_By_Customer_Summary' where code='Income By Customer Summary';
update "anv".reporting set code='Expenses_by_Contact' where code='Expenses by Contact';
update "anv".reporting set code='Budget_Variance' where code='Budget Variance';
update "anv".reporting set code='ACCOUNTS_RECEIVABLE_GRAPH' where code='ACCOUNTS RECEIVABLE GRAPH';