

insert into "0".model (formid, title, viewname, active) values('PRODUCT', 'Product/Service', 'productadd', true);
insert into "0".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PRODUCT_INFORMATION', 0, true);
insert into "0".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'FINANCIAL_INFORMATION', 1, true);
insert into "0".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'MULTI_CURRENCY_PRICE_SETTINGS', 2, false);
insert into "0".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'BILL_OF_MATERIALS', 3, false);
insert into "0".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'INVENTORY_STOCK_INFORMATION', 4, false);
insert into "0".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PRODUCT_GROUP_ITEMS_INFORMATION', 5, false);
insert into "0".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PARAMETRS', 6, false);
insert into "0".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'MORE_OPTIONS', 7, false);
insert into "0".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'ATTACHMENTS', 8, false);
insert into "0".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PRODUCT_CUSTOM_FIELDS', 9, false);
insert into "0".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PRODUCT_CATEGORY_CUSTOM_FIELDS', 10, false);
insert into "0".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'NAME', true, 'COL_1', 'PRODUCT_INFORMATION', 0);
insert into "0".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'TYPE', false, 'COL_1', 'PRODUCT_INFORMATION', 1);
insert into "0".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'ACTIVE', false, 'COL_1', 'PRODUCT_INFORMATION', 2);
insert into "0".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'NUMBER', false, 'COL_2', 'PRODUCT_INFORMATION', 0);
insert into "0".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'DESCRIPTION', false, 'COL_2', 'PRODUCT_INFORMATION', 1);
insert into "0".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'SALES_PRICE', true, 'COL_1', 'FINANCIAL_INFORMATION', 0);
insert into "0".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'SALES_ACCOUNT', false, 'COL_1', 'FINANCIAL_INFORMATION', 1);
insert into "0".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'FROM_PURCHASE_INVOICE', false, 'COL_1', 'FINANCIAL_INFORMATION', 2);
insert into "0".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'PURCHASE_PRICE', true, 'COL_2', 'FINANCIAL_INFORMATION', 0);
insert into "0".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'PURCHASE_ACCOUNT', false, 'COL_2', 'FINANCIAL_INFORMATION', 1);
insert into "0".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'MULTI_TABLE_PANEL', false, 'MULTI_CURRENCY_PRICE_SETTINGS', 0);
insert into "0".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'ASSEMBLY_ITEMS', false, 'BILL_OF_MATERIALS', 0);
insert into "0".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'WAREHOUSE_PANEL', false, 'INVENTORY_STOCK_INFORMATION', 0);
insert into "0".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'PRODUCT_GROUP', false, 'PRODUCT_GROUP_ITEMS_INFORMATION', 0);
insert into "0".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'CATEGORY', false, 'COL_1', 'PARAMETRS', 0);
insert into "0".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'BRAND', false, 'COL_1', 'PARAMETRS', 1);
insert into "0".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'INPUT_PRICE_LEVEL', false, 'COL_1', 'PARAMETRS', 2);
insert into "0".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'DISCOUNT_PANEL', false, 'COL_2', 'PARAMETRS', 0);
insert into "0".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'TAX', false, 'COL_2', 'PARAMETRS', 1);
insert into "0".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'MORE_DETAILS', false, 'MORE_OPTIONS', 0);
insert into "0".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'ATTACHMENTS', false, 'COL_1', 'ATTACHMENTS', 0);
insert into "0".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'IMAGE_UPLOAD', false, 'COL_2', 'ATTACHMENTS', 0);
insert into "0".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'INPUT_CUSTOM_FIELDS', false, 'PRODUCT_CUSTOM_FIELDS', 0);
insert into "0".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'INPUT_CUSTOM_FIELDS', false, 'PRODUCT_CATEGORY_CUSTOM_FIELDS', 0);
delete from "0".modelfield where field_id='INPUT_CUSTOM_FIELDS' and fsection='PRODUCT_CUSTOM_FIELDS';


insert into "anv".model (formid, title, viewname, active) values('PRODUCT', 'Product/Service', 'productadd', true);
insert into "anv".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PRODUCT_INFORMATION', 0, true);
insert into "anv".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'FINANCIAL_INFORMATION', 1, true);
insert into "anv".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'MULTI_CURRENCY_PRICE_SETTINGS', 2, false);
insert into "anv".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'BILL_OF_MATERIALS', 3, false);
insert into "anv".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'INVENTORY_STOCK_INFORMATION', 4, false);
insert into "anv".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PRODUCT_GROUP_ITEMS_INFORMATION', 5, false);
insert into "anv".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PARAMETRS', 6, false);
insert into "anv".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'MORE_OPTIONS', 7, false);
insert into "anv".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'ATTACHMENTS', 8, false);
insert into "anv".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PRODUCT_CUSTOM_FIELDS', 9, false);
insert into "anv".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PRODUCT_CATEGORY_CUSTOM_FIELDS', 10, false);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'NAME', true, 'COL_1', 'PRODUCT_INFORMATION', 0);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'TYPE', false, 'COL_1', 'PRODUCT_INFORMATION', 1);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'ACTIVE', false, 'COL_1', 'PRODUCT_INFORMATION', 2);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'NUMBER', false, 'COL_2', 'PRODUCT_INFORMATION', 0);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'DESCRIPTION', false, 'COL_2', 'PRODUCT_INFORMATION', 1);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'SALES_PRICE', true, 'COL_1', 'FINANCIAL_INFORMATION', 0);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'SALES_ACCOUNT', false, 'COL_1', 'FINANCIAL_INFORMATION', 1);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'FROM_PURCHASE_INVOICE', false, 'COL_1', 'FINANCIAL_INFORMATION', 2);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'PURCHASE_PRICE', true, 'COL_2', 'FINANCIAL_INFORMATION', 0);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'PURCHASE_ACCOUNT', false, 'COL_2', 'FINANCIAL_INFORMATION', 1);
insert into "anv".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'MULTI_TABLE_PANEL', false, 'MULTI_CURRENCY_PRICE_SETTINGS', 0);
insert into "anv".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'ASSEMBLY_ITEMS', false, 'BILL_OF_MATERIALS', 0);
insert into "anv".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'WAREHOUSE_PANEL', false, 'INVENTORY_STOCK_INFORMATION', 0);
insert into "anv".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'PRODUCT_GROUP', false, 'PRODUCT_GROUP_ITEMS_INFORMATION', 0);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'CATEGORY', false, 'COL_1', 'PARAMETRS', 0);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'BRAND', false, 'COL_1', 'PARAMETRS', 1);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'INPUT_PRICE_LEVEL', false, 'COL_1', 'PARAMETRS', 2);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'DISCOUNT_PANEL', false, 'COL_2', 'PARAMETRS', 0);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'TAX', false, 'COL_2', 'PARAMETRS', 1);
insert into "anv".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'MORE_DETAILS', false, 'MORE_OPTIONS', 0);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'ATTACHMENTS', false, 'COL_1', 'ATTACHMENTS', 0);
insert into "anv".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'IMAGE_UPLOAD', false, 'COL_2', 'ATTACHMENTS', 0);
insert into "anv".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'INPUT_PRODUCT_CUSTOM_FIELDS', false, 'PRODUCT_CUSTOM_FIELDS', 0);
insert into "anv".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'INPUT_CUSTOM_FIELDS', false, 'PRODUCT_CATEGORY_CUSTOM_FIELDS', 0);
delete from "anv".modelfield where field_id='INPUT_CUSTOM_FIELDS' and fsection='PRODUCT_CUSTOM_FIELDS';

insert into "0_template".model (formid, title, viewname, active) values('PRODUCT', 'Product/Service', 'productadd', true);
insert into "0_template".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PRODUCT_INFORMATION', 0, true);
insert into "0_template".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'FINANCIAL_INFORMATION', 1, true);
insert into "0_template".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'MULTI_CURRENCY_PRICE_SETTINGS', 2, false);
insert into "0_template".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'BILL_OF_MATERIALS', 3, false);
insert into "0_template".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'INVENTORY_STOCK_INFORMATION', 4, false);
insert into "0_template".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PRODUCT_GROUP_ITEMS_INFORMATION', 5, false);
insert into "0_template".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PARAMETRS', 6, false);
insert into "0_template".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'MORE_OPTIONS', 7, false);
insert into "0_template".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'ATTACHMENTS', 8, false);
insert into "0_template".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PRODUCT_CUSTOM_FIELDS', 9, false);
insert into "0_template".customformsection (form_id, section, sorder, expanded) values('PRODUCT', 'PRODUCT_CATEGORY_CUSTOM_FIELDS', 10, false);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'NAME', true, 'COL_1', 'PRODUCT_INFORMATION', 0);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'TYPE', false, 'COL_1', 'PRODUCT_INFORMATION', 1);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'ACTIVE', false, 'COL_1', 'PRODUCT_INFORMATION', 2);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'NUMBER', false, 'COL_2', 'PRODUCT_INFORMATION', 0);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'DESCRIPTION', false, 'COL_2', 'PRODUCT_INFORMATION', 1);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'SALES_PRICE', true, 'COL_1', 'FINANCIAL_INFORMATION', 0);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'SALES_ACCOUNT', false, 'COL_1', 'FINANCIAL_INFORMATION', 1);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'FROM_PURCHASE_INVOICE', false, 'COL_1', 'FINANCIAL_INFORMATION', 2);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'PURCHASE_PRICE', true, 'COL_2', 'FINANCIAL_INFORMATION', 0);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype, fsection, forder) values('PRODUCT', 'PURCHASE_ACCOUNT', false, 'COL_2', 'FINANCIAL_INFORMATION', 1);
insert into "0_template".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'MULTI_TABLE_PANEL', false, 'MULTI_CURRENCY_PRICE_SETTINGS', 0);
insert into "0_template".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'ASSEMBLY_ITEMS', false, 'BILL_OF_MATERIALS', 0);
insert into "0_template".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'WAREHOUSE_PANEL', false, 'INVENTORY_STOCK_INFORMATION', 0);
insert into "0_template".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'PRODUCT_GROUP', false, 'PRODUCT_GROUP_ITEMS_INFORMATION', 0);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'CATEGORY', false, 'COL_1', 'PARAMETRS', 0);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'BRAND', false, 'COL_1', 'PARAMETRS', 1);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'INPUT_PRICE_LEVEL', false, 'COL_1', 'PARAMETRS', 2);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'DISCOUNT_PANEL', false, 'COL_2', 'PARAMETRS', 0);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'TAX', false, 'COL_2', 'PARAMETRS', 1);
insert into "0_template".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'MORE_DETAILS', false, 'MORE_OPTIONS', 0);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'ATTACHMENTS', false, 'COL_1', 'ATTACHMENTS', 0);
insert into "0_template".modelfield (form_id, field_id, mandatory, columntype,  fsection, forder) values('PRODUCT', 'IMAGE_UPLOAD', false, 'COL_2', 'ATTACHMENTS', 0);
insert into "0_template".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'INPUT_PRODUCT_CUSTOM_FIELDS', false, 'PRODUCT_CUSTOM_FIELDS', 0);
insert into "0_template".modelfield (form_id, field_id, mandatory,  fsection, forder) values('PRODUCT', 'INPUT_CUSTOM_FIELDS', false, 'PRODUCT_CATEGORY_CUSTOM_FIELDS', 0);
delete from "0_template".modelfield where field_id='INPUT_CUSTOM_FIELDS' and fsection='PRODUCT_CUSTOM_FIELDS';