update "anv".mymodule set section='core',name='Outlook plugin',active=true where code='OUTLOOK_PLUGIN';
update "anv".mymodule set section='core',name='Syncronize with google',active=true where code='SYNCRONIZE_WITH_GOOGLE';
update "anv".mymodule set section='core',name='Timesheet plugin',active=true where code='TIMESHEET_PLUGIN';
update "anv".mymodule set section='core',name='Storefront',active=true where code='STOREFRONT';
update "anv".mymodule set section='core',name='Android apps',active=true where code='ANDROID_APPS';
update "anv".mymodule set section='core',name='Iphone apps',active=true where code='DOUBLE_TAX';
update "anv".mymodule set section='core',name='Franchise_management',active=true where code='FRANCHISE_MANAGEMENT';
update "anv".mymodule set section='core',name='Websites',active=true where code='MANUAL_TRANSLATIONS';
update "anv".mymodule set section='pm',name='Project emails',active=true where code='IPHONE_APPS';
update "anv".mymodule set section='core',name='Pm module',active=true where code='WEBSITES';
update "anv".mymodule set section='accounting',name='Double tax',active=true where code='PROJECT_EMAILS';
update "anv".mymodule set section='accounting',name='Manual translations',active=true where code='INVOICE_TEMPLATES';
update "anv".mymodule set section='accounting',name='Invoice templates',active=true where code='RESERVATIONS';
update "anv".mymodule set section='accounting',name='Reservations',active=true where code='PM_MODULE';
update "anv".mymodule set section='hrms',name='Meeting minutes',active=true where code='MEETING_MINUTES';
update "anv".mymodule set section='hrms',name='Stuff updates',active=true where code='STUFF_UPDATES';
update "anv".mymodule set section='core',name='Premium recomendations',active=true where code='PREMIUM_RECOMENDATIONS';
update "anv".mymodule set section='core',name='Notes',active=true where code='NOTES';
update "anv".mymodule set section='hrms',name='Company news',active=true where code='COMPANY_NEWS';
update "anv".mymodule set section='core',name='Active workflow status',active=true where code='IS_ACTIVE_WORKFLOW_STATUS';
update "anv".mymodule set section='core',name='Additional module',active=true where code='ADDITIONAL_MODULE';
update "anv".mymodule set section='core',name='Permission management',active=true where code='PERMISSION_MANAGEMENT';
update "anv".mymodule set section='core',name='Custom references',active=true where code='CUSTOM_REFERENCES';
update "anv".mymodule set section='core',name='Add ons module',active=true where code='ADD_ONS_MODULE';
update "anv".mymodule set section='accounting',name='Landing cost',active=true where code='LANDING_COST';
update "anv".mymodule set section='accounting',name='Serial number tracking',active=true where code='SERIAL_NUMBER_TRACKING';
update "anv".mymodule set section='core',name='Sms integration',active=true where code='SMS_INTEGRATION';
update "anv".mymodule set section='crm',name='Email marketing',active=true where code='EMAIL_MARKETING';
update "anv".mymodule set section='accounting',name='Chart of accounts',active=true where code='ACCOUNTING_CHART_OF_ACCOUNTS';
update "anv".mymodule set section='accounting',name='Customer center',active=true where code='ACCOUNTING_CUSTOMER_CENTER';
update "anv".mymodule set section='core',name='Accounting module',active=true where code='ACCOUNTING_MODULE';
update "anv".mymodule set section='crm',name='Activities',active=true where code='ACTIVITIES';
update "anv".mymodule set section='hrms',name='Attending tracking',active=true where code='ATTENDING_TRACKING';
update "anv".mymodule set section='accounting',name='Bank accounts',active=true where code='BANK_ACCOUNTS';
update "anv".mymodule set section='core',name='Booking items',active=true where code='BOOKING_ITEMS';
update "anv".mymodule set section='crm',name='Case management',active=true where code='CASE_MANAGEMENT';
update "anv".mymodule set section='accounting',name='Checks',active=true where code='CHECKS';
update "anv".mymodule set section='accounting',name='Consignments',active=true where code='CONSIGNMENTS';
update "anv".mymodule set section='crm',name='Contact management',active=true where code='CONTACT_MANAGEMENT';
update "anv".mymodule set section='core',name='Core',active=true where code='CORE';
update "anv".mymodule set section='crm',name='Crm calendar',active=true where code='CRM_CALENDAR';
update "anv".mymodule set section='core',name='Crm contact category',active=true where code='CRM_CONTACT_CATEGORY';
update "anv".mymodule set section='core',name='Crm module',active=true where code='CRM_MODULE';
update "anv".mymodule set section='accounting',name='Customer center',active=true where code='CUSTOMER_CENTER';
update "anv".mymodule set section='core',name='Custom fields',active=true where code='CUSTOM_FIELDS';
update "anv".mymodule set section='core',name='Document management',active=true where code='DOCUMENT_MANAGEMENT';
update "anv".mymodule set section='accounting',name='Employee expenses',active=true where code='EMPLOYEE_EXPENSES';
update "anv".mymodule set section='pm',name='Employee incidents',active=true where code='EMPLOYEE_INCIDENTS';
update "anv".mymodule set section='accounting',name='Expense reporting',active=true where code='EXPENSE_REPORTING';
update "anv".mymodule set section='accounting',name='Fixed assests',active=true where code='FIXED_ASSESTS';
update "anv".mymodule set section='pm',name='Gantt chart',active=true where code='GANTT_CHART';
update "anv".mymodule set section='hrms',name='Goal management',active=true where code='GOAL_MANAGEMENT';
update "anv".mymodule set section='core',name='Hrms module',active=true where code='HRMS_MODULE';
update "anv".mymodule set section='pm',name='Import from ms project',active=true where code='IMPORT_FROM_MS_PROJECT';
update "anv".mymodule set section='accounting',name='Inventory management',active=true where code='INVENTORY_MANAGEMENT';
update "anv".mymodule set section='accounting',name='Issue tracking',active=true where code='ISSUE_TRACKING';
update "anv".mymodule set section='crm',name='Lead management',active=true where code='LEAD_MANAGEMENT';
update "anv".mymodule set section='hrms',name='Leave management',active=true where code='LEAVE_MANAGEMENT';
update "anv".mymodule set section='accounting',name='Manual transactions',active=true where code='MANUAL_TRANSACTIONS';
update "anv".mymodule set section='crm',name='Message center',active=true where code='MESSAGE_CENTER';
update "anv".mymodule set section='pm',name='Monthly timesheet',active=true where code='MONTHLY_TIMESHEET';
update "anv".mymodule set section='accounting',name='Multiple warehouse',active=true where code='MULTIPLE_WAREHOUSE';
update "anv".mymodule set section='core',name='Myworkspace module',active=true where code='MYWORKSPACE_MODULE';
update "anv".mymodule set section='core',name='Onboarding',active=true where code='ONBOARDING';
update "anv".mymodule set section='crm',name='Opportunity tracking',active=true where code='OPPORTUNITY_TRACKING';
update "anv".mymodule set section='core',name='Payroll',active=true where code='PAYROLL';
update "anv".mymodule set section='hrms',name='Performance appraisal',active=true where code='PERFORMANCE_APPRAISAL';
update "anv".mymodule set section='core',name='Pm',active=true where code='PM';
update "anv".mymodule set section='accounting',name='Product inventory items',active=true where code='PRODUCT_INVENTORY_ITEMS';
update "anv".mymodule set section='accounting',name='Products services',active=true where code='PRODUCTS_SERVICES';
update "anv".mymodule set section='hrms',name='Promotions penalties',active=true where code='PROMOTIONS_PENALTIES';
update "anv".mymodule set section='accounting',name='Purchase invoicing',active=true where code='PURCHASE_INVOICING';
update "anv".mymodule set section='accounting',name='Purchase orders',active=true where code='PURCHASE_ORDERS';
update "anv".mymodule set section='accounting',name='Reccuring invoices',active=true where code='RECCURING_INVOICES';
update "anv".mymodule set section='hrms',name='Recruitment system',active=true where code='RECRUITMENT_SYSTEM';
update "anv".mymodule set section='accounting',name='Recurring bills',active=true where code='RECURRING_BILLS';
update "anv".mymodule set section='core',name='Reminders',active=true where code='REMINDERS';
update "anv".mymodule set section='core',name='Reporting system',active=true where code='REPORTING_SYSTEM';
update "anv".mymodule set section='accounting',name='Request for purchases',active=true where code='REQUEST_FOR_PURCHASES';
update "anv".mymodule set section='accounting',name='Request for quotes',active=true where code='REQUEST_FOR_QUOTES';
update "anv".mymodule set section='hrms',name='Resource planning',active=true where code='RESOURCE_PLANNING';
update "anv".mymodule set section='accounting',name='Sales invoicing',active=true where code='SALES_INVOICING';
update "anv".mymodule set section='accounting',name='Sales orders',active=true where code='SALES_ORDERS';
update "anv".mymodule set section='accounting',name='Sales quotes',active=true where code='SALES_QUOTES';
update "anv".mymodule set section='accounting',name='Supplier center',active=true where code='SUPPLIER_CENTER';
update "anv".mymodule set section='pm',name='Task management',active=true where code='TASK_MANAGEMENT';
update "anv".mymodule set section='core',name='Timer',active=true where code='TIMER';
update "anv".mymodule set section='pm',name='Timesheet',active=true where code='TIMESHEET';
update "anv".mymodule set section='accounting',name='Timesheet invoices',active=true where code='TIMESHEET_INVOICES';
update "anv".mymodule set section='core',name='Training center',active=true where code='TRAINING_CENTER';
update "anv".mymodule set section='core',name='Web forms',active=true where code='WEB_FORMS';
update "anv".mymodule set section='core',name='Workspace',active=true where code='WORKSPACE';
update "anv".mymodule set section='core',name='Workspace calendar',active=true where code='WORKSPACE_CALENDAR';

insert into "anv".mymodule (code,name,section,active) values ('OUTLOOK_PLUGIN','Outlook plugin','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('SYNCRONIZE_WITH_GOOGLE','Syncronize with google','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('TIMESHEET_PLUGIN','Timesheet plugin','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('STOREFRONT','Storefront','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('ANDROID_APPS','Android apps','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('IPHONE_APPS','Iphone apps','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('FRANCHISE_MANAGEMENT','Franchise_management','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('WEBSITES','Websites','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('PROJECT_EMAILS','Project emails','pm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('PM_MODULE','Pm module','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('DOUBLE_TAX','Double tax','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('MANUAL_TRANSLATIONS','Manual translations','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('INVOICE_TEMPLATES','Invoice templates','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('RESERVATIONS','Reservations','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('MEETING_MINUTES','Meeting minutes','hrms',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('STUFF_UPDATES','Stuff updates','hrms',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('PREMIUM_RECOMENDATIONS','Premium recomendations','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('NOTES','Notes','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('COMPANY_NEWS','Company news','hrms',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('IS_ACTIVE_WORKFLOW_STATUS','Active workflow status','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('ADDITIONAL_MODULE','Additional module','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('PERMISSION_MANAGEMENT','Permission management','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('CUSTOM_REFERENCES','Custom references','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('ADD_ONS_MODULE','Add ons module','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('LANDING_COST','Landing cost','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('SERIAL_NUMBER_TRACKING','Serial number tracking','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('SMS_INTEGRATION','Sms integration','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('EMAIL_MARKETING','Email marketing','crm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('ACCOUNTING_CHART_OF_ACCOUNTS','Chart of accounts','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('ACCOUNTING_CUSTOMER_CENTER','Customer center','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('ACCOUNTING_MODULE','Accounting module','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('ACTIVITIES','Activities','crm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('ATTENDING_TRACKING','Attending tracking','hrms',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('BANK_ACCOUNTS','Bank accounts','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('BOOKING_ITEMS','Booking items','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('CASE_MANAGEMENT','Case management','crm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('CHECKS','Checks','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('CONSIGNMENTS','Consignments','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('CONTACT_MANAGEMENT','Contact management','crm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('CORE','Core','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('CRM_CALENDAR','Crm calendar','crm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('CRM_CONTACT_CATEGORY','Crm contact category','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('CRM_MODULE','Crm module','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('CUSTOMER_CENTER','Customer center','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('CUSTOM_FIELDS','Custom fields','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('DOCUMENT_MANAGEMENT','Document management','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('EMPLOYEE_EXPENSES','Employee expenses','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('EMPLOYEE_INCIDENTS','Employee incidents','pm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('EXPENSE_REPORTING','Expense reporting','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('FIXED_ASSESTS','Fixed assests','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('GANTT_CHART','Gantt chart','pm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('GOAL_MANAGEMENT','Goal management','hrms',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('HRMS_MODULE','Hrms module','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('IMPORT_FROM_MS_PROJECT','Import from ms project','pm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('INVENTORY_MANAGEMENT','Inventory management','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('ISSUE_TRACKING','Issue tracking','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('LEAD_MANAGEMENT','Lead management','crm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('LEAVE_MANAGEMENT','Leave management','hrms',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('LOGISTICS_MODULE','Logistics module','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('MANUAL_TRANSACTIONS','Manual transactions','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('MESSAGE_CENTER','Message center','crm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('MONTHLY_TIMESHEET','Monthly timesheet','pm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('MULTIPLE_WAREHOUSE','Multiple warehouse','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('MYWORKSPACE_MODULE','Myworkspace module','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('ONBOARDING','Onboarding','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('OPPORTUNITY_TRACKING','Opportunity tracking','crm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('PAYROLL','Payroll','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('PERFORMANCE_APPRAISAL','Performance appraisal','hrms',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('PM','Pm','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('PRODUCT_INVENTORY_ITEMS','Product inventory items','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('PRODUCTS_SERVICES','Products services','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('PROMOTIONS_PENALTIES','Promotions penalties','hrms',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('PURCHASE_INVOICING','Purchase invoicing','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('PURCHASE_ORDERS','Purchase orders','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('RECCURING_INVOICES','Reccuring invoices','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('RECRUITMENT_SYSTEM','Recruitment system','hrms',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('RECURRING_BILLS','Recurring bills','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('REMINDERS','Reminders','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('REPORTING_SYSTEM','Reporting system','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('REQUEST_FOR_PURCHASES','Request for purchases','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('REQUEST_FOR_QUOTES','Request for quotes','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('RESOURCE_PLANNING','Resource planning','hrms',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('SALES_INVOICING','Sales invoicing','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('SALES_ORDERS','Sales orders','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('SALES_QUOTES','Sales quotes','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('SUPPLIER_CENTER','Supplier center','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('TASK_MANAGEMENT','Task management','pm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('TIMER','Timer','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('TIMESHEET','Timesheet','pm',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('TIMESHEET_INVOICES','Timesheet invoices','accounting',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('TRAINING_CENTER','Training center','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('WEB_FORMS','Web forms','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('WORKSPACE','Workspace','core',false) on conflict do nothing;
insert into "anv".mymodule (code,name,section,active) values ('WORKSPACE_CALENDAR','Workspace calendar','core',false) on conflict do nothing;

insert into "0".mymodule (code,name,section,active) values ('OUTLOOK_PLUGIN','Outlook plugin','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('SYNCRONIZE_WITH_GOOGLE','Syncronize with google','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('TIMESHEET_PLUGIN','Timesheet plugin','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('STOREFRONT','Storefront','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('ANDROID_APPS','Android apps','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('IPHONE_APPS','Iphone apps','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('FRANCHISE_MANAGEMENT','Franchise_management','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('WEBSITES','Websites','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('PROJECT_EMAILS','Project emails','pm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('PM_MODULE','Pm module','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('DOUBLE_TAX','Double tax','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('MANUAL_TRANSLATIONS','Manual translations','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('INVOICE_TEMPLATES','Invoice templates','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('RESERVATIONS','Reservations','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('MEETING_MINUTES','Meeting minutes','hrms',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('STUFF_UPDATES','Stuff updates','hrms',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('PREMIUM_RECOMENDATIONS','Premium recomendations','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('NOTES','Notes','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('COMPANY_NEWS','Company news','hrms',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('IS_ACTIVE_WORKFLOW_STATUS','Active workflow status','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('ADDITIONAL_MODULE','Additional module','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('PERMISSION_MANAGEMENT','Permission management','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('CUSTOM_REFERENCES','Custom references','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('ADD_ONS_MODULE','Add ons module','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('LANDING_COST','Landing cost','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('SERIAL_NUMBER_TRACKING','Serial number tracking','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('SMS_INTEGRATION','Sms integration','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('EMAIL_MARKETING','Email marketing','crm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('ACCOUNTING_CHART_OF_ACCOUNTS','Chart of accounts','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('ACCOUNTING_CUSTOMER_CENTER','Customer center','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('ACCOUNTING_MODULE','Accounting module','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('ACTIVITIES','Activities','crm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('ATTENDING_TRACKING','Attending tracking','hrms',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('BANK_ACCOUNTS','Bank accounts','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('BOOKING_ITEMS','Booking items','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('CASE_MANAGEMENT','Case management','crm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('CHECKS','Checks','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('CONSIGNMENTS','Consignments','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('CONTACT_MANAGEMENT','Contact management','crm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('CORE','Core','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('CRM_CALENDAR','Crm calendar','crm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('CRM_CONTACT_CATEGORY','Crm contact category','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('CRM_MODULE','Crm module','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('CUSTOMER_CENTER','Customer center','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('CUSTOM_FIELDS','Custom fields','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('DOCUMENT_MANAGEMENT','Document management','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('EMPLOYEE_EXPENSES','Employee expenses','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('EMPLOYEE_INCIDENTS','Employee incidents','pm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('EXPENSE_REPORTING','Expense reporting','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('FIXED_ASSESTS','Fixed assests','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('GANTT_CHART','Gantt chart','pm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('GOAL_MANAGEMENT','Goal management','hrms',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('HRMS_MODULE','Hrms module','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('IMPORT_FROM_MS_PROJECT','Import from ms project','pm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('INVENTORY_MANAGEMENT','Inventory management','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('ISSUE_TRACKING','Issue tracking','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('LEAD_MANAGEMENT','Lead management','crm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('LEAVE_MANAGEMENT','Leave management','hrms',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('LOGISTICS_MODULE','Logistics module','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('MANUAL_TRANSACTIONS','Manual transactions','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('MESSAGE_CENTER','Message center','crm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('MONTHLY_TIMESHEET','Monthly timesheet','pm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('MULTIPLE_WAREHOUSE','Multiple warehouse','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('MYWORKSPACE_MODULE','Myworkspace module','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('ONBOARDING','Onboarding','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('OPPORTUNITY_TRACKING','Opportunity tracking','crm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('PAYROLL','Payroll','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('PERFORMANCE_APPRAISAL','Performance appraisal','hrms',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('PM','Pm','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('PRODUCT_INVENTORY_ITEMS','Product inventory items','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('PRODUCTS_SERVICES','Products services','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('PROMOTIONS_PENALTIES','Promotions penalties','hrms',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('PURCHASE_INVOICING','Purchase invoicing','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('PURCHASE_ORDERS','Purchase orders','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('RECCURING_INVOICES','Reccuring invoices','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('RECRUITMENT_SYSTEM','Recruitment system','hrms',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('RECURRING_BILLS','Recurring bills','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('REMINDERS','Reminders','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('REPORTING_SYSTEM','Reporting system','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('REQUEST_FOR_PURCHASES','Request for purchases','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('REQUEST_FOR_QUOTES','Request for quotes','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('RESOURCE_PLANNING','Resource planning','hrms',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('SALES_INVOICING','Sales invoicing','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('SALES_ORDERS','Sales orders','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('SALES_QUOTES','Sales quotes','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('SUPPLIER_CENTER','Supplier center','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('TASK_MANAGEMENT','Task management','pm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('TIMER','Timer','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('TIMESHEET','Timesheet','pm',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('TIMESHEET_INVOICES','Timesheet invoices','accounting',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('TRAINING_CENTER','Training center','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('WEB_FORMS','Web forms','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('WORKSPACE','Workspace','core',false) on conflict do nothing;
insert into "0".mymodule (code,name,section,active) values ('WORKSPACE_CALENDAR','Workspace calendar','core',false) on conflict do nothing;
