#global configuration
globalauth.datasource.url=jdbc:postgresql://auth.workforcetrack.com:6432/globalauth
globalauth.datasource.username=wftauth
globalauth.datasource.password=wft
globalauth.datasource.driverClassName=org.postgresql.Driver
globalauth.datasource.hikari.connectionTimeout=120000
globalauth.datasource.hikari.leakDetectionThreshold=60000
globalauth.datasource.hikari.maxPoolSize=15
globalauth.datasource.hikari.idleTimeout=300000
globalauth.datasource.hikari.minIdle=15
globalauth.datasource.hikari.poolName=globalauth
#quartz configuration
quartz.enabled=false
quartz.datasource.url=jdbc:postgresql://qrtz.workforcetrack.com:6432/qrtzdb
quartz.datasource.username=wftauth
quartz.datasource.password=wft
quartz.datasource.driverClassName=org.postgresql.Driver
quartz.datasource.hikari.connectionTimeout=120000
quartz.datasource.hikari.leakDetectionThreshold=60000
quartz.datasource.hikari.maxPoolSize=5
quartz.datasource.hikari.idleTimeout=120000
quartz.datasource.hikari.minIdle=5
quartz.datasource.hikari.poolName=qrtzdb
#reporting configuration
reporting.datasource.url=jdbc:postgresql://masterdbpaid.workforcetrack.com:6432/reportservice_excel
reporting.datasource.username=wfmtest
reporting.datasource.password=wfm
reporting.datasource.driverClassName=org.postgresql.Driver
reporting.datasource.hikari.connectionTimeout=120000
reporting.datasource.hikari.leakDetectionThreshold=60000
reporting.datasource.hikari.maxPoolSize=5
reporting.datasource.hikari.idleTimeout=120000
reporting.datasource.hikari.minIdle=5
reporting.datasource.hikari.poolName=reporting
#tenant configuration
tenant.datasource.username=wfmtest
tenant.datasource.password=wfm
tenant.datasource.cluster.default=FREE
tenant.datasource.cluster.update=[FREE,PAID]
tenant.datasource.clusters=[FREE, PAID, PAID1]
#master database configuration
tenant.datasource.master.FREE.url=jdbc:postgresql://masterdbfree.workforcetrack.com:6432/multischemafree
tenant.datasource.master.PAID.url=jdbc:postgresql://masterdbpaid.workforcetrack.com:6432/multischemapaid
tenant.datasource.master.PAID1.url=jdbc:postgresql://masterdbpaid1.workforcetrack.com:6432/multischemapaid
tenant.datasource.master.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
tenant.datasource.master.jpa.database=POSTGRESQL
tenant.datasource.master.jpa.hibernate.ddl-auto=none
tenant.datasource.master.jpa.properties.hibernate.cache.use_second_level_cache=true
tenant.datasource.master.jpa.properties.hibernate.cache.use_query_cache=false
tenant.datasource.master.jpa.properties.hibernate.generate_statistics=false
tenant.datasource.master.jpa.properties.hibernate.cache.use_minimal_puts=true
tenant.datasource.master.jpa.properties.hibernate.hbm2ddl.auto=none
tenant.datasource.master.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.internal.JCacheRegionFactory
#master hikari configuration
tenant.datasource.master.hikari.connectionTimeout=60000
tenant.datasource.master.hikari.maxPoolSize=20
tenant.datasource.master.hikari.idleTimeout=120000
tenant.datasource.master.hikari.minIdle=20
tenant.datasource.master.hikari.leakDetectionThreshold=60000
tenant.datasource.master.hikari.poolName=master
#slave database configuration
tenant.datasource.slave.FREE.url=jdbc:postgresql://masterdbfree.workforcetrack.com:6432/multischemafree
tenant.datasource.slave.PAID.url=jdbc:postgresql://masterdbpaid.workforcetrack.com:6432/multischemapaid
tenant.datasource.slave.PAID1.url=jdbc:postgresql://masterdbpaid1.workforcetrack.com:6432/multischemapaid
tenant.datasource.slave.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
tenant.datasource.slave.jpa.database=POSTGRESQL
tenant.datasource.slave.jpa.hibernate.ddl-auto=none
tenant.datasource.slave.jpa.properties.hibernate.cache.use_second_level_cache=true
tenant.datasource.slave.jpa.properties.hibernate.cache.use_query_cache=false
tenant.datasource.slave.jpa.properties.hibernate.generate_statistics=false
tenant.datasource.slave.jpa.properties.hibernate.cache.use_minimal_puts=true
tenant.datasource.slave.jpa.properties.hibernate.hbm2ddl.auto=none
tenant.datasource.slave.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.internal.JCacheRegionFactory
#slave hikari configuration
tenant.datasource.slave.hikari.connectionTimeout=60000
tenant.datasource.slave.hikari.maxPoolSize=10
tenant.datasource.slave.hikari.idleTimeout=120000
tenant.datasource.slave.hikari.minIdle=10
tenant.datasource.slave.hikari.leakDetectionThreshold=60000
tenant.datasource.slave.hikari.poolName=slave
#logaudit configuration
logger.datasource.url=jdbc:postgresql://kpi.logger.com:6432/logaudit
logger.datasource.username=${tenant.datasource.username}
logger.datasource.password=${tenant.datasource.password}
#kafka
kafka.producer.bootstrap-servers=kafka.kpi.com:9092,kafka.kpi.com:9094,kafka.kpi.com:9096
kafka.producer.acks=all
kafka.producer.retries=3
kafka.producer.retries.backoffs=1000
kafka.producer.properties.delivery.timeout=120000
kafka.producer.properties.request.timeout=30000
kafka.producer.properties.linger=0
kafka.producer.properties.enable.idempotence=true
kafka.producer.properties.max.in.flight.request=5