update "90826".form_property
set settingsjsondata='
[
    {
        "code": "CLIENT",
        "title": "Customer",
        "aliasName": "CLIENT",
        "changed": false,
        "required": false,
        "widget": "Unknow",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "PROJECT",
        "title": "Project",
        "aliasName": "PROJECT",
        "changed": false,
        "required": true,
        "widget": "LOOKUP",
        "selectedId": 1,
        "defaultValue": "Вне проектные часы",
        "disabled": false,
        "roleEdit": [],
        "systemRequired": true,
        "approvalRelated": false
    },
    {
        "code": "NUMBER",
        "title": "Number",
        "aliasName": "NUMBER",
        "changed": false,
        "required": true,
        "widget": "Numbering",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": true,
        "approvalRelated": false
    },
    {
        "code": "NAME",
        "title": "Name",
        "aliasName": "NAME",
        "changed": false,
        "required": true,
        "widget": "TextBox",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "DESCRIPTION",
        "title": "Description",
        "aliasName": "DESCRIPTION",
        "changed": false,
        "required": false,
        "widget": "TextArea",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "START_DATE",
        "title": "Start date",
        "aliasName": "START_DATE",
        "changed": false,
        "required": true,
        "widget": "DatePicker",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "DUE_DATE",
        "title": "Due date",
        "aliasName": "DUE_DATE",
        "changed": false,
        "required": true,
        "widget": "DatePicker",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "WORKFLOW_DATE",
        "title": "Date",
        "aliasName": "WORKFLOW_DATE",
        "changed": false,
        "required": true,
        "widget": "Unknow",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "WORKFLOW_TIME_BASED",
        "title": "Execution time",
        "aliasName": "WORKFLOW_TIME_BASED",
        "changed": false,
        "required": false,
        "widget": "Unknow",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "BILLIBLE",
        "title": "Billable",
        "aliasName": "BILLIBLE",
        "changed": false,
        "required": false,
        "widget": "CheckBox",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "PRIORITY",
        "title": "Priority",
        "aliasName": "PRIORITY",
        "changed": false,
        "required": false,
        "widget": "DropDown",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "STATUS",
        "title": "Status",
        "aliasName": "STATUS",
        "changed": false,
        "required": false,
        "widget": "DropDown",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "TIME_SPENT",
        "title": "Time spent today",
        "aliasName": "TIME_SPENT",
        "changed": false,
        "required": false,
        "widget": "Unknow",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "TASK_AMOUNT",
        "title": "Task Amount",
        "aliasName": "TASK_AMOUNT",
        "changed": false,
        "required": false,
        "widget": "TextBox",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "PARENT_WORKSTREAM",
        "title": "Workstream",
        "aliasName": "PARENT_WORKSTREAM",
        "changed": false,
        "required": false,
        "widget": "Unknow",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "PREDECESSOR_TASK",
        "title": "Predecessor",
        "aliasName": "PREDECESSOR_TASK",
        "changed": false,
        "required": false,
        "widget": "Unknow",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "SUCCESSOR_TASK",
        "title": "Successor",
        "aliasName": "SUCCESSOR_TASK",
        "changed": false,
        "required": false,
        "widget": "Unknow",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "DUE_DATE_REMINDER",
        "title": "Due Date Reminder",
        "aliasName": "DUE_DATE_REMINDER",
        "changed": false,
        "required": false,
        "widget": "Unknow",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "RECURRENING",
        "title": "Recurring",
        "aliasName": "RECURRENING",
        "changed": false,
        "required": false,
        "widget": "Unknow",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "TASK_NOTES",
        "title": "Notes",
        "aliasName": "TASK_NOTES",
        "changed": false,
        "required": false,
        "widget": "TextBox",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    },
    {
        "code": "TYPE",
        "title": "Type",
        "aliasName": "TYPE",
        "changed": false,
        "required": false,
        "widget": "DropDown",
        "defaultValue": "",
        "disabled": false,
        "systemRequired": false,
        "approvalRelated": false
    }
]
'
where form_id = 'TASK_MAX_FORM';
