DELETE FROM "model"  WHERE formid = 'PAYROLL_STARTER_FORM';
DELETE FROM "modelfield"  WHERE form_id = 'PAYROLL_STARTER_FORM';

insert into model(active, formID, title, viewname) values(true, 'PAYROLL_STARTER_FORM', 'Payroll Employee Add Form', 'payrollstarterform');

insert into modelfield(form_ID,                 field_ID,                               sorder, mandatory,   hide,   isCustomField,        section,           defaultValue, widget, systemmandatory,            nolabelfor,                   nowrapperfor,           fullWidth,  split) values
                      ('PAYROLL_STARTER_FORM', 'FIRST_NAME',                              01,      false,   false,       false,   'EMPLOYEE_DETAILS',              '',    'TextBox',    false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'LAST_NAME',                               02,      false,   false,       false,   'EMPLOYEE_DETAILS',              '',    'TextBox',    false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'EMAIL',                                   03,      false,   false,       false,   'EMPLOYEE_DETAILS',              '',    'TextBox',    false,                      '',                            '',                   false,    true),
                      ('PAYROLL_STARTER_FORM', 'HIRE_DATE',                               04,      false,   false,       false,   'EMPLOYEE_DETAILS',              '',    'DatePicker', false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'BIRTH_DAY',                               05,      false,   false,       false,   'EMPLOYEE_DETAILS',              '',    'UNKNOWN',    false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'CONTRACT_START_DATE',                     06,      false,   false,       false,   'EMPLOYEE_DETAILS',              '',    'DatePicker', false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'CONTRACT_END_DATE',                       07,      false,   false,       false,   'EMPLOYEE_DETAILS',              '',    'DatePicker', false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'APPROVER',                                08,      false,   false,       false,   'EMPLOYEE_DETAILS',              '',    'LOOKUP',     false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'CITIZENSHIP',                             09,      false,   false,       false,   'EMPLOYEE_DETAILS',              '',    'DropDown',   false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'EMPLOYEE_IS_PAID',                        10,      false,   false,       false,   'PAYMENT_SETTINGS',              '',    'UNKNOWN',    false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'JOB_TITLE',                               11,      false,   false,       false,   'PAYMENT_SETTINGS',              '',    'MULTITABLE', false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'SALARY_GRADE',                            12,      false,   false,       false,   'PAYMENT_SETTINGS',              '',    'MULTITABLE', false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'SALARY_CURRENCY',                         13,      false,   false,       false,   'PAYMENT_SETTINGS',              '',    'DropDown',   false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'NORMAL_RATE',                             14,      false,   false,       false,   'PAYMENT_SETTINGS',              '',    'MULTITABLE', false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'OVER_TIME_RATE',                          15,      false,   false,       false,   'PAYMENT_SETTINGS',              '',    'MULTITABLE', false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'PAY_PERIOD',                              16,      false,   false,       false,   'PAYMENT_SETTINGS',              '',    'DropDown',   false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'PAY_METHOD',                              17,      false,   false,       false,   'PAYMENT_SETTINGS',              '',    'DropDown',   false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'EMPLOYEE_BONUS',                          18,      false,   false,       false,   'PAYMENT_SETTINGS',              '',    'UNKNOWN',    false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'EMPLOYEE_COMMISSION',                     19,      false,   false,       false,   'PAYMENT_SETTINGS',              '',    'TextBox',    false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'EMPLOYEE_CODE',                           20,      false,   false,       false,   'PAYROLL_SETTINGS',              '',    'UNKNOWN',    false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'WPS_NUMBER',                              21,      false,   false,       false,   'PAYROLL_SETTINGS',              '',    'TextBox',    false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'RESIGNATION_DATE',                        22,      false,   false,       false,   'PAYROLL_SETTINGS',              '',    'UNKNOWN',    false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'FAMILY_STATUS',                           23,      false,   false,       false,   'PAYROLL_SETTINGS',              '',    'DropDown',   false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'GENDER',                                  24,      false,   false,       false,   'PAYROLL_SETTINGS',              '',    'MULTITABLE', false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'JOB_DETAILS',                             25,      false,   false,       false,   'PAYROLL_SETTINGS',              '',    'UNKNOWN',    false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'OVERTIME_SETTINGS_TABLE',                 26,      false,   false,       false,   'EMPLOYEE_OVERTIME_SETTINGS',    '',    'MULTITABLE', false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'PAYMENT_TABLE',                           27,      false,   false,       false,   'PAYMENT_DEDUCTION_INFORMATION', '',    'MULTITABLE', false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'DEDUCTION_TABLE',                         28,      false,   false,       false,   'PAYMENT_DEDUCTION_INFORMATION', '',    'MULTITABLE', false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'LOAN_TABLE',                              29,      false,   false,       false,   'PAYMENT_DEDUCTION_INFORMATION', '',    'MULTITABLE', false,                      '',                            '',                   false,   false),
                      ('PAYROLL_STARTER_FORM', 'EMPLOYEE_PAYROLL_SETTINGS',               30,      false,   false,       false,   'EMPLOYEE_PAYROLL_SETTINGS',     '',    'UNKNOWN',    false,                      '',                            '',                   false,   false);


UPDATE modelfield set sectionStyle  = 'slideDown-box  group expand hideCustomField' WHERE form_id = 'PAYROLL_STARTER_FORM';
UPDATE modelfield set fieldSetStyle = 'slideDown-content group labelLine' WHERE form_id = 'PAYROLL_STARTER_FORM';
UPDATE modelfield set fieldSetStyle = 'slideDown-content group nobrd' WHERE noLabelFor is not null AND noLabelFor != '' AND form_id = 'PAYROLL_STARTER_FORM';
UPDATE modelfield set halfSetStyle = 'halfSet-1 left' WHERE form_id = 'PAYROLL_STARTER_FORM';
UPDATE modelfield set halfSetStyle = '' WHERE noLabelFor is not null AND noLabelFor != '' AND form_id = 'PAYROLL_STARTER_FORM';
UPDATE modelfield set rowStyle = 'row hideCustomField' WHERE form_id = 'PAYROLL_STARTER_FORM';
UPDATE modelfield set fieldStyle = 'field' WHERE form_id = 'PAYROLL_STARTER_FORM';

UPDATE company SET isdeleted = FALSE WHERE isdeleted IS NULL AND (SELECT "anv".convertCustomFieldsToModelFields('PAYROLL_STARTER_FORM', 'addpaymentcategory')) IS NOT NULL;