DELETE FROM "model"  WHERE formid = 'CLIENT_FORM';
DELETE FROM "modelfield"  WHERE form_id = 'CLIENT_FORM';

insert into model(active, formID, title, viewname) values(true, 'CLIENT_FORM', 'Client Form', 'CrmAccount');
insert into modelfield(form_ID,     field_ID,                                   sorder, mandatory,  hide,   isCustomField,         section,                     defaultValue, widget, systemmandatory,             nolabelfor,                   nowrapperfor,            fullWidth, split) values
                      ('CLIENT_FORM', 'CRM_ACCOUNT_OWNER',                        1,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'DropDown',    false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CLIENT_SUBSIDIARIES',                      2,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'LOOKUP',      false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_NAME',                         3,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'LOOKUP',      true,                      '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_PARENT',                       4,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'LOOKUP',      false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_NUMBER',                       5,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'TextBox',     false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'PRIMARY_CONTACT',                          6,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'LOOKUP',      false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_TYPE',                         7,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'MULTITABLE',  false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CLIENT_TYPE',                              8,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'DropDown',    false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_INDUSTRY',                     9,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'DropDown',    false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_OWNERSHIP',                   10,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'DropDown',    false,                     '',                            '',                   false,   true),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_EMAIL',                       11,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'TextBox',     false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_PHONE',                       12,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'MULTITABLE',  false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_WEBSITE',                     13,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'TextBox',     false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_FAX',                         14,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'MULTITABLE',  false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_ORGANIZATION_TYPE',           15,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'DropDown',    false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_NUMBER_OF_EMPLOYEE',          16,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'DropDown',    false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_ANNUAL_REVENUE',              17,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'DropDown',    false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_RATING',                      18,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'DropDown',    false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_PAYMENT_TYPE',                19,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'UNKNOWN',     false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'PAY_FOR_NO_SHOWS',                        20,      false,   false,       false,   'CRM_ACCOUNT_INFORMATION',                  '',    'UNKNOWN',     false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_BILLING_ADDRESS',             21,      false,   false,       false,   'CRM_ACCOUNT_ADDRESS_INFORMATION',          '',    'UNKNOWN',     false,         'addForm,editForm,viewForm',               '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_SHIPPING_ADDRESS',            22,      false,   false,       false,   'CRM_ACCOUNT_ADDRESS_INFORMATION',          '',    'UNKNOWN',     false,         'addForm,editForm,viewForm',               '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_ACTIVITIES',                          23,      false,   false,       false,   'CRM_ACTIVITIES',                           '',    'UNKNOWN',     false,         'addForm,editForm,viewForm',               '',                   true,    false),
                      ('CLIENT_FORM', 'CRM_ACCOUNT_LATEST_CONTACTS',             24,      false,   false,       false,   'CRM_ACCOUNT_LATEST_CONTACTS',              '',    'UNKNOWN',     false,         'addForm,editForm,viewForm',               '',                   true,    false),
                      ('CLIENT_FORM', 'ATTACHMENTS',                             25,      false,   false,       false,   'ATTACHMENTS',                              '',    'UNKNOWN',     false,         'addForm,editForm,viewForm',               '',                   true,    false),
                      ('CLIENT_FORM', 'CLIENT_BANK_ACCOUNT',                     26,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'DropDown',    false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CURRENCY',                                27,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'DropDown',    true,                      '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'VAT_NUMBER',                              28,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'TextBox',     false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'PAYMENT_METHOD',                          29,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'DropDown',    false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'REGISTRATION_NUMBER',                     30,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'TextBox',     false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CLIENT_INVOICE_TERM',                     31,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'LOOKUP',      false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CLIENT_VAT',                              32,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'LOOKUP',      false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CLIENT_DISCOUNT',                         33,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'UNKNOWN',     false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'ACCOUNTS_RECEIVABLE_PAYABLE',             34,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'LOOKUP',      false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'GL_ACCOUNT',                              35,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'CheckBox',    false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CLIENT_AS_OF_DATE',                       36,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'DatePicker',  false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CLIENT_AMOUNT',                           37,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'TextBox',     false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CLIENT_CREDIT_LIMIT',                     38,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'TextBox',     false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CLIENT_QUOTE_CREDIT_LIMIT',               39,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'TextBox',     false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'PRICE_LEVEL',                             40,      false,   false,       false,   'CRM_ACCOUNT_FINANCIAL_INFORMATION',        '',    'UNKNOWN',     false,                     '',                            '',                   false,   false),
                      ('CLIENT_FORM', 'CRM_NOTE',                                41,      false,   false,       false,   'CRM_NOTE',                                 '',    'NoteWidget',  false,         'addForm,editForm,viewForm',               '',                   true,    false);


UPDATE modelfield set sectionStyle = 'slideDown-box  group expand hideCustomField' WHERE form_id = 'CLIENT_FORM';
UPDATE modelfield set fieldSetStyle = 'slideDown-content group labelLine' WHERE form_id = 'CLIENT_FORM';
UPDATE modelfield set fieldSetStyle = 'slideDown-content group nobrd' WHERE noLabelFor is not null AND noLabelFor != '' AND form_id = 'CLIENT_FORM';
UPDATE modelfield set halfSetStyle = 'halfSet-1 left' WHERE form_id = 'CLIENT_FORM';
UPDATE modelfield set halfSetStyle = '' WHERE noLabelFor is not null AND noLabelFor != '' AND form_id = 'CLIENT_FORM' AND section != 'CRM_ACCOUNT_ADDRESS_INFORMATION';
UPDATE modelfield set rowStyle = 'row hideCustomField' WHERE form_id = 'CLIENT_FORM';
UPDATE modelfield set fieldStyle = 'field' WHERE form_id = 'CLIENT_FORM';

DELETE FROM "anv"."model"  WHERE formid = 'CLIENT_FORM';
DELETE FROM "anv"."modelfield"  WHERE form_id = 'CLIENT_FORM';

UPDATE company SET isdeleted = FALSE WHERE isdeleted IS NULL AND (SELECT "anv".convertCustomFieldsToModelFields('CLIENT_FORM', 'CrmAccount')) IS NOT NULL;