delete  from "anv".form_property where form_id ='HRMS_EMPLOYEE_FORM';
insert into "anv".form_property (form_id, settingsjsondata)
values ('HRMS_EMPLOYEE_FORM',
        '[

  {
    "code": "FIRST_NAME",
    "title": "First name",
    "aliasName": "FIRST_NAME",
    "changed": false,
    "required": true,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false,
    "systemRequired": true
  },
  {
    "code": "LAST_NAME",
    "title": "Last Name",
    "aliasName": "LAST_NAME",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
	{
    "code": "MIDDLE_NAME",
    "title": "Middle Name",
    "aliasName": "MIDDLE_NAME",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
    {
    "code": "EMPLOYEE_CODE",
    "title": "Employee Number",
    "aliasName": "EMPLOYEE_CODE",
    "changed": false,
    "required": true,
    "widget": "AutoNumber",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false,
    "systemRequired": true
  },
  {
    "code": "BIRTH_DAY",
    "title": "Date of birth",
    "aliasName": "BIRTH_DAY",
    "changed": false,
    "required": false,
    "widget": "DatePicker",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
   },
  {
    "code": "MARTIAL_STATUS",
    "title": "Maritial Status",
    "aliasName": "MARTIAL_STATUS",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "GENDER",
    "title": "Gender",
    "aliasName": "GENDER",
    "changed": false,
    "required": false,
    "widget": "UNKNOWN",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false

  },
   {
    "code": "PAYMENT_METHOD",
    "title": "Salary Level",
    "aliasName": "PAYMENT_METHOD",
    "changed": false,
    "required": false,
    "widget": "UNKNOWN",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "PHONE",
    "title": "Phone Number",
    "aliasName": "PHONE",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "EMAIL",
    "title": "Email",
    "aliasName": "EMAIL",
    "changed": false,
    "required": true,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "TELEGRAM",
    "title": "Telegram",
    "aliasName": "TELEGRAM",
    "changed": false,
    "required": false,
    "widget": "UNKNOWN",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  } ,
   {
    "code": "NATIONALITY",
    "title": "Nationality",
    "aliasName": "NATIONALITY",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "LANGUAGE",
    "title": "Spoken Languages",
    "aliasName": "LANGUAGE",
    "changed": false,
    "required": false,
    "widget": "UNKNOWN",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "EMPLOYEE_DEGREE",
    "title": "Employee degree",
    "aliasName": "EMPLOYEE_DEGREE",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "SUPERVISOR",
    "title": "Supervisor",
    "aliasName": "SUPERVISOR",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "POSITION",
    "title": "Position",
    "aliasName": "POSITION",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "DEPARTMENT",
    "title": "Department",
    "aliasName": "DEPARTMENT",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "WAGE_RATE",
    "title": "Wage Rate",
    "aliasName": "WAGE_RATE",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "CLIENT_CHARGE_RATE",
    "title": "Customer Charge Rate",
    "aliasName": "CLIENT_CHARGE_RATE",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "PROBATION_DAYS",
    "title": "Probation Period Days",
    "aliasName": "PROBATION_DAYS",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "HIRE_DATE",
    "title": "Hire Date",
    "aliasName": "HIRE_DATE",
    "changed": false,
    "required": false,
    "widget": "DatePicker",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "RESIGNATION_DATE",
    "title": "Resignation Date",
    "aliasName": "RESIGNATION_DATE",
    "changed": false,
    "required": false,
    "widget": "UNKNOWN",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "OPENING_BALANCE_DATE",
    "title": "Opening balance Date",
    "aliasName": "OPENING_BALANCE_DATE",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "JOB_TITLE",
    "title": "Job Title",
    "aliasName": "JOB_TITLE",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "EMPLOYMENT_CONTACT_TERMS",
    "title": "Employment Contact Terms",
    "aliasName": "EMPLOYMENT_CONTACT_TERMS",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "QUALIFICATION",
    "title": "Qualification",
    "aliasName": "QUALIFICATION",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
    {
    "code": "LOCATION_FIELD",
    "title": "Location",
    "aliasName": "LOCATION_FIELD",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
    {
    "code": "EMPLOYMENT_MODE",
    "title": "Employment Mode",
    "aliasName": "EMPLOYMENT_MODE",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "PASSPORT_NUMBER",
    "title": "Passport Number",
    "aliasName": "PASSPORT_NUMBER",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "PASSPORT_ISSUE",
    "title": "Passport Issue",
    "aliasName": "PASSPORT_ISSUE",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "PASSPORT_ISSUE_DATE",
    "title": "Passport Issue Date",
    "aliasName": "PASSPORT_ISSUE_DATE",
    "changed": false,
    "required": false,
    "widget": "DatePicker",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "PASSPORT_EXPIRY_DATE",
    "title": "Passport Expiry Date",
    "aliasName": "PASSPORT_EXPIRY_DATE",
    "changed": false,
    "required": false,
    "widget": "DatePicker",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "VISA_NUMBER",
    "title": "Viza Number",
    "aliasName": "VISA_NUMBER",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "VISA_ISSUE_DATE",
    "title": "Viza Issue Date",
    "aliasName": "VISA_ISSUE_DATE",
    "changed": false,
    "required": false,
    "widget": "DatePicker",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "VISA_EXPIRATION_DATE",
    "title": "Viza Expiry Date",
    "aliasName": "VISA_EXPIRATION_DATE",
    "changed": false,
    "required": false,
    "widget": "DatePicker",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "INSURANCE_NUMBER",
    "title": "Insurance Number",
    "aliasName": "INSURANCE_NUMBER",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "INSURANCE_EXPIRY_DATE",
    "title": "Insurance Expiry Date",
    "aliasName": "INSURANCE_EXPIRY_DATE",
    "changed": false,
    "required": false,
    "widget": "DatePicker",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
   {
    "code": "VISA_EXPIRATION_DATE_REMINDER",
    "title": "Set expiry reminder",
    "aliasName": "VISA_EXPIRATION_DATE_REMINDER",
    "changed": false,
    "required": false,
    "widget": "MULTITABLE",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
    {
    "code": "BANK_NAME",
    "title": "Bank Name",
    "aliasName": "BANK_NAME",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
    {
    "code": "BANK_ADDRESS",
    "title": "Bank Address",
    "aliasName": "BANK_ADDRESS",
    "changed": false,
    "required": false,
    "widget": "TextArea",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
    {
    "code": "AGENT_ID",
    "title": "Agent id",
    "aliasName": "AGENT_ID",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
    {
    "code": "ACCOUNT_NAME",
    "title": "Account Name",
    "aliasName": "ACCOUNT_NAME",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
    {
    "code": "ACCOUNT_NUMBER",
    "title": "Account Number",
    "aliasName": "ACCOUNT_NUMBER",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
    {
    "code": "SWIFT_CODE",
    "title": "Swift/BIC code",
    "aliasName": "SWIFT_CODE",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
    {
    "code": "IBAN_CODE",
    "title": "IBAN code",
    "aliasName": "IBAN_CODE",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
    {
    "code": "SORT_CODE",
    "title": "Sort code",
    "aliasName": "SORT_CODE",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
    {
    "code": "WPS_NUMBER",
    "title": "Wps code",
    "aliasName": "WPS_NUMBER",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "SALARY_AMOUNT",
    "title": "Basic Salary",
    "aliasName": "SALARY_AMOUNT",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  }
]');