package com.edatasite.workforce.gwt.profile.client.ui.view.accounting;

import com.edatasite.workforce.gwt.accounting.client.rpc.FinancialSettingsItem;
import com.edatasite.workforce.gwt.core.client.Utils;
import com.edatasite.workforce.gwt.core.client.Validation;
import com.edatasite.workforce.gwt.core.client.localization.WfmStrings;
import com.edatasite.workforce.gwt.core.client.rpc.DateNonConvertable;
import com.edatasite.workforce.gwt.core.client.ui.DataListBox;
import com.edatasite.workforce.gwt.core.client.ui.DatePicker;
import com.edatasite.workforce.gwt.core.client.ui.components.KpiCheckBox;
import com.edatasite.workforce.gwt.core.client.ui.components.KpiCustomToolTip;
import com.edatasite.workforce.gwt.core.client.ui.components.form.GColumn;
import com.edatasite.workforce.gwt.core.client.ui.components.form.GColumnEnum;
import com.edatasite.workforce.gwt.core.client.ui.notifications.Info;
import com.google.gwt.core.client.GWT;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.client.Command;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.Widget;
import gwt.material.design.client.ui.MaterialLink;
import gwt.material.design.client.ui.html.Div;
import gwt.material.design.client.ui.html.Span;

public class GccVatSettingsWidget extends VATSettingsWidget {
    @UiField
    Span vatRegisteredOnLabel;

    private static final UAEVATSettingsWidgetUiBinder uiBinder = GWT.create(UAEVATSettingsWidgetUiBinder.class);

    @UiField
    KpiCheckBox vatRegistered;
    @UiField
    Span trnLabel;
    @UiField
    TextBox txtTaxIdDisplayName;
    @UiField
    TextBox txtTaxIdNumber;
    private final String uaeVATSettingsWidget = "uaeVATSettingsWidget";
    @UiField
    Span tinLabel;
    @UiField
    TextBox txtTinDisplayName;   /// this fields tinLabel,txtTinDisplayName, txtTinIdNumber for Saudi companies
    @UiField
    TextBox txtTinIdNumber;
    @UiField
    TextBox otpCode;   /// this code nrrd to provide by tax payer from Footora portal
    @UiField
    MaterialLink validateTIN;
    @UiField
    Span reverseChargeLabel;
    @UiField
    KpiCheckBox reverseCharge;
    @UiField
    Span generateDateLabel;
    @UiField
    Div taxGenerateDateContainer;
    @UiField
    Span taxPeriodLabel;
    @UiField
    Div taxPeriodContainer;
    @UiField
    Div vatRegisteredOnContainer;
    @UiField
    HTMLPanel pnlContainer;
    @UiField
    HTMLPanel pnlVatConfigContainer;
    private DatePicker vatRegisteredOn;

    public GccVatSettingsWidget() {
    }

    @Override
    protected Widget getMainWidget() {
        return uiBinder.createAndBindUi(this);
    }

    private DatePicker firstTaxReturnFrom;
    private DataListBox taxPeriodList;
    @UiField
    MaterialLink validateTaxId;

    @Override
    protected void initialize() {
        vatRegistered.setText(accountingStrings.vatRegistered());
        trnLabel.setText(wfmStrings.trn());
        vatRegistered.addValueChangeHandler(vch -> {
            setFieldsVisibality(vatRegistered.getValue());
        });

        txtTaxIdNumber.ensureDebugId(uaeVATSettingsWidget + "taxIDNumber");
        Validation.addNumericKeyboardListener(txtTaxIdNumber);

        txtTaxIdDisplayName.ensureDebugId(uaeVATSettingsWidget + "taxIDDisplayNumber");

        if (Utils.isSaudiCompany()) {
            tinLabel.setText(accountingStrings.companyTin());
            txtTinIdNumber.ensureDebugId("saVATSettingsWidget " + "txtTinIdNumber");
            Validation.addNumericKeyboardListener(txtTinIdNumber);
            txtTinDisplayName.ensureDebugId("saVATSettingsWidget " + "txtTinDisplayName");
            otpCode.setPlaceHolder("OTP number should be 6 digit number generated by Footora portal");
            validateTIN.setText("Recreate certificate for zatca");
        }
        validateTaxId.setVisible(Utils.isSaudiCompany());
        validateTaxId.setText("Validate TRN");
        validateTaxId.setHref("https://eservices.tax.gov.ae/en-us/trn-verify");
        validateTaxId.setTarget("_blank");
        validateTaxId.setVisible(Utils.isUAECompany());

        reverseChargeLabel.setText(accountingStrings.internationalTrade());
        reverseCharge.setText("Enable trade with contacts outside " + Utils.getUserCountry());

        vatRegisteredOnLabel.setText(accountingStrings.vatRegisteredOn());
        vatRegisteredOn = new DatePicker();
        vatRegisteredOnContainer.add(new GColumn(GColumnEnum.COL_2, vatRegisteredOn));

        generateDateLabel.setText(accountingStrings.firstTaxReturnFrom());
        generateDateLabel.add(new KpiCustomToolTip(accountingStrings.descriptionFirstTaxReturnFrom()));
        firstTaxReturnFrom = new DatePicker();
        taxGenerateDateContainer.add(new GColumn(GColumnEnum.COL_2, firstTaxReturnFrom));

        taxPeriodLabel.setText(settingsStrings.taxPeriod());
        taxPeriodList = new DataListBox();
        taxPeriodContainer.add(new GColumn(GColumnEnum.COL_2, taxPeriodList));
    }

    public void initSpecificSettings(Command command) {
        validateTIN.addClickHandler(handler -> {
            if (command != null) {
                command.execute();
            }
        });
    }

    @Override
    public void fillSettings(FinancialSettingsItem settingsItem) {
        taxPeriodList.setItems(settingsItem.getTaxPeriods());
        vatRegistered.setValue(settingsItem.getVatRegistered());
        txtTaxIdDisplayName.setText(settingsItem.getTaxIdDisplayNumber());
        txtTaxIdNumber.setText(settingsItem.getTaxIdNumber());
        reverseCharge.setValue(settingsItem.isEnableContractOutsite());
        txtTinIdNumber.setText(settingsItem.getTinNumber());
        txtTinDisplayName.setText(settingsItem.getTinDisplayName());
        validateTIN.setVisible("ACTIVE".equalsIgnoreCase(settingsItem.getCsrStatus()));
        otpCode.setVisible(true);

        if (settingsItem.getVatRegisteredOn() != null) {
            vatRegisteredOn.setDate(settingsItem.getVatRegisteredOn().getDate());
        }
        if (settingsItem.getTaxGenerationDate() != null) {
            firstTaxReturnFrom.setDate(settingsItem.getTaxGenerationDate().getDate());
        }
        if (settingsItem.getTaxPeriodId() != null) {
            taxPeriodList.setSelected(settingsItem.getTaxPeriodId());
        }
        setFieldsVisibality(settingsItem.getVatRegistered());
    }

    @Override
    public FinancialSettingsItem getSettingsData(FinancialSettingsItem settingsItem) {

        if (settingsItem == null) {
            settingsItem = new FinancialSettingsItem();
        }
        settingsItem.setVatRegistered(vatRegistered.getValue());
        settingsItem.setTaxPeriodId(taxPeriodList.getSelectedId());
        settingsItem.setTaxIdDisplayNumber(txtTaxIdDisplayName.getText());
        settingsItem.setTaxIdNumber(txtTaxIdNumber.getValue());
        settingsItem.setTinDisplayName(txtTinDisplayName.getText());
        settingsItem.setTinNumber(txtTinIdNumber.getText());
        settingsItem.setOtpNumber(otpCode.getText());
        settingsItem.setEnableContractOutsite(reverseCharge.getValue());
        settingsItem.setVatRegisteredOn(new DateNonConvertable(vatRegisteredOn.getDate()));
        settingsItem.setTaxGenerationDate(new DateNonConvertable(firstTaxReturnFrom.getDate()));
        return settingsItem;
    }

    @Override
    public boolean validate() {
        int errors = 0;

        if (vatRegistered.getValue()) {

            if (!Validation.validateTextBoxRequired(txtTaxIdDisplayName)) {
                errors++;
            }
            if (!Validation.validateDate(vatRegisteredOn)) {
                errors++;
            }
            if (!Validation.validateDate(firstTaxReturnFrom)) {
                errors++;
            }
            if (!Validation.validateTextBoxRequired(txtTaxIdNumber)) {
                errors++;
            } else if (txtTaxIdNumber.getValue().length() != 15) {
                Info.show(WfmStrings.App.get().trnNumberErrorMessage(), Info.Type.WARNING);
                return false;
            }
            if (Utils.isSaudiCompany()) {
//                if (!Validation.validateTextBoxRequired(txtTinIdNumber)) {
//                    errors++;
//                } else if (txtTinIdNumber.getValue().length() != 10) {
//                    Info.show(accountingStrings.tinNumberErrorMessage(), Info.Type.WARNING);
//                    return false;
//                }
                if (!Validation.validateTextBoxRequired(txtTinIdNumber)) {
                    errors++;
                } else if (txtTinIdNumber.getValue().length() != 10) {
                    Info.show(accountingStrings.tinNumberErrorMessage(), Info.Type.WARNING);
                    return false;
                }
            }

            if (vatRegisteredOn.getDate() != null && firstTaxReturnFrom.getDate() != null) {

                if (firstTaxReturnFrom.getDate().before(vatRegisteredOn.getDate())) {
                    Info.show("Wrong date range!", Info.Type.WARNING);
                    return false;
                }
            }

            /*if (errors == 0 && firstTaxReturnFrom.getDate().compareTo(DateUtil.resetTime(new Date())) < 0) {
                Info.show("", Info.Type.WARNING);
                return false;
            }*/
        }

        return errors == 0;
    }

    private void setFieldsVisibality(boolean visible) {
        pnlContainer.clear();

        if (visible) {
            pnlContainer.add(pnlVatConfigContainer);
        }
    }

    interface UAEVATSettingsWidgetUiBinder extends UiBinder<HTMLPanel, GccVatSettingsWidget> {
    }
}
