
delete from "0".customformsection where form_id='PROJECT_FORM';
INSERT INTO "0".customformsection (active, custom, form_id, section, sorder) VALUES (true, false, 'PROJECT_FORM', 'DETAILS', 0);
INSERT INTO "0".customformsection (active, custom, form_id, section, sorder) VALUES (true, false, 'PROJECT_FORM', 'INVOLVED_EMPLOYEES', 1);
INSERT INTO "0".customformsection (active, custom, form_id, section, sorder) VALUES (true, false, 'PROJECT_FORM', 'MORE_DETAILS', 2);
INSERT INTO "0".customformsection (active, custom, form_id, section, sorder) VALUES (false, false, 'PROJECT_FORM', 'TASK_DETAILS', 3);
INSERT INTO "0".customformsection (active, custom, form_id, section, sorder) VALUES (true, false, 'PROJECT_FORM', 'ATTACHMENTS', 4);
INSERT INTO "0".customformsection (active, custom, form_id, section, sorder) VALUES (false, false, 'PROJECT_FORM', 'LINKS', 5);
INSERT INTO "0".customformsection (active, custom, form_id, section, sorder) VALUES (true, false, 'PROJECT_FORM', 'PROJECT_NOTE', 6);
INSERT INTO "0".customformsection (active, custom, form_id, section, sorder) VALUES (false, false, 'PROJECT_FORM', 'PROJECT_CHARTS', 7);
INSERT INTO "0".customformsection (active, custom, form_id, section, sorder) VALUES (true, false, 'PROJECT_FORM', 'UPDATES', 8);
INSERT INTO "0".customformsection (active, custom, form_id, section, sorder) VALUES (false, false, 'PROJECT_FORM', 'LOGGED_TIME_DETAILS', 9);
INSERT INTO "0".customformsection (active, custom, form_id, section, sorder) VALUES (true, false, 'PROJECT_FORM', 'ADDITIONAL_INFORMATION', 11);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'DETAILS', 'CONTRACT', 4, 'COL_2', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'DETAILS', 'PDF_VERSION', 1000, 'COL_3', true, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'DETAILS', 'CLIENT_RETAINER', 1000, 'COL_1', true, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'DETAILS', 'COMPLETED', 1, 'COL_3', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'ACTUAL_START_DATE', 1, 'COL_1', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'ACTUAL_END_DATE', 2, 'COL_1', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'ACTUAL_COST', 3, 'COL_1', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'WAITING_HOURS', 0, 'COL_2', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'REJECTED_HOURS', 1, 'COL_2', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'ESTIMATED_COST', 2, 'COL_2', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'ESTIMATED_TIME', 0, 'COL_3', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'TIME_SPENT', 1, 'COL_3', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'PROJECT_CHARTS', 'PROJECT_CHART', 0, 'COL_1', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'TASK_DETAILS', 'CLOSED_TASKS', 1, 'COL_3', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'TASK_DETAILS', 'WAITING_FOR_SOMEONE_ELSE', 1, 'COL_2', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'TASK_DETAILS', 'CANCELLED_TASKS', 0, 'COL_3', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'TASK_DETAILS', 'IN_PORGRESS_TASKS', 0, 'COL_2', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'TASK_DETAILS', 'COMPLETED_TASKS', 1, 'COL_1', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'TASK_DETAILS', 'NOT_STARTED_TASKS', 0, 'COL_1', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'UPDATES', 'CREATED_BY', 1, 'COL_1', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'UPDATES', 'CREATED_DATE', 0, 'COL_1', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'UPDATES', 'UPDATED_BY', 1, 'COL_2', false, false);
insert into "0".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'UPDATES', 'UPDATED_DATE', 0, 'COL_2', false, false);
update "0".modelfield set nolabelfor='addForm,editForm,viewForm', nowrapperfor='addForm,editForm,viewForm' where form_id='PROJECT_FORM' and field_id in ('ATTACHMENTS', 'INVOLVED_EMPLOYEE');



delete from "anv".customformsection where form_id='PROJECT_FORM';
INSERT INTO "anv".customformsection (active, custom, form_id, section, sorder) VALUES (true, false, 'PROJECT_FORM', 'DETAILS', 0);
INSERT INTO "anv".customformsection (active, custom, form_id, section, sorder) VALUES (true, false, 'PROJECT_FORM', 'INVOLVED_EMPLOYEES', 1);
INSERT INTO "anv".customformsection (active, custom, form_id, section, sorder) VALUES (true, false, 'PROJECT_FORM', 'MORE_DETAILS', 2);
INSERT INTO "anv".customformsection (active, custom, form_id, section, sorder) VALUES (false, false, 'PROJECT_FORM', 'TASK_DETAILS', 3);
INSERT INTO "anv".customformsection (active, custom, form_id, section, sorder) VALUES (true, false, 'PROJECT_FORM', 'ATTACHMENTS', 4);
INSERT INTO "anv".customformsection (active, custom, form_id, section, sorder) VALUES (false, false, 'PROJECT_FORM', 'LINKS', 5);
INSERT INTO "anv".customformsection (active, custom, form_id, section, sorder) VALUES (true, false, 'PROJECT_FORM', 'PROJECT_NOTE', 6);
INSERT INTO "anv".customformsection (active, custom, form_id, section, sorder) VALUES (false, false, 'PROJECT_FORM', 'PROJECT_CHARTS', 7);
INSERT INTO "anv".customformsection (active, custom, form_id, section, sorder) VALUES (true, false, 'PROJECT_FORM', 'UPDATES', 8);
INSERT INTO "anv".customformsection (active, custom, form_id, section, sorder) VALUES (false, false, 'PROJECT_FORM', 'LOGGED_TIME_DETAILS', 9);
INSERT INTO "anv".customformsection (active, custom, form_id, section, sorder) VALUES (true, false, 'PROJECT_FORM', 'ADDITIONAL_INFORMATION', 11);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'DETAILS', 'CONTRACT', 4, 'COL_2', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'DETAILS', 'PDF_VERSION', 1000, 'COL_3', true, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'DETAILS', 'CLIENT_RETAINER', 1000, 'COL_1', true, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'DETAILS', 'COMPLETED', 1, 'COL_3', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'ACTUAL_START_DATE', 1, 'COL_1', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'ACTUAL_END_DATE', 2, 'COL_1', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'ACTUAL_COST', 3, 'COL_1', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'WAITING_HOURS', 0, 'COL_2', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'REJECTED_HOURS', 1, 'COL_2', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'ESTIMATED_COST', 2, 'COL_2', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'ESTIMATED_TIME', 0, 'COL_3', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'MORE_DETAILS', 'TIME_SPENT', 1, 'COL_3', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'PROJECT_CHARTS', 'PROJECT_CHART', 0, 'COL_1', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'TASK_DETAILS', 'CLOSED_TASKS', 1, 'COL_3', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'TASK_DETAILS', 'WAITING_FOR_SOMEONE_ELSE', 1, 'COL_2', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'TASK_DETAILS', 'CANCELLED_TASKS', 0, 'COL_3', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'TASK_DETAILS', 'IN_PORGRESS_TASKS', 0, 'COL_2', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'TASK_DETAILS', 'COMPLETED_TASKS', 1, 'COL_1', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'TASK_DETAILS', 'NOT_STARTED_TASKS', 0, 'COL_1', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'UPDATES', 'CREATED_BY', 1, 'COL_1', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'UPDATES', 'CREATED_DATE', 0, 'COL_1', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'UPDATES', 'UPDATED_BY', 1, 'COL_2', false, false);
insert into "anv".modelfield (form_id, fsection, field_id, forder, columntype, hide, hideincustomizeform) values('PROJECT_FORM', 'UPDATES', 'UPDATED_DATE', 0, 'COL_2', false, false);
update "anv".modelfield set nolabelfor='addForm,editForm,viewForm', nowrapperfor='addForm,editForm,viewForm' where form_id='PROJECT_FORM' and field_id in ('ATTACHMENTS', 'INVOLVED_EMPLOYEE');