UPDATE permission set sorder=null where ismainmenu=true;
UPDATE permission set sorder=1 WHERE code='WORKSPACE_MAIN_MENU';
UPDATE permission set sorder=2,name='Accounts' WHERE code='ACCOUNTING_MAIN_MENU';
UPDATE permission set sorder=3,name='Humans' WHERE code='HRMS_MAIN_MENU';
UPDATE permission set sorder=4,name='Sales' WHERE code='CRM_MAIN_MENU';
UPDATE permission set sorder=5,name='Projects' WHERE code='PM_MAIN_MENU';
UPDATE permission set sorder=6 WHERE code='PAYROLL_MAIN_MENU';
UPDATE permission set sorder=7 WHERE code='DOCUMENTS_MAIN_MENU';
UPDATE permission set sorder=8,name='Reports' WHERE code='REPORTING_MAIN_MENU';
UPDATE permission set sorder=9 WHERE code='MYACCOUNT_MAIN_MENU';
UPDATE permission set sorder=10 WHERE code='SETTINGS_MAIN_MENU';
UPDATE permission set sorder=11 WHERE code='DASHBOARD_MAIN_MENU';
UPDATE permission set sorder=12 WHERE code='PM_LOCATION_LIST' and ismainmenu=true;
UPDATE permission set sorder=13 WHERE code='NOTES_WIDGET' and ismainmenu=true;
UPDATE permission set sorder=14 WHERE code='TC_MAIN_MENU';
UPDATE permission set sorder=15 WHERE code='LOGISTICS_MAIN_MENU';

UPDATE permission set name='Accounts Menu' where code='ACCOUNTING_ACCOUNTING_MENU';
UPDATE permission set name='Accounts Add-ons' where code='ACCOUNTING_ADD_ON_SETTINGS';
UPDATE permission set name='Accounts Settings' where code='SETTINGS_ACCOUNTING_SETTINGS';

UPDATE permission set name='Humans home tab' where code='HRMS_SECTION_TAB';
UPDATE permission set name='Humans Employee Steps' where code='HRMS_EMPLOYEE_STEPS';
UPDATE permission set name='Humans Settings' where code='SETTINGS_HRMS_SETTINGS';
UPDATE permission set name='Humans Welcome' where code='HRMS_MAIN_SECTION';
UPDATE permission set name='Humans see all department list' where code='HRMS_SEE_ALL_DEPARTMENT_LIST';
UPDATE permission set name='Humans appraisals archive list' where code='HRMS_APPRAISALS_ARCHIVE';
UPDATE permission set name='Humans employee notes view' where code='HRMS_PROFILE_NOTE';
UPDATE permission set name='Humans New Employee 360 appraisals' where code='HRMS_NEW_EMPLOYEE_360_APPRAISALS';
UPDATE permission set name='Humans Add Links' where code='HRMS_GOAL_LINKS';
UPDATE permission set name='Humans Position Summary' where code='HRMS_POSITION_SUMMARRY';
UPDATE permission set name='Humans Employee Steps' where code='HRMS_EMPLOYEE_STEPS';
UPDATE permission set name='Humans Expense Void' where code='HRMS_EXPENSE_REPORT_VOID';


update permission set name='Sales' where code='CRM_MAIN_MENU';
update permission set name='Sales tab' where code='CRM_SALES_TAB';
update permission set name='Sales Add New Opportunity' where code='CRM_ADD_NEW_OPPORTUNITIES';
update permission set name='Sales Edit Opportunity' where code='CRM_EDIT_OPPORTUNITIES';
update permission set name='Sales Settings' where code='SETTINGS_CRM_SETTINGS';
update permission set name='Sales Edit Contact' where code='CRM_EDIT_CONTACT';
update permission set name='Sales CRM Contact' where code='WORKSPACE_CONTACTS_ADD';
update permission set name='Sales Add New Log a Call' where code='CRM_ADD_NEW_ACTIVITY_LOG_A_CALL';
update permission set name='Sales Edit Activity' where code='CRM_EDIT_ACTIVITY';
update permission set name='Sales Remove Activity' where code='CRM_REMOVE_ACTIVITY';
update permission set name='Sales Remove Contact' where code='CRM_REMOVE_CONTACT';
update permission set name='Sales Copy Case' where code='CRM_COPY_CASE';
update permission set name='Sales Solutions list' where code='CRM_SOLUTIONS_LIST';
update permission set name='Sales Edit Solution' where code='CRM_EDIT_SOLUTION';
update permission set name='Sales Remove Solution' where code='CRM_REMOVE_SOLUTION';
update permission set name='Sales Remove Opportunity' where code='CRM_REMOVE_OPPORTUNITIES';
update permission set name='Sales Add New Contact' where code='CRM_ADD_NEW_CONTACT';
update permission set name='Sales Contact Look Up' where code='CRM_CONTACT_LOOK_UP';
update permission set name='Sales Add New Category' where code='CRM_ADD_NEW_CATEGORY';
update permission set name='Sales Copy To Category' where code='CRM_COPY_TO_CATEGORY';
update permission set name='Sales Move To Category' where code='CRM_MOVE_TO_CATEGORY';
update permission set name='Sales Add New Campaign' where code='CRM_ADD_NEW_CAMPAIGN';
update permission set name='Sales Edit Campaign' where code='CRM_EDIT_CAMPAIGN';
update permission set name='Sales Remove Campaign' where code='CRM_REMOVE_CAMPAIGN';
update permission set name='Sales Add New Event' where code='CRM_ADD_NEW_ACTIVITY_EVENT';
update permission set name='Sales Calendar' where code='CRM_Calendar';
update permission set name='Sales Edit Category' where code='CRM_EDIT_CATEGORY';
update permission set name='Sales Share Category' where code='CRM_SHARE_CATEGORY';
update permission set name='Sales Remove Category' where code='CRM_REMOVE_CATEGORY';
update permission set name='Sales' where code='WORKSPACE_WIDGET_CATEGORY_CRM';
update permission set name='Sales Online Training List' where code='EMPLOYEE_STEP_CRM_ONLINE_TRAINING_LIST_65437';
update permission set name='Sales Online Training Add' where code='EMPLOYEE_STEP_CRM_ONLINE_TRAINING_ADD_65437';
update permission set name='Sales Online Training Edit' where code='EMPLOYEE_STEP_CRM_ONLINE_TRAINING_EDIT_65437';
update permission set name='Sales Online Training Delete' where code='EMPLOYEE_STEP_CRM_ONLINE_TRAINING_DELETE_65437';
update permission set name='Sales Online Training Export' where code='EMPLOYEE_STEP_CRM_ONLINE_TRAINING_EXPORT_65437';
update permission set name='Sales Welcome' where code='CRM_WELCOME_PAGE';
update permission set name='Sales Add New Web Form' where code='CRM_ADD_NEW_WEB_FORM';
update permission set name='Sales Edit Web Form' where code='CRM_EDIT_WEB_FORM';
update permission set name='Sales Remove Web Form' where code='CRM_REMOVE_WEB_FORM';
update permission set name='Sales Message Remove' where code='CRM_MESSAGE_REMOVE';
update permission set name='Sales Cases list' where code='CRM_CASES_LIST';
update permission set name='Sales Edit Case' where code='CRM_EDIT_CASE';
update permission set name='Sales Remove Case' where code='CRM_REMOVE_CASE';
update permission set name='Sales Change Status Case' where code='CRM_CHANGE_STATUS_CASE';
update permission set name='Sales Change Priority Case' where code='CRM_CHANGE_PRIORITY_CASE';
update permission set name='Sales Change Assignee Case' where code='CRM_CHANGE_ASSIGNEE_CASE';
update permission set name='Sales Message Edit' where code='CRM_MESSAGE_EDIT';
update permission set name='Sales Update Statistic in Sent Message' where code='CRM_UPDATE_STATISTIC_IN_SENT_MESSAGE';
update permission set name='Sales Track Messages in Sent Message' where code='CRM_TRACK_MESSAGES_IN_SENT_MESSAGE';
update permission set name='Sales Add New Message' where code='CRM_ADD_NEW_MESSAGE';
update permission set name='Sales Queued Messages List' where code='CRM_QUEUED_MESSAGES_LIST';
update permission set name='Sales Sent Messages List' where code='CRM_SENT_MESSAGES_LIST';
update permission set name='Sales Draft Messages List' where code='CRM_DRAFT_MESSAGES_LIST';
update permission set name='Sales Close Case' where code='CRM_CLOSE_CASE';
update permission set name='Sales Convert To Case' where code='CRM_CONVERT_TO_CASE';
update permission set name='Sales Message Center' where code='CRM_MESSAGE_CENTER';
update permission set name='Sales Remove Mailing List' where code='CRM_REMOVE_MAILING_LIST';
update permission set name='Sales Edit Mailing List' where code='CRM_EDIT_MAILING_LIST';
update permission set name='Sales Mailing List' where code='CRM_MAILING_LIST';
update permission set name='Sales E-mail Marketing tab' where code='CRM_E_MAIL_MARKETING_TAB';