delete from "anv".modelfield where form_id in ('ACCOUNT_FORM','CLIENT_FORM','SUPPLIER_FORM') and field_id in ('CRM_ACCOUNT_OWNERSHIP','CRM_ACCOUNT_ORGANIZATION_TYPE',
'CRM_ACCOUNT_NUMBER_OF_EMPLOYEE','CRM_ACCOUNT_ANNUAL_REVENUE','CRM_ACCOUNT_RATING','CRM_ACCOUNT_PAYMENT_TYPE','PAY_FOR_NO_SHOWS');
delete from "0".modelfield where form_id in ('ACCOUNT_FORM','CLIENT_FORM','SUPPLIER_FORM') and field_id in ('CRM_ACCOUNT_OWNERSHIP','CRM_ACCOUNT_ORGANIZATION_TYPE',
'CRM_ACCOUNT_NUMBER_OF_EMPLOYEE','CRM_ACCOUNT_ANNUAL_REVENUE','CRM_ACCOUNT_RATING','CRM_ACCOUNT_PAYMENT_TYPE','PAY_FOR_NO_SHOWS');
delete from modelfield where form_id in ('ACCOUNT_FORM','CLIENT_FORM','SUPPLIER_FORM') and field_id in ('CRM_ACCOUNT_OWNERSHIP','CRM_ACCOUNT_ORGANIZATION_TYPE',
'CRM_ACCOUNT_NUMBER_OF_EMPLOYEE','CRM_ACCOUNT_ANNUAL_REVENUE','CRM_ACCOUNT_RATING','CRM_ACCOUNT_PAYMENT_TYPE','PAY_FOR_NO_SHOWS');

delete from "anv".modelfield where form_id in ('CONTACT_FORM','LEAD_FORM','CANDIDATE_FORM') and field_id in ('CRM_ACCOUNT_ORGANIZATION_TYPE','CRM_ACCOUNT_ANNUAL_REVENUE',
'CRM_ACCOUNT_NUMBER_OF_EMPLOYEE','CRM_ACCOUNT_OWNERSHIP');
delete from "0".modelfield where form_id in ('CONTACT_FORM','LEAD_FORM','CANDIDATE_FORM') and field_id in ('CRM_ACCOUNT_ORGANIZATION_TYPE','CRM_ACCOUNT_ANNUAL_REVENUE',
'CRM_ACCOUNT_NUMBER_OF_EMPLOYEE','CRM_ACCOUNT_OWNERSHIP');
delete from modelfield where form_id in ('CONTACT_FORM','LEAD_FORM','CANDIDATE_FORM') and field_id in ('CRM_ACCOUNT_ORGANIZATION_TYPE','CRM_ACCOUNT_ANNUAL_REVENUE',
'CRM_ACCOUNT_NUMBER_OF_EMPLOYEE','CRM_ACCOUNT_OWNERSHIP');
