MODULE_NAME_HR=HR
MODULE_NAME_PM=PM
MODULE_NAME_CRM=CRM
MODULE_NAME_ACCOUNTING=Accounting
MODULE_NAME_PAYROLL=Payroll
MODULE_NAME_WORKSPACE=My Workspace
YOU_HAVE_NOTIFICATIONS=You have {0} notifications
# Category
LeaveRequests=Leave
TimeSheetApproval=Timesheet
ExpenseClaim=Expense
GoogleCalendarEvent=Calendar
TaskDueReminder=Task due
ProjectDueReminder=Project due
MEETING_MINUTES=Meeting assignments
MeetingMinutesNotification=Meeting
BenefitRequest=Benefit
BENEFIT_REQUEST=Benefit requests
WorkstreamDueReminder=Workstream due
CRMCase=CRM Cases
TimeSheetDueReminder=Timesheet due
InvoiceDueReminder=Invoice due
TaskAssignee=Task assignees
LeadAssignee=Lead assignees
SaleInvoiceApproval=Sale invoice
CRMContact=CRM contacts
Employee=Employees
ProjectApproval=Project
CrmOpportunity=Crm Opportunity
CashAdvance=Cash Advance
CashAdvance_WAIT_APPROVAL_LONG=Cash Advance is waiting for approval
CashAdvance_WAIT_APPROVAL=Cash advance is waiting for approval
CashAdvance_APPROVED_LONG=Your cash advance has been approved
CashAdvance_APPROVED=Your cash advance has been approved
CashAdvance_REJECTED_LONG=Your cash advance has been rejected
CashAdvance_REJECTED=Your cash advance has been rejected
OnboardingStep=Onboarding Step
OnboardingStep_WAIT_APPROVAL_LONG={0} is waiting for approval
OnboardingStep_WAIT_APPROVAL={0} is waiting for approval
OnboardingStep_APPROVED_LONG=Your {0} has been approved
OnboardingStep_APPROVED=Your {0} has been approved
OnboardingStep_REJECTED_LONG=Your {0} has been rejected
OnboardingStep_REJECTED=Your {0} has been rejected
# Leave Request
LeaveRequests_WAIT_APPROVAL= Leave request is waiting for approval
LeaveRequests_APPROVED=Your leave request has been approved
LeaveRequests_DENIED=Your leave request has been denied
LeaveRequests_WAIT_APPROVAL_LONG=Leave request is waiting for approval
LeaveRequests_APPROVED_LONG=Your leave request has been approved
LeaveRequests_DENIED_LONG=Your leave request has been denied
# Time Sheet approval
TimeSheetApproval_WAIT_APPROVAL=Timesheet hours have been submitted for your review
TimeSheetApproval_APPROVED=Your timesheet hours have been reviewed
TimeSheetApproval_REJECTED=Your timesheet hours have been rejected
TimeSheetApproval_WAIT_APPROVAL_LONG=Timesheet hours have been submitted for your review
TimeSheetApproval_APPROVED_LONG=Your timesheet hours have been reviewed
TimeSheetApproval_REJECTED_LONG=Your timesheet hours have been rejected
# Expense Claim
ExpenseClaim_WAIT_APPROVAL=Expense claim is waiting for your approval
ExpenseClaim_APPROVED=Your expense claim has been approved
ExpenseClaim_DECLINE=Your expense claim has been denied
ExpenseClaim_REMOVE= Your expense claim has been removed
ExpenseClaim_WAIT_APPROVAL_LONG= Expense claim is waiting for your approval
ExpenseClaim_APPROVED_LONG= Your expense claim has been approved
ExpenseClaim_DECLINE_LONG= Your expense claim has been denied
ExpenseClaim_REMOVE_LONG=Your expense claim has been removed
# Event
GoogleCalendarEvent_EVENT=Google calendar event has been added
GoogleCalendarEvent_EVENT_LONG=Google calendar event has been added
# Task
TaskDueReminder_TASK_REMINDER=Task due reminder
TaskDueReminder_TASK_REMINDER_LONG=Task due reminder
# Project
ProjectDueReminder_PROJECT_REMINDER=Project due reminder
ProjectDueReminder_PROJECT_REMINDER_LONG=Project due reminder
# Meeting
MeetingMinutesNotification_MEETING_MINUTES=Meeting Minutes Notification
MeetingMinutesNotification_MEETING_MINUTES_LONG=Meeting Minutes Notification
# Benefit Request
BenefitRequest_WAIT_APPROVAL=Benefit request is waiting for approval
BenefitRequest_APPROVED=Your benefit request has been approved
BenefitRequest_REJECTED= Your benefit request has been rejected
BenefitRequest_WAIT_APPROVAL_LONG= Benefit request is waiting for approval
BenefitRequest_APPROVED_LONG= Your benefit request has been approved
BenefitRequest_REJECTED_LONG= Your benefit request has been rejected
# Workstream
WorkstreamDueReminder_WORKSTREAM_REMINDER=Workstream due reminder
WorkstreamDueReminder_WORKSTREAM_REMINDER_LONG=Workstream due reminder
# Crm case
CRMCase_ASSIGNED=You are assigned to the case {0}
CRMCase_ASSIGNED_LONG= You are assigned to the case {0}
# Time Sheet due reminder
TimeSheetDueReminder_TIMESHEET_REMINDER=Timesheet due date reminder {0}
TimeSheetDueReminder_TIMESHEET_REMINDER_LONG=Timesheet date e-mail reminder {0}
# Invoice due date reminder
InvoiceDueReminder_INVOICE_REMINDER=Invoice due date reminder {0}
InvoiceDueReminder_INVOICE_REMINDER_LONG=Invoice due date reminder {0}
# Task assignee
TaskAssignee_ASSIGNED=You are assigned to task {0}
TaskAssignee_ASSIGNED_LONG= You are assigned to task {0}
# Lead assignee
LeadAssignee_ASSIGNED=You are assigned to lead {0}
LeadAssignee_ASSIGNED_LONG=You are assigned to lead {0}
# SaleInvoice approvals
SaleInvoiceApproval_APPROVED=Sale invoice has been approved {0}
SaleInvoiceApproval_APPROVED_LONG= Sale invoice has been approved {0}
# Project approvals
ProjectApproval_APPROVED=Client has approved graphic design for {0}
ProjectApproval_APPROVED_LONG=Client has approved graphic design for {0}
ProjectApproval_REJECTED=Client has rejected graphic design for {0}
ProjectApproval_REJECTED_LONG=Client has rejected graphic design for {0}
PurchaseOrder = Purchase Order
Candidate = Candidate
SalesQuote=Sales Quote
SalesQuote_WAIT_APPROVAL=Sales Quote is waiting for approval
SalesQuote_WAIT_APPROVAL_LONG=Sales Quote is waiting for approval
SalesOrder_WAIT_APPROVAL=Sales Order is waiting for approval
SalesOrder_WAIT_APPROVAL_LONG=Sales Order is waiting for approval