package com.edatasite.workforce.gwt.core.client.rpc.itemtablesettings;

/**
 * Created by Normurod on 3/23/2017.
 */
public enum ItemTableEnum {
    SALE_INVOICE_ITEM("SALE_INVOICE_ITEM"),
    SALE_ORDER_ITEM("SALE_ORDER_ITEM"),
    SALE_QUOTE_ITEM("SALE_QUOTE_ITEM"),
    CREDIT_NOTE_ITEM("CREDIT_NOTE_ITEM"),
    DEBIT_NOTE_ITEM("DEBIT_NOTE_ITEM"),
    PURCHASE_INVOICE_ITEM("PURCHASE_INVOICE_ITEM"),
    PURCHASE_ORDER_ITEM("PURCHASE_ORDER_ITEM"),
    OPPORTUNITY_SUB_ITEM("OPPORTUNITY_SUB_ITEM"),
    RENTAL_ORDER_ITEM("RENTAL_ORDER_ITEM"),
    BILL_OF_MATERIALS_ITEM("BILL_OF_MATERIALS_ITEM"),
    EXPENSE_CLAIM_ITEM("EXPENSE_CLAIM_ITEM"),
    RFQ_ITEM("RFQ_ITEM"),
    RFP_ITEM("RFP_ITEM"),
    CLIENT_ITEM("CLIENT_ITEM"),
    SUPPLIER_ITEM("SUPPLIER_ITEM"),
    CUSTOM_FORM("CUSTOM_FORM"),
    OPPORTUNITY_CUSTOM_ITEM("OPPORTUNITY_CUSTOM_ITEM"),
    PROJECT_CUSTOM_ITEM("PROJECT_CUSTOM_ITEM"),
    EMPLOYEE_CUSTOM_ITEM("EMPLOYEE_CUSTOM_ITEM"),
    CLIENT_FORM_ATTACHMENTS("CLIENT_FORM_ATTACHMENTS"),
    PRODUCT_ATTACHMENTS("PRODUCT_ATTACHMENTS"),
    GENERAL_ATTACHMENTS("GENERAL_ATTACHMENTS"),
    COMPANY_DOC_ATTACHMENTS("COMPANY_DOC_ATTACHMENTS"),
    OPPORTUNITY_STAGE_HISTORY("OPPORTUNITY_STAGE_HISTORY"),
    MANUAL_JOURNAL_ITEM("MANUAL_JOURNAL_ITEM"),
    BANK_PAYMENT_ITEM("BANK_PAYMENT_ITEM"),
    BANK_RECEIPT_ITEM("BANK_RECEIPT_ITEM"),
    CASH_PAYMENT_ITEM("CASH_PAYMENT_ITEM"),
    CASH_RECEIPT_ITEM("CASH_RECEIPT_ITEM"),
    LEAD_ITEM("LEAD_ITEM"),
    VACANCY_ITEM("VACANCY_ITEM"),
    DEPARTMENT_ITEM("DEPARTMENT_ITEM"),
    POSITION_ITEM("POSITION_ITEM"),
    ADDITIONAL_PAYMENT_ITEM("ADDITIONAL_PAYMENT_ITEM"),
    PLACEMENT_CUSTOM_ITEM("PLACEMENT_CUSTOM_ITEM"),
    VACANCY_CUSTOM_ITEM("VACANCY_CUSTOM_ITEM"),

    ROTATION_ITEM_TABLE("ROTATION_ITEM_TABLE"),
    GROUP_PLACEMENT_ITEM_TABLE("GROUP_PLACEMENT_ITEM_TABLE"),

    CANDIDATE_CUSTOM_ITEM("CANDIDATE_CUSTOM_ITEM"),

    EXPERIENCE_ITEM_TABLE("EXPERIENCE_ITEM_TABLE"),
    PICKLIST("PICKLIST");
    private String title;

    ItemTableEnum(String title) {
        this.title = title;
    }

    public String getTitle() {
        return title;
    }
}
