update "0".modelfield set customizabletable = true where field_id='ATTACHMENTS' AND form_id='CLIENT_FORM';
update "anv".modelfield set customizabletable = true where field_id='ATTACHMENTS' AND form_id='CLIENT_FORM';

update "0".modelfield set customizabletable = true where field_id='CRM_OPPORTUNITY_STAGE_HISTORY' AND form_id='OPPORTUNITY_FORM';
update "anv".modelfield set customizabletable = true where field_id='CRM_OPPORTUNITY_STAGE_HISTORY' AND form_id='OPPORTUNITY_FORM';

DELETE FROM "0".itemtable_settings WHERE section = 'GENERAL_ATTACHMENTS';
DELETE FROM "anv".itemtable_settings WHERE section = 'GENERAL_ATTACHMENTS';
INSERT INTO "0".itemtable_settings (section, settingsjsondata) VALUES ('GENERAL_ATTACHMENTS', '[{"code":"NAME","title":"Name","width":25,"selected":true,"required":false,"disabled":false,"changed":false,"order":0},{"code":"DESCRIPTION","title":"Description","width":35,"selected":true,"required":false,"disabled":false,"changed":false,"order":1},{"code":"CREATED_DATE","title":"Created Date","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":2},{"code":"FILE_SIZE","title":"File Size","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":3},{"code":"DOWNLOAD","title":"Download","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":4},{"code":"REMOVE","title":"Remove","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":5}]');
INSERT INTO "anv".itemtable_settings (section, settingsjsondata) VALUES ('GENERAL_ATTACHMENTS', '[{"code":"NAME","title":"Name","width":25,"selected":true,"required":false,"disabled":false,"changed":false,"order":0},{"code":"DESCRIPTION","title":"Description","width":35,"selected":true,"required":false,"disabled":false,"changed":false,"order":1},{"code":"CREATED_DATE","title":"Created Date","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":2},{"code":"FILE_SIZE","title":"File Size","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":3},{"code":"DOWNLOAD","title":"Download","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":4},{"code":"REMOVE","title":"Remove","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":5}]');

DELETE FROM "0".itemtable_settings WHERE section = 'CLIENT_FORM_ATTACHMENTS';
DELETE FROM "anv".itemtable_settings WHERE section = 'CLIENT_FORM_ATTACHMENTS';
INSERT INTO "0".itemtable_settings (section, settingsjsondata) VALUES ('CLIENT_FORM_ATTACHMENTS', '[{"code":"NAME","title":"Name","width":20,"selected":true,"required":false,"disabled":false,"changed":false,"order":0},{"code":"DESCRIPTION","title":"Description","width":20,"selected":true,"required":false,"disabled":false,"changed":false,"order":1},{"code":"DOCUMENT_ID","title":"Document ID","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":2},{"code":"TYPE","title":"Type","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":3},{"code":"FILE_SIZE","title":"File Size","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":4},{"code":"CREATED_DATE","title":"Created Date","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":5},{"code":"DOWNLOAD","title":"Download","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":6},{"code":"REMOVE","title":"Remove","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":7}]');
INSERT INTO "anv".itemtable_settings (section, settingsjsondata) VALUES ('CLIENT_FORM_ATTACHMENTS', '[{"code":"NAME","title":"Name","width":20,"selected":true,"required":false,"disabled":false,"changed":false,"order":0},{"code":"DESCRIPTION","title":"Description","width":20,"selected":true,"required":false,"disabled":false,"changed":false,"order":1},{"code":"DOCUMENT_ID","title":"Document ID","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":2},{"code":"TYPE","title":"Type","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":3},{"code":"FILE_SIZE","title":"File Size","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":4},{"code":"CREATED_DATE","title":"Created Date","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":5},{"code":"DOWNLOAD","title":"Download","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":6},{"code":"REMOVE","title":"Remove","width":10,"selected":true,"required":false,"disabled":false,"changed":false,"order":7}]');