delete from "anv".modelfield where form_id = 'PAYROLL_STARTER_FORM' and iscustomfield = false;

insert into "anv".modelfield(columntype, field_id, forder, form_id, fsection, hide, type, widget) values
            ('COL_1', 'SALARY_GRADE', 0, 'PAYROLL_STARTER_FORM', 'PAYMENT_DEDUCTION_INFORMATION', false, 'text', 'MULTITABLE'),
            ('COL_1', 'BIRTH_DAY', 1001, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_DETAILS', true, 'text', 'UNKNOWN'),
            ('COL_2', 'CONTRACT_START_DATE', 1000, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_DETAILS', true, 'text', 'DatePicker'),
            ('COL_1', 'TOTAL_SALARY', 1, 'PAYROLL_STARTER_FORM', 'PAYMENT_DEDUCTION_INFORMATION', false, 'text', 'TextBox'),
            ('COL_1', 'EMPLOYEE_IS_PAID', 0, 'PAYROLL_STARTER_FORM', 'PAYMENT_SETTINGS', false, 'text', 'UNKNOWN'),
            ('COL_2', 'ACCOUNT_STATUS', 1, 'PAYROLL_STARTER_FORM', 'ACCOUNT_INFORMATION', false, 'text', 'Dropdown'),
            ('COL_2', 'ESS_USER', 3, 'PAYROLL_STARTER_FORM', 'ACCOUNT_INFORMATION', false, 'text', 'CheckBox'),
            ('COL_1', 'ACCOUNT_ROLES', 0, 'PAYROLL_STARTER_FORM', 'ACCOUNT_INFORMATION', false, 'text', 'UNKNOWN'),
            ('COL_2', 'NO_ACCESS', 5, 'PAYROLL_STARTER_FORM', 'ACCOUNT_INFORMATION', false, 'text', 'CheckBox'),
            ('COL_1', 'EMPLOYEE_PAYROLL_SETTINGS', 0, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_PAYROLL_SETTINGS', false, 'text', 'UNKNOWN'),
            ('COL_2', 'JOB_TITLE', 2, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_DETAILS', false, 'text', 'MULTITABLE'),
            ('COL_1', 'CITIZENSHIP', 1000, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_DETAILS', true, 'text', 'Dropdown'),
            ('COL_2', 'HIRE_DATE', 0, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_DETAILS', false, 'text', 'DatePicker'),
            ('COL_1', 'FIRST_NAME', 1, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_DETAILS', false, 'text', 'TextBox'),
            ('COL_1', 'EMPLOYEE_CODE', 0, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_DETAILS', false, 'text', 'UNKNOWN'),
            ('COL_2', 'RESIGNATION_DATE', 1, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_DETAILS', false, 'text', 'UNKNOWN'),
            ('COL_1', 'OVERTIME_SETTINGS_TABLE', 0, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_OVERTIME_SETTINGS', false, 'text', 'MULTITABLE'),
            ('COL_2', 'CONTRACT_END_DATE', 1001, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_DETAILS', true, 'text', 'DatePicker'),
            ('COL_2', 'APPROVER', 1002, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_DETAILS', true, 'text', 'LOOKUP'),
            ('COL_3', 'FAMILY_STATUS', 0, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_DETAILS', false, 'text', 'DropDown'),
            ('COL_2', 'PAYMENT_TABLE', 0, 'PAYROLL_STARTER_FORM', 'PAYMENT_DEDUCTION_INFORMATION', false, 'text', 'MULTITABLE'),
            ('COL_3', 'EMAIL', 1, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_DETAILS', false, 'text', 'TextBox'),
            ('COL_2', 'GENDER', 1000, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_DETAILS', true, 'text', 'MULTITABLE'),
            ('COL_2', 'SALARY_CURRENCY', 0, 'PAYROLL_STARTER_FORM', 'PAYMENT_SETTINGS', false, 'text', 'DropDown'),
            ('COL_2', 'PAY_METHOD', 1, 'PAYROLL_STARTER_FORM', 'PAYMENT_SETTINGS', false, 'text', 'DropDown'),
            ('COL_2', 'ACCOUNT_STATUS', 0, 'PAYROLL_STARTER_FORM', 'ACCOUNT_INFORMATION', false, null, 'DropDown'),
            ('COL_3', 'PAY_PERIOD', 0, 'PAYROLL_STARTER_FORM', 'PAYMENT_SETTINGS', false, 'text', 'DropDown'),
            ('COL_3', 'WPS_NUMBER', 1, 'PAYROLL_STARTER_FORM', 'PAYMENT_SETTINGS', false, 'text', 'TextBox'),
            ('COL_2', 'EMPLOYEE_BONUS', 1000, 'PAYROLL_STARTER_FORM', 'PAYMENT_DEDUCTION_INFORMATION', true, 'text', 'UNKNOWN'),
            ('COL_1', 'NORMAL_RATE', 1000, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_OVERTIME_SETTINGS', true, 'text', 'MULTITABLE'),
            ('COL_2', 'EMPLOYEE_COMMISSION', 1001, 'PAYROLL_STARTER_FORM', 'PAYMENT_DEDUCTION_INFORMATION', true, 'text', 'TextBox'),
            ('COL_1', 'OVER_TIME_RATE', 1001, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_OVERTIME_SETTINGS', true, 'text', 'MULTITABLE'),
            ('COL_1', 'LAST_NAME', 2, 'PAYROLL_STARTER_FORM', 'EMPLOYEE_DETAILS', false, 'text', 'TextBox'),
            ('COL_1', 'DEDUCTION_TABLE', 1000, 'PAYROLL_STARTER_FORM', 'PAYMENT_DEDUCTION_INFORMATION', true, 'text', 'MULTITABLE'),
            ('COL_1', 'LOAN_TABLE', 1002, 'PAYROLL_STARTER_FORM', 'PAYMENT_DEDUCTION_INFORMATION', true, 'text', 'MULTITABLE'),
            ('COL_1', 'ACCOUNT_ROLES', 1, 'PAYROLL_STARTER_FORM', 'ACCOUNT_INFORMATION', false, null, 'UNKNOWN'),
            ('COL_2', 'ESS_USER', 2, 'PAYROLL_STARTER_FORM', 'ACCOUNT_INFORMATION', false, null, 'CheckBox'),
            ('COL_1', 'EMPLOYER_CONTRIBUTION_TABLE', 1001, 'PAYROLL_STARTER_FORM', 'PAYMENT_DEDUCTION_INFORMATION', true, 'text', 'MULTITABLE');

update "anv".customformsection set active = false where form_ID = 'PAYROLL_STARTER_FORM' and section in ('ACCOUNT_INFORMATION', 'PAYROLL_SETTINGS');

