delete  from "anv".form_property where form_id ='PAYROLL_STARTER_FORM';
insert into "anv".form_property (form_id, settingsjsondata)
values ('PAYROLL_STARTER_FORM',
        '[
  {
    "code": "ESS_USER",
    "title": "ESS User",
    "aliasName": "ESS_USER",
    "changed": false,
    "required": false,
    "widget": "Unknown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
   "code": "SALARY_CURRENCY",
    "title": "Salary Currency",
    "aliasName": "SALARY_CURRENCY",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "FIRST_NAME",
    "title": "First Name",
    "aliasName": "FIRST_NAME",
    "changed": false,
    "required": true,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "LAST_NAME",
    "title": "Last Name",
    "aliasName": "LAST_NAME",
    "changed": false,
    "required": true,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "EMAIL",
    "title": "E-mail",
    "aliasName": "EMAIL",
    "changed": false,
    "required": true,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "HIRE_DATE",
    "title": "Hire date",
    "aliasName": "HIRE_DATE",
    "changed": false,
    "required": false,
    "widget": "DatePicker",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "BIRTH_DAY",
    "title": "Date of birth",
    "aliasName": "BIRTH_DAY",
    "changed": false,
    "required": false,
    "widget": "Unknown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CITIZENSHIP",
    "title": "Citizenship",
    "aliasName": "CITIZENSHIP",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "APPROVER",
    "title": "Approver",
    "aliasName": "APPROVER",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CONTRACT_START_DATE",
    "title": "Contract Start",
    "aliasName": "CONTRACT_START_DATE",
    "changed": false,
    "required": false,
    "widget": "DatePicker",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "CONTRACT_END_DATE",
    "title": "Contract End",
    "aliasName": "CONTRACT_END_DATE",
    "changed": false,
    "required": false,
    "widget": "DatePicker",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "EMPLOYEE_IS_PAID",
    "title": "Employee is paid",
    "aliasName": "EMPLOYEE_IS_PAID",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "SALARY_GRADE",
    "title": "Payment Category",
    "aliasName": "SALARY_GRADE",
    "changed": false,
    "required": true,
    "widget": "Unknown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "PAY_PERIOD",
    "title": "Pay period",
    "aliasName": "PAY_PERIOD",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "PAY_METHOD",
    "title": "Payment method",
    "aliasName": "PAY_METHOD",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "EMPLOYEE_BONUS",
    "title": "Bonus",
    "aliasName": "EMPLOYEE_BONUS",
    "changed": false,
    "required": false,
    "widget": "Unknown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "EMPLOYEE_COMMISSION",
    "title": "Commission",
    "aliasName": "EMPLOYEE_COMMISSION",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "JOB_TITLE",
    "title": "Job Title",
    "aliasName": "JOB_TITLE",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "TOTAL_SALARY",
    "title": "Total Salary",
    "aliasName": "TOTAL_SALARY",
    "changed": false,
    "required": false,
    "widget": "AutoNumber",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "FAMILY_STATUS",
    "title": "Marital Status",
    "aliasName": "FAMILY_STATUS",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "GENDER",
    "title": "Gender",
    "aliasName": "GENDER",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "EMPLOYEE_CODE",
    "title": "Employee Code",
    "aliasName": "EMPLOYEE_CODE",
    "changed": false,
    "required": false,
    "widget": "Unknown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "WPS_NUMBER",
    "title": "WPS No",
    "aliasName": "WPS_NUMBER",
    "changed": false,
    "required": false,
    "widget": "TextBox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "RESIGNATION_DATE",
    "title": "Resignation Date",
    "aliasName": "RESIGNATION_DATE",
    "changed": false,
    "required": false,
    "widget": "DatePicker",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "PAYMENT_METHOD",
    "title": "Salary Level",
    "aliasName": "PAYMENT_METHOD",
    "changed": false,
    "required": false,
    "widget": "DropDown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "ACCOUNT_ROLES",
    "title": "Roles",
    "aliasName": "ACCOUNT_ROLES",
    "changed": false,
    "required": false,
    "widget": "Checkbox",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "ACCOUNT_STATUS",
    "title": "Account Status",
    "aliasName": "ACCOUNT_STATUS",
    "changed": false,
    "required": false,
    "widget": "LOOKUP",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
  {
    "code": "NO_ACCESS",
    "title": "No Access",
    "aliasName": "NO_ACCESS",
    "changed": false,
    "required": false,
    "widget": "Unknown",
    "selectedId": null,
    "defaultValue": "",
    "disabled": false
  },
]');