#Accounting
PRODUCT=product_add.html
salequote=sale-quote.html
creditnote=credit-note.html
saleinvoice=sale-invoice.html
purchaseorder=purchase-order.html
PICK_LIST_FORM=picklist.html
purchaseinvoice=purchase-invoice.html
BRAND_FORM.addForm=brand.html
BATCH_PAYMENT_FORM=batch_payment.html
DISCOUNT_FORM.addForm=discount.html
BANK_TRANSACTION_FORM=bank_transfer.html
BRAND_FORM.editForm=brand.html
CURRENCY_FORM.addForm=currency_form.html
CURRENCY_FORM.editForm=currency_form.html
INVOICE_PAYMENT_VIEW.viewForm=invoice_payment.html
manualtransactions=manual_entry.html
PREPAYMENT_FORM.addForm=prepayment_add_edit.html
PREPAYMENT_FORM.viewForm=prepayment_add_edit.html
BANK_CHECK_FORM=bank-check.html
TRANSACTION_ITEM_VIEW_FORM=transaction_item_view.html
EXCHANGE_RATE_FORM.addForm=exchange_rate.html
PRODUCT_NUMBERING_SETTINGS_FORM.addForm=product_numbering_settings.html
ACCOUNT_NUMBERING_SETTINGS_FORM.addForm=account_numbering_settings.html
BUILD_ASSEMBLY_FORM=build_assembly.html
FINANCIAL_SETTINGS_FORM.addForm=financial_settings.html
CONVERSION_BALANCE.addForm=conversion_balance.html
FIXED_ASSET_FORM.addForm=fixed_asset_add_edit.html
FIXED_ASSET_FORM.editForm=fixed_asset_add_edit.html
FIXED_ASSET_FORM.viewForm=fixed_asset_view.html
INVOICE_SETTINGS_FORM.addForm=invoice_settings.html
PRICE_LEVEL_FORM.addForm=price-level.html
STOCK_TRANSFER_FORM=stock_transfer.html
STOCK_TRANSFER_FORM.viewForm=stock_transfer_view.html
STOCKADJUSTMENTS_FORM.addForm=stock_adjustment.html
REQUEST_FOR_PURCHASE_FORM.addForm=RequestForPurchase_RFP.html
REQUEST_FOR_PURCHASE_FORM.editForm=RequestForPurchase_RFP.html
REQUEST_FOR_PURCHASE_FORM.viewForm=RequestForPurchase_RFP.html
TAX_RATE_FORM.addForm=tax_add_edit.html
WAREHOUSE_FORM.addForm=warehouse_add_edit.html
IMPORT_PRODUCT_FORM.addForm=product_import.html
IMPORT_PRODUCT_FORM.editForm=product_import.html
EXPENSE_REPORT=ExpenseReportAddEditView.html
EXPENSE_PAYMENT_FORM=expense_payment.html

CUSTOM_FORM_FORM.addForm=custom_form.html
CUSTOM_FORM_FORM.editForm=custom_form.html
#HRMS
IMPORT_SUPPLIER_FORM.importForm=supplier_import.html
BENEFIT_REQUEST_FORM.addForm=benefitRequest_add.html
PERSONAL_GOAL_FORM.addForm=personalGoal_add.html
PERSONAL_GOAL_FORM.editForm=personalGoal_add.html
PERSONAL_GOAL_FORM.viewForm=personalGoal_edit_view.html
BUSINESS_GOAL_FORM.addForm=bussines_goal_add_edit_view.html
BUSINESS_GOAL_FORM.editForm=bussines_goal_add_edit_view.html
BUSINESS_GOAL_FORM.viewForm=bussines_goal_add_edit_view.html
COMPANY_GOAL_FORM.addForm=company_goal_add_edit_view.html
COMPANY_GOAL_FORM.editForm=company_goal_add_edit_view.html
COMPANY_GOAL_FORM.viewForm=company_goal_add_edit_view.html
CERTIFICATE_OF_EMPLOYMENT_FORM.addForm=certificate_add_edit_view.html
CERTIFICATE_OF_EMPLOYMENT_FORM.viewForm=certificate_add_edit_view.html
EMPLOYEE_CLIENT_DOCUMENTS_FORM.viewForm=company_document.html
EMPLOYEE_DOCUMENTS_FORM.viewForm=employee_document.html
EMPLOYEE_LEAVE_TYPES_FORM.addForm=employee_leaveType.html
IMPORT_LEAVE_ALLOWANCE_FORM.importForm=employee_leave_allowance_import.html
EMPLOYEE_LEAVE_TYPES_FORM.editForm=employee_leaveType.html
LEAVE_REQUEST_FORM.addForm=leaveRequest_add_edit.html
LEAVE_REQUEST_COMMENT_FORM.addForm=leaveRequestComment.html
MULTIPLE_APPROVAL_REQUEST_FORM.viewForm=multiApprovalRequest.html
ONBOARDING_PERIOD_FORM.addForm=onboarding_period.html
ONBOARDING_PERIOD_FORM.editForm=onboarding_period.html
OVERTIME_FORM.addForm=overtime_view.html
SELECT_CANDIDATE_FORM.addForm=select_candidate.html
IMPORT_HRMS_CANDIDATE_FORM.importForm=candidate_import.html
HRMS_EMPLOYEE_FORM.importForm=employee_import.html
CUSTOMIZE_CERTIFICATE.editForm=customize_certificate.html
HOLIDAY_FORM.addForm=holiday.html
HOLIDAY_FORM.editForm=holiday.html
HOLIDAY_FORM.viewForm=holiday.html
EMPLOYEE_BENEFIT_FORM.addForm=employee_benefit_form.html
EMPLOYEE_BENEFIT_FORM.editForm=employee_benefit_form.html
JOB_DESCRIPTION_FORM.viewForm=job_description.html
JOB_DESCRIPTION_FORM.editForm=job_description.html
POSITION_FORM.viewForm=position.html
POSITION_FORM.addForm=position.html
POSITION_FORM.editForm=position.html
IMPORT_POSITION_FORM.importForm=position_import.html
IMPORT_DEPARTMENT_FORM.importForm=department_import.html
REFERENCE_FORM.editForm=reference.html
REFERENCE_FORM.addForm=reference.html
TIMESLOT_FORM.addForm=timeslot.html
TIMESLOT_FORM.editForm=timeslot.html
TIMESLOT_FORM.viewForm=timeslot.html
SHIFT_SETTINGS_FORM.addForm=shift_settings.html
SHIFT_SETTINGS_FORM.editForm=shift_settings.html
SHIFT_SETTINGS_FORM.viewForm=shift_settings.html
COUNTRY_SETTINGS_FORM.addForm=country_settings.html
COUNTRY_SETTINGS_FORM.editForm=country_settings.html
#PM
DEPARTMENT_FORM.addForm=department_add_edit_view.html
DEPARTMENT_FORM.editForm=department_add_edit_view.html
DEPARTMENT_FORM.viewForm=department_add_edit_view.html
ISSUE_FORM.addForm=issue_add_edit_view.html
ISSUE_FORM.editForm=issue_add_edit_view.html
ISSUE_FORM.viewForm=issue_add_edit_view.html
LOCATION_FORM.addForm=location_add_edit_view.html
LOCATION_FORM.editForm=location_add_edit_view.html
LOCATION_FORM.viewForm=location_add_edit_view.html
WORKSTREAM_FORM.addForm=workstream_add_edit_view.html
WORKSTREAM_FORM.editForm=workstream_add_edit_view.html
WORKSTREAM_FORM.viewForm=workstream_add_edit_view.html
IMPORT_PROJECT_FORM.importForm=project_import.html
#CRM
OPPORTUNITY_FORM.importForm=opportunity_import.html
IMPORT_CRM_LEAD_FORM.importForm=lead_import.html
IMPORT_CRM_ACCOUNT_FORM.importForm=account_import.html
IMPORT_CLIENT_FORM.importForm=client_import.html
IMPORT_CRM_CONTACT_FORM.importForm=contact_import.html
IMPORT_PURCHASE_ORDERS_FORM.importForm=purchase_orders_import.html
ACTIVITY_FORM.editForm=event_edit.html
ACTIVITY_FORM.viewForm=event_summary.html
MULTILEAD_OR_CONTACT_FORM.addForm=lead_contact_multi.html
MESSAGE_CENTER_FORM.viewForm=email_summary.html
#DYNAMIC_FORM_VIEW
CUSTOMIZE_FORM.addForm=customize_form.html
SOLUTION_FORM.editForm=solution.html
SOLUTION_FORM.viewForm=solution.html
INTRODUCTION_PAGE_FORM.addForm=introductionPage.html
INTRODUCTION_PAGE_FORM.viewForm=introductionPageSummary.html
#Payroll
PAYROLL_ALLOWANCE_DEDUCTION_SETTINGS_FORM.addForm=allowance_deduction_settings.html
PAYROLL_ALLOWANCE_DEDUCTION_SETTINGS_FORM.editForm=allowance_deduction_settings.html
PAYROLL_COMPANY_SETTINGS_FORM.addForm=employer_settings.html
PAYROLL_COMPANY_SETTINGS_FORM.viewForm=employer_settings.html
PAYROLL_EOS_CALCULATION_FORM.addForm=end_of_service.html
PAYROLL_EOS_CALCULATION_FORM.viewForm=end_of_service.html
PAYROLL_END_OF_SERVICE_SETTINGS_FORM.addForm=end_of_service_settings.html
PAYROLL_PAYSLIP_TABLE_FORM.addForm=group_payrun.html
PAYROLL_PAYSLIP_TABLE_FORM.editForm=group_payrun.html
PAYROLL_PAYSLIP_TABLE_FORM.viewForm=group_payrun.html
PAYROLL_BATCH_FORM.addForm=payroll_batch.html
PAYROLL_BATCH_FORM.editForm=payroll_batch.html
PAYROLL_PENSION_PROVIDER_FORM.addForm=pension_provider.html
PAYROLL_PENSION_PROVIDER_FORM.editForm=pension_provider.html
PAYROLL_PENSION_SCHEMA_FORM.addForm=pension_schema.html
PAYROLL_PENSION_SCHEMA_FORM.editForm=pension_schema.html
PAYROLL_PENSION_SCHEMA_FORM.viewForm=pension_schema.html
IMPORT_GROUP_PAYRUN_FORM.importForm=group_payrun_import.html
IMPORT_BUDGET_MANAGER_FORM.importForm=budget_manager_import.html
IMPORT_PAYMENT_DEDUCTION_FORM.importForm=payment_deduction_import.html
IMPORT_PRODUCT_CATEGORIES_FORM.importForm=product_categories_import.html
IMPORT_BRAND_FORM.importForm=brand_import.html
PAYROLL_PAYRUN_PAYMENT_FORM.addForm=payrun_payment.html
PAYROLL_PAYRUN_PAYMENT_FORM.viewForm=payrun_payment.html
PAYROLL_PAYMENT_FORM.addForm=payroll_payment.html
PAYROLL_PAYMENT_FORM.viewForm=payroll_payment.html
#PMSettings
TIMESHEET_SETTINGS_FORM.addForm=timesheet_settings.html
#EmailSettings
EMAIL_TEMPLATE_FORM.addForm=email_template_settings.html
EMAIL_TEMPLATE_FORM.editForm=email_template_settings.html
EMAIL_TEMPLATE_FORM.viewForm=email_template_settings.html
SIGNATURE_FORM.addForm=signature_add_edit_view.html
SIGNATURE_FORM.editForm=signature_add_edit_view.html
SIGNATURE_FORM.viewForm=signature_add_edit_view.html
SMS_TEMPLATE_FORM.addForm=smsTemplate.html
SMS_TEMPLATE_FORM.editForm=smsTemplate.html
SMS_TEMPLATE_FORM.viewForm=smsTemplate.html
#CrmSettings
CRM_SETTINGS_FORM.viewForm=crm_settings_view.html
EMAIL_PARENT_FILTER_FORM.addForm=email_filter.add.edit.html
EMAIL_PARENT_FILTER_FORM.editForm=email_filter.add.edit.html
SMS_SETTINGS_FORM.editForm=sms_settings_add.edit.view.html
#Switchvox
SWITCHVOX_FORM.addForm=switchvox.html
#TimesheetReminder
TIMESHEET_REMINDER_FORM.viewForm=timesheet_reminder_view.html
USER_CREDENTIALS_FORM.editForm=userCredentials.html
#ConsolidationSettings
CONSOLIDATION_COMPANY_FORM.addForm=consalidation_add_edit.html
REQUEST_FOR_QUOTE_FORM.addForm=rfq_form.html
REQUEST_FOR_QUOTE_FORM.editForm=rfq_form.html
REQUEST_FOR_QUOTE_FORM.viewForm=rfq_form.html
#Education
EDUCATION_FORM.addForm=education_add_edit_view.html
EDUCATION_FORM.editForm=education_add_edit_view.html
EDUCATION_FORM.viewForm=education_add_edit_view.html
#Award
AWARD_FORM.addForm=award_add_edit_view.html
AWARD_FORM.editForm=award_add_edit_view.html
AWARD_FORM.viewForm=award_add_edit_view.html

EMAIL_COMPOSE_FORM.addForm=email_compose.html
EMAIL_COMPOSE_FORM.editForm=email_compose.html
EMAIL_SUMMARY_COMPOSE_FORM.viewForm=email_summary_compose.html

ACCOUNTING_EMAIL_COMPOSE_FORM.addForm=accounting_email_compose.html
ACCOUNTING_EMAIL_COMPOSE_FORM.editForm=accounting_email_compose.html

EXPENSE_EMAIL_COMPOSE_FORM.addForm=expense_email_compose.html
EXPENSE_EMAIL_COMPOSE_FORM.editForm=expense_email_compose.html

#Custom Pdf Settings
PHANTOM_PDF_FORM.addForm=phantom_pdf_add_edit.html
PHANTOM_PDF_FORM.editForm=phantom_pdf_add_edit.html
ITEXT_PDF_FORM.addForm=itext_pdf_add_edit.html
ITEXT_PDF_FORM.editForm=itext_pdf_add_edit.html
AIPHANTOM_PDF_FORM.addForm=aiphantom_pdf_add_edit.html

#Meeting Minutes
MEETING_MINUTES.addForm=meeting_minutes_add_edit.html
MEETING_MINUTES.editForm=meeting_minutes_add_edit.html
MEETING_MINUTES.viewForm=meeting_minutes_view.html
INCIDENT_FORM.addForm=incident_add_edit_view.html
INCIDENT_FORM.editForm=incident_add_edit_view.html
INCIDENT_FORM.viewForm=incident_add_edit_view.html
APPRAISAL_TEMPLATE_FORM.addForm=competencies_template_add.html
COMPETENCY_FORM.addForm=competencie_add_edit.html
COMPETENCY_FORM.editForm=competencie_add_edit.html
PERFORMANCE_NOTE_FORM.addForm=performance_note_add_edit_view.html
PERFORMANCE_NOTE_FORM.editForm=performance_note_add_edit_view.html
PERFORMANCE_NOTE_FORM.viewForm=performance_note_add_edit_view.html
BONUS_SETTING_FORM.addForm=bonus_settings_add_edit.html
BONUS_SETTING_FORM.editForm=bonus_settings_add_edit.html
LEAVE_REASON_FORM.editForm=leaveReason.html
LEAVE_REASON_FORM.addForm=leaveReason.html
GOODS_RECEIVED_NOTES=goods_received_notes.html
BOOKINGITEMS=bookingItems.html
BOOKINGITEMSRESERVATION=bookingItemsReservation.html
GOOGLE_INTEGRATION_FORM.editForm=google_integration_form.html
MICROSOFT_INTEGRATION_FORM.editForm=microsoft_integration_form.html
PAYPAL_PAYMENT_FORM.editForm=paypal_payment_form.html
STRIPE_PAYMENT_FORM.editForm=stripe_payment_form.html
SHOPIFY_INTEGRATION_FORM.editForm=shopify_integration_form.html
TELEPHONY_SETTINGS_FORM.addForm=telephony_settings_form.html
MESSENGER_SETTINGS_FORM.addForm=messenger_settings_form.html
REFERENCE_LOCALE_FORM.addForm=reference_locale_form.html
TELEGRAM_BOT_SETTINGS_FORM.addForm=telegram_bot_settings_form.html
TELEGRAM_BOT_SETTINGS_FORM.editForm=telegram_bot_settings_form.html
CUSTOM_FORM_LOCALIZATION.editForm=custom_form_localization.html
RECRUITMENT_INTEGRATION_FORM.editForm=recruitment_integration_form.html
DOCUMENT_INTEGRATION_FORM.editForm=document_integration_form.html
PAYROLL_ZONE_FORM.addForm=payroll_zone_form.html
MINIMUM_WAGE_FORM.addForm=minimum_wage_form.html
WAGE_RATE_FORM.addForm=wage_rate_form.html
ATTENDANCE_TERMINAL_FORM.viewForm=attendance_terminal_form.html
ATTENDANCE_TERMINAL_FORM.editForm=attendance_terminal_edit_form.html