insert into "anv".customformsection (form_id, section, sorder, expanded)
values ('WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', 3, false);

delete
from "anv".modelfield
where form_id = 'WORKFLOW_WEB_HOOK_FORM'
  and fsection = 'RESPONSE_ATTRIBUTES';
insert into "anv".modelfield(columntype, field_id, forder, form_id, fsection, mandatory, systemmandatory)
values ('COL_1', 'FIELD_1', 0, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_2', 1, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_3', 2, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_4', 3, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_5', 4, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_6', 5, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_7', 6, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_8', 7, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_9', 8, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_10', 9, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_11', 10, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_12', 11, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_13', 12, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_14', 13, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_15', 14, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_16', 15, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_17', 16, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_18', 17, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_19', 18, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_20', 19, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_21', 20, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_22', 21, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_23', 22, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_24', 23, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_25', 24, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_26', 25, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_27', 26, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_28', 27, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_29', 28, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_30', 29, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_31', 30, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_32', 31, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_33', 32, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_34', 33, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_35', 34, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_36', 35, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_37', 36, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_38', 37, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_39', 38, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_40', 39, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_41', 40, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_42', 41, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_43', 42, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_44', 43, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_45', 44, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_46', 45, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_47', 46, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_3', 'FIELD_48', 47, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_1', 'FIELD_49', 48, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false),
       ('COL_2', 'FIELD_50', 49, 'WORKFLOW_WEB_HOOK_FORM', 'RESPONSE_ATTRIBUTES', false, false);