insert into "anv".itemtable_settings (section, settingsjsondata)
values ('GROUP_PLACEMENT_ITEM_TABLE',
        '[
      {
        "aliasName": "LOCATION",
        "changed": false,
        "clickable": true,
        "code": "LOCATION",
        "disabled": false,
        "hasDefault": false,
        "minValue": 0,
        "order": 0,
        "required": true,
        "selected": true,
        "title": "Location",
        "width": 25
      },
      {
          "aliasName": "TYPE",
        "changed": false,
        "clickable": false,
        "code": "TYPE",
        "disabled": false,
        "hasDefault": false,
        "minValue": 0,
        "order": 1,
        "required": true,
        "selected": true,
        "title": "Type",
        "width": 15
      },
      {
        "aliasName": "CANDIDATE",
        "changed": false,
        "clickable": false,
        "code": "CANDIDATE",
        "disabled": false,
        "hasDefault": false,
        "minValue": 0,
        "order": 2,
        "required": false,
        "selected": true,
        "title": "Candidate",
        "width": 15
      },
      {
          "aliasName": "DEPARTMENT",
        "changed": false,
        "clickable": false,
        "code": "DEPARTMENT",
        "disabled": false,
        "hasDefault": false,
        "minValue": 0,
        "order": 3,
        "required": false,
        "selected": true,
        "title": "Department",
        "width": 15
      },
      {
        "aliasName": "POSITION",
        "changed": false,
        "clickable": false,
        "code": "POSITION",
        "disabled": false,
        "hasDefault": false,
        "minValue": 0,
        "order": 4,
        "required": false,
        "selected": true,
        "title": "Position",
        "width": 15
      },
        {
        "aliasName": "VACANCY",
        "changed": false,
        "clickable": false,
        "code": "VACANCY",
        "disabled": false,
        "hasDefault": false,
        "minValue": 0,
        "order": 5,
        "required": false,
        "selected": true,
        "title": "Vacancy",
        "width": 15
      },
        {
        "aliasName": "FROM_DATE",
        "changed": false,
        "clickable": false,
        "code": "FROM_DATE",
        "disabled": false,
        "hasDefault": false,
        "minValue": 0,
        "order": 5,
        "required": false,
        "selected": true,
        "title": "Effective Date",
        "width": 15
      }
    ]');