#master persistence unit
cluster.freedb.url=jdbc:postgresql://masterdbfree.workforcetrack.com:6432/multischemafree
cluster.paidb.url=jdbc:postgresql://masterdbpaid.workforcetrack.com:6432/multischemafree
cluster.paidb1.url=jdbc:postgresql://masterdbpaid1.workforcetrack.com:6432/multischemafree

#slave persistence unit
cluster.freedb-slave.url=jdbc:postgresql://masterdbfree.workforcetrack.com:6432/multischemafree
cluster.paidb-slave.url=jdbc:postgresql://masterdbpaid.workforcetrack.com:6432/multischemafree
cluster.paidb1-slave.url=jdbc:postgresql://masterdbpaid1.workforcetrack.com:6432/multischemafree

hibernate.qrtzdb.connection.url=jdbc:postgresql://qrtz.workforcetrack.com:6432/qrtzdb
hibernate.globalauth.connection.url=jdbc:postgresql://auth.workforcetrack.com:6432/globalauth
hibernate.connection.reporting_custom_url=jdbc:postgresql://masterdbpaid.workforcetrack.com:6432/reportservice_excel

aws.paidb.url=jdbc:postgresql://aws.masterdbpaid.kpi.com:6432/multischemapaid
aws.freedb.url=jdbc:postgresql://aws.masterdbfree.kpi.com:6432/multischemafree

cluster.solr.free.url=http://solr.workforcetrack.com:8983/solr/
cluster.solr.paid.url=http://solr.workforcetrack.com:8983/solr/
cluster.solr.paid1.url=http://solr.workforcetrack.com:8983/solr/

hibernate.connection.username = wfmtest
hibernate.connection.password = wfm

hibernate.globalauth.connection.username = wftauth
hibernate.globalauth.connection.password = wft

hibernate.connection.reporting_custom_username = wfmtest
hibernate.connection.reporting_custom_password = wfm

auth.domain = auth.workforcetrack.com
cluster.type=FREE
cluster.update=[FREE,PAID]

active.mq.connection=tcp://mq.kpi.com:61616

kpi.discovery.service-id=dev-service

## Redis configuration

# Redis conniction pool
redis.pool.timeout= 2000
redis.pool.maxTotal= 20
redis.pool.minIdle= 1
redis.pool.maxIdle= 5

# Redis secure
redis.host= 127.0.0.1
redis.port= 6379
redis.password= EOBdu3b3hScNX4mW

#kpi.logger.db.url=jdbc:postgresql://kpi.logger.com:6432/logaudit
kpi.logger.db.url=jdbc:postgresql://kpi.logger.com:6432/logaudit

tomcat.urls=https://aws.kpi.com/reportingsynchronization?database=PAID ; https://aws.kpi.com/reportingsynchronization?database=FREE ; https://app.kpi.com/reportingsynchronization?database=PAID ; https://app.kpi.com/reportingsynchronization?database=FREE ; http://kg.kpi.com/reportingsynchronization?database=PAID ; http://app.1erp.sa/reportingsynchronization?database=PAID ; http://app.1erp.sa/reportingsynchronization?database=FREE

#Kpi Zatca
kpi.zatca.url=https://zatca.kpi.com/api/

# Production mode property for schema update
sqlpatch.production.path=/mnt/webapps/projects/newui.kpi.com/ROOT/WEB-INF/classes/DatabasePatches
