package com.edatasite.workforce.gwt.core.client.ui.listpanel;


import com.edatasite.workforce.gwt.core.client.ui.customfields.ViewName;
import com.google.gwt.user.client.rpc.IsSerializable;

/**
 * User: Dilsh0d
 * Email: dilshod.toj@gmail.com
 * Date: 18-Aug-2010
 * Time: 14:55:15
 */
public enum ListPanelType implements IsSerializable {
    CompanySavedReportPanel("Company Saved Report Panel", ViewName.CompanySavedReport),
    CompanyDashletsPanel("Company Dashlets Panel", ViewName.Dashlets),
    ReportsListPanel("Reports List Panel", ViewName.Reports),
    DirectoryListPanel("Directory List Panel", ViewName.Directory),
    AccountTransactionsListPanel("Account Transactions List Panel", ViewName.AccountTransactions),
    AEOListPanel("AEO List Panel", ViewName.AEO),
    ActivityListPanel("Activity List Panel", ViewName.Activity),
    BlogListPanel("Blog List Panel", ViewName.Blog),
    WebsiteListPanel("Website List Panel", ViewName.Website),
    TagListPanel("Tag List Panel", ViewName.Tag),
    PageBlockListPanel("Page Block List Panel", ViewName.PageBlock),
    PageLayoutBlockListPanel("PageLayout Block List Panel", ViewName.PageLayoutBlock),
    WebsiteLayoutBlockListPanel("Website Layout Block List Panel", ViewName.WebsiteLayoutBlock),
    WebSiteLayoutListPanel("WebSite Layout List Panel", ViewName.WebSiteLayout),
    BlockListPanel("Block List Panel", ViewName.Block),
    PageLayoutList("PageLayout List Panel", ViewName.PageLayout),
    QuickbookSynchHistoryPanel("QuickbookSynchHistory list panel", ViewName.QuickbookSynchHistory),
    PAYETaxListPanel("PAYET tax list panek", ViewName.PAYETax),
    NiTaxChangesListPanel("Ni Tax  ChangesList", ViewName.NiTaxChangesList),
    PageCategoryPanel("Page Category Panel", ViewName.PageCategoryPanel),
    PageListPanel("Page List Panel", ViewName.Page),
    WebsiteScriptPanel("Website Script List Panel", ViewName.Page),
    WebSiteMenuListPanel("WebSite List Panel", ViewName.WebsiteMenu),
    BugsListSummaryLisstPanel("BugsListSummary Lisst Panel", ViewName.BugsListSummary),
    BouncedMessageListPanel("BouncedMessage List Panel", ViewName.BouncedMessage),
    UnsubbedListPanel("Unsubbed List Panel", ViewName.Unsubbed),
    MessageTrackListPanel("MessageTrack List Panel", ViewName.MessageTrack),
    MessageClickTrackListPanel("MessageClickTrack List Panel", ViewName.MessageClickTrack),
    ProductCategoryListPanel("ProductCategory List Panel", ViewName.ProductCategoryStoreFront),
    CustomPageListPanel("CustomPage List Panel", ViewName.CustomPage),
    StoreFrontListPanel("StoreFront List Panel", ViewName.StoreFront),
    MailListPanel("Mail List Panel", ViewName.Mail),
    SentMessageListPanel("SentMessage List Panel", ViewName.SentMessage),
    MessageListPanel("Message List Panel", ViewName.Message),
    QueuedMessagesListPanel("Message List Panel", ViewName.QueuedMessages),
    WebFormListPanel("WebForn List Panel", ViewName.WebForm),
    CampaignListPanel("Campain List Panel", ViewName.Campain),
    WorkflowAlertListPanel("Workflow Alert List Panel", ViewName.WorkflowAlert),
    WorkflowSMSAlertListPanel("Workflow SMS Alert List Panel", ViewName.WorkflowSMSAlert),
    WorkflowTelegramAlertListPanel("Workflow Telegram Alert List Panel", ViewName.WorkflowTelegramAlert),
    WorkflowUpdateFieldListPanel("Workflow Update Field List Panel", ViewName.WorkflowUpdateField),
    WorkflowActionsListPanel("Workflow Actions List Panel", ViewName.WorkflowActions),
    WorkflowWebHooksListPanel("Workflow Web Hooks List Panel", ViewName.WorkflowWebHooks),
    WebHookResponsesListPanel("Web Hook Responses List Panel", ViewName.WebHookResponses),
    WorkflowEmployeeStepListPanel("Workflow Employee Step List Panel", ViewName.WorkflowEmployeeStep),
    WorkflowEmployeeListPanel("Workflow Employee List Panel", ViewName.WorkflowEmployee),
    WorkflowInvoiceListPanel("Workflow Invoice List Panel", ViewName.WorkflowInvoice),
    WorkflowPushNotificationListPanel("Workflow Push Notification List Panel", ViewName.WorkflowPushNotification),
    RecurringInvoicePanel("Reccuring Invoice List Panel", ViewName.RecurringInvoice),
    VatReportsListPanel("Vat Report List Panel", ViewName.VatReports),
    UnitMeasurementsListPanel("Unit Measurement List Panel", ViewName.MeasurementsList),
    WarehouseProductListPanel("Warehouse Product List Panel", ViewName.WarehouseProduct),
    PurchaseInvoicePanel("Purchase Invoice List Panel", ViewName.PurchaseInvoice),
    RecurringBillPanel("Recurring Bill List Panel", ViewName.RecurringBill),
    TaskListPanel("Task List Panel", ViewName.Task),
    FixedAssetListPanel("Fixed Asset List Panel", ViewName.FixedAsset),
    TimeSheetApprovalPanel("TimeSheet Approval List Panel", ViewName.TimeSheetApproval),
    PositionsPanel("Positions List Panel", ViewName.Positions),
    TaxPanel("Tax rates List Panel", ViewName.TaxRates),
    ShippingMethodsPanel("Tax rates List Panel", ViewName.TaxRates),
    PickListPanel("Tax rates List Panel", ViewName.PickLists),
    WarehousesPanel("Warehouses List Panel", ViewName.WareHouses),
    BankAccountPanel("Bank Accounting List Panel", ViewName.BankAccounts),
    TeamTaskListPanel("Task List Panel", ViewName.Task),
    ProjectTaskListPanel("Task List Panel", ViewName.Task),
    ProjectListPanel("Project List Panel", ViewName.Project),
    ContractListPanel("Contract List Panel", ViewName.Contract),
    DepartmentListPanel("Department List Panel", ViewName.Department),
    EmployeeListPanel("Employee List Panel", ViewName.Employee),
    PayrollEmployeeListPanel("Payroll Employee List Panel", ViewName.Employee),
    PricingEmployeeListPanel("Pricing Employee List Panel", ViewName.Employee),
    MessageCenter("Message Center", ViewName.MessageCenter),
    LeadListPanel("Lead List Panel", ViewName.Lead),
    ShemaListPanel("Schema List Panel", ViewName.Schemas),
    ContactListPanel("Contact List Panel", ViewName.Contact),
    CrmAccountListPanel("CrmAccount List Panel", ViewName.CrmAccount),
    MailListMemberListPanel("Members Panel", ViewName.MailListMember),
    SolrInconsistencyPanel("Solr Inconsistency List Panel", ViewName.SolrInconsistency),
    PollListPanel("Polls List View", ViewName.Poll),
    SurveyListPanel("Surveys List View", ViewName.Survey),
    SurveyListValues("Manage List Values", ViewName.BmtListValues),
    ServerLogPanel("Server Log List View", ViewName.ServerLog),
    RecurrenceLogPanel("Recurrence List View", ViewName.RecurrenceLog),
    NewsListPanel("News List View", ViewName.News),
    ClientListPanel("Client List View", ViewName.CrmAccount),
    SupplierListPanel("Supplier List View", ViewName.CrmAccount),
    CaseListPanel("Case List Panel", ViewName.CrmCase),
    SaleInvoiceListPanel("Sale Invoice List Panel", ViewName.SaleInvoice),
    SaleQuoteListPanel("Sale Quote List Panel", ViewName.SaleQuote),
    HrmsEmployeeListPanel("Employee List Panel", ViewName.Employee),
    LocationListPanel("Location List Panel", ViewName.Location),
    SaleOrderListPanel("Sale Order List Panel", ViewName.SaleOrder),
    CustomFieldsListPanel("Custom Fields List Panel", ViewName.CustomFields),
    HelpDocumentListPanel("Help Document List Panel", ViewName.HelpDocuments),
    LocalizationPropertyListPanel("Localization Property List Panel", ViewName.LocalizationProperty),
    LocalizationPermissionListPanel("Localization Permission List Panel", ViewName.LocalisationPermission),
    ReportingSystemListPanel("Reporting List Panel", ViewName.ReportingSystem),
    DocumentListPanel("Document List Panel", ViewName.Document),
    OpportunitiesListPanel("Opportunities List Panel", ViewName.Opportunity),
    EventsListPanel("Events List Panel", ViewName.LogACall),
    IssuesListPanel("Issues List Panel", ViewName.Issues),
    TaskTimeEntriesPanel("Task Time Entries List Panel", ViewName.TimeEntries),
    AssessmentArchiveListPanel("Assessment Archive List Panel", ViewName.AssessmentArchive),
    DepartmentsListPanel("Issues List Panel", ViewName.Departments),
    RequestForQuoteListPanel("Request For Quote List Panel", ViewName.RequestForQuote),
    RequestForPurchaseListPanel("Request For Purchase List Panel", ViewName.RequestForPurchase),
    PurchaseOrderListPanel("Purchase Order List Panel", ViewName.PurchaseOrder),
    GoalListPanel("Goal list panel", ViewName.PersonalGoal),
    GroupGoalListPanel("Group Goal list panel", ViewName.GroupPersonalGoal),
    DepartmentGoalListPanel("Department Goal list panel", ViewName.DepartmentGoal),
    ProjectGoalListPanel("Project Goal list panel", ViewName.ProjectGoal),
    BusinessGoalListPanel("Business Goal list panel", ViewName.BusinessGoal),
    CompanyGoalListPanel("Company goal list panel", ViewName.CompanyGoal),
    EmployeesGoalListPanel("Employee goal list panel", ViewName.EmployeesGoal),
    NotesWorkspaceListPanel("Notes List Panel", ViewName.Notes),
    NewsWorkspaceListPanel("News List Panel", ViewName.WorkspaceNews),
    NewsWorkspaceCategory("News Category List Panel", ViewName.WorkspaceCategory),
    UpdatesWorkspace("Updates List Panel", ViewName.WorkspaceUpdates),
    HolidayListPanel("Holiday List Panel", ViewName.Holiday),
    SalaryGradeListPanel("Salary Grade List Panel", ViewName.SalaryGrade),
    QueryListPanel("Query List Panel", ViewName.Query),
    CustomEntityListPanel("Custom Entity List Panel", ViewName.CustomEntity),
    CustomListListPanel("Custom List List Panel", ViewName.CustomList),
    CustomListItemsPanel("Custom List Items Panel", ViewName.CustomItems),
    CustomEntityFormsListPanel("Custom Forms List Panel", ViewName.CustomForms),
    CustomEmailTemplateListPanel("Custom Forms List Panel", ViewName.CustomEmailTemplate),
    CustomPdfTemplateListPanel("Custom Pdf List Panel", ViewName.CustomEmailTemplate),
    ReportingXMLTemplatesListPanel("Reporting XML Templates List Panel", ViewName.ReportingXMLTemplates),
    DashboardListPanel("Dashboard List Panel", ViewName.ReportingDashboard),
    DashletListPanel("Dashlet List Panel", ViewName.ReportingDashlet),
    DashboardDownloadLinkListPanel("Dashoboard Download Link List Panel", ViewName.ReportingDashoboardDownloadLink),
    AppraisalTemplateListPanel("Appraisal Template List Panel", ViewName.AppraisalTemplate),
    CompetencyListPanel("Competency List Panel", ViewName.Competency),
    CompetencyGroupListPanel("Competency Group List Panel", ViewName.CompetencyGroup),
    PerformanceNoteListPanel("Performance Note List Panel", ViewName.PerformanceNote),
    UsageHistoryListPanel("Usage History List Panel", ViewName.UsageHistory),
    EmailTemplatesListPanel("Email Templates List Panel", ViewName.EmailTemplates),
    SMSTemplatesListPanel("SMS Templates List Panel", ViewName.SMSTemplates),
    SignatureListPanel("Signature List Panel", ViewName.Signature),
    SolutionListPanel("Solution List Panel", ViewName.Solution),
    PriceLevelListPanel("Price Level List Panel", ViewName.PriceLevel),
    DiscountListPanel("Discount List Panel", ViewName.Discount),
    TermsListPanel("Terms List Panel", ViewName.Terms),
    CategoryReportListPanel("Category Report List Panel", ViewName.CategoryReportList),
    PrePaymentListPanel("Prepayment List Panel", ViewName.Prepayment),
    SupplierCreditListPanel("Supplier Credit List Panel", ViewName.Supplier),
    BugListPanel("Bug List Panel", ViewName.Bug),
    RoleListPanel("Role List Panel", ViewName.Role),
    PermissionRoleListPanel("Manage Role Panel", ViewName.ManageRolePermission),
    BlackListPanel("Black List Panel", ViewName.Black),
    FixedAssetRegisterListPanel("Fixed Asset Register List Panel", ViewName.FixedAsset),
    TimeslotListPanel("Timeslot List Panel", ViewName.Timeslot),
    EmployeeLeaveRequestListPanel("Employee Leave Status", ViewName.EmployeeLeave),
    BackendPaypalReceiptsListView("Paypal Receipts List Panel", ViewName.PaypalReceipts),
    BackendReportingListPanel("Reporting List Panel", ViewName.ReportingListPanel),
    AccountManagementListPanel("Account Management List Panel", ViewName.BackendAccountManagementListPanel),
    WFTPluginListPanel("WFT Plugin List Panel", ViewName.BackendWFTPluginListPanel),
    SummaryBySectionListPanel("Summary by Section List Panel", ViewName.BackendSummaryBySectionListPanel),
    AccessLogListPanel("Access Log List Panel", ViewName.BackendAccessLogListPanel),
    ErrorLogListPanel("Error Log List Panel", ViewName.BackendErrorLogListPanel),
    SubscriptionManagementListPanel("SubscriptionManagement List Panel", ViewName.BackendSubscriptionManagementListPanel),
    CustomisedPDFTemplatesListView("Customised PDF Templates List Panel", ViewName.BackendCustomisedPDFTemplatesListView),
    GenericSettingsListViiew("Generic Settings List View", ViewName.GenericSettingsListView),
    BackendViewPanel("Backend View List Panel", ViewName.BackendView),
    ReturnBackendPanel("Return Backend List Panel", ViewName.ReturnBackendView),
    ProductServiceStockPanel("Product Service Stock List Panel", ViewName.ProducktServiceStockView),
    ReservationPanel("Reservation List Panel", ViewName.ReservationView),
    AccoundListPanel("Accounting  List Panel", ViewName.AccountingView),
    ExpenceReportListPanel("Expence List Panel", ViewName.ExpenceReportView),
    ProductServiceListPanel("Product Service List Panel", ViewName.ProductServiceView),
    InventoryItemsListPanel("Inventory Items List Panel", ViewName.InventoryItemsView),
    RentalProductsListPanel("Rental Products List Panel", ViewName.RentalProductsView),
    AssemblyItemsListPanel("Assembly Items List Panel", ViewName.AssemblyItemsView),
    RentalOrdersListPanel("Rental Prders List Panel", ViewName.RentalOrdersView),
    HrmsExpenceReportListPanel("Hrms Expence List Panel", ViewName.HrmsExpenceReportView),
    AwaitingReportListPanel("Awaiting Report List Panel", ViewName.HrmsExpenceReportView),
    AccoundChartListPanel("Account Chart List Panel", ViewName.AccoundChartView),
    PaymentDeductionListPanel("Payment/Deduction list panel", ViewName.PaymentDeductionListPanel),
    PayrollBatchListPanel("Payroll Batch list panel", ViewName.PayrollBatchListPanel),
    PensionProviderListPanel("Pension Provider list panel", ViewName.PensionProviderListPanel),
    PayslipListPanel("Payslip list panel", ViewName.PayslipListPanel),
    SinglePayrunListPanel("Single Payrun list panel", ViewName.SinglePayrun),
    WidgetListPanel("Widget List View", ViewName.WidgetListView),
    XTemplateListPanel("XTemplate List Panel", ViewName.XTemplateListView),
    ThemeListPanel("Theme List Panel", ViewName.ThemeListView),
    ProjectStatusListPanel("Project Status List Panel", ViewName.ProjectStatusListView),
    ProjectPurchaseOrderListPanel("Project Purchase Order List Panel", ViewName.ProjectPurchaseOrderListView),
    ProjectPurchaseInvoiceListPanel("Project Purchase Invoice List Panel", ViewName.ProjectPurchaseInvoiceListView),
    ProjectExpenseClaimsListPanel("Project Expense Claims List Panel", ViewName.ProjectExpenseClaimsListView),
    PayrollCategoryListPanel("Payroll Category List Panel", ViewName.PayrollCategoryListPanel),
    PaymentDeductionCategoryListPanel("Payment/Deduction Category List Panel", ViewName.BackendPaymentCategoryListPanel),
    OrganizationListPanel("Payment/Deduction Category List Panel", ViewName.OrganizationListPanel),
    BankStatementItemListPanel("Bank Statement Item List Panel", ViewName.BankStatementItemList),
    BankStatementListPanel("Bank Statement List Panel", ViewName.BankStatementList),
    PensionSchemeListPanel("Pension Scheme List Panel", ViewName.PensionSchemeList),
    BrendsListPanel("Brands List Panel", ViewName.BrandsListView),
    WareHousesLocationsListPanel("Ware Houses Locations List Panel", ViewName.WareHousesLocations),
    ProductCommentsListPanel("Product Comments List Panel", ViewName.ProductComments),
    ManualTransactionsListPanel("Manual Transactions List Panel", ViewName.ManualTransaction),
    CheckListPanel("Check List Panel", ViewName.CheckList),
    TrashBinListPanel("Trash Bin List Panel", ViewName.TrashBin),
    EmailFilterListPanel("Email Filter Panel", ViewName.EmailFilter),
    SMSSettingListPanel("SMS Setting List Panel", ViewName.SMSSetting),
    TwilioSettingListPanel("Twilio Setting List Panel", ViewName.TwilioSetting),
    AsteriskSettingListPanel("Asterisk Setting List Panel", ViewName.AsteriskSetting),
    SipuniSettingListPanel("Sipuni Setting List Panel", ViewName.SipuniSetting),
    MyCallsSettingListPanel("My Calls Setting List Panel", ViewName.MyCallsSetting),
    TelegramSettingListPanel("Telegram Setting List Panel", ViewName.TelegramSetting),
    AsteriskEmployeeListPanel("Asterisk Employee List Panel", ViewName.AsteriskEmployees),
    CustomEntityItemListPanel("Custom Entity Item List Panel", ViewName.CustomEntityItem),
    BreadCrumbsListPanel("BreadCrumbs list panel", ViewName.BreadCrumbs),
    ProjectInvoicesListPanel("Project Invoices List Panel", ViewName.ProjectInvoicesListView),
    AttendanceTrackingListPanel("Attendance Tracking List Panel", ViewName.AttendanceTrackingListView),
    InvoiceTemplatesListPanel("Invoice Templates List Panel", ViewName.InvoiceTemplatesListView),
    DependentListPanel("Dependent List Panel", ViewName.Dependent),
    PastEmploymentListPanel("Past Employment List Panel", ViewName.PastEmploymentListView),
    SolrMonitorListPanel("Solr Monitor", ViewName.SolrMonitorView),
    SolrCoreCompanyListPanel("Solr Core Company List", ViewName.SolrMonitorView),
    ReferenceListPanel("Reference List", ViewName.ReferenceView),
    LeaveReasonListPanel("Leave Reason List", ViewName.LeaveReasonView),
    OrganizeModulListPanel("Organize Module List", ViewName.OrganizeModuleView),
    OverallFeaturesListPanel("Features List", ViewName.OverallFeaturesView),
    AccessTokenListPanel("Access Token List", ViewName.AccessTokenView),
    ImportLogsListPanel("Import Logs List", ViewName.ImportLogsView),
    MessagesListPanel("Messages List", ViewName.MessagesView),
    TalentProfileListPanel("Talent Profile List", ViewName.TalentProfileView),
    BackendManagementListPanel("Backend Management List", ViewName.BackendManagementView),
    MeetingMinutesListPanel("Meeting Notes List", ViewName.MeetingMInutesView),
    BookingItemsListPanel("Booking Items List", ViewName.BookingItemsView),
    ProjectSaleQuoteListView("Project Sale Quote List Panel", ViewName.ProjectSaleQuoteListView),
    VacancyListPanel("Vacancy List Panel", ViewName.Vacancy),
    CandidateListPanel("Candidate List Panel", ViewName.Candidate),
    ShortListPanel("Short List Panel", ViewName.ShortList),
    AnnualAllowanceListPanel("Annual Allowance List Panel", ViewName.AnnualAllowanceListView),
    PlacementListPanel("Placement List Panel", ViewName.Placement),
    PublicEventListPanel("Public Event List Panel", ViewName.EventList),
    ValidityPeriodListPanel("Validity Period List Panel", ViewName.ValidityPeriodListView),
    PeriodAppraisalsListPanel("Period Appraisals List Panel", ViewName.PeriodAppraisalsListView),
    AppraisalApprovalListPanel("Appraisal Approval List Panel", ViewName.AppraisalApprovalListView),
    OnboardingPeriodListPanel("Onboarding Period List Panel", ViewName.OnboardingPeriodListView),
    OnboardingStepListPanel("Onboarding Step List Panel", ViewName.OnboardingStep),
    EmployeeStepListPanel("Employee Step List Panel", ViewName.OnboardingStep),
    StudentsListPanel("Students List Panel", ViewName.Students),
    RegistratedStudentsListPanel("Registrated Students List Panel", ViewName.Students),
    AssessmentListPanel("Assessment List Panel", ViewName.Assessment),
    EnquiryListPanel("Enquiry List Panel", ViewName.EnquiryView),
    CourseListPanel("Course List Panel", ViewName.Course),
    CourseSubjectListPanel("Course Subject List Panel", ViewName.CourseSubject),
    CourseStudentsListPanel("Course Students List Panel", ViewName.CourseStudents),
    ScheduledCourseListPanel("Scheduled Course List Panel", ViewName.ScheduledCourse),
    InstructorReassignListPanel("Instructor Reassign List Panel", ViewName.InstructorReassign),
    InstructorListPanel("Instructor List Panel", ViewName.Instructor),
    CourseBookingListPanel("Course Booking List Panel", ViewName.CourseBooking),
    TrainingContractListPanel("Training Contract List Panel", ViewName.TrainingContract),
    CertificateListPanel("Certificate List Panel", ViewName.Certificates),
    CompanyConsolidation("Company Consolidation List Panel", ViewName.Consolidation),
    StockAdjustmentsListPanel("Stock Adjustments List Panel", ViewName.StockAdjustments),
    DynamicListPanel("Dynamic List Panel!", ViewName.DynamicList),
    MenuGroupsListPanel("Menu Groups List Panel", ViewName.MenuGroupsList),
    PunishmentsPromotionsListPanel("Punishments/Promotions List Panel", ViewName.PunishmentsPromotionsList),
    EmployeePunishmentsPromotionsListPanel("Employee Punishments/Promotions List Panel", ViewName.EmployeePunishmentsPromotionsList),
    PremiumRecommendationsListPanel("Premium Recommendations List Panel", ViewName.PremiumRecommendationsList),
    TenderCardListPanel("Tender Card List Panel", ViewName.TenderCardList),
    WorkflowListPanel("Workflow List Panel", ViewName.Workflow),
    WorkflowActivitiesListPanel("Workflow Activities List Panel", ViewName.WorkflowActivities),
    EstimateListPanel("Estimate List Panel", ViewName.Estimate),
    EmployeePayslipListPanel("Employee Payslip List Panel", ViewName.EmployeePayslipList),
    EndOfServiceGratuityListPanel("End Of Service Gratuity List Panel", ViewName.EndOfServiceGratuityList),
    PayslipTableListPanel("Payslip Table List Panel", ViewName.PayslipTableList),
    OpportunityExpenseClaimListPanel("Opportunity Expense Claim List Panel", ViewName.OpportunityExpenseClaimListPanel),
    TaxiPayrunListPanel("Taxi Payrun List Panel", ViewName.TaxiPayrunList),
    PassportListPanel("Passport List Panel", ViewName.HSEPassports),
    CashAdvancePanel("Cash Advance List Panel", ViewName.CashAdvanceList),
    MultiCashAdvancePanel("Multi Cash Advance List Panel", ViewName.MultiCashAdvanceList),
    AdditionalPayment("Additional Payment List Panel", ViewName.AdditionalPayment),
    CertificatePanel("Certificate List Panel", ViewName.CertificateList),
    BenefitPanel("Benefit List Panel", ViewName.BenefitList),
    BenefitRequestPanel("Benefit Request List Panel", ViewName.BenefitRequestList),
    CertificateTypePanel("Certificate List Panel", ViewName.CertificateTypeList),
    StockTransferListPanel("Stock Transfer List Panel", ViewName.StockTransferList),
    SerialNumberListPanel("Serial Number List Panel", ViewName.SerialNumberList),
    BatchHistoryListPanel("Batch History List Panel", ViewName.BatchHistoryList),
    CashPaymentListPanel("Bank/Cash Transfer List Panel", ViewName.BankTransferList),
    CashReceiptListPanel("Bank/Cash Transfer List Panel", ViewName.BankTransferList),
    BankPaymentListPanel("Bank/Cash Transfer List Panel", ViewName.BankTransferList),
    BankReceiptListPanel("Bank/Cash Transfer List Panel", ViewName.BankTransferList),
    ConsignmentListPanel("Consignment List Panel", ViewName.ConsignmentList),
    NotificationsListPanel("Notifications List Panel", ViewName.NotivicationsView),
    EmployeeDocumentListPanel("Employee Document List Panel", ViewName.EmployeeDocumentList),
    CompanyDocumentListPanel("Company Document List Panel", ViewName.CompanyDocumentList),
    BatchInvoicePaymentListPanel("Batch Invoice Payment List Panel", ViewName.BatchInvoicePaymentView),
    BatchPayBillListPanel("Batch Pay Bill List Panel", ViewName.BatchPayBillView),
    NotificationConfigListPanel("Notification Config List Panel", ViewName.NotificationConfigView),
    PayrollEmployeeTemplateListPanel("Payroll Employee Template List Panel", ViewName.EmployeeTemplateList),
    CountrySettingsListPanel("Country Settings List", ViewName.CountrySettingsList),
    EmailAccountsListPanel("Email Accounts List Panel", ViewName.EmailAccount),
    CurrencyListPanel("Currency Rates List Panel", ViewName.CurrencyList),
    PaymentMethodListPanel("Payment Method List Panel", ViewName.PaymentMethodList),
    FingerprintView("Fingerprint List Panel", ViewName.FingerprintView),
    FingerPrintDeviceStatusHistoryListPanel("Fingerprint Device Status History Panel", ViewName.FingerPrintDeviceStatusHistoryList),
    CashAdvancePaymentListView("Cash Advance Payment List View", ViewName.CashAdvancePaymentList),
    EmployeeHistoryListView("Employee History List View", ViewName.EmployeeHistoryList),
    ProductHistoryListView("Product History List View", ViewName.ProductHistoryList),
    OpportunityHistoryListView("Opportunity History List View", ViewName.OpportunityHistoryList),
    RolePermissionHistoryListView("Role Permission History List View", ViewName.RolePermissionHistoryList),
    AuditLogListView("Audit Log List View", ViewName.AuditLogList),
    AnnualLeaveBalanceList("Annual Leave balance", ViewName.AnnualLeaveBalance),
    LeaveBalanceReport("Leave balance report", ViewName.LeaveBalanceReport),
    FilteredStatusesForMobile("Filtered Statuses", ViewName.FilteredStatuses),
    TasksQuickFilterForMobile("Task Quick Filter", ViewName.Task),
    CrmAccountQuickFilterForMobile("Crm Account Quick Filter", ViewName.CrmAccount),
    ContactsQuickFilterForMobile("Contacts Quick Filter", ViewName.Contact),
    LeaveRequestQuickFilterForMobile("Leave Request Quick Filter", ViewName.LeaveRequest),
    LeadListPanelOTF("Lead One Time Filter", ViewName.Lead),
    LeaveRequestApproveOTF("Leave Request One Time Filter", ViewName.LeaveRequest),
    TaskListPanelOTF("Task One Time Filter", ViewName.Task),
    OpportunitiesQuickFilterForMobile("Opportunity Quick Filter", ViewName.Opportunity),
    OpportunityListPanelOTF("Opportunity One Time Filter", ViewName.Opportunity),
    CaseListPanelOTF("Case One Time Filter", ViewName.CrmCase),
    ShppingDataListPanel("Shipping Data List Panel", ViewName.ShippingData),
    ContactCategoryListPanel("Contact Category List Panel", ViewName.ContactCategory),
    ContactListPanelOTF("Contact One Time Filter", ViewName.Contact),
    CrmAccountListPanelOTF("Crm Account One Time Filter", ViewName.CrmAccount),
    LeadKanbanPanel("Lead Kanban Board", ViewName.Lead),
    ModuleDashboardPanel("Module Dashboard", ViewName.ModuleDashboard),
    OpportunitiesKanbanPanel("Opportunities Kanban Board", ViewName.Opportunity),
    CaseKanbanPanel("Case Kanban Board", ViewName.CrmCase),
    TaskKanbanPanel("Task Kanban Board", ViewName.Task),
    CandidateKanbanPanel("Candidate Kanban Board", ViewName.Candidate),
    LeaveRequestApprove("Leave Request approval list", ViewName.LeaveRequest),
    IncientListPanel("Incient list panel", ViewName.Incient),
    EmployeeMetricsPanel("Department Goal, Employee Metrics Panel", ViewName.EmployeeMetrics),
    SettingsPdfTemplateListPanel("Pdf Template List View", ViewName.SettingsPdfTemplateList),
    CustomFormItemsPanel("Custom form items Panel", ViewName.CustomFormItems),
    VatReturnsListPanel("Vat Returns List Panel", ViewName.VatReturns),
    GoodsReceivedNoteListPanel("Goods Received Note List Panel", ViewName.GoodsReceivedNote),
    GoodsDeliveredNoteListPanel("Goods Delivered Note List Panel", ViewName.GoodsDeliveredNote),
    TaskHistoryListView("Task History List View", ViewName.TaskHistoryList),
    CandidateHistoryListView("Candidate History List View", ViewName.CandidateHistoryList),
    ShiftList("Shift List View", ViewName.ShiftList),
    RotationList("Rotation List View", ViewName.RotationList),
    BrigadaList("Brigada List View", ViewName.BrigadaList),
    GroupPlacementList("Group Placement List View", ViewName.GroupPlacementList),
    DynamicLoginListPanel("Dynamic Login List View", ViewName.DynamicLogin),
    WhiteLabelListPanel("White Label List View", ViewName.WhiteLabelList),
    SubscriptionListPanel("Subscription List View", ViewName.SubscriptionList),
    Overtime("Overtime List panel", ViewName.Overtime),
    RecurringPayDeductionPanel("Recurring Pay Deduct List Panel", ViewName.RecurringPayDeductionList),
    BackupsEmployee("Backups Employee List panel", ViewName.BackupsEmployee),
    EmployeeSalaryHistoryList("Employee Salary History List View", ViewName.EmployeeSalaryHistoryList),
    PayrollZoneList("Payroll Zone List View", ViewName.PayrollZoneList),
    MinimumWageList("Minimum Wage List View", ViewName.MinimumWageList),
    WageRateList("Wage Rate List View", ViewName.WageRateList),
    BuildAssembly("Build Assembly", ViewName.BuildAssembly),
    AttendanceTerminalListPanel("Terminals", ViewName.AttendanceTerminalList),
    AttendanceMarksListPanel("Attendance Marks", ViewName.AttendanceMarksList);

    ListPanelType(String listName, ViewName viewName) {
        this.listName = listName;
        this.viewName = viewName;
    }

    private Integer id;
    private String listName;
    private ViewName viewName;

    ListPanelType() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getListName() {
        return listName;
    }

    public ViewName getViewName() {
        return viewName;
    }

    public static ListPanelType getByViewName(String viewName_) {
        ViewName viewName = ViewName.valueOf(viewName_);
        ListPanelType[] values = values();
        if (values != null && values.length > 0) {
            for (ListPanelType listPanelType : values) {
                if (listPanelType.getViewName() != null && listPanelType.getViewName().equals(viewName)) {
                    return listPanelType;
                }
            }
        }
        return null;
    }

    @Override
    public String toString() {
        if (id != null) {
            return super.toString() + id;
        }
        return super.toString();
    }
}
